force-app/main/default/objects/EYI_Payment_Receipt__c/EYI_Payment_Receipt__c.object-meta.xml
<CustomObject>
    <label>Bank Payment Receipt</label>
    <nameField>
        <displayFormat>PR-{0}</displayFormat>
        <label>Payment Receipt</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Payment Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Account__c.field-meta.xml
<CustomField>
    <fullName>EYI_Account__c</fullName>
    <label>Account</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>EYI_Account_ID__c</fullName>
    <label>Account ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Account_Type__c</fullName>
    <label>Account Type</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Assignment__c.field-meta.xml
<CustomField>
    <fullName>EYI_Assignment__c</fullName>
    <label>Assignment</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Attached_By__c.field-meta.xml
<CustomField>
    <fullName>EYI_Attached_By__c</fullName>
    <label>Attached By</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Attachment_Remark__c.field-meta.xml
<CustomField>
    <fullName>EYI_Attachment_Remark__c</fullName>
    <label>Attachment Remark</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Bank_Payment_Confirmation_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Bank_Payment_Confirmation_Date__c</fullName>
    <label>Bank Payment Confirmation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Business_Trans_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_Business_Trans_Code__c</fullName>
    <label>Business Trans Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Change_Remark__c.field-meta.xml
<CustomField>
    <fullName>EYI_Change_Remark__c</fullName>
    <label>Change Remark</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Check_number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Check_number__c</fullName>
    <label>Cheque/DD Number</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_Company_Name__c</fullName>
    <label>Company Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Delay_WRT_Creation__c.field-meta.xml
<CustomField>
    <fullName>EYI_Delay_WRT_Creation__c</fullName>
    <label>Delay WRT Creation</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Department_ID__c.field-meta.xml
<CustomField>
    <fullName>EYI_Department_ID__c</fullName>
    <label>Department ID</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Department_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_Department_Name__c</fullName>
    <label>Department Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Description__c.field-meta.xml
<CustomField>
    <fullName>EYI_Description__c</fullName>
    <label>Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_DMS_Doc_No__c.field-meta.xml
<CustomField>
    <fullName>EYI_DMS_Doc_No__c</fullName>
    <label>DMS Doc No</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_DMS_Doc_Part__c.field-meta.xml
<CustomField>
    <fullName>EYI_DMS_Doc_Part__c</fullName>
    <label>DMS Doc Part</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_DMS_Doc_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_DMS_Doc_Type__c</fullName>
    <label>DMS Doc Type</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>EYI_Fiscal_Year__c</fullName>
    <label>Fiscal Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_G_L_Account__c.field-meta.xml
<CustomField>
    <fullName>EYI_G_L_Account__c</fullName>
    <label>G/L Account</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_House_Bank__c.field-meta.xml
<CustomField>
    <fullName>EYI_House_Bank__c</fullName>
    <label>House Bank</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Initial_Remark__c.field-meta.xml
<CustomField>
    <fullName>EYI_Initial_Remark__c</fullName>
    <label>Initial Remark</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Is_Reversed__c.field-meta.xml
<CustomField>
    <fullName>EYI_Is_Reversed__c</fullName>
    <label>Is Reversed</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Memo_Record_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Memo_Record_Number__c</fullName>
    <label>Memo Record Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Payment_Confirmed_Amount_From_SAP__c.field-meta.xml
<CustomField>
    <fullName>EYI_Payment_Confirmed_Amount_From_SAP__c</fullName>
    <label>Payment Confirmed Amount From SAP</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>EYI_Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REJECT</fullName>
            </value>
            <value>
                <fullName>APPROVE</fullName>
            </value>
            <value>
                <fullName>SUBMITTED</fullName>
            </value>
            <value>
                <fullName>HOLD</fullName>
            </value>
            <value>
                <fullName>INPROCESS</fullName>
            </value>
            <value>
                <fullName>Bounced</fullName>
                <isActive>false</isActive>
                <label>Bounced</label>
            </value>
            <value>
                <fullName>Cleared</fullName>
                <isActive>false</isActive>
                <label>Cleared</label>
            </value>
            <value>
                <fullName>IRRELEVANT</fullName>
                <isActive>false</isActive>
                <label>IRRELEVANT</label>
            </value>
            <value>
                <fullName>MAILSENT</fullName>
                <isActive>false</isActive>
                <label>MAILSENT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Processed_By__c.field-meta.xml
<CustomField>
    <fullName>EYI_Processed_By__c</fullName>
    <label>Processed By</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Receivable_Desk_Document_Version__c.field-meta.xml
<CustomField>
    <fullName>EYI_Receivable_Desk_Document_Version__c</fullName>
    <label>Receivable_Desk Document Version</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Receivable_Desk_Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Receivable_Desk_Tracking_Number__c</fullName>
    <label>Receivable Desk Tracking Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Recv_Desk_Approved_By__c.field-meta.xml
<CustomField>
    <fullName>EYI_Recv_Desk_Approved_By__c</fullName>
    <label>Recv Desk Approved By</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Recv_Desk_Approved_By_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_Recv_Desk_Approved_By_Name__c</fullName>
    <label>Recv Desk Approved By Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Recv_Desk_Changed_By__c.field-meta.xml
<CustomField>
    <fullName>EYI_Recv_Desk_Changed_By__c</fullName>
    <label>Recv Desk Changed By</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Recv_Desk_Changed_By_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_Recv_Desk_Changed_By_Name__c</fullName>
    <label>Recv Desk Changed By Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Recv_Desk_Created_By__c.field-meta.xml
<CustomField>
    <fullName>EYI_Recv_Desk_Created_By__c</fullName>
    <label>Recv Desk Created By</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Recv_Desk_Created_By_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_Recv_Desk_Created_By_Name__c</fullName>
    <label>Recv Desk Created By Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Recv_Desk_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Recv_Desk_Created_Date__c</fullName>
    <label>Recv Desk Created Date</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Recv_Desk_Processed_By__c.field-meta.xml
<CustomField>
    <fullName>EYI_Recv_Desk_Processed_By__c</fullName>
    <label>Recv Desk Processed By</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Reference__c.field-meta.xml
<CustomField>
    <fullName>EYI_Reference__c</fullName>
    <label>Reference</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_SAP_BRS_Document_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_BRS_Document_Number__c</fullName>
    <label>SAP BRS Document Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_SAP_Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Customer_Name__c</fullName>
    <label>SAP Customer Name</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_SAP_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Customer_Number__c</fullName>
    <label>SAP Customer Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_SAP_Document_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Document_Number__c</fullName>
    <label>SAP Document Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_SAP_Payment_Advice_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Payment_Advice_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>SAP Payment Advice Number</label>
    <length>128</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_SAP_Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Reason_Code__c</fullName>
    <label>SAP Reason Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_SAP_Reason_Description__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Reason_Description__c</fullName>
    <label>SAP Reason Description</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_SAP_Rejection_Hold_Remark__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Rejection_Hold_Remark__c</fullName>
    <label>SAP Rejection/Hold Remark</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_SAP_Sync_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Sync_Date__c</fullName>
    <description>Capture SAP sync date.</description>
    <label>SAP Sync Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_SAP_Transaction__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Transaction__c</fullName>
    <label>SAP Transaction</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Short_Key__c.field-meta.xml
<CustomField>
    <fullName>EYI_Short_Key__c</fullName>
    <label>Short Key</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Site__c.field-meta.xml
<CustomField>
    <fullName>EYI_Site__c</fullName>
    <label>Site</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Site_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_Site_Name__c</fullName>
    <label>Site Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Statement_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Statement_Date__c</fullName>
    <label>Statement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Statement_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Statement_Number__c</fullName>
    <label>Statement Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EYI_PaymentReceipt.cls
@RestResource(urlMapping='/UpdatePaymentReceiptStatus/*')
global without sharing class EYI_PaymentReceipt {
    
    global class CustomResponse {
        public String id;
        // public String sapExternalId;
        public Boolean success;
        public String message;
        //public List<String> errors;
        
        public CustomResponse(String id, Boolean success, String message) {
            this.id = id;
            //this.sapExternalId = sapExternalId;
            this.success = success;
            this.message = message;
            //this.errors = errors;
        }
    }
    
    @HttpPatch
    global static List<CustomResponse> createPaymentReceipts(){
        RestRequest req = RestContext.request;
        String requestBody = req.requestBody.toString();
        List<EYI_Payment_Receipt__c> recordsToInsertOrUpdate = new List<EYI_Payment_Receipt__c>();
        System.debug('requestBody ==> ' + requestBody);
        
        List<CustomResponse> responses = new List<CustomResponse>(); // List to hold responses for each record
        
        try{
            EYI_PaymentReceitStatusWrapper paymentReceiptRequest = (EYI_PaymentReceitStatusWrapper)JSON.deserialize(requestBody, EYI_PaymentReceitStatusWrapper.class);
            List<EYI_PaymentReceitStatusWrapper.PaymentWrapper> payment = paymentReceiptRequest.ReceiptStatus;
            for (EYI_PaymentReceitStatusWrapper.PaymentWrapper paymentReceipt : payment){
                system.debug('insidefor-->116');
                EYI_Payment_Receipt__c record = new EYI_Payment_Receipt__c(
                    EYI_Receivable_Desk_Tracking_Number__c = paymentReceipt.ReceivableDeskTrackingNumber,
                    EYI_Receivable_Desk_Document_Version__c = (paymentReceipt.ReceivableDeskDocumentVersion !=null && paymentReceipt.ReceivableDeskDocumentVersion != '')? Decimal.valueOf(paymentReceipt.ReceivableDeskDocumentVersion) : 0,
                    EYI_SAP_Company_Code__c = paymentReceipt.SapCompanyCode,
                    EYI_House_Bank__c = paymentReceipt.HouseBank,            
                    EYI_Account_ID__c = paymentReceipt.AccountId,
                    EYI_Short_Key__c = (paymentReceipt.ShortKey !=null && paymentReceipt.ShortKey != '')? Decimal.valueOf(paymentReceipt.ShortKey) : 0,
                    EYI_G_L_Account__c = paymentReceipt.GlAccount,
                    EYI_Statement_Number__c = (paymentReceipt.StatementNumber !=null && paymentReceipt.StatementNumber != '')? Decimal.valueOf(paymentReceipt.StatementNumber) : 0,
                    EYI_Memo_Record_Number__c = (paymentReceipt.MemoRecordNumber !=null && paymentReceipt.MemoRecordNumber != '')? Decimal.valueOf(paymentReceipt.MemoRecordNumber) : 0,
                    EYI_Business_Trans_Code__c = paymentReceipt.BusinessTransCode,
                    EYI_SAP_Transaction__c = paymentReceipt.SapTransaction,
                    EYI_Payment_Confirmed_Amount_From_SAP__c = paymentReceipt.PaymentConfirmedAmountFromSAP,
                    EYI_Account_Type__c = paymentReceipt.AccountType,
                    EYI_Account__c = paymentReceipt.Account,
                    EYI_SAP_Document_Number__c = paymentReceipt.SapDocumentNumber,
                    EYI_Fiscal_Year__c = (paymentReceipt.FiscalYear !=null && paymentReceipt.FiscalYear != '')? Decimal.valueOf(paymentReceipt.FiscalYear) : 0,
                    EYI_Is_Reversed__c = (paymentReceipt.IsReversed !=null && paymentReceipt.IsReversed!= '')? Decimal.valueOf(paymentReceipt.IsReversed) : 0,	
                    EYI_Company_Name__c = paymentReceipt.CompanyName,
                    EYI_Reference__c = paymentReceipt.Reference,
                    EYI_Assignment__c = paymentReceipt.Assignment,
                    EYI_Check_number__c = paymentReceipt.Checknumber,
                    EYI_Department_ID__c = paymentReceipt.DepartmentID,
                    EYI_Department_Name__c = paymentReceipt.DepartmentName,
                    EYI_Description__c = paymentReceipt.Description,
                    EYI_Site__c = paymentReceipt.Site,
                    EYI_Site_Name__c = paymentReceipt.SiteName,
                    EYI_Payment_Status__c = paymentReceipt.PaymentStatus,
                    EYI_SAP_Customer_Name__c = paymentReceipt.SapCustomerNumber,
                    EYI_SAP_Customer_Number__c = paymentReceipt.SapCustomerName,
                    EYI_SAP_Payment_Advice_Number__c = paymentReceipt.SapPaymentAdviceNumber,
                    EYI_Initial_Remark__c = paymentReceipt.InitialRemark,
                    EYI_Attachment_Remark__c = paymentReceipt.AttachmentRemark,
                    EYI_Attached_By__c = paymentReceipt.AttachedBy,
                    EYI_DMS_Doc_Type__c = paymentReceipt.DmsDocType,
                    EYI_DMS_Doc_Part__c = paymentReceipt.DmsDocPart,
                    EYI_DMS_Doc_No__c = paymentReceipt.DmsDocNo,
                    EYI_SAP_Reason_Code__c = paymentReceipt.SapReasonCode,
                    EYI_SAP_Reason_Description__c = paymentReceipt.SapReasonDescription,
                    EYI_SAP_Rejection_Hold_Remark__c = paymentReceipt.SapRejectionHoldRemarks,
                    EYI_Delay_WRT_Creation__c = paymentReceipt.DelayWRTCreation,
                    EYI_SAP_BRS_Document_Number__c = paymentReceipt.SapBRSDocumentNumber,
                    EYI_Processed_By__c = paymentReceipt.ProcessedBy,
                    EYI_Recv_Desk_Approved_By__c = paymentReceipt.RecvDeskApprovedBy,
                    EYI_Recv_Desk_Approved_By_Name__c = paymentReceipt.RecvDeskApprovedByName,
                    EYI_Recv_Desk_Changed_By__c = paymentReceipt.RecvDeskChangedBy,
                    EYI_Recv_Desk_Created_By__c = paymentReceipt.RecvDeskCreatedBy,
                    EYI_Recv_Desk_Created_By_Name__c = paymentReceipt.RecvDeskCreatedByName,
                    EYI_Recv_Desk_Created_Date__c = paymentReceipt.RecvDeskCreatedDate,
                    EYI_Recv_Desk_Processed_By__c = paymentReceipt.RecvDeskProcessedBy,
                    EYI_Recv_Desk_Changed_By_Name__c = paymentReceipt.RecvDeskChangedByName,
                    EYI_SAP_Sync_Date__c = System.now(),
                    
                    EYI_Bank_Payment_Confirmation_Date__c = String.isBlank(paymentReceipt.BankPaymentConfirmationDate) ? null : Date.valueOf(paymentReceipt.BankPaymentConfirmationDate),
                    EYI_Statement_Date__c = String.isBlank(paymentReceipt.StatementDate) ? null : Date.valueOf(paymentReceipt.StatementDate),
                    EYI_Change_Remark__c = String.isBlank(paymentReceipt.ChangeRemark) ? null : Date.valueOf(paymentReceipt.ChangeRemark),
                    EYI_Attached_On__c = String.isBlank(paymentReceipt.AttachedOn) ? null : Date.valueOf(paymentReceipt.AttachedOn),
                    EYI_Bank_Posting_Date__c = String.isBlank(paymentReceipt.BankPostingDate) ? null : Date.valueOf(paymentReceipt.BankPostingDate),
                    EYI_Recv_Desk_Approved_Date__c = String.isBlank(paymentReceipt.RecvDeskApprovedDate) ? null : Date.valueOf(paymentReceipt.RecvDeskApprovedDate),
                    EYI_Recv_Desk_Changed_On__c = String.isBlank(paymentReceipt.RecvDeskChangedOn) ? null : Date.valueOf(paymentReceipt.RecvDeskChangedOn),
                    EYI_Recv_Desk_Processed_Date__c = String.isBlank(paymentReceipt.RecvDeskProcessedDate) ? null : Date.valueOf(paymentReceipt.RecvDeskProcessedDate),
                    
                    EYI_Attached_At__c = String.isBlank(paymentReceipt.AttachedAt) ? null : Time.newInstance(
                        Integer.valueOf(paymentReceipt.AttachedAt.split(':')[0]),
                        Integer.valueOf(paymentReceipt.AttachedAt.split(':')[1]),
                        Integer.valueOf(paymentReceipt.AttachedAt.split(':')[2]),
                        0
                    ),
                    EYI_Recv_Desk_Approved_Time__c = String.isBlank(paymentReceipt.RecvDeskApprovedTime) ? null : Time.newInstance(
                        Integer.valueOf(paymentReceipt.RecvDeskApprovedTime.split(':')[0]),
                        Integer.valueOf(paymentReceipt.RecvDeskApprovedTime.split(':')[1]),
                        Integer.valueOf(paymentReceipt.RecvDeskApprovedTime.split(':')[2]),
                        0
                    ),
                    EYI_Recv_Desk_Changed_Time__c = String.isBlank(paymentReceipt.RecvDeskChangedTime) ? null : Time.newInstance(
                        Integer.valueOf(paymentReceipt.RecvDeskChangedTime.split(':')[0]),
                        Integer.valueOf(paymentReceipt.RecvDeskChangedTime.split(':')[1]),
                        Integer.valueOf(paymentReceipt.RecvDeskChangedTime.split(':')[2]),
                        0
                    ),
                    EYI_Recv_Desk_Created_Time__c = String.isBlank(paymentReceipt.RecvDeskCreatedTime) ? null : Time.newInstance(
                        Integer.valueOf(paymentReceipt.RecvDeskCreatedTime.split(':')[0]),
                        Integer.valueOf(paymentReceipt.RecvDeskCreatedTime.split(':')[1]),
                        Integer.valueOf(paymentReceipt.RecvDeskCreatedTime.split(':')[2]),
                        0
                    ),
                    EYI_Recv_Desk_Processed_Time__c = String.isBlank(paymentReceipt.RecvDeskProcessedTime) ? null : Time.newInstance(
                        Integer.valueOf(paymentReceipt.RecvDeskProcessedTime.split(':')[0]),
                        Integer.valueOf(paymentReceipt.RecvDeskProcessedTime.split(':')[1]),
                        Integer.valueOf(paymentReceipt.RecvDeskProcessedTime.split(':')[2]),
                        0
                    )
                    
                    
                    
                );
                    system.debug('recordsToInsertOrUpdate'+ recordsToInsertOrUpdate);
                    recordsToInsertOrUpdate.add(record);
            }
            
            
            // Perform bulk DML operation (insert or update)
            List<Database.UpsertResult> results;
            Schema.SObjectField externalIdField = EYI_Payment_Receipt__c.EYI_SAP_Payment_Advice_Number__c;
            
            results = Database.upsert(recordsToInsertOrUpdate,externalIdField, false);
            system.debug('results ==> '+results);
            
            
            
            
            
            // Iterate through each result to construct the response
            for (Integer i = 0; i < results.size(); i++) {
                Database.UpsertResult result = results[i];
                if (result.isSuccess()) {
                    // Success response for each record
                    String successMessage = result.isCreated() ? 'Record was successfully created.' : 'Record was successfully updated.';
                    if(result.isCreated()){
                        responses.add(new CustomResponse(
                            result.getId(),
                            true,
                            successMessage
                        ));                            
                    }else{
                        responses.add(new CustomResponse(
                            result.getId(),
                            true,
                            successMessage
                        ));                            
                    }
                    
                } else {
                    // Error response for each record
                    String errorMessage;
                    for (Database.Error err : result.getErrors()) {
                        if(err.getMessage() == 'EYI_SAP_Payment_Advice_Number__c not specified'){
                            errorMessage = System.label.Payment_Receipt_Error;
                        }else{
                            errorMessage = err.getMessage();
                        }
                        
                        
                    }
                    responses.add(new CustomResponse(
                        null,
                        false,
                        errorMessage
                        
                    ));
                }
            }
        } catch (Exception e) {
            // General error response if an exception occurs
            //String errorMessage = e.getMessage();
            
            responses.add(new CustomResponse(
                null,
                false,
                e.getMessage()
                
            ));
        }
        system.debug('responses -> '+responses);
        system.debug('serialized responses -> '+JSON.serialize(responses));
        // Serialize the list of responses and return it
        return responses;
        
        
    }
    
    
    
    
}