force-app/main/default/objects/EYI_Payment_Receipt__c/EYI_Payment_Receipt__c.object-meta.xml
<CustomObject>
    <label>Bank Payment Receipt</label>
    <nameField>
        <displayFormat>PR-{0}</displayFormat>
        <label>Payment Receipt</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Payment Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Amount__c.field-meta.xml
<CustomField>
    <fullName>EYI_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>EYI_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Payment_Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>EYI_Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REJECT</fullName>
            </value>
            <value>
                <fullName>APPROVE</fullName>
            </value>
            <value>
                <fullName>SUBMITTED</fullName>
            </value>
            <value>
                <fullName>HOLD</fullName>
            </value>
            <value>
                <fullName>INPROCESS</fullName>
            </value>
            <value>
                <fullName>Bounced</fullName>
                <isActive>false</isActive>
                <label>Bounced</label>
            </value>
            <value>
                <fullName>Cleared</fullName>
                <isActive>false</isActive>
                <label>Cleared</label>
            </value>
            <value>
                <fullName>IRRELEVANT</fullName>
                <isActive>false</isActive>
                <label>IRRELEVANT</label>
            </value>
            <value>
                <fullName>MAILSENT</fullName>
                <isActive>false</isActive>
                <label>MAILSENT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentReceiptTest.cls
@isTest
public class PaymentReceiptTest {

    @isTest
    public static void testPaymentMethod(){
        EYI_Payment_Receipt__c receipt = new EYI_Payment_Receipt__c(
         //   Name = 'Receipt1',
            EYI_Amount__c = 100,
            EYI_Payment_Status__c = 'SUBMITTED'
            //EYI_Opportunity__c = testOpportunity.Id
        );
        insert receipt;
        receipt.EYI_Payment_Status__c ='APPROVE';
        update receipt;

    }
}