force-app/main/default/objects/EYI_Payment_Receipt__c/EYI_Payment_Receipt__c.object-meta.xml
<CustomObject>
    <label>Bank Payment Receipt</label>
    <nameField>
        <displayFormat>PR-{0}</displayFormat>
        <label>Payment Receipt</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Payment Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_SAP_Error__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Error__c</fullName>
    <description>Field to store error messages coming from SAP sync API</description>
    <label>SAP Error</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/PaymentReceiptQueueable.cls
public class PaymentReceiptQueueable implements Queueable, Database.AllowsCallouts {
    private List<Map<String, Object>> updatedRecords;
    private Map<String, Object> formData;

    public PaymentReceiptQueueable(List<Map<String, Object>> updatedRecords, Map<String, Object> formData) {
        this.updatedRecords = updatedRecords;
        this.formData = formData;
    }

    public void execute(QueueableContext context) {
        HttpResponse hr = EY_SAP_Gateway.sendPayementReceipt(null, updatedRecords, formData);

        // Retrieve the Payment Receipt record using the ID from formData
        Id receiptId = (Id) formData.get('paymentReceiptId');
        EYI_Payment_Receipt__c paymentReceipt = [SELECT Id, EYI_SAP_Error__c FROM EYI_Payment_Receipt__c WHERE Id = :receiptId LIMIT 1];

        // Process response & update record
        //EYI_SAP_PaymentReceiptSyncLwcController.processPaymentResponse(hr, paymentReceipt);
    }
}