force-app/main/default/objects/EYI_Car_Park_Master__c/EYI_Car_Park_Master__c.object-meta.xml
<CustomObject>
    <label>Car Park Master</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Car Parking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Park Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Inventory__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <referenceTo>EYI_Inventory__c</referenceTo>
    <relationshipLabel>Car Park Masters</relationshipLabel>
    <relationshipName>Car_Park_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Car Park Masters</relationshipLabel>
    <relationshipName>Car_Park_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.EYI_Project__c</field>
            <operation>equals</operation>
            <valueField>EYI_Tower__c.EYI_Project_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Car Park Masters</relationshipLabel>
    <relationshipName>Car_Park_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Global_Charges__c/EYI_Global_Charges__c.object-meta.xml
<CustomObject>
    <label>Global Charges</label>
    <nameField>
        <label>Global Charges Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Global_Charges__c/fields/EYI_Condition_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Condition_Type__c</fullName>
    <formula>CASE(
EYI_SAP_Condition_Type__c,
&apos;ZADC&apos;, &apos;Infra Charges&apos;,
&apos;ZBP0&apos;, &apos;Base Price&apos;,
&apos;ZBRA&apos;, &apos;Brokerage Additional&apos;,
&apos;ZBRK&apos;, &apos;Brokerage&apos;,
&apos;ZCLB&apos;, &apos;Club House&apos;,
&apos;ZFRC&apos;, &apos;Floor Rise&apos;,
&apos;ZLAN&apos;, &apos;Land Cost&apos;,
&apos;ZPRM&apos;, &apos;2 Wheeler Charges&apos;,
&apos;ZRCP&apos;, &apos;Base Price-Booking&apos;,
&apos;MSEB&apos;, &apos;MSEB Charges&apos;,
&apos;SDR-RECOVERABLE&apos;, &apos;STAMP DUTY AND REG - RECOVERABLE&apos;,
&apos;SDR-NONRECOVER&apos;, &apos;STAMP DUTY NON RECOVERABLE&apos;,
&apos;&apos;
)</formula>
    <label>Condition Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Global_Charges__c/fields/EYI_SAP_Material_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Material_Name__c</fullName>
    <description>This field is to Update the SAP material Name for the other charges</description>
    <externalId>true</externalId>
    <label>SAP Material Name</label>
    <length>55</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/EYI_Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Inventory_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Inventory Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_SAP_Material_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Material_Code__c</fullName>
    <externalId>true</externalId>
    <label>SAP Material Code</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>EYI_Tower__c.EYI_SubProject_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.EYI_SubProject__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/EYI_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Global_Charges__c.field-meta.xml
<CustomField>
    <fullName>EYI_Global_Charges__c</fullName>
    <label>Global Charges</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
            </value>
            <value>
                <fullName>Infra</fullName>
            </value>
            <value>
                <fullName>Floor Rise</fullName>
            </value>
            <value>
                <fullName>MSEB</fullName>
            </value>
            <value>
                <fullName>Club House</fullName>
            </value>
            <value>
                <fullName>Legal Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Project_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Code__c</fullName>
    <label>Project Code</label>
    <length>55</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_SAP_Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Plant_Code__c</fullName>
    <label>SAP Plant Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_SAP_Salesorg__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Salesorg__c</fullName>
    <label>SAP Sales-org</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Stamp_Duty__c.field-meta.xml
<CustomField>
    <fullName>EYI_Stamp_Duty__c</fullName>
    <label>Stamp Duty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/recordTypes/Residential.recordType-meta.xml
<RecordType>
    <fullName>Residential</fullName>
    <active>true</active>
    <label>Residential</label>
</RecordType>

force-app/main/default/objects/EYI_Rate_List__c/EYI_Rate_List__c.object-meta.xml
<CustomObject>
    <label>Rate List</label>
    <nameField>
        <displayFormat>Rate List-{00}</displayFormat>
        <label>Rate List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Global_Charges__c.field-meta.xml
<CustomField>
    <fullName>EYI_Global_Charges__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Charges</label>
    <referenceTo>EYI_Global_Charges__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Inventory__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory</label>
    <referenceTo>EYI_Inventory__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Tower__c/EYI_Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Tower__c/fields/EYI_SAP_Plant_ID__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Plant_ID__c</fullName>
    <label>SAP Plant Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Tower__c/recordTypes/Residential.recordType-meta.xml
<RecordType>
    <fullName>Residential</fullName>
    <active>true</active>
    <label>Residential</label>
</RecordType>

force-app/main/default/objects/Project_Charges__c/Project_Charges__c.object-meta.xml
<CustomObject>
    <label>Project Charges</label>
    <nameField>
        <label>Project Charges Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Charges__c/fields/EYI_Active__c.field-meta.xml
<CustomField>
    <fullName>EYI_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Charges__c/fields/EYI_Charge_Calculated_As__c.field-meta.xml
<CustomField>
    <fullName>EYI_Charge_Calculated_As__c</fullName>
    <label>Charge Calculated As</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rate List at Unit Level</fullName>
            </value>
            <value>
                <fullName>Lumpsum at Project Level</fullName>
            </value>
            <value>
                <fullName>Percentage of Agreement Value</fullName>
            </value>
            <value>
                <fullName>Higher of Ready Reckoner or Agreement Value</fullName>
                <isActive>false</isActive>
                <label>Higher of Ready Reckoner or Agreement Value</label>
            </value>
            <value>
                <fullName>Higher of Ready Reckoner or Flatcost</fullName>
                <isActive>false</isActive>
                <label>Higher of Ready Reckoner or Flatcost</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Charges__c/fields/EYI_Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Charge_Type__c</fullName>
    <label>Charge Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pricing Charges</fullName>
            </value>
            <value>
                <fullName>Other Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Charges__c/fields/EYI_Global_Charges__c.field-meta.xml
<CustomField>
    <fullName>EYI_Global_Charges__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Charges</label>
    <referenceTo>EYI_Global_Charges__c</referenceTo>
    <relationshipLabel>Project Charges</relationshipLabel>
    <relationshipName>Project_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Charges__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Project Charges</relationshipLabel>
    <relationshipName>Project_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Charges__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Project Charges</relationshipLabel>
    <relationshipName>Project_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EYI_PricingCalloutTest.cls
@isTest
private class EYI_PricingCalloutTest {
    
    class MockHttpResponseGenerator implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setStatusCode(200);
            res.setBody('{"TYPE":"S","ID":"123","NUMBER":1,"n0:ZSD_CREATE_PRICE_FROM_SFResponse":{"E_RETURN":{"item":{"TYPE":"A","MESSAGE":"Success"}}}}');
            return res;
        }
    }
    
    class MockHttpResponseGenerator1 implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setStatusCode(200);
            res.setBody('{"TYPE":"S","ID":"123","NUMBER":1,"n0:ZSD_CREATE_PRICE_FROM_SFResponse":{"ABC":{"item":{"TYPE":"S","MESSAGE":"Success"}}}}');
            return res;
        }
    }
    
    class MockHttpResponseGenerator2 implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setStatusCode(200);
			res.setBody('{"TYPE":"S","ID":"123","NUMBER":1,"n0:ZSD_CREATE_PRICE_FROM_SFResponse":{"E_RETURN":{"item":[{"TYPE":"E","MESSAGE":"Error 1"},{"TYPE":"W","MESSAGE":"Warning 1"},{"TYPE":"S","MESSAGE":"Success 1"}]}}}');
            return res;
        }
    }
    
    class MockHttpResponseGenerator3 implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setStatusCode(200);
            res.setBody('{"TYPE":"S","ID":"123","NUMBER":1,"n0:ZSD_CREATE_PRICE_FROM_SFResponse":{"E_RETURN":{"item":[{"TYPE":"E","MESSAGE":"Some error message"}]}}}');
            return res;
        }
    }
    
    public static String testData(){
        EYI_Project__c proj = new EYI_Project__c(Name='Test Balewadi', EYI_SAP_Salesorg__c='1000', EYI_SAP_Plant_Code__c='P001', EYI_Project_Code__c = '123', EYI_Stamp_Duty__c= 133);
        insert proj;

        EYI_Tower__c tower = new EYI_Tower__c(Name='Test Tower', EYI_SAP_Plant_ID__c='PL01');
        insert tower;

        EYI_Inventory__c inv = new EYI_Inventory__c(Name='Inventory', EYI_Inventory_Number__c='MAT001', EYI_SAP_Material_Code__c='M123');
        insert inv;

        EYI_Global_Charges__c gcharge = new EYI_Global_Charges__c(
            Name = 'Test',
            EYI_Charge_Type__c = 'Pricing Charges',
            EYI_SAP_Material_Name__c = 'TEst'
        );
        insert gcharge;
        
        Project_Charges__c projectCharge = new Project_Charges__c(
        	Name = 'Test1234',
            EYI_Charge_Calculated_As__c = 'Rate List at Unit Level',
            EYI_Global_Charges__c = gcharge.id,
            EYI_Project__c = proj.id,
            EYI_Tower__c = tower.id,
            EYI_Active__c = true,
            EYI_Charge_Type__c = 'Pricing Charges'
        );
		insert projectCharge;
        
        EYI_Rate_List__c rate = new EYI_Rate_List__c(
            EYI_Project__c = proj.Id,
            EYI_Tower__c = tower.Id,
            EYI_Inventory__c = inv.Id,
            EYI_Condition_Type__c = 'Brokerage',
            EYI_Distruibution_Channel__c = 'Residential Sales',
            EYI_Calculation_Type__c = 'Fixed Amount',
            EYI_Pricing_Amount__c = 500,
            EYI_is_Sync_SAP__c = false,
            EYI_Global_Charges__c = gcharge.Id
        );
        insert rate;
        
        
        // Insert field mapping
        insert new SAP_SF_Field_Map__c(Name='Test123',SF_Field_Name__c='EYI_Condition_Type__c', SF_Value__c='Brokerage', SAP_Value__c='COND1');
        insert new SAP_SF_Field_Map__c(Name='Test1234',SF_Field_Name__c='EYI_Distruibution_Channel__c', SF_Value__c='Residential Sales', SAP_Value__c='CHN1');
        insert new SAP_SF_Field_Map__c(Name='Test1235',SF_Field_Name__c='EYI_Calculation_Type__c', SF_Value__c='Fixed Amount', SAP_Value__c='FA');
		
        return tower.id;
    }

    @isTest
    static void testPricingDataSyncWithTower() {
        String towerId = testData();
        // Set mock callout
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());        
        Test.startTest();
        EYI_PricingCallout.lwcMessage msg = EYI_PricingCallout.pricingDataSync(towerId);
        Test.stopTest();

        System.assertEquals('S', msg.type);
        System.assert(msg.message.contains('Pricing Synced'));
    }
    
    @isTest
    static void testPricingDataSyncWithTower1() {
        String towerId = testData();
        // Set mock callout
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator1());        
        Test.startTest();
        EYI_PricingCallout.lwcMessage msg = EYI_PricingCallout.pricingDataSync(towerId);
        Test.stopTest();

        System.assertEquals('S', msg.type);
        System.assert(msg.message.contains('Pricing Synced'));
    }
    
    @isTest
    static void testPricingDataSyncWithTower2() {
        String towerId = testData();
        // Set mock callout
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator2());        
        Test.startTest();
        EYI_PricingCallout.lwcMessage msg = EYI_PricingCallout.pricingDataSync(towerId);
        Test.stopTest();

        System.assertEquals('S', msg.type);
        System.assert(msg.message.contains('Pricing Synced'));
    }
    
    @isTest
    static void testPricingDataSyncWithTower3() {
        String towerId = testData();
        // Set mock callout
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator3());        
        Test.startTest();
        EYI_PricingCallout.lwcMessage msg = EYI_PricingCallout.pricingDataSync(towerId);
        Test.stopTest();

        System.assertEquals('S', msg.type);
        System.assert(msg.message.contains('Pricing Synced'));
    }
    
    @isTest
    static void testPricingDataSyncWithTower4() {
        String towerId = testData();
		EYI_Project__c project = [SELECT Id, Name FROM EYI_Project__c WHERE Name =: 'Test Balewadi' AND EYI_SAP_Salesorg__c =:'1000' LIMIT 1];
        // Set mock callout
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator1());        
        Test.startTest();
        EYI_PricingCallout.lwcMessage msg = EYI_PricingCallout.pricingDataSync(project.id);
        Test.stopTest();

        System.assertEquals('S', msg.type);
        System.assert(msg.message.contains('Pricing Synced'));
    }
    
    @isTest
    static void testPricingDataSyncWithTower5() {
        String towerId = testData();
		EYI_Inventory__c inventory = [SELECT Id, Name FROM EYI_Inventory__c WHERE Name =: 'Inventory' AND EYI_Inventory_Number__c =:'MAT001' LIMIT 1];
        // Set mock callout
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator1());        
        Test.startTest();
        EYI_PricingCallout.lwcMessage msg = EYI_PricingCallout.pricingDataSync(inventory.id);
        Test.stopTest();
    }
    
    @isTest
    static void processPricingRecordsTest(){
        String towerId = testData();
        EYI_Rate_List__c rate = [SELECT Id FROM EYI_Rate_List__c WHERE EYI_Tower__c = :towerId LIMIT 1];
        List<EYI_Rate_List__c> rt = new List<EYI_Rate_List__c>	();
        rt.add(rate);
        Test.startTest();
        EYI_PricingCallout.processPricingRecords(rt, true);
        Test.stopTest();
    }
    

    @isTest
    static void testPricingDataSyncWithNullId() {
        Test.startTest();
        EYI_PricingCallout.lwcMessage msg = EYI_PricingCallout.pricingDataSync(null);
        Test.stopTest();

        System.assertEquals('E', msg.type);
        System.assertEquals('Record Id Missing', msg.message);
    }
    
    @isTest
    public static void getSyncValueTest(){
        String towerID = testData();
		EYI_Project__c project = [SELECT Id, Name FROM EYI_Project__c WHERE Name =: 'Test Balewadi' AND EYI_SAP_Salesorg__c =:'1000' LIMIT 1];
        Test.startTest();
        EYI_PricingCallout.getSyncValue(project.Id, 'Pricing');
        Test.stopTest();
    }
    
    @isTest
    public static void getSyncValueTest1(){
        String towerID = testData();
		EYI_Project__c project = [SELECT Id, Name FROM EYI_Project__c WHERE Name =: 'Test Balewadi' AND EYI_SAP_Salesorg__c =:'1000' LIMIT 1];
		EYI_Inventory__c inventory = [SELECT Id, Name FROM EYI_Inventory__c WHERE Name =: 'Inventory' AND EYI_Inventory_Number__c =:'MAT001' LIMIT 1];
        inventory.EYI_Is_Syc__c = false;
        inventory.EYI_Project__c = project.Id;
        update inventory;
        Test.startTest();
        EYI_PricingCallout.getSyncValue(project.Id, 'Inventory');
        Test.stopTest();
    }
    
    @isTest
    public static void getSyncValueTest2(){
        String towerID = testData();
    EYI_Project__c project = [SELECT Id, Name FROM EYI_Project__c WHERE Name =: 'Test Balewadi' AND EYI_SAP_Salesorg__c =:'1000' LIMIT 1];
    EYI_Tower__c tower = [SELECT Id FROM EYI_Tower__c WHERE Name = 'Test Tower' LIMIT 1];
    
    EYI_Car_Park_Master__c cpm = new EYI_Car_Park_Master__c(
        EYI_Is_Syc__c = false,
        EYI_Parking_Number__c = 'C130C09014',
        EYI_Project__c = project.id,
        EYI_Tower__c = tower.id
    );
    
    Test.startTest();
    try {
        insert cpm;
    } catch (DmlException e) {
        // Handle potential trigger errors gracefully in test context
        System.debug('Car park insert failed: ' + e.getMessage());
    }
    EYI_PricingCallout.getSyncValue(project.Id, '');
    Test.stopTest();
}
}