force-app/main/default/objects/EYI_Car_Park_Master__c/EYI_Car_Park_Master__c.object-meta.xml
<CustomObject>
    <label>Car Park Master</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Car Parking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Park Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Distruibution_Channel__c.field-meta.xml
<CustomField>
    <fullName>EYI_Distruibution_Channel__c</fullName>
    <label>Distruibution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential Sales</fullName>
            </value>
            <value>
                <fullName>Commercial Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Inventory__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <referenceTo>EYI_Inventory__c</referenceTo>
    <relationshipLabel>Car Park Masters</relationshipLabel>
    <relationshipName>Car_Park_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Is_Syc__c.field-meta.xml
<CustomField>
    <fullName>EYI_Is_Syc__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Syc</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Car Park Masters</relationshipLabel>
    <relationshipName>Car_Park_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_SAP_Error__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Error__c</fullName>
    <label>SAP Error</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.EYI_Project__c</field>
            <operation>equals</operation>
            <valueField>EYI_Tower__c.EYI_Project_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Car Park Masters</relationshipLabel>
    <relationshipName>Car_Park_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/EYI_Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Inventory_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Inventory Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Is_Syc__c.field-meta.xml
<CustomField>
    <fullName>EYI_Is_Syc__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Syc</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_SAP_Material_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Material_Code__c</fullName>
    <externalId>true</externalId>
    <label>SAP Material Code</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>EYI_Tower__c.EYI_SubProject_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.EYI_SubProject__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/EYI_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Project__c/fields/EYI_SAP_Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Plant_Code__c</fullName>
    <label>SAP Plant Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_SAP_Salesorg__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Salesorg__c</fullName>
    <label>SAP Sales-org</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/EYI_Rate_List__c.object-meta.xml
<CustomObject>
    <label>Rate List</label>
    <nameField>
        <displayFormat>Rate List-{00}</displayFormat>
        <label>Rate List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Calculation_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Calculation_Type__c</fullName>
    <label>Calculation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Fixed Amount</fullName>
            </value>
            <value>
                <fullName>Quantity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Condition_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Condition_Type__c</fullName>
    <label>Condition Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Infra Charges</fullName>
            </value>
            <value>
                <fullName>Base Price</fullName>
            </value>
            <value>
                <fullName>Brokerage Additional</fullName>
            </value>
            <value>
                <fullName>Brokerage</fullName>
            </value>
            <value>
                <fullName>Club House</fullName>
            </value>
            <value>
                <fullName>Floor Rise</fullName>
            </value>
            <value>
                <fullName>Land Cost</fullName>
            </value>
            <value>
                <fullName>2 Wheeler Charges</fullName>
            </value>
            <value>
                <fullName>Base Price-Booking</fullName>
            </value>
            <value>
                <fullName>MSEB Charges</fullName>
            </value>
            <value>
                <fullName>STAMP DUTY AND REG - RECOVERABLE</fullName>
            </value>
            <value>
                <fullName>STAMP DUTY NON RECOVERABLE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Distruibution_Channel__c.field-meta.xml
<CustomField>
    <fullName>EYI_Distruibution_Channel__c</fullName>
    <label>Distruibution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential Sales</fullName>
            </value>
            <value>
                <fullName>Commercial Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Inventory__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory</label>
    <referenceTo>EYI_Inventory__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_is_Sync_SAP__c.field-meta.xml
<CustomField>
    <fullName>EYI_is_Sync_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Sync SAP?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Non_Master_Price__c.field-meta.xml
<CustomField>
    <fullName>EYI_Non_Master_Price__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non Master Price</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Pricing_Amount__c.field-meta.xml
<CustomField>
    <fullName>EYI_Pricing_Amount__c</fullName>
    <label>Pricing Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Pricing_Percentage__c.field-meta.xml
<CustomField>
    <fullName>EYI_Pricing_Percentage__c</fullName>
    <label>Pricing Percentage</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Pricing_Quantity__c.field-meta.xml
<CustomField>
    <fullName>EYI_Pricing_Quantity__c</fullName>
    <label>Pricing Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Rate__c.field-meta.xml
<CustomField>
    <fullName>EYI_Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_SAP_Error__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Error__c</fullName>
    <label>SAP Error</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_SAP_Request__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Request__c</fullName>
    <label>SAP Request</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Tower__c/EYI_Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Tower__c/fields/EYI_SAP_Plant_ID__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Plant_ID__c</fullName>
    <label>SAP Plant Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_SF_Field_Map__c/SAP_SF_Field_Map__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SAP SF Field Map</label>
</CustomObject>

force-app/main/default/objects/SAP_SF_Field_Map__c/fields/SAP_Value__c.field-meta.xml
<CustomField>
    <fullName>SAP_Value__c</fullName>
    <label>SAP Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_SF_Field_Map__c/fields/SF_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>SF_Field_Name__c</fullName>
    <label>SF Field Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_SF_Field_Map__c/fields/SF_Value__c.field-meta.xml
<CustomField>
    <fullName>SF_Value__c</fullName>
    <label>SF Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EYI_PricingCallout.cls
public class EYI_PricingCallout {
    @AuraEnabled
    public static lwcMessage pricingDataSync(String recordId ){
        lwcMessage lm = new lwcMessage();
        Boolean isPATCHOperation = false;
        
        
        if(recordId!= null){
            SObjectType sobjTypeId = Id.valueOf(recordId).getSObjectType();
            System.debug('sobjTypeId: ' + sobjTypeId);
            
            if (sobjTypeId == EYI_Tower__c.SObjectType) {          
                EYI_Tower__c RecTower= [Select id , name ,
                                        (select id,EYI_Condition_Type__c, EYI_Tower__r.EYI_SAP_Plant_ID__c, EYI_Non_Master_Price__c, EYI_Project__r.EYI_SAP_Salesorg__c,EYI_Project__r.EYI_SAP_Plant_Code__c, EYI_Pricing_Amount__c,EYI_Pricing_Percentage__c,
                                         EYI_Pricing_Quantity__c,EYI_Calculation_Type__c, EYI_Rate__c, EYI_Inventory__r.EYI_Inventory_Number__c,EYI_Distruibution_Channel__c,EYI_is_Sync_SAP__c,
                                         EYI_Inventory__r.EYI_SAP_Material_Code__c
                                         from Rate_Lists__r where EYI_is_Sync_SAP__c=false AND EYI_Non_Master_Price__c= false order by createddate asc)
                                        from EYI_Tower__c where id=:recordId limit 1];
                
                if(RecTower!= null){
                    return processPricingRecords(RecTower.Rate_Lists__r, isPATCHOperation);
                }
            }Else if(sobjTypeId == EYI_Project__c.SObjectType){
                EYI_Project__c RecProject= [Select id , name ,
                                            (select id,EYI_Condition_Type__c, EYI_Non_Master_Price__c, EYI_Tower__r.EYI_SAP_Plant_ID__c, EYI_Project__r.EYI_SAP_Salesorg__c,EYI_Project__r.EYI_SAP_Plant_Code__c, EYI_Pricing_Amount__c,EYI_Pricing_Percentage__c,
                                             EYI_Pricing_Quantity__c,EYI_Calculation_Type__c, EYI_Rate__c, EYI_Inventory__r.EYI_Inventory_Number__c,EYI_Distruibution_Channel__c,EYI_is_Sync_SAP__c,
                                             EYI_Inventory__r.EYI_SAP_Material_Code__c
                                             from Rate_Lists__r where EYI_is_Sync_SAP__c=false AND EYI_Non_Master_Price__c= false order by createddate asc)
                                            from EYI_Project__c where id=:recordId limit 1];
                if(RecProject!= null){
                    return processPricingRecords(RecProject.Rate_Lists__r, isPATCHOperation);
                    
                }
            }else {
                lm.type = 'E';
                lm.message = 'Unsupported record type for Pricing Sync';
                return lm;
            }   
        }else{
            
            lm.type =  'E';
            lm.message = 'Record Id Missing';
            return lm;
        }
        return null;
    }
    public static lwcMessage processPricingRecords(List<EYI_Rate_List__c> PricingList,  Boolean isPATCHOperation) {
        Map<String, String> sfmapSAP = new Map<String, String>();
        String PricingId ='';
        lwcMessage lm = new lwcMessage();
        EYI_PricingCreationWrapper pc = new EYI_PricingCreationWrapper();
        EYI_PricingCreationWrapper.IMaster imast = new EYI_PricingCreationWrapper.IMaster();
        
        system.debug('PricingList size --> '+ PricingList.size());
        // List<EYI_PricingCreationWrapper.EReturn> pcRetunr =new List<EYI_PricingCreationWrapper.EReturn>();
        // List<EYI_PricingCreationWrapper.item> pcRetunr =new List<EYI_PricingCreationWrapper.item>();
        List<SAP_SF_Field_Map__c> mapData = [select Id, Name, SF_Field_Name__c, SF_Value__c, SAP_Value__c from SAP_SF_Field_Map__c 
                                             where SF_Field_Name__c IN ('EYI_Condition_Type__c','EYI_Distruibution_Channel__c','EYI_Calculation_Type__c')];
        if(!mapData.isEmpty()){
            for(SAP_SF_Field_Map__c mp :mapData){
                sfmapSAP.put(mp.SF_Field_Name__c + '~' + mp.SF_Value__c, mp.SAP_Value__c);
                system.debug('key'+mp.SF_Field_Name__c + '~' + mp.SF_Value__c+'value'+mp.SAP_Value__c);
            } 
        }
        try{
             
            for(EYI_Rate_List__c rl :PricingList){
                PricingId= rl.id;
                // EYI_PricingCreationWrapper.EReturn er = new EYI_PricingCreationWrapper.EReturn();
                EYI_PricingCreationWrapper.cls_item er = new EYI_PricingCreationWrapper.cls_item();
                
                if(rl.EYI_Condition_Type__c !=null && sfmapSAP.containsKey('EYI_Condition_Type__c'+'~'+rl.EYI_Condition_Type__c)) 
                    if(rl.EYI_Condition_Type__c == 'Base Price'){
                        er.KSCHL='ZRCP';
                    }else{
                        er.KSCHL = sfmapSAP.get('EYI_Condition_Type__c'+'~'+rl.EYI_Condition_Type__c);// '1';//test
                    }
                    
                if(rl.EYI_Project__c!=null && rl.EYI_Project__r.EYI_SAP_Salesorg__c!=null)   
                    er.VKORG =rl.EYI_Project__r.EYI_SAP_Salesorg__c ;
                if(rl.EYI_Tower__c!=null && rl.EYI_Tower__r.EYI_SAP_Plant_ID__c!=null)       
                    er.WERKS = rl.EYI_Tower__r.EYI_SAP_Plant_ID__c;
                if(rl.EYI_Distruibution_Channel__c!=null  && sfmapSAP.containsKey('EYI_Distruibution_Channel__c'+'~'+rl.EYI_Distruibution_Channel__c))
                    er.VTWEG = sfmapSAP.get('EYI_Distruibution_Channel__c'+'~'+rl.EYI_Distruibution_Channel__c);
                if(rl.EYI_Inventory__c !=null )   
                    er.MATNR = rl.EYI_Inventory__r.EYI_Inventory_Number__c;
                if(rl.EYI_Calculation_Type__c!=null){
                    if(rl.EYI_Calculation_Type__c =='Percentage' && rl.EYI_Pricing_Percentage__c!=null) 
                        er.KBETR = rl.EYI_Pricing_Percentage__c;
                    else if(rl.EYI_Calculation_Type__c =='Fixed Amount' && rl.EYI_Pricing_Amount__c!=null) 
                        er.KBETR = rl.EYI_Pricing_Amount__c;
                    else if(rl.EYI_Calculation_Type__c =='Quantity' && rl.EYI_Rate__c!=null) 
                        er.KBETR = rl.EYI_Rate__c;
                }
                if(rl.EYI_Calculation_Type__c !=null &&  sfmapSAP.containsKey('EYI_Calculation_Type__c'+'~'+rl.EYI_Calculation_Type__c))   
                    er.KRECH = sfmapSAP.get('EYI_Calculation_Type__c'+'~'+rl.EYI_Calculation_Type__c);
                
                imast.item.add(er);
            }
            // system.debug('Genrate jsonBody'+imast);
            
            //for loop end
            // pc.E_RETURN = pcRetunr;
            //imast.item = pcRetunr;
            pc.I_MASTER = imast;
            HttpRequest req = new HttpRequest();
            String jsonBody =JSON.serialize(pc);
            
           	HTTPResponse res = new HTTPResponse();
            res = EY_SAP_Gateway.pricingSync(jsonBody);
            /*system.debug('Genrate jsonBody'+jsonBody);
            req.setBody(jsonBody);
            req.setMethod('POST'); 
            req.setTimeout(120000);
            
            req.setEndpoint('callout:SAP_Integration_Base' +'/CreatePriceMasterSalesForce' );
            // Create an HTTP object to send the request
            Http http = new Http();
            HttpResponse res;
            
            // Send the HTTP request and get the response
            res = http.send(req);*/
            
            // Check the response status code
            if (res.getStatusCode() == 200) {
                system.debug('Success jsonBody-->: '+res.getBody());
                Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
                String typeVal = (String) responseMap.get('TYPE');
                String idVal = (String) responseMap.get('ID');
                Integer numberVal = (Integer) responseMap.get('NUMBER');
                //String type = (String) responseMap.get('MESSAGE');
                // Extract the "n0:ZSD_CREATE_PRICE_FROM_SFResponse" field from the map
                
                Map<String, Object> PricingResponse = (Map<String, Object>) responseMap.get('n0:ZSD_CREATE_PRICE_FROM_SFResponse');
                system.debug('PricingResponse-->'+PricingResponse);
                // Now you can access individual fields within the "item" map
                String type = '';
                String messagDisp = '';
                // Extract the message from vendorResponse map.
                if(PricingResponse.containskey('E_RETURN')){
                    Map<String, Object> E_RETURN = (Map<String, Object>) PricingResponse.get('E_RETURN');
                    system.debug('E_RETURN  '+E_RETURN);
                    Object item =  E_RETURN.get('item');
                    system.debug('item-->'+item);
                    
                    
                    if (item instanceof List<Object>) {
                        List<Object> itemList = (List<Object>) item;
                        
                        for (Object obj : itemList) {
                            Map<String, Object> objitem = (Map<String, Object>) obj;
                            string types =(String) objitem.get('TYPE');
                            //system.debug('Updating type '+type);
                            // if (!type.contains('S')) {
                            if(types!='S'){
                                type =(String) objitem.get('TYPE');
                                system.debug('Updating type  inside S loop '+types);
                                messagDisp =messagDisp+'\n--'+ (String) objitem.get('MESSAGE');
                            }
                        }
                    }else if(item instanceof Map<String, Object>){
                        SYSTEM.DEBUG('item   '+item);
                        Map<String, Object> objitem = (Map<String, Object>) item;
                        SYSTEM.DEBUG('objitem   '+objitem);
                        type =  (String) objitem.get('TYPE');
                        
                        if(type!='S'){
                            type =(String) objitem.get('TYPE');
                            system.debug('Updating type  inside S loop '+type);
                            messagDisp =messagDisp+'\n--'+ (String) objitem.get('MESSAGE');
                        }
                    }
                }else{
                    type= 'E';
                    messagDisp='E_RETURN do not get any value';
                }
                System.debug('messagDisp ::: '+messagDisp);
                System.debug('type ::: '+type);
                System.debug('isPATCHOperation ::: '+isPATCHOperation);
                if(messagDisp!=null && type!=null && isPATCHOperation ==true){
                    EYI_Rate_List__c recUpd = new EYI_Rate_List__c();
                    recUpd.Id =PricingId;
                    recUpd.EYI_SAP_Error__c = messagDisp;
                    //recUpd.EYI_SAP_Request__c = jsonBody;
                    update recUpd;
                    system.debug('Updating Pricing code');
                    
                }else{
                    System.debug('Inside else to Update SF Paricing Data '+PricingList.Size());
                    list<EYI_Rate_List__c> updatelist= new  list<EYI_Rate_List__c>();
                    for(EYI_Rate_List__c invoBJ : PricingList){
                        invoBJ.EYI_is_Sync_SAP__c = true;  
                        updatelist.add(invoBJ);
                    }
                    System.debug('updatelist : '+updatelist.Size());
                    if(updatelist.size()>0){
                        update updatelist;
                        Type ='S';
                        messagDisp = updatelist.size()+' Pricing Synced to SAP Successfully.';
                    }
                }
                SYSTEM.DEBUG('type   '+type);
                SYSTEM.DEBUG('messagDisp   '+messagDisp);
                lm.type =  type;
                lm.message = messagDisp;
                SYSTEM.DEBUG('lm   '+lm);
                return lm;                
            }
            
        }catch(exception e){
            system.debug('error-->'+e.getMessage());
            lwcMessage lm2 = new lwcMessage();
            lm2.type =  'E';
            lm2.message = e.getMessage()+'---' +e.getLineNumber();
            return lm2;
        }
        return null;
    }
    
    @AuraEnabled(cacheable=true)
    public static Boolean getSyncValue(Id projectId, String lwc){
        Boolean isSynced = true;
        try{
            if(lwc == 'Pricing'){
                List<EYI_Rate_List__c> rateList = [Select Id, EYI_is_Sync_SAP__c from EYI_Rate_List__c where EYI_Project__c = :projectId and EYI_is_Sync_SAP__c = false AND EYI_Non_Master_Price__c= false];
                if(rateList.size() > 0){
                    isSynced = false;
                }
            }
            else if(lwc == 'Inventory'){
                List<EYI_Inventory__c> inventoryList = [Select Id, EYI_Is_Syc__c from EYI_Inventory__c where EYI_Project__c = :projectId and EYI_Is_Syc__c = false];
                if(inventoryList.size() > 0){
                    isSynced = false;
                }
            }
            else{
                List<EYI_Car_Park_Master__c	> carParkList = [Select Id, EYI_Is_Syc__c from EYI_Car_Park_Master__c	 where EYI_Project__c = :projectId and EYI_Is_Syc__c = false];
                if(carParkList.size() > 0){
                    isSynced = false;
                }
            }
        }
        catch(Exception e){
            System.debug('Exception--->'+e);
        }
        return isSynced;
    }
    public class lwcMessage{
        @AuraEnabled  public string type;
        @AuraEnabled  public string message;
    }
}