force-app/main/default/objects/EYI_Car_Park_Master__c/EYI_Car_Park_Master__c.object-meta.xml
<CustomObject>
    <label>Car Park Master</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Car Parking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Park Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Inventory__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <referenceTo>EYI_Inventory__c</referenceTo>
    <relationshipLabel>Car Park Masters</relationshipLabel>
    <relationshipName>Car_Park_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Parking_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Parking_Number__c</fullName>
    <externalId>true</externalId>
    <label>Parking Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Car Park Masters</relationshipLabel>
    <relationshipName>Car_Park_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.EYI_Project__c</field>
            <operation>equals</operation>
            <valueField>EYI_Tower__c.EYI_Project_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Car Park Masters</relationshipLabel>
    <relationshipName>Car_Park_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/EYI_Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Inventory_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Inventory Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>EYI_Tower__c.EYI_SubProject_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.EYI_SubProject__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/EYI_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Project_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Code__c</fullName>
    <label>Project Code</label>
    <length>55</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/EYI_Rate_List__c.object-meta.xml
<CustomObject>
    <label>Rate List</label>
    <nameField>
        <displayFormat>Rate List-{00}</displayFormat>
        <label>Rate List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Inventory__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory</label>
    <referenceTo>EYI_Inventory__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Tower__c/EYI_Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Tower__c/fields/EYI_Project_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EYI_FutureCalloutClassTest.cls
@isTest
public class EYI_FutureCalloutClassTest {
    private class EYI_HttpCalloutMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setBody('{"success": true}');
            res.setStatusCode(200);
            return res;
        }
    }

    @isTest
    static void testCarParkingDataSync() {
        Test.setMock(HttpCalloutMock.class, new EYI_HttpCalloutMock());
        Account acc = new Account();
        acc.Name= 'Test';
        insert acc;
        Test.startTest();
        EYI_FutureCalloutClass.carParkingDataSync(new Set<Id>{acc.Id});
        Test.stopTest();
        System.assert(true, 'Test ran without unmocked callout errors.');
    }
    
	@isTest
	static void testPricingDataSync() {
    	// Insert parent project
    	EYI_Project__c project = new EYI_Project__c(
       		Name = 'Test Project',
        	EYI_Project_Code__c = 'PRJ-001'
    	);
    	insert project;

    	// Insert tower (if required by Inventory)
    	EYI_Tower__c tower = new EYI_Tower__c(
        	Name = 'Test Tower',
        	EYI_Project_Name__c = project.Id
    	);
    	insert tower;

    	// Insert inventory
    	EYI_Inventory__c inventory = new EYI_Inventory__c(
        	EYI_Project__c = project.Id,
        	EYI_Tower__c = tower.Id,
            EYI_Inventory_Number__c = 'INV-001'
    	);
    	insert inventory;

    	// Insert rate list, referencing inventory
    	EYI_Rate_List__c rate = new EYI_Rate_List__c(
        	EYI_Inventory__c = inventory.Id
    	);
    	insert rate;

    	// Set up and call your test
    	Test.setMock(HttpCalloutMock.class, new EYI_HttpCalloutMock());
    	Test.startTest();
    	EYI_FutureCalloutClass.pricingDataSync(new Set<Id>{ rate.Id });
    	Test.stopTest();
	}
    
	@isTest
	static void testInventoryDataSync() {
    	// Insert required parent: Project
    	EYI_Project__c project = new EYI_Project__c(
        	Name = 'Test Project',
        	EYI_Project_Code__c = 'PRJ-002'
    	);
    	insert project;

    	// Insert required parent: Tower (if needed)
    	EYI_Tower__c tower = new EYI_Tower__c(
       	 	Name = 'Test Tower',
        	EYI_Project_Name__c = project.Id
    	);
    	insert tower;

    	// Insert Inventory with all required fields
    	EYI_Inventory__c inv = new EYI_Inventory__c(
        	EYI_Project__c = project.Id,
        	EYI_Tower__c = tower.Id,
        	EYI_Inventory_Number__c = 'INV-002'
    	);
    	insert inv;

    	Test.setMock(HttpCalloutMock.class, new EYI_HttpCalloutMock());
    	Test.startTest();
    	EYI_FutureCalloutClass.inventoryDataSync(new Set<Id>{ inv.Id }, true);
    	Test.stopTest();
	}
    
	@isTest
	static void testCarParkingDataSync2() {
    	// Insert required parent: Project
    	EYI_Project__c project = new EYI_Project__c(
        	Name = 'Test Project',
        	EYI_Project_Code__c = 'PRJ-003'
    	);
    	insert project;

    	// Insert required parent: Tower (if needed)
    	EYI_Tower__c tower = new EYI_Tower__c(
        	Name = 'Test Tower',
        	EYI_Project_Name__c = project.Id
    	);
    	insert tower;

    	// Insert required inventory (if needed by Car Park)
    	EYI_Inventory__c inventory = new EYI_Inventory__c(
        	EYI_Project__c = project.Id,
        	EYI_Tower__c = tower.Id,
        	EYI_Inventory_Number__c = 'INV-003'
    	);
    	insert inventory;

    	// Insert Car Park Master with required lookup(s)
    	EYI_Car_Park_Master__c carPark = new EYI_Car_Park_Master__c(
        	EYI_Project__c = project.Id,
        	EYI_Tower__c = tower.Id,
        	EYI_Inventory__c = inventory.Id,
            EYI_Parking_Number__c = 'PARK-001'
    	);
    	insert carPark;

    	Test.setMock(HttpCalloutMock.class, new EYI_HttpCalloutMock());
    	Test.startTest();
    	EYI_FutureCalloutClass.carParkingDataSync(new Set<Id>{ carPark.Id });
    	Test.stopTest();
	}  
}