force-app/main/default/objects/EYI_Car_Park_Master__c/EYI_Car_Park_Master__c.object-meta.xml
<CustomObject>
    <label>Car Park Master</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Car Parking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Park Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Built_up_Area__c.field-meta.xml
<CustomField>
    <fullName>EYI_Built_up_Area__c</fullName>
    <label>Built-up Area</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Inventory__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <referenceTo>EYI_Inventory__c</referenceTo>
    <relationshipLabel>Car Park Masters</relationshipLabel>
    <relationshipName>Car_Park_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Is_Syc__c.field-meta.xml
<CustomField>
    <fullName>EYI_Is_Syc__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Syc</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Parking_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Parking_Number__c</fullName>
    <externalId>true</externalId>
    <label>Parking Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Parking_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Parking_Type__c</fullName>
    <label>Parking Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ground Podium</fullName>
            </value>
            <value>
                <fullName>Mezzaine Podium</fullName>
            </value>
            <value>
                <fullName>Ground Stilt</fullName>
            </value>
            <value>
                <fullName>Covered Parking</fullName>
            </value>
            <value>
                <fullName>Open Car Parking</fullName>
            </value>
            <value>
                <fullName>Stack Car Parking</fullName>
            </value>
            <value>
                <fullName>Two Wheeler Parking</fullName>
            </value>
            <value>
                <fullName>VILLA V3</fullName>
                <label>Garage V3</label>
            </value>
            <value>
                <fullName>VILLA V1</fullName>
                <label>Garage V1</label>
            </value>
            <value>
                <fullName>VILLA V2</fullName>
                <label>Garage V2</label>
            </value>
            <value>
                <fullName>Measurement Podium</fullName>
                <isActive>false</isActive>
                <label>Measurement Podium</label>
            </value>
            <value>
                <fullName>Tanti Villa</fullName>
                <isActive>false</isActive>
                <label>Tanti Villa</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Car Park Masters</relationshipLabel>
    <relationshipName>Car_Park_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.EYI_Project__c</field>
            <operation>equals</operation>
            <valueField>EYI_Tower__c.EYI_Project_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Car Park Masters</relationshipLabel>
    <relationshipName>Car_Park_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/EYI_Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Built_up_Area__c.field-meta.xml
<CustomField>
    <fullName>EYI_Built_up_Area__c</fullName>
    <label>Built-up Area</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Inventory_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Inventory Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Is_Syc__c.field-meta.xml
<CustomField>
    <fullName>EYI_Is_Syc__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Syc</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Parking_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Parking_Type__c</fullName>
    <label>Parking Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parking - Conventional</fullName>
            </value>
            <value>
                <fullName>Parking - Electrical Veh.</fullName>
            </value>
            <value>
                <fullName>Parking - Stack</fullName>
            </value>
            <value>
                <fullName>Parking - Puzzle</fullName>
            </value>
            <value>
                <fullName>Parking - BIG</fullName>
            </value>
            <value>
                <fullName>Parking - Big &amp; Small</fullName>
            </value>
            <value>
                <fullName>Parking - MLCP</fullName>
            </value>
            <value>
                <fullName>Parking - Small</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>EYI_Tower__c.EYI_SubProject_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.EYI_SubProject__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/EYI_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Project_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Code__c</fullName>
    <label>Project Code</label>
    <length>55</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/EYI_Rate_List__c.object-meta.xml
<CustomObject>
    <label>Rate List</label>
    <nameField>
        <displayFormat>Rate List-{00}</displayFormat>
        <label>Rate List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Inventory__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory</label>
    <referenceTo>EYI_Inventory__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Tower__c/EYI_Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Tower__c/fields/EYI_Project_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EYI_CarParkingTriggerHandlerTest.cls
@isTest
public class EYI_CarParkingTriggerHandlerTest {

    @isTest
    static void testHandleBeforeUpdate_FieldChangedAndFutureCallout() {
        // Test that EYI_Is_Syc__c is set to false when EYI_Built_up_Area__c changes
        EYI_Project__c proj = new EYI_Project__c(Name='Test Project', EYI_Project_Code__c='P001');
        insert proj;

        EYI_Tower__c tower = new EYI_Tower__c(Name='Tower 1', EYI_Project_Name__c=proj.Id);
        insert tower;
		
       	EYI_Inventory__c inv = new EYI_Inventory__c(
    		Name = 'Test Inventory',
    		EYI_Inventory_Number__c = 'INV-TEST-001'
		);
		insert inv;
        
        EYI_Car_Park_Master__c carPark = new EYI_Car_Park_Master__c(
            EYI_Built_up_Area__c = 500,
            EYI_Is_Syc__c = true,
            EYI_Parking_Number__c = 'P1',
            EYI_Project__c = proj.Id,
            EYI_Tower__c = tower.Id,
            EYI_Inventory__c = inv.Id
            // Remove EYI_Rate_List__c and EYI_Parking_Type__c unless you confirm their correct API names and types
        );
        insert carPark;
		
        Test.setMock(HttpCalloutMock.class, new CarParkingCalloutMock());
        
        Test.startTest();
        carPark.EYI_Built_up_Area__c = 600;
        update carPark;
        Test.stopTest();

        EYI_Car_Park_Master__c updated = [
            SELECT EYI_Is_Syc__c FROM EYI_Car_Park_Master__c WHERE Id = :carPark.Id
        ];
        System.assertEquals(false, updated.EYI_Is_Syc__c, 'EYI_Is_Syc__c should be set to false when area changes');
    }

    @isTest
    static void testHandleBeforeUpdate_MultipleRecords_NoFutureCallout() {
        // Test that multiple records are handled correctly
        EYI_Project__c proj1 = new EYI_Project__c(Name='Test Project 1', EYI_Project_Code__c='P002');
        EYI_Project__c proj2 = new EYI_Project__c(Name='Test Project 2', EYI_Project_Code__c='P003');
        insert new List<EYI_Project__c>{proj1, proj2};

        EYI_Tower__c tower1 = new EYI_Tower__c(Name='Tower 1', EYI_Project_Name__c=proj1.Id);
        EYI_Tower__c tower2 = new EYI_Tower__c(Name='Tower 2', EYI_Project_Name__c=proj2.Id);
        insert new List<EYI_Tower__c>{tower1, tower2};

        EYI_Inventory__c inv1 = new EYI_Inventory__c(
    		Name = 'Test Inv 1',
    		EYI_Inventory_Number__c = 'INV-MULTI-1'
		);

        EYI_Inventory__c inv2 = new EYI_Inventory__c(
    		Name = 'Test Inv 2',
    		EYI_Inventory_Number__c = 'INV-MULTI-2'
		);

        insert new List<EYI_Inventory__c>{inv1, inv2};
        
        EYI_Car_Park_Master__c carPark1 = new EYI_Car_Park_Master__c(
            EYI_Built_up_Area__c = 300, EYI_Is_Syc__c = true, EYI_Parking_Number__c = 'P2', EYI_Project__c = proj1.Id, EYI_Tower__c = tower1.Id, EYI_Inventory__c = inv1.Id
        );
        EYI_Car_Park_Master__c carPark2 = new EYI_Car_Park_Master__c(
            EYI_Built_up_Area__c = 400, EYI_Is_Syc__c = true, EYI_Parking_Number__c = 'P3', EYI_Project__c = proj2.Id, EYI_Tower__c = tower2.Id, EYI_Inventory__c = inv2.Id
        );
        insert new List<EYI_Car_Park_Master__c>{carPark1, carPark2};
		
        Test.setMock(HttpCalloutMock.class, new CarParkingCalloutMock());
            
        Test.startTest();
        carPark1.EYI_Built_up_Area__c = 310;
        carPark2.EYI_Built_up_Area__c = 420;
        update new List<EYI_Car_Park_Master__c>{carPark1, carPark2};
        Test.stopTest();

        List<EYI_Car_Park_Master__c> updated = [
            SELECT EYI_Is_Syc__c FROM EYI_Car_Park_Master__c WHERE Id IN :new List<Id>{carPark1.Id, carPark2.Id}
        ];
        for (EYI_Car_Park_Master__c cp : updated) {
            System.assertEquals(false, cp.EYI_Is_Syc__c, 'EYI_Is_Syc__c should be set to false for all updated records');
        }
    }

    @isTest
    static void testNoFieldChange_IsSycRemainsTrue() {
        // Test that EYI_Is_Syc__c remains true if EYI_Built_up_Area__c is not changed
    	EYI_Project__c proj = new EYI_Project__c(Name='Test Project N', EYI_Project_Code__c='P00N');
   		insert proj;

    	EYI_Tower__c tower = new EYI_Tower__c(Name='Tower N', EYI_Project_Name__c=proj.Id);
    	insert tower;

    	EYI_Inventory__c inv = new EYI_Inventory__c(
        	Name = 'Test Inventory',
        	EYI_Inventory_Number__c = 'INV-TEST-007'
    	);
    	insert inv;

    	EYI_Car_Park_Master__c carPark = new EYI_Car_Park_Master__c(
        	EYI_Built_up_Area__c = 950,
        	EYI_Is_Syc__c = true,
        	EYI_Parking_Number__c = 'P7',
        	EYI_Project__c = proj.Id,
        	EYI_Tower__c = tower.Id,
        	EYI_Inventory__c = inv.Id // <-- THIS LINE FIXES THE ERROR
    	);
    	insert carPark;
		Test.setMock(HttpCalloutMock.class, new CarParkingCalloutMock());
        Test.startTest();
        update carPark;
        Test.stopTest();

        EYI_Car_Park_Master__c updated = [
            SELECT EYI_Is_Syc__c FROM EYI_Car_Park_Master__c WHERE Id = :carPark.Id
        ];
        System.assertEquals(true, updated.EYI_Is_Syc__c, 'EYI_Is_Syc__c should remain true if area does not change');
    }

    @isTest
    static void testIsSycInitiallyFalse() {
        // Test that EYI_Is_Syc__c remains false if it is already false
        EYI_Project__c proj = new EYI_Project__c(Name='Test Project 4', EYI_Project_Code__c='P005');
        insert proj;

        EYI_Tower__c tower = new EYI_Tower__c(Name='Tower 4', EYI_Project_Name__c=proj.Id);
        insert tower;

        EYI_Inventory__c inv = new EYI_Inventory__c(
    		Name = 'Test Inventory',
    		EYI_Inventory_Number__c = 'INV-TEST-005'
		);
		insert inv;

		EYI_Car_Park_Master__c carPark = new EYI_Car_Park_Master__c(
    		EYI_Built_up_Area__c = 800,
    		EYI_Is_Syc__c = false,
    		EYI_Parking_Number__c = 'P5',
    		EYI_Project__c = proj.Id,
    		EYI_Tower__c = tower.Id,
    		EYI_Inventory__c = inv.Id 
		);
		insert carPark;
		Test.setMock(HttpCalloutMock.class, new CarParkingCalloutMock());
        Test.startTest();
        carPark.EYI_Built_up_Area__c = 900;
        update carPark;
        Test.stopTest();

        EYI_Car_Park_Master__c updated = [
            SELECT EYI_Is_Syc__c FROM EYI_Car_Park_Master__c WHERE Id = :carPark.Id
        ];
        System.assertEquals(false, updated.EYI_Is_Syc__c, 'EYI_Is_Syc__c should remain false if it was already false');
    }

    @isTest
    static void testInsertPath() {
        // Test that EYI_Is_Syc__c is true on insert
        EYI_Project__c proj = new EYI_Project__c(Name='Test Project 5', EYI_Project_Code__c='P006');
        insert proj;

        EYI_Tower__c tower = new EYI_Tower__c(Name='Tower 5', EYI_Project_Name__c=proj.Id);
        insert tower;

        EYI_Inventory__c inv = new EYI_Inventory__c(
    		Name = 'Test Inventory',
    		EYI_Inventory_Number__c = 'INV-TEST-006'
		);
		insert inv;
		
        Test.setMock(HttpCalloutMock.class, new CarParkingCalloutMock());
        
		EYI_Car_Park_Master__c carPark = new EYI_Car_Park_Master__c(
    		EYI_Built_up_Area__c = 900,
    		EYI_Is_Syc__c = true,
    		EYI_Parking_Number__c = 'P6',
    		EYI_Project__c = proj.Id,
	    	EYI_Tower__c = tower.Id,
    		EYI_Inventory__c = inv.Id 
		);
		insert carPark;

        EYI_Car_Park_Master__c inserted = [
            SELECT EYI_Is_Syc__c, EYI_Built_up_Area__c FROM EYI_Car_Park_Master__c WHERE Id = :carPark.Id
        ];
        System.assertEquals(true, inserted.EYI_Is_Syc__c, 'EYI_Is_Syc__c should be true on insert');
    }

    @isTest
    static void testUpdateWithSameValue() {
    	EYI_Project__c proj = new EYI_Project__c(Name='Test Project', EYI_Project_Code__c='P008');
    	insert proj;

    	EYI_Tower__c tower = new EYI_Tower__c(Name='Tower 8', EYI_Project_Name__c=proj.Id);
    	insert tower;

        EYI_Inventory__c inv = new EYI_Inventory__c(
        	Name = 'Test Inventory',
        	EYI_Inventory_Number__c = 'INV-TEST-008'
    	);
    	insert inv;
        
    	EYI_Car_Park_Master__c carPark = new EYI_Car_Park_Master__c(
        	EYI_Built_up_Area__c = 1000,
        	EYI_Is_Syc__c = true,
        	EYI_Parking_Number__c = 'P8',
        	EYI_Project__c = proj.Id,
        	EYI_Tower__c = tower.Id,
            EYI_Inventory__c = inv.Id
    	);
    	insert carPark;
        
		Test.setMock(HttpCalloutMock.class, new CarParkingCalloutMock());
        
        Test.startTest();
        carPark.EYI_Built_up_Area__c = 1000;// No actual change
        update carPark;
        Test.stopTest();

        EYI_Car_Park_Master__c updated = [
            SELECT EYI_Is_Syc__c FROM EYI_Car_Park_Master__c WHERE Id = :carPark.Id
        ];
        System.assertEquals(true, updated.EYI_Is_Syc__c, 'EYI_Is_Syc__c should remain true if value does not change');
    }
}