force-app/main/default/objects/EYI_Applied_Project_Charge__c/EYI_Applied_Project_Charge__c.object-meta.xml
<CustomObject>
    <description>Junction object of Quote and Project Charge</description>
    <label>Applied Project Charge</label>
    <nameField>
        <label>Applied Project Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applied Project Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Applied_Project_Charge__c/fields/EYI_Quote__c.field-meta.xml
<CustomField>
    <fullName>EYI_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Applied Project Charges</relationshipLabel>
    <relationshipName>Applied_Project_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Booking__c/EYI_Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>BF-{0000000}</displayFormat>
        <label>Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Booking__c/fields/EYI_Actual_Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Actual_Booking_Date__c</fullName>
    <label>Actual Booking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Booking__c/fields/EYI_Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Booking__c/fields/EYI_Quote__c.field-meta.xml
<CustomField>
    <fullName>EYI_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Booking__c/fields/EYI_SAP_Sales_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Sales_Order_Number__c</fullName>
    <label>SAP Sales Order Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Demand__c/EYI_Demand__c.object-meta.xml
<CustomObject>
    <label>Demand</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Demand Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Demand__c/fields/EYI_Actual_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Actual_Date__c</fullName>
    <label>Actual Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Demand__c/fields/EYI_Amount_to_be_paid__c.field-meta.xml
<CustomField>
    <fullName>EYI_Amount_to_be_paid__c</fullName>
    <label>Milestone Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EYI_Demand__c/fields/EYI_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Billing_Date__c</fullName>
    <label>Billing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Demand__c/fields/EYI_Booking__c.field-meta.xml
<CustomField>
    <fullName>EYI_Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>EYI_Booking__c</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Demand__c/fields/EYI_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>EYI_Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Demand__c/fields/EYI_Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>EYI_Payment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fiel created to update date for specific demand.</description>
    <label>Payment Schedule</label>
    <referenceTo>EYI_Payment_Schedule__c</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Demand__c/fields/EYI_Relationship_Manager__c.field-meta.xml
<CustomField>
    <fullName>EYI_Relationship_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Demands1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Demand__c/fields/EYI_SAP_Milestone_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Milestone_Code__c</fullName>
    <externalId>true</externalId>
    <label>SAP Milestone Code</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Demand__c/fields/EYI_SAP_Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Plant_Code__c</fullName>
    <label>SAP Plant Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Demand__c/fields/EYI_SAP_Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Sales_Org__c</fullName>
    <label>SAP Sales Org</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Demand__c/fields/EYI_Usage__c.field-meta.xml
<CustomField>
    <fullName>EYI_Usage__c</fullName>
    <label>Usage</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Demand__c/fields/EYI_Usage_Description__c.field-meta.xml
<CustomField>
    <fullName>EYI_Usage_Description__c</fullName>
    <label>Usage Description</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10th Installment</fullName>
            </value>
            <value>
                <fullName>3rd Installment</fullName>
            </value>
            <value>
                <fullName>4th Installment</fullName>
            </value>
            <value>
                <fullName>5th Installment</fullName>
            </value>
            <value>
                <fullName>6th Installment</fullName>
            </value>
            <value>
                <fullName>7th Installment</fullName>
            </value>
            <value>
                <fullName>8th Installment</fullName>
            </value>
            <value>
                <fullName>9th Installment</fullName>
            </value>
            <value>
                <fullName>Booking Amount</fullName>
            </value>
            <value>
                <fullName>CLUBHOUSECHARGES</fullName>
            </value>
            <value>
                <fullName>LEGALCHARGES</fullName>
            </value>
            <value>
                <fullName>MAINTENANCECHARGES</fullName>
            </value>
            <value>
                <fullName>MAINTENANCEDEPOSIT</fullName>
            </value>
            <value>
                <fullName>MSEBCHARGES</fullName>
            </value>
            <value>
                <fullName>On Booking</fullName>
            </value>
            <value>
                <fullName>On Completion Electrical &amp; Plumbing Work</fullName>
            </value>
            <value>
                <fullName>On Completion of 10th Slab</fullName>
            </value>
            <value>
                <fullName>On Completion of 12th Slab</fullName>
            </value>
            <value>
                <fullName>On Completion of 2nd Slab</fullName>
            </value>
            <value>
                <fullName>On Completion of 4th Slab</fullName>
            </value>
            <value>
                <fullName>On Completion of 6th Slab</fullName>
            </value>
            <value>
                <fullName>On Completion of 8th Slab</fullName>
            </value>
            <value>
                <fullName>On Completion of Plinth</fullName>
            </value>
            <value>
                <fullName>On Completion of the walls &amp; internal pl</fullName>
            </value>
            <value>
                <fullName>On or before Agreement</fullName>
            </value>
            <value>
                <fullName>On Possession</fullName>
            </value>
            <value>
                <fullName>On Registration of Agreement</fullName>
            </value>
            <value>
                <fullName>SDR-NONRECOVER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/EYI_Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PM-{000000}</displayFormat>
        <label>Payment Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/EYI_Actual_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Actual_Date__c</fullName>
    <description>Actual Completion Date</description>
    <label>Actual Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/EYI_Amount_to_be_paid__c.field-meta.xml
<CustomField>
    <fullName>EYI_Amount_to_be_paid__c</fullName>
    <label>Amount to be paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/EYI_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Billing_Date__c</fullName>
    <label>Billing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/EYI_Invoice_Percentage__c.field-meta.xml
<CustomField>
    <fullName>EYI_Invoice_Percentage__c</fullName>
    <label>Percentage of value to be invoiced</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/EYI_Milestone__c.field-meta.xml
<CustomField>
    <fullName>EYI_Milestone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Milestone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/EYI_Milestone_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Milestone_Number__c</fullName>
    <label>Milestone Number</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/EYI_Milestone_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Milestone_Type__c</fullName>
    <label>Milestone Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CLP</fullName>
            </value>
            <value>
                <fullName>Time Bound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/EYI_SAP_Milestone_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Milestone_Code__c</fullName>
    <externalId>true</externalId>
    <label>SAP Milestone Code</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/EYI_SAP_Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Plant_Code__c</fullName>
    <label>SAP Plant Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/EYI_SAP_Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Sales_Org__c</fullName>
    <label>SAP Sales Org</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/EYI_Usage__c.field-meta.xml
<CustomField>
    <fullName>EYI_Usage__c</fullName>
    <label>Usage</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/EYI_Usage_Description__c.field-meta.xml
<CustomField>
    <fullName>EYI_Usage_Description__c</fullName>
    <label>Usage Description</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plan</label>
    <referenceTo>Payment_Plan__c</referenceTo>
    <relationshipLabel>Payment Schedules</relationshipLabel>
    <relationshipName>Payment_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Plan__c/Payment_Plan__c.object-meta.xml
<CustomObject>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Plan__c/fields/EYI_Quote__c.field-meta.xml
<CustomField>
    <fullName>EYI_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Payment Plans</relationshipLabel>
    <relationshipName>Payment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EYI_CreateDemandTriggerHandlerTest.cls
@isTest
private class EYI_CreateDemandTriggerHandlerTest {

    @testSetup
    static void setupTestData() {
        // Create test user
        User testUser = [SELECT Id FROM User WHERE IsActive = true LIMIT 1];
        
        // Create separate accounts for each test
        List<Account> accounts = new List<Account>();
        accounts.add(new Account(Name = 'Test Account 1'));
        accounts.add(new Account(Name = 'Test Account 2'));
        accounts.add(new Account(Name = 'Test Account 3'));
        insert accounts;
    }

    @isTest
    static void testHandleAfterUpdate() {
        User testUser = [SELECT Id FROM User WHERE IsActive = true LIMIT 1];
        Account acc = [SELECT Id FROM Account WHERE Name = 'Test Account 1' LIMIT 1];
        
        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity 1',
            StageName = 'Prospecting',
            CloseDate = System.today().addDays(30),
            AccountId = acc.Id,
            EYI_Ownership_Status__c = 'Accepted',
            EYI_Relationship_Manager__c = testUser.Id
        );
        insert opp;

        Quote quote = new Quote(
            Name = 'Test Quote 1',
            OpportunityId = opp.Id,
            Status = 'Approved'
        );
        insert quote;

        opp.SyncedQuoteId = quote.Id;
        update opp;

        EYI_Booking__c booking = new EYI_Booking__c(
            EYI_Opportunity_Name__c = opp.Id,
            EYI_Actual_Booking_Date__c = Date.today()
        );
        insert booking;

        Payment_Plan__c plan = new Payment_Plan__c(
            Name = 'Plan 1',
            EYI_Quote__c = quote.Id
        );
        insert plan;

        EYI_Payment_Schedule__c schedule = new EYI_Payment_Schedule__c(
            Payment_Plan__c = plan.Id,
            EYI_Actual_Date__c = Date.today(),
            EYI_Billing_Date__c = Date.today().addDays(5),
            EYI_Milestone_Type__c = 'CLP',
            EYI_Milestone__c = true,
            EYI_SAP_Milestone_Code__c = 'MST001',
            EYI_SAP_Plant_Code__c = 'PLANT01',
            EYI_SAP_Sales_Org__c = 'ORG01',
            EYI_Usage__c = 'EYIN',
            EYI_Usage_Description__c = '3BHK',
            EYI_Milestone_Number__c = 1,
            EYI_Amount_to_be_paid__c = 100000,
            EYI_Invoice_Percentage__c = 100
        );
        insert schedule;

        Test.startTest();
        
        EYI_Booking__c oldBooking = booking.clone();
        oldBooking.EYI_SAP_Sales_Order_Number__c = null;
        booking.EYI_SAP_Sales_Order_Number__c = 'SAP123';
        update booking;

        Test.stopTest();

        List<EYI_Demand__c> demands = [
            SELECT Id, EYI_Booking__c, EYI_Opportunity__c, EYI_Amount_to_be_paid__c, EYI_Demand_Status__c
            FROM EYI_Demand__c
            WHERE EYI_Booking__c = :booking.Id
        ];

        System.assertEquals(1, demands.size(), 'One demand should be created');
        System.assertEquals('Open', demands[0].EYI_Demand_Status__c, 'Demand status should be Open');
    }

    @isTest
    static void testHandleAfterUpdateNoSAPChange() {
        User testUser = [SELECT Id FROM User WHERE IsActive = true LIMIT 1];
        Account acc = [SELECT Id FROM Account WHERE Name = 'Test Account 2' LIMIT 1];
        
        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity 2',
            StageName = 'Prospecting',
            CloseDate = System.today().addDays(30),
            AccountId = acc.Id,
            EYI_Ownership_Status__c = 'Accepted',
            EYI_Relationship_Manager__c = testUser.Id
        );
        insert opp;

        EYI_Booking__c booking = new EYI_Booking__c(
            EYI_Opportunity_Name__c = opp.Id,
            EYI_SAP_Sales_Order_Number__c = 'SAP456'
        );
        insert booking;

        Test.startTest();
        
        EYI_Booking__c oldBooking = booking.clone();
        oldBooking.EYI_SAP_Sales_Order_Number__c = 'SAP456';
        booking.EYI_SAP_Sales_Order_Number__c = 'SAP456';
        update booking;

        Test.stopTest();

        List<EYI_Demand__c> demands = [
            SELECT Id FROM EYI_Demand__c WHERE EYI_Booking__c = :booking.Id
        ];

        System.assertEquals(0, demands.size(), 'No demand should be created when SAP number doesn\'t change');
    }

    @isTest
    static void testHandleAfterUpdateTimeBoundMilestone() {
        User testUser = [SELECT Id FROM User WHERE IsActive = true LIMIT 1];
        Account acc = [SELECT Id FROM Account WHERE Name = 'Test Account 3' LIMIT 1];
        
        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity 3',
            StageName = 'Prospecting',
            CloseDate = System.today().addDays(30),
            AccountId = acc.Id,
            EYI_Relationship_Manager__c = testUser.Id
        );
        insert opp;

        Quote quote = new Quote(
            Name = 'Test Quote 3',
            OpportunityId = opp.Id,
            Status = 'Approved'
        );
        insert quote;

        opp.SyncedQuoteId = quote.Id;
        opp.EYI_Ownership_Status__c = 'Accepted';
        update opp;

        EYI_Booking__c booking = new EYI_Booking__c(
            EYI_Opportunity_Name__c = opp.Id,
            EYI_Actual_Booking_Date__c = Date.today()
        );
        insert booking;

        Payment_Plan__c plan = new Payment_Plan__c(
            Name = 'Plan 3',
            EYI_Quote__c = quote.Id
        );
        insert plan;

        EYI_Payment_Schedule__c schedule = new EYI_Payment_Schedule__c(
            Payment_Plan__c = plan.Id,
            EYI_Actual_Date__c = Date.today(),
            EYI_Billing_Date__c = Date.today().addDays(10),
            EYI_Milestone_Type__c = 'Time Bound',
            EYI_Amount_to_be_paid__c = 50000,
            EYI_Invoice_Percentage__c = 50,
            EYI_Milestone_Number__c = 3,
            EYI_SAP_Plant_Code__c = 'PLANT03',
            EYI_SAP_Sales_Org__c = 'ORG03',
            EYI_Usage__c = 'EYIN',
            EYI_Usage_Description__c = '1BHK',
            EYI_Milestone__c = true,
            EYI_SAP_Milestone_Code__c = 'MST999'
        );
        insert schedule;

        // Debug: Check existing demands before test
        List<EYI_Demand__c> existingDemands = [SELECT Id FROM EYI_Demand__c];
        System.debug('Existing demands before test: ' + existingDemands.size());

        Test.startTest();
        
        EYI_Booking__c oldBooking = booking.clone();
        oldBooking.EYI_SAP_Sales_Order_Number__c = null;
        booking.EYI_SAP_Sales_Order_Number__c = 'SAP789';
        update booking;

        Test.stopTest();

        List<EYI_Demand__c> demands = [
            SELECT Id, EYI_Demand_Type__c, EYI_Actual_Date__c, EYI_Billing_Date__c, EYI_Payment_Schedule__c
            FROM EYI_Demand__c
            WHERE EYI_Booking__c = :booking.Id
        ];

        System.debug('Demands created for this booking: ' + demands.size());
        for(EYI_Demand__c demand : demands) {
            System.debug('Demand: ' + demand.Id + ', Type: ' + demand.EYI_Demand_Type__c + ', Schedule: ' + demand.EYI_Payment_Schedule__c);
        }

        System.assertEquals(1, demands.size(), 'One demand should be created for Time Bound test');
        if(demands.size() > 0) {
            System.assertEquals('Time Bound', demands[0].EYI_Demand_Type__c, 'Demand type should be Time Bound');
            System.assertEquals(Date.today().addDays(10), demands[0].EYI_Actual_Date__c, 'Actual date should be billing date for Time Bound');
        }
    }
    @isTest
    static void testHandleAfterUpdateTimeBoundMilestone1() {
        User testUser = [SELECT Id FROM User WHERE IsActive = true LIMIT 1];
        Account acc = [SELECT Id FROM Account WHERE Name = 'Test Account 3' LIMIT 1];
        
        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity 3',
            StageName = 'Prospecting',
            CloseDate = System.today().addDays(30),
            AccountId = acc.Id,
            EYI_Relationship_Manager__c = testUser.Id
        );
        insert opp;

        Quote quote = new Quote(
            Name = 'Test Quote 3',
            OpportunityId = opp.Id,
            Status = 'Approved'
        );
        insert quote;

        opp.SyncedQuoteId = quote.Id;
        opp.EYI_Ownership_Status__c = 'Accepted';
        update opp;

        EYI_Booking__c booking = new EYI_Booking__c(
            EYI_Opportunity_Name__c = opp.Id,
            EYI_Actual_Booking_Date__c = Date.today()
        );
        insert booking;
        
        EYI_Global_Charges__c globalCharges = new EYI_Global_Charges__c(
            Name = 'GC1',
            EYI_SAP_Material_Name__c = 'Material X',
            EYI_SAP_Sequence_Number__c = 1,
            EYI_Demand_Applicable__c = true
        );
        insert globalCharges;

        Project_Charges__c projectCharges = new Project_Charges__c(
            Name = 'Charge 1',
            EYI_Charge_Type__c = 'Other Charges',
            EYI_Global_Charges__c = globalCharges.Id
        );
        insert projectCharges;
        EYI_Applied_Project_Charge__c charge = new EYI_Applied_Project_Charge__c(
            Name = 'Test Applied Charge',
            EYI_Quote__c = quote.Id,
            EYI_Project_Charges__c = projectCharges.Id
        );
        insert charge;

        Payment_Plan__c plan = new Payment_Plan__c(
            Name = 'Plan 3',
            EYI_Quote__c = quote.Id
        );
        insert plan;

        EYI_Payment_Schedule__c schedule = new EYI_Payment_Schedule__c(
            Payment_Plan__c = plan.Id,
            EYI_Actual_Date__c = Date.today(),
            EYI_Billing_Date__c = Date.today().addDays(10),
            EYI_Milestone_Type__c = 'Time Bound',
            EYI_Amount_to_be_paid__c = 50000,
            EYI_Invoice_Percentage__c = 50,
            EYI_Milestone_Number__c = 3,
            EYI_SAP_Plant_Code__c = 'PLANT03',
            EYI_SAP_Sales_Org__c = 'ORG03',
            EYI_Usage__c = 'EYIN',
            EYI_Usage_Description__c = '1BHK',
            EYI_Milestone__c = true,
            EYI_SAP_Milestone_Code__c = 'MST999'
        );
        insert schedule;

        // Debug: Check existing demands before test
        List<EYI_Demand__c> existingDemands = [SELECT Id FROM EYI_Demand__c];
        System.debug('Existing demands before test: ' + existingDemands.size());

        Test.startTest();
        
        EYI_Booking__c oldBooking = booking.clone();
        oldBooking.EYI_SAP_Sales_Order_Number__c = null;
        booking.EYI_SAP_Sales_Order_Number__c = 'SAP789';
        update booking;

        Test.stopTest();

      
    }
}