force-app/main/default/objects/EYI_Applied_Project_Charge__c/EYI_Applied_Project_Charge__c.object-meta.xml
<CustomObject>
    <description>Junction object of Quote and Project Charge</description>
    <label>Applied Project Charge</label>
    <nameField>
        <label>Applied Project Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applied Project Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Applied_Project_Charge__c/fields/EYI_Grand_Total_Value_in_Words__c.field-meta.xml
<CustomField>
    <fullName>EYI_Grand_Total_Value_in_Words__c</fullName>
    <label>Grand Total Value in Words</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Applied_Project_Charge__c/fields/Grand_Total__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total__c</fullName>
    <formula>CASE( Name , 
&apos;Central GST&apos;, EYI_Charged_Amount__c ,
&apos;State GST&apos;, EYI_Charged_Amount__c,

EYI_Calculated_Amount__c +  EYI_GST_Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grand Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/EYI_AppliedProjectChargesHandler.cls
public class EYI_AppliedProjectChargesHandler {
	public static void convert(List<EYI_Applied_Project_Charge__c> newListQuote) {
        for (EYI_Applied_Project_Charge__c q : newListQuote) {
            Decimal aggVal = q.Grand_Total__c;
            if (aggVal != null) {
                Integer intPart = Integer.valueOf(aggVal.setScale(0, RoundingMode.DOWN));
                Integer decimalPart = Integer.valueOf(((aggVal - intPart) * 100).setScale(0, RoundingMode.HALF_UP));

                String words = EYI_ConverAmountToWordHandler.convertToIndianWords(intPart);

                if (decimalPart > 0) {
                    words += ' and ' + EYI_ConverAmountToWordHandler.convertToIndianWords(decimalPart) + ' Paise';
                }

                q.EYI_Grand_Total_Value_in_Words__c = words;
            } else {
                q.EYI_Grand_Total_Value_in_Words__c = null;
            }
        }
    }
}