force-app/main/default/objects/EYI_Assignment_Group__c/EYI_Assignment_Group__c.object-meta.xml
<CustomObject>
    <label>Assignment Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Assignment_Group__c/fields/EYI_Presales_Head__c.field-meta.xml
<CustomField>
    <fullName>EYI_Presales_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assignment_Groups1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Assignment_Group__c/fields/EYI_Team_Lead_TL__c.field-meta.xml
<CustomField>
    <fullName>EYI_Team_Lead_TL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Lead (TL)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assignment_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Assignment_Group_Member__c/EYI_Assignment_Group_Member__c.object-meta.xml
<CustomObject>
    <label>Assignment Group Member</label>
    <nameField>
        <label>Assignment Group Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Assignment_Group_Member__c/fields/EYI_Assignment_Group__c.field-meta.xml
<CustomField>
    <fullName>EYI_Assignment_Group__c</fullName>
    <label>Assignment Group</label>
    <referenceTo>EYI_Assignment_Group__c</referenceTo>
    <relationshipLabel>Assignment Group Members</relationshipLabel>
    <relationshipName>Assignment_Group_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EYI_Assignment_Group_Member__c/fields/EYI_Assignment_Member__c.field-meta.xml
<CustomField>
    <fullName>EYI_Assignment_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignment Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assignment_Group_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Assignment_Group_Member__c/fields/EYI_Team_Lead_TL__c.field-meta.xml
<CustomField>
    <fullName>EYI_Team_Lead_TL__c</fullName>
    <formula>EYI_Assignment_Member__r.Manager.FirstName + &quot; &quot; +  EYI_Assignment_Member__r.Manager.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Team Lead (TL)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EYI_AssignmentGroupUtility_test.cls
@isTest
public class EYI_AssignmentGroupUtility_test {
    @isTest
    public static void testAssignmentGroup() {
        // Create test Assignment Group
        EYI_Assignment_Group__c assignmentGroup = new EYI_Assignment_Group__c(
            Name = 'Pre-Sales For Lead Enquiry',
            EYI_Team_Lead_TL__c = UserInfo.getUserId(),
            EYI_Presales_Head__c = UserInfo.getUserId()
        );
        insert assignmentGroup;

        // Create test Assignment Group Member
        EYI_Assignment_Group_Member__c member = new EYI_Assignment_Group_Member__c(
            Name = 'Test Member',
            EYI_Assignment_Group__c = assignmentGroup.Id,
            EYI_Assignment_Member__c = UserInfo.getUserId()
        );
        insert member;

        Test.startTest();
        List<EYI_Assignment_Group__c> groupData = EYI_AssignmentGroupUtility.getGroupAssignedData(assignmentGroup.Name);
        System.assertEquals(1, groupData.size(), 'Group data should return one record');

        List<EYI_Assignment_Group_Member__c> escalationUsers = EYI_AssignmentGroupUtility.getEscalationUsers();
       // System.assertEquals(1, escalationUsers.size(), 'Escalation users should return one record');
        Test.stopTest();
    }
}