force-app/main/default/objects/EYI_Assignment_Group__c/EYI_Assignment_Group__c.object-meta.xml
<CustomObject>
    <label>Assignment Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Assignment_Group__c/fields/EYI_Presales_Head__c.field-meta.xml
<CustomField>
    <fullName>EYI_Presales_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assignment_Groups1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Assignment_Group__c/fields/EYI_Team_Lead_TL__c.field-meta.xml
<CustomField>
    <fullName>EYI_Team_Lead_TL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Lead (TL)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assignment_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Assignment_Group_Member__c/EYI_Assignment_Group_Member__c.object-meta.xml
<CustomObject>
    <label>Assignment Group Member</label>
    <nameField>
        <label>Assignment Group Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Assignment_Group_Member__c/fields/EYI_Assignment_Group__c.field-meta.xml
<CustomField>
    <fullName>EYI_Assignment_Group__c</fullName>
    <label>Assignment Group</label>
    <referenceTo>EYI_Assignment_Group__c</referenceTo>
    <relationshipLabel>Assignment Group Members</relationshipLabel>
    <relationshipName>Assignment_Group_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EYI_Assignment_Group_Member__c/fields/EYI_Assignment_Member__c.field-meta.xml
<CustomField>
    <fullName>EYI_Assignment_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignment Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assignment_Group_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Assignment_Group_Member__c/fields/EYI_Team_Lead_TL__c.field-meta.xml
<CustomField>
    <fullName>EYI_Team_Lead_TL__c</fullName>
    <formula>EYI_Assignment_Member__r.Manager.FirstName + &quot; &quot; +  EYI_Assignment_Member__r.Manager.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Team Lead (TL)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EYI_AssignmentGroupUtility.cls
/**
 * @description       : 
 * @author            : Digambar Ganage 
 * @group             : EY Notification Framework
 * @last modified on  : 11-21-2024
 * @last modified by  : Digambar Ganage 
**/
public with sharing class EYI_AssignmentGroupUtility {
    public static List<EYI_Assignment_Group__c> getGroupAssignedData(String groupName) {
        List<EYI_Assignment_Group__c> assignedGroupList = new List<EYI_Assignment_Group__c>();
        assignedGroupList = [SELECT Id, Name, EYI_Team_Lead_TL__c,EYI_Team_Lead_TL__r.Email ,EYI_Presales_Head__c,EYI_Presales_Head__r.Email
                                FROM EYI_Assignment_Group__c 
                                WHERE Name =: groupName
                                LIMIT 1];
        return assignedGroupList;
    }

    public static List<EYI_Assignment_Group_Member__c> getEscalationUsers() {
        List<EYI_Assignment_Group_Member__c> assignedGroupList = new List<EYI_Assignment_Group_Member__c>();
        assignedGroupList = [SELECT Id, Name, EYI_Assignment_Member__r.Email 
                                FROM EYI_Assignment_Group_Member__c 
                                WHERE EYI_Assignment_Group__r.Name =: System.Label.EYI_PresalesL3EscalationGroupLabel
                                LIMIT 1];
        return assignedGroupList;
    }

}