force-app/main/default/objects/EYI_Payment_Line_Item__c/EYI_Payment_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Object to store line item information for payment receipts</description>
    <label>Payment Line Item</label>
    <nameField>
        <displayFormat>PLI-{0000}</displayFormat>
        <label>Payment Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Payment_Line_Item__c/fields/EYI_Adjustment_Amount__c.field-meta.xml
<CustomField>
    <fullName>EYI_Adjustment_Amount__c</fullName>
    <description>Amount entered by agents while punching the receipt</description>
    <label>Adjustment Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Line_Item__c/fields/EYI_Currency_Key__c.field-meta.xml
<CustomField>
    <fullName>EYI_Currency_Key__c</fullName>
    <label>Currency Key</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Line_Item__c/fields/EYI_Outstanding_Amount__c.field-meta.xml
<CustomField>
    <fullName>EYI_Outstanding_Amount__c</fullName>
    <formula>IF(NOT(ISBLANK( EYI_Previously_Adjustment_Amount__c )),EYI_Principal_Tax_Amount__c - (EYI_Adjustment_Amount__c + EYI_Previously_Adjustment_Amount__c), EYI_Principal_Tax_Amount__c - EYI_Adjustment_Amount__c     
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Outstanding Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Line_Item__c/fields/EYI_Payment_Receipt__c.field-meta.xml
<CustomField>
    <fullName>EYI_Payment_Receipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to payment receipt</description>
    <label>Payment Receipt</label>
    <referenceTo>EYI_Payment_Receipt__c</referenceTo>
    <relationshipLabel>Payment Line Items</relationshipLabel>
    <relationshipName>Payment_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Line_Item__c/fields/EYI_Principal_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>EYI_Principal_Tax_Amount__c</fullName>
    <description>Princinpal or tax amount associated with the demand</description>
    <label>Billed Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Line_Item__c/fields/EYI_SAP_External_Id__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External Id combination for SAP integration</description>
    <externalId>true</externalId>
    <label>SAP External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EYI_Payment_Line_Item__c/fields/EYI_Status__c.field-meta.xml
<CustomField>
    <fullName>EYI_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Payment_Line_Item__c/fields/EYI_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>EYI_Total_Amount__c</fullName>
    <description>Total amount to be adjusted against the demand</description>
    <label>Total Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/EYI_Payment_Receipt__c.object-meta.xml
<CustomObject>
    <label>Bank Payment Receipt</label>
    <nameField>
        <displayFormat>PR-{0}</displayFormat>
        <label>Payment Receipt</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Payment Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Amount__c.field-meta.xml
<CustomField>
    <fullName>EYI_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_Bank_Name__c</fullName>
    <label>Bank Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HDFC Bank Ltd</fullName>
            </value>
            <value>
                <fullName>ICICI Bank</fullName>
            </value>
            <value>
                <fullName>Kotak Bank</fullName>
            </value>
            <value>
                <fullName>State Bank of India</fullName>
            </value>
            <value>
                <fullName>Bank of India</fullName>
            </value>
            <value>
                <fullName>Yes Bank Ltd</fullName>
            </value>
            <value>
                <fullName>IDBI Bank</fullName>
            </value>
            <value>
                <fullName>Bank of Maharashtra</fullName>
            </value>
            <value>
                <fullName>Axis Bank</fullName>
            </value>
            <value>
                <fullName>Allahabad Bank</fullName>
            </value>
            <value>
                <fullName>Andhra Bank</fullName>
            </value>
            <value>
                <fullName>Bank of Bahrain and Kuwait</fullName>
            </value>
            <value>
                <fullName>Bank of Baroda - Corporate Banking</fullName>
            </value>
            <value>
                <fullName>Bank of Baroda - Retail Banking</fullName>
            </value>
            <value>
                <fullName>Canara Bank</fullName>
            </value>
            <value>
                <fullName>Central Bank of India</fullName>
            </value>
            <value>
                <fullName>City Union Bank</fullName>
            </value>
            <value>
                <fullName>Corporation Bank</fullName>
            </value>
            <value>
                <fullName>Deutsche Bank</fullName>
            </value>
            <value>
                <fullName>Development Credit Bank</fullName>
            </value>
            <value>
                <fullName>Dhanlaxmi Bank</fullName>
            </value>
            <value>
                <fullName>Federal Bank</fullName>
            </value>
            <value>
                <fullName>Indian Bank</fullName>
            </value>
            <value>
                <fullName>Indian Overseas Bank</fullName>
            </value>
            <value>
                <fullName>IndusInd Bank</fullName>
            </value>
            <value>
                <fullName>ING Vysya Bank</fullName>
            </value>
            <value>
                <fullName>Jammu and Kashmir Bank</fullName>
            </value>
            <value>
                <fullName>Karnataka Bank Ltd</fullName>
            </value>
            <value>
                <fullName>Karur Vysya Bank</fullName>
            </value>
            <value>
                <fullName>Laxmi Vilas Bank</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Currency_Key__c.field-meta.xml
<CustomField>
    <fullName>EYI_Currency_Key__c</fullName>
    <description>Field created to store currency iso code for SAP sync API</description>
    <label>Currency Key</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INR</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Instrument_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Instrument_Number__c</fullName>
    <label>Instrument Number</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Is_Syc__c.field-meta.xml
<CustomField>
    <fullName>EYI_Is_Syc__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox field to validate if the record is synced with SAP</description>
    <label>Is sync?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>EYI_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Payment_Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Principal_Amount__c.field-meta.xml
<CustomField>
    <fullName>EYI_Principal_Amount__c</fullName>
    <description>Field created for SAP sync to store principal amount</description>
    <formula>EYI_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Principal Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_SAP_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Customer_Number__c</fullName>
    <label>SAP Customer Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_SAP_Customer_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Customer_Reference_Number__c</fullName>
    <description>Field created for payment receipt post SAP Sync API</description>
    <displayFormat>CN-{0000}</displayFormat>
    <label>SAP Customer Reference Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_SAP_Error__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Error__c</fullName>
    <description>Field to store error messages coming from SAP sync API</description>
    <label>SAP Error</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_SAP_Payment_Advice_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Payment_Advice_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>SAP Payment Advice Number</label>
    <length>128</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Status__c.field-meta.xml
<CustomField>
    <fullName>EYI_Status__c</fullName>
    <label>Status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tax_Amount__c</fullName>
    <description>Field created for SAP sync API to store tax amount</description>
    <formula>EYI_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tax_Code__c</fullName>
    <label>Tax Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Output GST Taxable</fullName>
                <default>true</default>
                <label>Output GST Taxable</label>
            </value>
            <value>
                <fullName>input TCS</fullName>
            </value>
            <value>
                <fullName>Output GST NIL Rate</fullName>
            </value>
            <value>
                <fullName>Output GST Reverse Charge</fullName>
            </value>
            <value>
                <fullName>Output GST SEZ - NIL Rate</fullName>
            </value>
            <value>
                <fullName>Output GST SEZ - Taxable</fullName>
            </value>
            <value>
                <fullName>Output Advance Receipt CGST/SGST - 5%</fullName>
            </value>
            <value>
                <fullName>Output Advance Receipt CGST/SGST - 12%</fullName>
            </value>
            <value>
                <fullName>Output Advance Receipt CGST/SGST - 18%</fullName>
            </value>
            <value>
                <fullName>Output Advance Receipt CGST/SGST - 28%</fullName>
            </value>
            <value>
                <fullName>Output Advance Receipt IGST - 5%</fullName>
            </value>
            <value>
                <fullName>Output Advance Receipt IGST - 12%</fullName>
            </value>
            <value>
                <fullName>Output Advance Receipt IGST - 18%</fullName>
            </value>
            <value>
                <fullName>Output Advance Receipt IGST - 28%</fullName>
            </value>
            <value>
                <fullName>Foreign Exchange</fullName>
            </value>
            <value>
                <fullName>Import GST</fullName>
            </value>
            <value>
                <fullName>RCM Input GST</fullName>
            </value>
            <value>
                <fullName>output Interim TCS</fullName>
            </value>
            <value>
                <fullName>output TCS Payable</fullName>
            </value>
            <value>
                <fullName>Input GST</fullName>
            </value>
            <value>
                <fullName>Input GST 0%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advance</fullName>
            </value>
            <value>
                <fullName>Demand</fullName>
            </value>
            <value>
                <fullName>Token</fullName>
            </value>
            <value>
                <fullName>TDS</fullName>
            </value>
            <value>
                <fullName>Principal</fullName>
                <isActive>false</isActive>
                <label>Principal</label>
            </value>
            <value>
                <fullName>Tax</fullName>
                <isActive>false</isActive>
                <label>Tax</label>
            </value>
            <value>
                <fullName>13-02</fullName>
                <isActive>false</isActive>
                <label>Token not needed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EYI_SAP_PaymentReceiptSyncLwcController.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 03-26-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class EYI_SAP_PaymentReceiptSyncLwcController {
    @AuraEnabled
    public static lwcMessage PaymentsSync(Id recordId) {
        lwcMessage lm = new lwcMessage();
        Map<String, String> messageAndType = new Map<String, String>();
        EYI_Payment_Receipt__c receiptData =  [Select Id,EYI_Transaction_Type__c,EYI_Opportunity__r.EYI_Project_Enquired__r.EYI_SAP_Company_Code__c,
                                               EYI_Opportunity__r.EYI_SAP_Customer_Number__c,EYI_Amount__c,
                                               EYI_Bank_Name__c,EYI_Instrument_Number__c,
                                               EYI_Instrument_Date__c,
                                               EYI_Opportunity__r.EYI_Inventory__r.Name, EYI_Currency_Key__c,EYI_SAP_Error__c,EYI_Is_Syc__c,EYI_SAP_Customer_Reference_Number__c,EYI_Principal_Amount__c,EYI_Tax_Amount__c,EYI_Tax_Code__c,
                                               EYI_Opportunity__r.EYI_Inventory__r.EYI_SAP_Profit_Center__c,EYI_SAP_Payment_Advice_Number__c,(Select Id,EYI_Total_Amount__c, EYI_Status__c, EYI_SAP_External_Id__c, 
                                               EYI_Principal_Tax_Amount__c, EYI_Adjustment_Amount__c,
                                               EYI_Outstanding_Amount__c, EYI_Payment_Receipt__r.EYI_Opportunity__r.EYI_Project_Enquired__r.EYI_SAP_Company_Code__c,
                                               EYI_Payment_Receipt__r.EYI_SAP_Customer_Number__c, EYI_Fiscal_Year__c,
                                               EYI_Number_of_Line_Items__c, 
                                               EYI_Billing_Document__c, EYI_Milestone_No__c, EYI_Unit_Code_SAP__c,
                                               EYI_Adjustment_Type__c, EYI_FL_Document_Number__c
                                        FROM Payment_Line_Items__r)
                                               from EYI_Payment_Receipt__c where Id = :recordId];
        //try {
        HttpResponse hr = EY_SAP_Gateway.sendPayementReceipt(receiptData,null, null);
        processPaymentResponse(hr,receiptData);
        return lm;
    }
    
    public static lwcMessage paymentResponseProcessing(HttpResponse response, EYI_Payment_Receipt__c paymentData) {
        lwcMessage lm = new lwcMessage();
        
        // check if response is valid
        if(response.getStatusCode() == 200) {
            try{
                Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
                // Extract the "n0:ZSD_CREATE_UNITS_FROM_SFResponse" field from the map
                Map<String, Object> paymentReceiptResponse = (Map<String, Object>) responseMap.get('n0:ZSD_CREATE_PAYMT_RCPT_FROM_SFResponse');
                // Extract the message from CarparkingResponse map.
                String avsId = (String)paymentReceiptResponse.get('EX_AVSID');
                String BELNR = (String)paymentReceiptResponse.get('EX_BELNR');
                String GJAHR = (String)paymentReceiptResponse.get('EX_GJAHR');
                String BUKRS = (String)paymentReceiptResponse.get('EX_BUKRS');  
                if(avsId != null && avsId != ''){
                    lm.type = 'S';
                    lm.message = 'Payment receipt is successfully synced';
                    if(paymentData !=null){
                        paymentData.EYI_SAP_Payment_Advice_Number__c = avsId;
                        paymentData.EYI_Is_Syc__c = true;
                        paymentData.EYI_SAP_Error__c = null;
                        //paymentData.EYI_Account_Document_Number__c = BELNR;
                        paymentData.EYI_Doc_Year__c = GJAHR;
                        paymentData.EYI_SAP_Company_Code__c = BUKRS;
                        paymentData.EYI_Payment_Status__c = 'Submitted';
                        update paymentData;
                    }
                    lm.EX_AVSID = avsId;
                    if(BELNR != null && BELNR != ''){
                        //lm.BELNR = BELNR;
                    }
                    if(GJAHR != null && GJAHR != ''){
                        lm.GJAHR = GJAHR;
                    }
                    if(BUKRS != null && BUKRS != ''){
                        lm.BUKRS = BUKRS;
                    }
                        
                    
                    return lm;
                }  
                
                Map<String, Object> exReturn = (Map<String, Object>) paymentReceiptResponse.get('EX_RETURN');
                if(exReturn == null){
                    
                }
                system.debug('exReturn  '+exReturn);
                Object item =  exReturn.get('item');
                
                // Now you can access individual fields within the "item" map
                string successtype='';
                String type = '';
                String messagDisp = '';
                if (item instanceof List<Object>) {
                    List<Object> itemList = (List<Object>) item;
                    
                    for (Object obj : itemList) { 
                        
                        Map<String, Object> objitem = (Map<String, Object>) obj;
                        //type = type +'-'+ (String) objitem.get('TYPE');
                        successtype = successtype +'-'+ (String) objitem.get('TYPE');
                        string types =(String) objitem.get('TYPE');
                        //system.debug('Updating type '+type);
                        // if (!type.contains('S')) {
                        if(types!='S'){
                            type =(String) objitem.get('TYPE');
                            system.debug('Updating type  inside S loop '+types);
                            messagDisp =messagDisp+'\n--'+ (String) objitem.get('MESSAGE');
                        }
                    }
                    system.debug('messagDisp  240==== '+messagDisp);
                }else if(item instanceof Map<String, Object>){
                    SYSTEM.DEBUG('item   '+item);
                    Map<String, Object> objitem = (Map<String, Object>) item;
                    SYSTEM.DEBUG('objitem   '+objitem);
                    type =  (String) objitem.get('TYPE');
                    successtype = (String) objitem.get('TYPE');
                    if(type!='S'){
                        type =(String) objitem.get('TYPE');
                        system.debug('Updating type  inside S loop '+type);
                        messagDisp =messagDisp+'\n--'+ (String) objitem.get('MESSAGE');
                    }
                    // messagDisp =(String) objitem.get('MESSAGE');
                }
                system.debug('messageDisp inside loop '+messagDisp);
                if(messagDisp!=null && type!=null ){
                    if(paymentData != null){
                        paymentData.EYI_SAP_Error__c = messagDisp;
                        update paymentData;
                        system.debug('Updating payment receipt for error');
                    }
                    
                    
                }
                String cleanedType = successtype.replaceAll('-', '');
                
                // Check if the cleaned string contains only 'S'
                if (cleanedType != '' && cleanedType.replaceAll('S', '') == '') {
                    if(paymentData != null){
                        paymentData.EYI_Is_Syc__c = true;  
                    }
                    Type ='S';
                    messagDisp = 'Payment Receipt Synced to SAP Successfully.';
                    if(paymentData != null){
                        update paymentData;
                    }
                }
                
                SYSTEM.DEBUG('type  ==>>  '+type);
                SYSTEM.DEBUG('messagDisp   '+messagDisp);
                lm.type =  type;
                lm.message = messagDisp;
                SYSTEM.DEBUG('lm   '+lm);
                return lm;
            }
            catch(Exception e){
                lm.type =  'E';
                lm.message = e.getMessage();
                return lm;
            }
        }
        
        return lm;
    }

    public static void processPaymentResponse(HttpResponse response, EYI_Payment_Receipt__c paymentData) {
        if (response.getStatusCode() == 200) {
            try {
                Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
                Map<String, Object> paymentReceiptResponse = (Map<String, Object>) responseMap.get('n0:ZSD_CREATE_PAYMT_RCPT_FROM_SFResponse');

                String avsId = (String)paymentReceiptResponse.get('EX_AVSID');
                String BELNR = (String)paymentReceiptResponse.get('EX_BELNR');
                String GJAHR = (String)paymentReceiptResponse.get('EX_GJAHR');
                String BUKRS = (String)paymentReceiptResponse.get('EX_BUKRS');

                if (avsId != null && avsId != '') {
                    if (paymentData != null) {
                        paymentData.EYI_SAP_Payment_Advice_Number__c = avsId;
                        paymentData.EYI_Is_Syc__c = true;
                        paymentData.EYI_SAP_Error__c = null;
                        //paymentData.EYI_Account_Document_Number__c = BELNR;
                        paymentData.EYI_Doc_Year__c = GJAHR;
                        paymentData.EYI_Payment_Status__c = 'Submitted';
                        paymentData.EYI_SAP_Company_Code__c = BUKRS;
                        update paymentData; // ✅ Update Salesforce record inside Queueable execution
                    }
                } else {
                    if (paymentData != null) {
                        paymentData.EYI_SAP_Error__c = 'SAP Sync Failed';
                        update paymentData;
                    }
                }
            } catch (Exception e) {
                if (paymentData != null) {
                    paymentData.EYI_SAP_Error__c = e.getMessage(); // Capture error in the object itself
                    update paymentData;
                }
            }
        }
    }

    
    public class lwcMessage {
        @AuraEnabled public String type;
        @AuraEnabled public String message;  
        public string EX_AVSID;
        public string BELNR;
        public string GJAHR;
        public String BUKRS;
    }
   
    public static lwcMessage paymentSyncFromUI(List<Map<String, Object>> updatedRecords, Map<String, Object> formData){
        lwcMessage lm = new lwcMessage();
        //try {
        HttpResponse hr = EY_SAP_Gateway.sendPayementReceipt(null, updatedRecords, formData);
        lm = paymentResponseProcessing(hr,null);
        return lm;
    }
   /* public static void paymentSyncFromUI(List<Map<String, Object>> updatedRecords, Map<String, Object> formData) {
        System.enqueueJob(new PaymentReceiptQueueable(updatedRecords, formData));
    }*/

    
}