force-app/main/default/objects/EYI_Global_Charges__c/EYI_Global_Charges__c.object-meta.xml
<CustomObject>
    <label>Global Charges</label>
    <nameField>
        <label>Global Charges Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Global_Charges__c/fields/EYI_SAP_Calculation_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Calculation_Type__c</fullName>
    <label>SAP Calculation Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>EYI_SAP_Condition_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Amount</fullName>
            </value>
            <value>
                <fullName>Quantity</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Global_Charges__c/fields/EYI_SAP_Condition_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Condition_Type__c</fullName>
    <label>SAP Condition Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZADC</fullName>
            </value>
            <value>
                <fullName>ZBP0</fullName>
            </value>
            <value>
                <fullName>ZBRA</fullName>
            </value>
            <value>
                <fullName>ZBRK</fullName>
            </value>
            <value>
                <fullName>ZCLB</fullName>
            </value>
            <value>
                <fullName>ZFRC</fullName>
            </value>
            <value>
                <fullName>ZLAN</fullName>
            </value>
            <value>
                <fullName>ZPRM</fullName>
            </value>
            <value>
                <fullName>ZRCP</fullName>
            </value>
            <value>
                <fullName>MSEB</fullName>
            </value>
            <value>
                <fullName>SDR-RECOVERABLE</fullName>
            </value>
            <value>
                <fullName>SDR-NONRECOVER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/EYI_Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Inventory_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Inventory Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>EYI_Tower__c.EYI_SubProject_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.EYI_SubProject__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/EYI_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Global_Charges__c.field-meta.xml
<CustomField>
    <fullName>EYI_Global_Charges__c</fullName>
    <label>Global Charges</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
            </value>
            <value>
                <fullName>Infra</fullName>
            </value>
            <value>
                <fullName>Floor Rise</fullName>
            </value>
            <value>
                <fullName>MSEB</fullName>
            </value>
            <value>
                <fullName>Club House</fullName>
            </value>
            <value>
                <fullName>Legal Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Project_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Code__c</fullName>
    <label>Project Code</label>
    <length>55</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/EYI_Rate_List__c.object-meta.xml
<CustomObject>
    <label>Rate List</label>
    <nameField>
        <displayFormat>Rate List-{00}</displayFormat>
        <label>Rate List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Global_Charges__c.field-meta.xml
<CustomField>
    <fullName>EYI_Global_Charges__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Charges</label>
    <referenceTo>EYI_Global_Charges__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Inventory__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory</label>
    <referenceTo>EYI_Inventory__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Tower__c/EYI_Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Charges__c/Project_Charges__c.object-meta.xml
<CustomObject>
    <label>Project Charges</label>
    <nameField>
        <label>Project Charges Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Charges__c/fields/EYI_Active__c.field-meta.xml
<CustomField>
    <fullName>EYI_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Charges__c/fields/EYI_Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Charge_Type__c</fullName>
    <label>Charge Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pricing Charges</fullName>
            </value>
            <value>
                <fullName>Other Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Charges__c/fields/EYI_Global_Charges__c.field-meta.xml
<CustomField>
    <fullName>EYI_Global_Charges__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Charges</label>
    <referenceTo>EYI_Global_Charges__c</referenceTo>
    <relationshipLabel>Project Charges</relationshipLabel>
    <relationshipName>Project_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Charges__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Project Charges</relationshipLabel>
    <relationshipName>Project_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Charges__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Project Charges</relationshipLabel>
    <relationshipName>Project_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EYI_RateListTriggerTest.cls
@isTest
private class EYI_RateListTriggerTest {

    @isTest
    static void testBeforeInsertTrigger() {
        EYI_Global_Charges__c globalCharge = new EYI_Global_Charges__c(
            Name = 'Test Global Charge',
			EYI_SAP_Condition_Type__c = 'ZBP0',
            EYI_SAP_Calculation_Type__c = 'Fixed Amount'
        );
        insert globalCharge;

        EYI_Project__c project = new EYI_Project__c(Name = 'Test Project',EYI_Project_Code__c = '123456');
        insert project;

        EYI_Tower__c tower = new EYI_Tower__c(Name = 'Test Tower');
        insert tower;
        
        EYI_Inventory__c inv = new EYI_Inventory__c(Name = '1502',EYI_Active__c = true,EYI_Inventory_Number__c = '2134324');
		insert inv;
        Project_Charges__c projectCharge = new Project_Charges__c(
            EYI_Global_Charges__c = globalCharge.Id,
            EYI_Charge_Type__c = 'Pricing Charges',
            EYI_Project__c = project.Id,
            EYI_Tower__c = tower.Id,
            EYI_Active__c = true
        );
        insert projectCharge;

        EYI_Rate_List__c rateList = new EYI_Rate_List__c(
            EYI_Project__c = project.Id,
            EYI_Tower__c = tower.Id,
            EYI_Global_Charges__c = globalCharge.Id,
            EYI_Inventory__c = inv.Id
        );

        Test.startTest();
        insert rateList;
        Test.stopTest();
    }

    @isTest
    static void testBeforeUpdateTrigger() {
        // Create and insert a record
        //
        EYI_Global_Charges__c globalCharge = new EYI_Global_Charges__c(
            Name = 'Test Global Charge',
            EYI_SAP_Condition_Type__c = 'ZBP0',
            EYI_SAP_Calculation_Type__c = 'Fixed Amount'
        );
        insert globalCharge; 
        EYI_Project__c project = new EYI_Project__c(Name = 'Test Project',EYI_Project_Code__c = '123456');
        insert project;

        EYI_Tower__c tower = new EYI_Tower__c(Name = 'Test Tower');
        insert tower;
        
        EYI_Inventory__c inv = new EYI_Inventory__c(Name = '1502',EYI_Active__c = true,EYI_Inventory_Number__c = '2134324');
        insert inv;
        EYI_Rate_List__c rateList = new EYI_Rate_List__c(
			EYI_Project__c = project.Id,
            EYI_Tower__c = tower.Id,
			EYI_Inventory__c = inv.Id
            // Add any required fields that are part of the field set
        );
        insert rateList;

        // Simulate a field change
        rateList.EYI_Global_Charges__c = globalCharge.Id;

        Test.startTest();
        update rateList;
        Test.stopTest();
    }
    @isTest
    static void testAfterInsert() {
        // Prepare test data
        EYI_Project__c proj = new EYI_Project__c(
            Name = 'Test Project',
            EYI_Project_Code__c = 'PRJ001'
        );

        Test.startTest();
        insert proj;
        Test.stopTest();

        // You can optionally query to confirm the record was inserted
        EYI_Project__c inserted = [SELECT Id, Name FROM EYI_Project__c WHERE Id = :proj.Id];
        System.assertEquals('Test Project', inserted.Name);
    }

    @isTest
    static void testAfterUpdateWithSameProjectCode() {
        // Insert initial record
        EYI_Project__c proj = new EYI_Project__c(
            Name = 'Test Project',
            EYI_Project_Code__c = 'PRJ001'
        );
        insert proj;

        // Update record without changing EYI_Project_Code__c
        proj.Name = 'Updated Project Name';
        Test.startTest();
        update proj;
        Test.stopTest();

        EYI_Project__c updated = [SELECT Id, Name FROM EYI_Project__c WHERE Id = :proj.Id];
        System.assertEquals('Updated Project Name', updated.Name);
    }

    @isTest
    static void testAfterUpdateWithChangedProjectCode() {
        // Insert initial record
        EYI_Project__c proj = new EYI_Project__c(
            Name = 'Project Change Test',
            EYI_Project_Code__c = 'OLD_CODE'
        );
        insert proj;

        // Update with changed EYI_Project_Code__c — should be skipped by the trigger
        proj.EYI_Project_Code__c = 'NEW_CODE';
        proj.Name = 'Changed Code Project';
        Test.startTest();
        update proj;
        Test.stopTest();

        // Optional validation
        EYI_Project__c updated = [SELECT EYI_Project_Code__c FROM EYI_Project__c WHERE Id = :proj.Id];
        System.assertEquals('NEW_CODE', updated.EYI_Project_Code__c);
    }
}