force-app/main/default/objects/EYI_Global_Charges__c/EYI_Global_Charges__c.object-meta.xml
<CustomObject>
    <label>Global Charges</label>
    <nameField>
        <label>Global Charges Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Global_Charges__c/fields/EYI_Condition_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Condition_Type__c</fullName>
    <formula>CASE(
EYI_SAP_Condition_Type__c,
&apos;ZADC&apos;, &apos;Infra Charges&apos;,
&apos;ZBP0&apos;, &apos;Base Price&apos;,
&apos;ZBRA&apos;, &apos;Brokerage Additional&apos;,
&apos;ZBRK&apos;, &apos;Brokerage&apos;,
&apos;ZCLB&apos;, &apos;Club House&apos;,
&apos;ZFRC&apos;, &apos;Floor Rise&apos;,
&apos;ZLAN&apos;, &apos;Land Cost&apos;,
&apos;ZPRM&apos;, &apos;2 Wheeler Charges&apos;,
&apos;ZRCP&apos;, &apos;Base Price-Booking&apos;,
&apos;MSEB&apos;, &apos;MSEB Charges&apos;,
&apos;SDR-RECOVERABLE&apos;, &apos;STAMP DUTY AND REG - RECOVERABLE&apos;,
&apos;SDR-NONRECOVER&apos;, &apos;STAMP DUTY NON RECOVERABLE&apos;,
&apos;&apos;
)</formula>
    <label>Condition Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Global_Charges__c/fields/EYI_SAP_Calculation_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Calculation_Type__c</fullName>
    <label>SAP Calculation Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>EYI_SAP_Condition_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Amount</fullName>
            </value>
            <value>
                <fullName>Quantity</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Project__c/EYI_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Global_Charges__c.field-meta.xml
<CustomField>
    <fullName>EYI_Global_Charges__c</fullName>
    <label>Global Charges</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
            </value>
            <value>
                <fullName>Infra</fullName>
            </value>
            <value>
                <fullName>Floor Rise</fullName>
            </value>
            <value>
                <fullName>MSEB</fullName>
            </value>
            <value>
                <fullName>Club House</fullName>
            </value>
            <value>
                <fullName>Legal Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/EYI_Rate_List__c.object-meta.xml
<CustomObject>
    <label>Rate List</label>
    <nameField>
        <displayFormat>Rate List-{00}</displayFormat>
        <label>Rate List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Calculation_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Calculation_Type__c</fullName>
    <label>Calculation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Fixed Amount</fullName>
            </value>
            <value>
                <fullName>Quantity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Condition_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Condition_Type__c</fullName>
    <label>Condition Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Infra Charges</fullName>
            </value>
            <value>
                <fullName>Base Price</fullName>
            </value>
            <value>
                <fullName>Brokerage Additional</fullName>
            </value>
            <value>
                <fullName>Brokerage</fullName>
            </value>
            <value>
                <fullName>Club House</fullName>
            </value>
            <value>
                <fullName>Floor Rise</fullName>
            </value>
            <value>
                <fullName>Land Cost</fullName>
            </value>
            <value>
                <fullName>2 Wheeler Charges</fullName>
            </value>
            <value>
                <fullName>Base Price-Booking</fullName>
            </value>
            <value>
                <fullName>MSEB Charges</fullName>
            </value>
            <value>
                <fullName>STAMP DUTY AND REG - RECOVERABLE</fullName>
            </value>
            <value>
                <fullName>STAMP DUTY NON RECOVERABLE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Global_Charges__c.field-meta.xml
<CustomField>
    <fullName>EYI_Global_Charges__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Charges</label>
    <referenceTo>EYI_Global_Charges__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Tower__c/EYI_Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Charges__c/Project_Charges__c.object-meta.xml
<CustomObject>
    <label>Project Charges</label>
    <nameField>
        <label>Project Charges Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Charges__c/fields/EYI_Active__c.field-meta.xml
<CustomField>
    <fullName>EYI_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Charges__c/fields/EYI_Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Charge_Type__c</fullName>
    <label>Charge Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pricing Charges</fullName>
            </value>
            <value>
                <fullName>Other Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Charges__c/fields/EYI_Global_Charges__c.field-meta.xml
<CustomField>
    <fullName>EYI_Global_Charges__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Charges</label>
    <referenceTo>EYI_Global_Charges__c</referenceTo>
    <relationshipLabel>Project Charges</relationshipLabel>
    <relationshipName>Project_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Charges__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Project Charges</relationshipLabel>
    <relationshipName>Project_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Charges__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Project Charges</relationshipLabel>
    <relationshipName>Project_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EYI_RateListTriggerHandler.cls
public class EYI_RateListTriggerHandler {
    
    public static void handleBeforeInsert(List<EYI_Rate_List__c> newRateLists){
        Set<Id> projectIds = new Set<Id>();
        Set<Id> towerIds = new Set<Id>();
        Map<Id, Id> rateListToGlobalCharge = new Map<Id, Id>();
        Set<Id> globalChargeId = new Set<Id>();
        
        for (EYI_Rate_List__c rl : newRateLists) {
            if (rl.EYI_Project__c != null) {
                projectIds.add(rl.EYI_Project__c);
            }
            if (rl.EYI_Tower__c != null) {
                towerIds.add(rl.EYI_Tower__c);
            }
            if (rl.EYI_Global_Charges__c != null) {
                rateListToGlobalCharge.put(rl.Id, rl.EYI_Global_Charges__c);
                globalChargeId.add(rl.EYI_Global_Charges__c);
            }
        }
        
        Map<Id, String> globalChargeToCalculationType = new Map<Id, String>();
        Map<Id, String> globalChargeToConditionType = new Map<Id, String>();
        
        List<EYI_Global_Charges__c> globalChargeList = [
            SELECT Id, EYI_Condition_Type__c, EYI_SAP_Calculation_Type__c
            FROM EYI_Global_Charges__c
            WHERE Id IN :globalChargeId
        ];
        System.debug('globalChargeList : '+globalChargeList);
        if(globalChargeList.size() > 0){
            for (EYI_Global_Charges__c gbCharge : globalChargeList) {
                globalChargeToCalculationType.put(gbCharge.Id, gbCharge.EYI_SAP_Calculation_Type__c);
                globalChargeToConditionType.put(gbCharge.Id, gbCharge.EYI_Condition_Type__c);
            }
            System.debug('globalChargeToCalculationType : '+globalChargeToCalculationType);
            System.debug('globalChargeToConditionType : '+globalChargeToConditionType);
            
            List<Project_Charges__c> existingProjectCharges = [
                SELECT Id, EYI_Global_Charges__c,EYI_Charge_Type__c, EYI_Project__c, EYI_Tower__c,EYI_Active__c
                FROM Project_Charges__c
                WHERE (EYI_Project__c IN :projectIds OR EYI_Tower__c IN :towerIds)
                      AND EYI_Global_Charges__c != null AND EYI_Charge_Type__c='Pricing Charges' AND EYI_Active__c = true
            ];
            
            
            Set<Id> conflictingGlobalCharges = new Set<Id>();
            Map<Id, Set<Id>> projectToGlobalCharges = new Map<Id, Set<Id>>();
            Map<Id, Set<Id>> towerToGlobalCharges = new Map<Id, Set<Id>>();
            for (Project_Charges__c pc : existingProjectCharges) {
                if (pc.EYI_Project__c != null) {
                    if (!projectToGlobalCharges.containsKey(pc.EYI_Project__c)) {
                        projectToGlobalCharges.put(pc.EYI_Project__c, new Set<Id>());
                    }
                    projectToGlobalCharges.get(pc.EYI_Project__c).add(pc.EYI_Global_Charges__c);
                }
                if (pc.EYI_Tower__c != null) {
                    if (!towerToGlobalCharges.containsKey(pc.EYI_Tower__c)) {
                        towerToGlobalCharges.put(pc.EYI_Tower__c, new Set<Id>());
                    }
                    towerToGlobalCharges.get(pc.EYI_Tower__c).add(pc.EYI_Global_Charges__c);
                }
            }
            System.debug('projectToGlobalCharges : '+projectToGlobalCharges);
            System.debug('towerToGlobalCharges : '+towerToGlobalCharges);
            
            for (EYI_Rate_List__c rl : newRateLists) {
                System.debug('rl.EYI_Global_Charges__c : '+rl.EYI_Global_Charges__c);
                if (rl.EYI_Global_Charges__c == null){
                    rl.addError('Global Charge can not be blank');
                }
                if (globalChargeToCalculationType.containsKey(rl.EYI_Global_Charges__c)) {
                    rl.EYI_Calculation_Type__c = globalChargeToCalculationType.get(rl.EYI_Global_Charges__c);
                }
                if (globalChargeToConditionType.containsKey(rl.EYI_Global_Charges__c)) {
                    rl.EYI_Condition_Type__c = globalChargeToConditionType.get(rl.EYI_Global_Charges__c);
                }
                Boolean isChargeAvailableInProject = false;
                Boolean isChargeAvailableInTower = false;
                Boolean isChargeNotAvailableInTower = false;
                // Check Tower-GlobalCharge conflict
                Set<Id> globalCharges = new Set<Id>();
                
                //check and store tower related global charges
                if(!towerToGlobalCharges.isEmpty()){
                    globalCharges = towerToGlobalCharges.get(rl.EYI_Tower__c);
                }
                System.debug('globalCharges : '+globalCharges);
                
                //check tower related global charges is not blank and tower is present in towerToGlobalCharges map
                if (rl.EYI_Tower__c != null && 
                    towerToGlobalCharges.containsKey(rl.EYI_Tower__c) && !globalCharges.isEmpty()) {
                    System.debug('Inside globalCharges if not empty');
                        //Display error if global charge is not present in that map for repsective tower
                        if(!towerToGlobalCharges.get(rl.EYI_Tower__c).contains(rl.EYI_Global_Charges__c)){
                            System.debug('inside tower error');
                            isChargeNotAvailableInTower = true;
                            rl.addError('Global charge is not applicable for this Tower');
                        }else if(towerToGlobalCharges.get(rl.EYI_Tower__c).contains(rl.EYI_Global_Charges__c)){ // this condition indicated rate list created 
                            System.debug('inside update of tower');
                            isChargeAvailableInTower = true;
                        }
                    }
    
                // Check Project-GlobalCharge conflict
                 if (rl.EYI_Project__c != null &&
                     !projectToGlobalCharges.containsKey(rl.EYI_Project__c) && isChargeAvailableInTower == false && isChargeNotAvailableInTower == false){
                         System.debug('Insdie Project First Error');
                         rl.addError('Global charge is not applicablea for this Project'); 
                 } 
                 else if (rl.EYI_Project__c != null &&
                     projectToGlobalCharges.containsKey(rl.EYI_Project__c) && !projectToGlobalCharges.get(rl.EYI_Project__c).contains(rl.EYI_Global_Charges__c) && isChargeAvailableInTower == false && isChargeNotAvailableInTower == false) {
                    System.debug('Insdie Project Second Error');
                    //isChargeAvailableInProject = true;
                    rl.addError('Global charge is not applicable for this Project');
                }
            }
        }
    }

}