force-app/main/default/objects/Dynamic_Batch_Setting__c/Dynamic_Batch_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to handle batch size and last batch run modstamp</description>
    <label>Dynamic Batch Setting</label>
</CustomObject>

force-app/main/default/objects/Dynamic_Batch_Setting__c/fields/Last_Batch_Run__c.field-meta.xml
<CustomField>
    <fullName>Last_Batch_Run__c</fullName>
    <description>Field to store last batch run time</description>
    <label>Last Batch Run</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/EYI_Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_SAP_Material_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Material_Code__c</fullName>
    <externalId>true</externalId>
    <label>SAP Material Code</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EYI_Project__c/EYI_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Project__c/fields/EYI_SAP_Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Plant_Code__c</fullName>
    <label>SAP Plant Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_SAP_Salesorg__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Salesorg__c</fullName>
    <label>SAP Sales-org</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/EYI_Rate_List__c.object-meta.xml
<CustomObject>
    <label>Rate List</label>
    <nameField>
        <displayFormat>Rate List-{00}</displayFormat>
        <label>Rate List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Calculation_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Calculation_Type__c</fullName>
    <label>Calculation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Fixed Amount</fullName>
            </value>
            <value>
                <fullName>Quantity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Condition_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Condition_Type__c</fullName>
    <label>Condition Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Infra Charges</fullName>
            </value>
            <value>
                <fullName>Base Price</fullName>
            </value>
            <value>
                <fullName>Brokerage Additional</fullName>
            </value>
            <value>
                <fullName>Brokerage</fullName>
            </value>
            <value>
                <fullName>Club House</fullName>
            </value>
            <value>
                <fullName>Floor Rise</fullName>
            </value>
            <value>
                <fullName>Land Cost</fullName>
            </value>
            <value>
                <fullName>2 Wheeler Charges</fullName>
            </value>
            <value>
                <fullName>Base Price-Booking</fullName>
            </value>
            <value>
                <fullName>MSEB Charges</fullName>
            </value>
            <value>
                <fullName>STAMP DUTY AND REG - RECOVERABLE</fullName>
            </value>
            <value>
                <fullName>STAMP DUTY NON RECOVERABLE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Distruibution_Channel__c.field-meta.xml
<CustomField>
    <fullName>EYI_Distruibution_Channel__c</fullName>
    <label>Distruibution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential Sales</fullName>
            </value>
            <value>
                <fullName>Commercial Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Inventory__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory</label>
    <referenceTo>EYI_Inventory__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_is_Sync_SAP__c.field-meta.xml
<CustomField>
    <fullName>EYI_is_Sync_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Sync SAP?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Non_Master_Price__c.field-meta.xml
<CustomField>
    <fullName>EYI_Non_Master_Price__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non Master Price</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Pricing_Amount__c.field-meta.xml
<CustomField>
    <fullName>EYI_Pricing_Amount__c</fullName>
    <label>Pricing Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Pricing_Percentage__c.field-meta.xml
<CustomField>
    <fullName>EYI_Pricing_Percentage__c</fullName>
    <label>Pricing Percentage</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Pricing_Quantity__c.field-meta.xml
<CustomField>
    <fullName>EYI_Pricing_Quantity__c</fullName>
    <label>Pricing Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EYI_PricingCalloutBatchJob.cls
global class EYI_PricingCalloutBatchJob implements Database.Batchable<sObject>,Database.AllowsCallouts { 
    
    public List<EYI_Rate_List__c> start(Database.BatchableContext BC) {
        Dynamic_Batch_Setting__c batchSetting = [Select id,Last_Batch_Run__c from Dynamic_Batch_Setting__c where name = 'Rate List Sync'];
       
        return [select id,EYI_Condition_Type__c,EYI_Project__r.EYI_SAP_Salesorg__c,EYI_Project__r.EYI_SAP_Plant_Code__c, EYI_Pricing_Amount__c,EYI_Pricing_Percentage__c,
                                     EYI_Pricing_Quantity__c,EYI_Calculation_Type__c,EYI_Distruibution_Channel__c,
                                     EYI_Inventory__r.EYI_SAP_Material_Code__c
                                     from EYI_Rate_List__c where EYI_is_Sync_SAP__c=false AND EYI_Non_Master_Price__c=false  AND lastmodifieddate > :batchSetting.Last_Batch_Run__c]; 
    }

    // Execute method - performs the actual logic and the callout
    public void execute(Database.BatchableContext BC, List<EYI_Rate_List__c> scope) {
        EYI_PricingCallout.processPricingRecords(scope,false);
    }

    // Finish method - after all batches have been processed
    public void finish(Database.BatchableContext BC) {
       Dynamic_Batch_Setting__c batchSetting = [Select id,Last_Batch_Run__c from Dynamic_Batch_Setting__c where name = 'Rate List Sync'];
        batchSetting.Last_Batch_Run__c = System.now();
        update batchSetting;
    }

    
}