force-app/main/default/objects/Dynamic_Batch_Setting__c/Dynamic_Batch_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to handle batch size and last batch run modstamp</description>
    <label>Dynamic Batch Setting</label>
</CustomObject>

force-app/main/default/objects/Dynamic_Batch_Setting__c/fields/Last_Batch_Run__c.field-meta.xml
<CustomField>
    <fullName>Last_Batch_Run__c</fullName>
    <description>Field to store last batch run time</description>
    <label>Last Batch Run</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EYI_Booking__c/EYI_Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>BF-{0000000}</displayFormat>
        <label>Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Booking__c/fields/EYI_Floor_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Floor_Number__c</fullName>
    <label>Floor Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/EYI_Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Inventory__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>2BHK</fullName>
            </value>
            <value>
                <fullName>2.5BHK</fullName>
            </value>
            <value>
                <fullName>3BHK</fullName>
            </value>
            <value>
                <fullName>3.5BHK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Balcony_Area__c.field-meta.xml
<CustomField>
    <fullName>EYI_Balcony_Area__c</fullName>
    <label>Balcony Area</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Booking__c.field-meta.xml
<CustomField>
    <fullName>EYI_Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>EYI_Booking__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Built_up_Area__c.field-meta.xml
<CustomField>
    <fullName>EYI_Built_up_Area__c</fullName>
    <label>Built-up Area</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Carpet_Area__c.field-meta.xml
<CustomField>
    <fullName>EYI_Carpet_Area__c</fullName>
    <label>Carpet Area</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Common_Area__c.field-meta.xml
<CustomField>
    <fullName>EYI_Common_Area__c</fullName>
    <label>Common Area</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Floor_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Floor_Number__c</fullName>
    <label>Floor Number</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Garden_Area__c.field-meta.xml
<CustomField>
    <fullName>EYI_Garden_Area__c</fullName>
    <label>Garden Area</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_GST_Tax_Classification__c.field-meta.xml
<CustomField>
    <fullName>EYI_GST_Tax_Classification__c</fullName>
    <label>GST Tax Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Taxable under GST</fullName>
            </value>
            <value>
                <fullName>GST - Exempted</fullName>
            </value>
            <value>
                <fullName>Non Taxable GST</fullName>
            </value>
            <value>
                <fullName>Excisable with GST</fullName>
            </value>
            <value>
                <fullName>Bill of supply</fullName>
            </value>
            <value>
                <fullName>5% Scheme-New RERA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Inventory_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Inventory Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Inventory_Status__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory_Status__c</fullName>
    <label>Inventory Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vacant</fullName>
            </value>
            <value>
                <fullName>Refuge</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Possesion Given</fullName>
            </value>
            <value>
                <fullName>Reserve</fullName>
            </value>
            <value>
                <fullName>Booking</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
                <isActive>false</isActive>
                <label>Available</label>
            </value>
            <value>
                <fullName>EOI Blocked</fullName>
                <isActive>false</isActive>
                <label>EOI Blocked</label>
            </value>
            <value>
                <fullName>Hold For Booking</fullName>
                <isActive>false</isActive>
                <label>Hold For Booking</label>
            </value>
            <value>
                <fullName>Not Sanctioned</fullName>
                <isActive>false</isActive>
                <label>Not Sanctioned</label>
            </value>
            <value>
                <fullName>Payment In Progress</fullName>
                <isActive>false</isActive>
                <label>Payment In Progress</label>
            </value>
            <value>
                <fullName>Possession Given</fullName>
                <isActive>false</isActive>
                <label>Possession Given</label>
            </value>
            <value>
                <fullName>Quotation Is Sent</fullName>
                <isActive>false</isActive>
                <label>Quotation Is Sent</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Inventory_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory_Type__c</fullName>
    <label>Inventory Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential Sales</fullName>
            </value>
            <value>
                <fullName>Commercial Sales</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
                <isActive>false</isActive>
                <label>Commercial</label>
            </value>
            <value>
                <fullName>Residential</fullName>
                <isActive>false</isActive>
                <label>Residential</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Material_Group__c.field-meta.xml
<CustomField>
    <fullName>EYI_Material_Group__c</fullName>
    <label>Material Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apartment</fullName>
            </value>
            <value>
                <fullName>Business Unit</fullName>
            </value>
            <value>
                <fullName>Plots</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Club House</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
                <isActive>false</isActive>
                <label>Parking</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_SAP_Material_Description__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Material_Description__c</fullName>
    <label>Description</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_SAP_Material_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Material_Type__c</fullName>
    <label>Material Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finished Unit</fullName>
            </value>
            <value>
                <fullName>Saleable Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Super_Built_up_Area__c.field-meta.xml
<CustomField>
    <fullName>EYI_Super_Built_up_Area__c</fullName>
    <label>Super Built-Up Area</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_TCS_Tax_Classification__c.field-meta.xml
<CustomField>
    <fullName>EYI_TCS_Tax_Classification__c</fullName>
    <label>TCS Tax Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TCS Applicable</fullName>
            </value>
            <value>
                <fullName>TCS Not Applicable</fullName>
            </value>
            <value>
                <fullName>TDS Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Terrace_Area__c.field-meta.xml
<CustomField>
    <fullName>EYI_Terrace_Area__c</fullName>
    <label>Terrace Area</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_UOM__c.field-meta.xml
<CustomField>
    <fullName>EYI_UOM__c</fullName>
    <label>UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Square foot</fullName>
            </value>
            <value>
                <fullName>Each</fullName>
                <isActive>false</isActive>
                <label>Each</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/EYI_Rate_List__c.object-meta.xml
<CustomObject>
    <label>Rate List</label>
    <nameField>
        <displayFormat>Rate List-{00}</displayFormat>
        <label>Rate List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Inventory__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory</label>
    <referenceTo>EYI_Inventory__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EYI_PricingCalloutBatchJob_Test.cls
@isTest
public class EYI_PricingCalloutBatchJob_Test {
    @isTest
    static void testBatchJob() {
    
        Dynamic_Batch_Setting__c setting = new Dynamic_Batch_Setting__c(
            Name = 'Rate List Sync',
            Last_Batch_Run__c = System.now().addDays(-1)
        );
        insert setting;
        EYI_Inventory__c invtry = new EYI_Inventory__c(
            // EYI_Booking__c=book.id,
            EYI_Inventory_Number__c ='PATN04020',
            Name ='Balewadi Inventory 2',
            EYI_SAP_Material_Type__c='Finished Unit',
            EYI_TCS_Tax_Classification__c='TDS Applicable',
            EYI_GST_Tax_Classification__c ='Non Taxable GST',
            EYI_SAP_Material_Description__c ='qwerty',
            EYI_Inventory_Type__c ='Residential Sales',
            EYI_UOM__c ='Square foot',
            EYI_Material_Group__c='Apartment',
            EYI_Super_Built_up_Area__c=20,
            EYI_Carpet_Area__c =14,
            EYI_Garden_Area__c =20,
            EYI_Terrace_Area__c='50',
            EYI_Balcony_Area__c='30',
            EYI_Built_up_Area__c= 10,
            EYI_Common_Area__c=10,
            EYI_Inventory_Status__c='Reserve',
            EYI_Floor_Number__c='003',
            Configuration__c='Studio',
            EYI_View_based_on_Directions__c='East',
            EYI_View_based_on_Amenities__c='Amenity Facing',
            EYI_SAP_Affordable_Type__c='Affordable Housing',
            EYI_SAP_Profit_Center__c='R150R1R15I'
        );
        insert invtry;

        EYI_Rate_List__c rate = new EYI_Rate_List__c(
            EYI_Condition_Type__c = 'Floor Rise',
            EYI_Pricing_Amount__c = 10000,
            EYI_Pricing_Percentage__c = 10,
            EYI_Pricing_Quantity__c = 5,
            EYI_Calculation_Type__c = 'Percentage',
            EYI_Distruibution_Channel__c = 'Commercial Sales',
            EYI_is_Sync_SAP__c = false,
            EYI_Non_Master_Price__c = false,
            EYI_Inventory__c = invtry.Id
            
          
        );
        insert rate;

        Test.startTest();
        EYI_PricingCalloutBatchJob batch = new EYI_PricingCalloutBatchJob();
        Database.executeBatch(batch, 1);
        Test.stopTest();

       
        Dynamic_Batch_Setting__c updatedSetting = [SELECT Last_Batch_Run__c FROM Dynamic_Batch_Setting__c WHERE Id = :setting.Id];
        System.assert(updatedSetting.Last_Batch_Run__c != null, 'Last_Batch_Run__c should be updated');

        //  EYI_Rate_List__c updatedRate = [SELECT EYI_is_Sync_SAP__c FROM EYI_Rate_List__c WHERE Id = :rate.Id];
        // System.assert(updatedRate.EYI_is_Sync_SAP__c, 'Pricing records should be synced.');

    }
}