force-app/main/default/objects/Dynamic_Batch_Setting__c/Dynamic_Batch_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to handle batch size and last batch run modstamp</description>
    <label>Dynamic Batch Setting</label>
</CustomObject>

force-app/main/default/objects/Dynamic_Batch_Setting__c/fields/Batch_size__c.field-meta.xml
<CustomField>
    <fullName>Batch_size__c</fullName>
    <description>Field to store the batch size</description>
    <label>Batch size</label>
    <precision>14</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EYI_PricingCalloutBatchScheduler_Test.cls
@isTest
public class EYI_PricingCalloutBatchScheduler_Test {
    @isTest
    static void testExecute() {
       
        Dynamic_Batch_Setting__c setting = new Dynamic_Batch_Setting__c(
            Name = 'Rate List Sync',
            Batch_size__c = 20
        );
        insert setting;
        Test.startTest();
        EYI_PricingCalloutBatchScheduler scheduler = new EYI_PricingCalloutBatchScheduler();
        scheduler.execute(null);
        Test.stopTest();

        System.assert(true, 'Scheduler executed without error');
    }
}