force-app/main/default/objects/Dynamic_Batch_Setting__c/Dynamic_Batch_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to handle batch size and last batch run modstamp</description>
    <label>Dynamic Batch Setting</label>
</CustomObject>

force-app/main/default/objects/Dynamic_Batch_Setting__c/fields/Batch_size__c.field-meta.xml
<CustomField>
    <fullName>Batch_size__c</fullName>
    <description>Field to store the batch size</description>
    <label>Batch size</label>
    <precision>14</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dynamic_Batch_Setting__c/fields/Last_Batch_Run__c.field-meta.xml
<CustomField>
    <fullName>Last_Batch_Run__c</fullName>
    <description>Field to store last batch run time</description>
    <label>Last Batch Run</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/EYI_Car_Park_Master__c.object-meta.xml
<CustomObject>
    <label>Car Park Master</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Car Parking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Park Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>Ground Podium Parking</fullName>
            </value>
            <value>
                <fullName>Mezzaine Podium Parking</fullName>
            </value>
            <value>
                <fullName>Ground Stilt Parking</fullName>
            </value>
            <value>
                <fullName>Mezzaine Stilt Parking</fullName>
            </value>
            <value>
                <fullName>Stack car parking</fullName>
            </value>
            <value>
                <fullName>Two wheeler parking</fullName>
            </value>
            <value>
                <fullName>Open car parking</fullName>
            </value>
            <value>
                <fullName>Tendom Parking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Account_Assignment_Group__c.field-meta.xml
<CustomField>
    <fullName>EYI_Account_Assignment_Group__c</fullName>
    <label>Account Assignment Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vehicle Parking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Base_UOM__c.field-meta.xml
<CustomField>
    <fullName>EYI_Base_UOM__c</fullName>
    <label>Base UOM</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Each</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Built_up_Area__c.field-meta.xml
<CustomField>
    <fullName>EYI_Built_up_Area__c</fullName>
    <label>Built-up Area</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Distruibution_Channel__c.field-meta.xml
<CustomField>
    <fullName>EYI_Distruibution_Channel__c</fullName>
    <label>Distruibution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential Sales</fullName>
            </value>
            <value>
                <fullName>Commercial Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_External_Material_Group__c.field-meta.xml
<CustomField>
    <fullName>EYI_External_Material_Group__c</fullName>
    <label>External Material Group</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Floor_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Floor_Number__c</fullName>
    <label>Floor Number</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_GST_Tax_Classification__c.field-meta.xml
<CustomField>
    <fullName>EYI_GST_Tax_Classification__c</fullName>
    <label>GST Tax Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Taxable under GST</fullName>
            </value>
            <value>
                <fullName>GST - Exempted</fullName>
            </value>
            <value>
                <fullName>Non Taxable GST</fullName>
            </value>
            <value>
                <fullName>Excisable with GST</fullName>
            </value>
            <value>
                <fullName>Bill of supply</fullName>
            </value>
            <value>
                <fullName>5% Scheme-New RERA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Is_Syc__c.field-meta.xml
<CustomField>
    <fullName>EYI_Is_Syc__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Syc</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Item_Category__c.field-meta.xml
<CustomField>
    <fullName>EYI_Item_Category__c</fullName>
    <label>Item Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parking Item Cat Grp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Lab_Office__c.field-meta.xml
<CustomField>
    <fullName>EYI_Lab_Office__c</fullName>
    <label>Lab/Office</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Material_Group__c.field-meta.xml
<CustomField>
    <fullName>EYI_Material_Group__c</fullName>
    <label>Material Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Parking_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Parking_Number__c</fullName>
    <externalId>true</externalId>
    <label>Parking Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Car Park Masters</relationshipLabel>
    <relationshipName>Car_Park_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Sales_Unit__c.field-meta.xml
<CustomField>
    <fullName>EYI_Sales_Unit__c</fullName>
    <label>Sales Unit</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_SAP_Affordable_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Affordable_Type__c</fullName>
    <label>Affordable / Non-Affordable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Affordable Housing</fullName>
            </value>
            <value>
                <fullName>Non Affordable Housing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_SAP_Material_Description__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Material_Description__c</fullName>
    <label>Description</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_SAP_Material_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Material_Type__c</fullName>
    <label>Material Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saleable Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_SAP_Profit_Center__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Profit_Center__c</fullName>
    <label>Profit Center</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Status__c.field-meta.xml
<CustomField>
    <fullName>EYI_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Vacant</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_TCS_Tax_Classification__c.field-meta.xml
<CustomField>
    <fullName>EYI_TCS_Tax_Classification__c</fullName>
    <label>TCS Tax Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TCS Applicable</fullName>
            </value>
            <value>
                <fullName>TCS Not Applicable</fullName>
            </value>
            <value>
                <fullName>TDS Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.EYI_Project__c</field>
            <operation>equals</operation>
            <valueField>EYI_Tower__c.EYI_Project_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Car Park Masters</relationshipLabel>
    <relationshipName>Car_Park_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Car_Park_Master__c/fields/EYI_X_Plant_Mat_Status__c.field-meta.xml
<CustomField>
    <fullName>EYI_X_Plant_Mat_Status__c</fullName>
    <label>X-Plant Mat.Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Blocked for procment/whse</fullName>
            </value>
            <value>
                <fullName>Blocked for task list/BOM</fullName>
            </value>
            <value>
                <fullName>MPN: Blocked f.BOM header</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Project__c/EYI_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Project__c/fields/EYI_SAP_Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Plant_Code__c</fullName>
    <label>SAP Plant Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_SAP_Salesorg__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Salesorg__c</fullName>
    <label>SAP Sales-org</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Tower__c/EYI_Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Tower__c/fields/EYI_SAP_Delivery_Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Delivery_Plant_Code__c</fullName>
    <label>SAP Delivery Plant Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Tower__c/fields/EYI_SAP_Plant_ID__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Plant_ID__c</fullName>
    <label>SAP Plant Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EYI_CarParkCalloutBatch.cls
global class EYI_CarParkCalloutBatch implements Database.Batchable<sObject>,Database.AllowsCallouts { 
    
    private List<EYI_Car_Park_Master__c> recordsToProcess;
    private Boolean isFromAura;
    
        // Constructor to accept records when called from Aura
    global EYI_CarParkCalloutBatch(List<EYI_Car_Park_Master__c> records) {
        this.recordsToProcess = records;
        this.isFromAura = true;
    }

    // Default constructor for scheduled execution
    global EYI_CarParkCalloutBatch() {
        this.isFromAura = false;
    }
    
    public List<EYI_Car_Park_Master__c> start(Database.BatchableContext BC) {
        if (isFromAura && recordsToProcess != null && !recordsToProcess.isEmpty()) {
            return [SELECT id,Name,EYI_SAP_Material_Type__c,EYI_Material_Group__c,EYI_Tower__r.EYI_SAP_Plant_ID__c,	EYI_Base_UOM__c,EYI_Tower__r.EYI_SAP_Delivery_Plant_Code__c,EYI_SAP_Material_Description__c,
                    EYI_Project__r.EYI_SAP_Salesorg__c,EYI_Status__c,EYI_Parking_Number__c,EYI_Distruibution_Channel__c,EYI_Project__r.EYI_SAP_Plant_Code__c,EYI_External_Material_Group__c,
                    EYI_Lab_Office__c,EYI_X_Plant_Mat_Status__c,EYI_Built_up_Area__c,EYI_Floor_Number__c,EYI_SAP_Affordable_Type__c,Configuration__c,EYI_SAP_Profit_Center__c,
                    EYI_Account_Assignment_Group__c,EYI_Sales_Unit__c,EYI_Item_Category__c,EYI_GST_Tax_Classification__c,EYI_TCS_Tax_Classification__c
                    from EYI_Car_Park_Master__c WHERE Id IN :recordsToProcess];
        } else{
            List<Dynamic_Batch_Setting__c> batchSettings = [Select id,Last_Batch_Run__c from Dynamic_Batch_Setting__c where name = 'Car Park Sync' LIMIT 1];
            DateTime lastRunDate = (batchSettings.isEmpty()) ? System.now().addDays(-1) : batchSettings[0].Last_Batch_Run__c;
            
            return [SELECT id,Name,EYI_SAP_Material_Type__c,EYI_Material_Group__c, EYI_Tower__r.EYI_SAP_Plant_ID__c, EYI_Base_UOM__c,EYI_Tower__r.EYI_SAP_Delivery_Plant_Code__c,EYI_SAP_Material_Description__c,
                    EYI_Project__r.EYI_SAP_Salesorg__c,EYI_Status__c,EYI_Parking_Number__c,EYI_Distruibution_Channel__c,EYI_Project__r.EYI_SAP_Plant_Code__c,EYI_External_Material_Group__c,
                    EYI_Lab_Office__c,EYI_X_Plant_Mat_Status__c,EYI_Built_up_Area__c,EYI_Floor_Number__c,EYI_SAP_Affordable_Type__c,Configuration__c,EYI_SAP_Profit_Center__c,
                    EYI_Account_Assignment_Group__c,EYI_Sales_Unit__c,EYI_Item_Category__c,EYI_GST_Tax_Classification__c,EYI_TCS_Tax_Classification__c
                    from EYI_Car_Park_Master__c where EYI_Is_Syc__c=false AND lastmodifieddate > :lastRunDate]; 
        }
    }

    // Execute method - performs the actual logic and the callout
    public void execute(Database.BatchableContext BC, List<EYI_Car_Park_Master__c> scope) {
        EYI_CarParkingSyncLwcController.processCarparkingRecords(scope, true);
        
    }

    // Finish method - after all batches have been processed
    public void finish(Database.BatchableContext BC) {
        List<Dynamic_Batch_Setting__c> batchSettings = [Select id,Last_Batch_Run__c from Dynamic_Batch_Setting__c where name = 'Car Park Sync' LIMIT 1];
        
        if(!batchSettings.isEmpty()) {
            Dynamic_Batch_Setting__c batchSetting = batchSettings[0];
            batchSetting.Last_Batch_Run__c = System.now();
            update batchSetting;
        } else {
            // Create the setting if it doesn't exist
            Dynamic_Batch_Setting__c newBatchSetting = new Dynamic_Batch_Setting__c(
                Name = 'Car Park Sync',
                Last_Batch_Run__c = System.now(),
                Batch_size__c = 20
            );
            insert newBatchSetting;
        }
    }

    
}