force-app/main/default/objects/Dynamic_Batch_Setting__c/Dynamic_Batch_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting to handle batch size and last batch run modstamp</description>
    <label>Dynamic Batch Setting</label>
</CustomObject>

force-app/main/default/objects/Dynamic_Batch_Setting__c/fields/Batch_size__c.field-meta.xml
<CustomField>
    <fullName>Batch_size__c</fullName>
    <description>Field to store the batch size</description>
    <label>Batch size</label>
    <precision>14</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EYI_InventoryCalloutBatchScheduler.cls
global class EYI_InventoryCalloutBatchScheduler implements Schedulable {
    global void execute(SchedulableContext sc) {
        // Fetch batch size from Custom Metadata
        Dynamic_Batch_Setting__c batchSetting = [SELECT Batch_size__c FROM Dynamic_Batch_Setting__c WHERE Name = 'Inventory Sync' LIMIT 1];
        
        // Default batch size if not set
        Integer batchSize = (batchSetting.Batch_size__c != null) ? Integer.valueOf(batchSetting.Batch_size__c) : 20;
        
        // Execute the batch job
        EYI_InventoryCalloutBatch batchJob = new EYI_InventoryCalloutBatch();
        Database.executeBatch(batchJob, batchSize);
    }
}