force-app/main/default/objects/EYI_REC__c/EYI_REC__c.object-meta.xml
<CustomObject>
    <label>REC Account</label>
    <nameField>
        <label>REC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REC Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_REC__c/fields/DigiLocker_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>DigiLocker_Transaction_Id__c</fullName>
    <label>DigiLocker Transaction Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_REC__c/fields/EYI_Email__c.field-meta.xml
<CustomField>
    <fullName>EYI_Email__c</fullName>
    <label>Primary Email Id</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/EYI_REC__c/fields/EYI_First_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_First_Name__c</fullName>
    <label>First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_REC__c/fields/EYI_Gender__c.field-meta.xml
<CustomField>
    <fullName>EYI_Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Not Specified</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Nonbinary</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_REC__c/fields/EYI_Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>EYI_Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
            <value>
                <fullName>Widowed</fullName>
            </value>
            <value>
                <fullName>Divorced</fullName>
            </value>
            <value>
                <fullName>Separated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_REC__c/fields/EYI_Mobile__c.field-meta.xml
<CustomField>
    <fullName>EYI_Mobile__c</fullName>
    <label>REC Primary Mobile Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/EYI_REC__c/fields/EYI_Occupation__c.field-meta.xml
<CustomField>
    <fullName>EYI_Occupation__c</fullName>
    <label>Occupation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salaried</fullName>
            </value>
            <value>
                <fullName>Business/Self-Employed</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
            <value>
                <fullName>Housewife</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_REC__c/fields/EYI_PAN_No__c.field-meta.xml
<CustomField>
    <fullName>EYI_PAN_No__c</fullName>
    <label>PAN No</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_REC__c/fields/is_Aadhar_E_KYC_Completed__c.field-meta.xml
<CustomField>
    <fullName>is_Aadhar_E_KYC_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Aadhar E-KYC Completed ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EYI_REC__c/fields/is_PAN_E_KYC_Completed__c.field-meta.xml
<CustomField>
    <fullName>is_PAN_E_KYC_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is PAN E-KYC Completed ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EYI_AadharTxnDetailsUpdateBatchJob_Test.cls
@isTest
public class EYI_AadharTxnDetailsUpdateBatchJob_Test {
    // Helper method to create a test EYI_REC__c record
    private static EYI_REC__c createTestRecord() {
        EYI_REC__c rec = new EYI_REC__c();
        rec.EYI_First_Name__c = 'Test';
        rec.EYI_Last_Name__c = 'Test';
        rec.EYI_PAN_No__c ='BKLJA0667J';
        rec.EYI_Salutation__c ='Mr.';
        rec.EYI_Gender__c = 'Male';
        rec.EYI_Marital_Status__c ='Married';
        rec.EYI_Occupation__c = 'Business';
        rec.is_PAN_E_KYC_Completed__c = false;
        rec.is_Aadhar_E_KYC_Completed__c = false;
        rec.EYI_Email__c ='test@gmail.com';
        rec.EYI_Mobile__c ='9999999999';
        rec.DigiLocker_Transaction_Id__c= 012;
        rec.is_Aadhar_E_KYC_Completed__c=false ;
        insert rec;
        return rec;
    }
    
    // Simple test case for the batch job
    @isTest
    public static void testBatchJob() {
        // Arrange: Create test record
        EYI_REC__c rec = createTestRecord();
        
        // Create an instance of the batch job
        EYI_AadharTxnDetailsUpdateBatchJob batchJob = new EYI_AadharTxnDetailsUpdateBatchJob();
        
        // Start the test to measure the governor limits used by the batch job
        Test.startTest();
        //Test.setMock(HttpCalloutMock.class, new MockAadharResponse());
        Test.setMock(HttpCalloutMock.class, new MockAuthorizationKeyResponse());
        
        // Execute the batch job
        Database.executeBatch(batchJob);
        EYI_AadharTxnDetailsUpdateBatchJob.ResponseAadharDigilockerStatus kd =new  EYI_AadharTxnDetailsUpdateBatchJob.ResponseAadharDigilockerStatus();
        EYI_AadharTxnDetailsUpdateBatchJob.kycdetails kd2 =new EYI_AadharTxnDetailsUpdateBatchJob.kycdetails();
        
        // Stop the test
        Test.stopTest();
        
        
        
        
    }
    public class MockAadharResponse implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setStatusCode(200);
            String jsonResponse = '{"respcode":"200", "respdesc":"Success", "status":"Success", "kycdetails": {' +
                '"name":"John Doe", "fname":"Father Name", "dob":"01-01-1990", "gender":"Male", "uid":"1234567890", ' +
                '"address":"Some Address"}}';
            res.setBody(jsonResponse);
            
            return res;
        }
    }
    
    public class MockAuthorizationKeyResponse implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setStatusCode(200);
            res.setBody('{"respcode": "200", "authkey": "mockAuthKey","respdesc":"Success", "status":"Success", "kycdetails": {' +
                '"name":"John Doe", "fname":"Father Name", "dob":"01-01-1990", "gender":"Male", "uid":"1234567890", ' +
                '"address":"Some Address"}}');
            return res;
        }
    }
}