force-app/main/default/objects/EYI_City__c/fields/EYI_Pincode__c.field-meta.xml
<CustomField>
    <fullName>EYI_Pincode__c</fullName>
    <label>Pincode</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_City__c/fields/EYI_State__c.field-meta.xml
<CustomField>
    <fullName>EYI_State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EYI_Mailing_state</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/EYI_Customer_Information_Form__c.object-meta.xml
<CustomObject>
    <label>CIF Records</label>
    <nameField>
        <displayFormat>CIF-{0000}</displayFormat>
        <label>Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CIF Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Address_1__c.field-meta.xml
<CustomField>
    <fullName>EYI_Address_1__c</fullName>
    <inlineHelpText>Office/House No</inlineHelpText>
    <label>Address 1</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Address_2__c.field-meta.xml
<CustomField>
    <fullName>EYI_Address_2__c</fullName>
    <inlineHelpText>Area/Street</inlineHelpText>
    <label>Address 2</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Address_3__c.field-meta.xml
<CustomField>
    <fullName>EYI_Address_3__c</fullName>
    <inlineHelpText>Landmark</inlineHelpText>
    <label>Address 3</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_City__c.field-meta.xml
<CustomField>
    <fullName>EYI_City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>EYI_City__c</referenceTo>
    <relationshipLabel>CIF Records</relationshipLabel>
    <relationshipName>CIF_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Customer_Address_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Customer_Address_Type__c</fullName>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EYI_Address_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Date_of_birth__c.field-meta.xml
<CustomField>
    <fullName>EYI_Date_of_birth__c</fullName>
    <label>Date of birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Email_Id__c.field-meta.xml
<CustomField>
    <fullName>EYI_Email_Id__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_First_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Mobile_number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Mobile_number__c</fullName>
    <label>Mobile number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Occupation__c.field-meta.xml
<CustomField>
    <fullName>EYI_Occupation__c</fullName>
    <label>Occupation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salaried</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Self Employed</fullName>
            </value>
            <value>
                <fullName>Homemaker</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
                <label>Student</label>
            </value>
            <value>
                <fullName>Defence</fullName>
                <isActive>false</isActive>
                <label>Defence</label>
            </value>
            <value>
                <fullName>Govt employee</fullName>
                <isActive>false</isActive>
                <label>Govt employee</label>
            </value>
            <value>
                <fullName>Private Service</fullName>
                <isActive>false</isActive>
                <label>Private Service</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>EYI_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>CIF Records</relationshipLabel>
    <relationshipName>CIF_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Pincode__c.field-meta.xml
<CustomField>
    <fullName>EYI_Pincode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pincode</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please enter a valid Pincode</errorMessage>
        <filterItems>
            <field>EYI_Panchshil_Master__c.Master_Type__c</field>
            <operation>equals</operation>
            <value>Pincode</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EYI_Panchshil_Master__c</referenceTo>
    <relationshipLabel>CIF Records</relationshipLabel>
    <relationshipName>CIF_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_REC_Account__c.field-meta.xml
<CustomField>
    <fullName>EYI_REC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>REC Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>EYI_REC__c.EYI_REC_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EYI_REC__c</referenceTo>
    <relationshipLabel>CIF Records</relationshipLabel>
    <relationshipName>CIF_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_State__c.field-meta.xml
<CustomField>
    <fullName>EYI_State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>EYI_Customer_Address_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>EYI_Mailing_state</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_FCM_Detail__c/EYI_FCM_Detail__c.object-meta.xml
<CustomObject>
    <label>FCM Detail</label>
    <nameField>
        <displayFormat>FCM-{0000}</displayFormat>
        <label>FCM Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FCM Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_FCM_Detail__c/fields/EYI_Custom_Device_ID__c.field-meta.xml
<CustomField>
    <fullName>EYI_Custom_Device_ID__c</fullName>
    <label>Custom Device ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_FCM_Detail__c/fields/EYI_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>EYI_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>FCM Details</relationshipLabel>
    <relationshipName>FCM_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Panchshil_Master__c/EYI_Panchshil_Master__c.object-meta.xml
<CustomObject>
    <label>Panchshil Master</label>
    <nameField>
        <displayFormat>Master-{0000000000}</displayFormat>
        <label>Master Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panchshil Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Panchshil_Master__c/fields/EYI_Pincode__c.field-meta.xml
<CustomField>
    <fullName>EYI_Pincode__c</fullName>
    <label>Pincode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Panchshil_Master__c/fields/EYI_State__c.field-meta.xml
<CustomField>
    <fullName>EYI_State__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Panchshil_Master__c/fields/EYI_Sub_Urb__c.field-meta.xml
<CustomField>
    <fullName>EYI_Sub_Urb__c</fullName>
    <label>Sub Urb</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Panchshil_Master__c/fields/EYI_Zone__c.field-meta.xml
<CustomField>
    <fullName>EYI_Zone__c</fullName>
    <label>Zone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Panchshil_Master__c/fields/Master_Type__c.field-meta.xml
<CustomField>
    <fullName>Master_Type__c</fullName>
    <label>Master Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pincode</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/EYI_Address_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pune</fullName>
    </customValue>
    <customValue>
        <fullName>Mumbai</fullName>
    </customValue>
    <customValue>
        <fullName>OS (Rest of India)</fullName>
    </customValue>
    <customValue>
        <fullName>NRI</fullName>
    </customValue>
    <masterLabel>Address Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/EYI_Mailing_state.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abu Dhabi</fullName>
    </customValue>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Alberta</fullName>
    </customValue>
    <customValue>
        <fullName>Andhra Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Arizona</fullName>
    </customValue>
    <customValue>
        <fullName>Arunachal Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Assam</fullName>
    </customValue>
    <customValue>
        <fullName>Auckland</fullName>
    </customValue>
    <customValue>
        <fullName>Bihar</fullName>
    </customValue>
    <customValue>
        <fullName>British Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>California</fullName>
    </customValue>
    <customValue>
        <fullName>Chandigarh</fullName>
    </customValue>
    <customValue>
        <fullName>Chhattisgarh</fullName>
    </customValue>
    <customValue>
        <fullName>Chicago</fullName>
    </customValue>
    <customValue>
        <fullName>Delhi</fullName>
    </customValue>
    <customValue>
        <fullName>Dubai</fullName>
    </customValue>
    <customValue>
        <fullName>Flordia</fullName>
    </customValue>
    <customValue>
        <fullName>Georgia</fullName>
    </customValue>
    <customValue>
        <fullName>Goa</fullName>
    </customValue>
    <customValue>
        <fullName>Gujarat</fullName>
    </customValue>
    <customValue>
        <fullName>Haryana</fullName>
    </customValue>
    <customValue>
        <fullName>Himachal Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>Illinois</fullName>
    </customValue>
    <customValue>
        <fullName>Jammu and Kashmir</fullName>
    </customValue>
    <customValue>
        <fullName>Jharkhand</fullName>
    </customValue>
    <customValue>
        <fullName>Karnataka</fullName>
    </customValue>
    <customValue>
        <fullName>Kerala</fullName>
    </customValue>
    <customValue>
        <fullName>Louisiana</fullName>
    </customValue>
    <customValue>
        <fullName>Madhya Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Maharashtra</fullName>
        <default>true</default>
        <label>Maharashtra</label>
    </customValue>
    <masterLabel>Mailing state</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpprtunityHandlerTest.cls
@isTest
public class OpprtunityHandlerTest {
    @isTest
	static void testProcessFromReceiptsAndReceiptIds() {
        //payment receipt trigger and handler test class
        EYI_Panchshil_Master__c mster = new EYI_Panchshil_Master__c(
            EYI_City__c='Pune',
            EYI_State__c='Maharashtra',
            EYI_Pincode__c='410405',
            Master_Type__c='Pincode',
            EYI_Zone__c ='Pune Region',
            EYI_Sub_Urb__c='Pune Moffusil Division'
        );
        insert mster;
        EYI_City__c city = new EYI_City__c(
            Name='Pune',
            EYI_State__c='Maharashtra',
            EYI_Pincode__c='410405'
        );
        insert city;
        
        EYI_Customer_Information_Form__c CIF = new EYI_Customer_Information_Form__c(
            EYI_City__c =city.id,
            EYI_Salutation__c='Mr.',
            //EYI_REC_Account__c= Acc.id,
            EYI_Pincode__c =mster.id,
            EYI_First_Name__c ='test applicant',
            EYI_Last_Name__c='cif',
            EYI_Mobile_number__c= '9764212568',
            EYI_Address_1__c ='noida test',
            EYI_Address_2__c='test',
            EYI_Address_3__c='test',
            EYI_Email_Id__c='test@gmail.com',
            EYI_Customer_Address_Type__c ='OS (Rest of India)',
            EYI_State__c= 'Maharashtra'
            
        );
        insert CIF;
        
         Account Acc = new Account(
            Name='test Account',
            EYI_Marital_Status__c='Single',
            EYI_Nationality__c='Indian',
            EYI_Occupation__c='Salaried',
            EYI_Email__c='nilesh.ghodke@in.ey.com',
            EYI_Date_Of_Birth__c= system.today()-10
             
        );
        insert Acc;
        Opportunity testOpportunity = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Prospecting',
            AccountId=Acc.Id,
            EYI_CIF_Record__c =CIF.id,
            CloseDate = Date.today().addDays(30),
            EYI_Primary_Closing_Manager__c=UserInfo.getUserId(),
            Primary_Closing_Manager_Head__c= UserInfo.getUserId(),
            EYI_Relationship_Manager__c = UserInfo.getUserId()
        );
        insert testOpportunity;
        
        EYI_FCM_Detail__c fcm = new EYI_FCM_Detail__c(
            EYI_Opportunity__c = testOpportunity.Id,
            EYI_Custom_Device_ID__c = 'mock_device_token_123'
        );
        insert fcm;
        Test.setMock(HttpCalloutMock.class, new EYI_FCMCalloutMock());
        test.startTest();
        testOpportunity.EYI_NCF_Status__c = 'Received';
        update testOpportunity;
        test.stopTest();
    }
}