force-app/main/default/objects/EYI_Lead_Enquiry__c/EYI_Lead_Enquiry__c.object-meta.xml
<CustomObject>
    <label>Lead Enquiry</label>
    <nameField>
        <label>Lead Entries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Enquiries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/DNC__c.field-meta.xml
<CustomField>
    <fullName>DNC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DNC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_DNC__c.field-meta.xml
<CustomField>
    <fullName>EYI_DNC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EYI DNC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>EYI_Lead_Status__c</fullName>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Follow Up</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Visit Proposed</fullName>
            </value>
            <value>
                <fullName>Visit Confirmed</fullName>
            </value>
            <value>
                <fullName>Visit Done</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Non-contactable</fullName>
                <label>Non-Contactable</label>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>REC</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
                <isActive>false</isActive>
                <label>Converted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_No_of_Not_Connected_Follow_Ups__c.field-meta.xml
<CustomField>
    <fullName>EYI_No_of_Not_Connected_Follow_Ups__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No of Not Connected Follow Ups</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Parent_Record__c.field-meta.xml
<CustomField>
    <fullName>EYI_Parent_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Lead_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Site_Visit_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Site_Visit_Date__c</fullName>
    <label>Proposed Date of Visit</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/EYI_RemoveDNCBatchTest.cls
@isTest
private class EYI_RemoveDNCBatchTest {

@IsTest
    static void testStartMethod() {
        // Create a test EYI_Lead_Enquiry__c record with DNC__c = True and EYI_DNC__c = True
        Lead newLead = new Lead(
            LastName = 'TestLastName',
            Company = 'TestCompany',
            LeadSource = 'Web',
            Email = 'test@test.com'
        );
        insert newLead;

        EYI_Lead_Enquiry__c testLead = new EYI_Lead_Enquiry__c(
            EYI_Lead_Status__c = 'Open',
            EYI_Site_Visit_Date__c = Date.today().addDays(-1),
            DNC__c = True,
            EYI_DNC__c = True,
            EYI_No_of_Not_Connected_Follow_Ups__c = 0,
            EYI_Parent_Record__c = newLead.Id
        );
        insert testLead;
        List<SObject> sobjlist = new List<SObject>();
        sobjlist.add(testLead);

        Test.startTest();
        EYI_RemoveDNCBatch batch = new EYI_RemoveDNCBatch();
        Database.BatchableContext bc = null;
        Database.QueryLocator queryLocator = batch.start(bc);
        batch.execute(bc,sobjlist);
        EYI_RemoveDNCBatchScheduler scheBatch = new EYI_RemoveDNCBatchScheduler();
        scheBatch.execute(null);
        Test.stopTest();

        // Assert that the query locator is not null
    }
}