force-app/main/default/objects/EYI_Lead_Enquiry__c/EYI_Lead_Enquiry__c.object-meta.xml
<CustomObject>
    <label>Lead Enquiry</label>
    <nameField>
        <label>Lead Entries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Enquiries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Client_Communication_Preference__c.field-meta.xml
<CustomField>
    <fullName>EYI_Client_Communication_Preference__c</fullName>
    <label>Client Communication Preference</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>All</fullName>
                <default>true</default>
                <label>All</label>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Whats App</fullName>
                <isActive>false</isActive>
                <label>Whats App</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>EYI_Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Advertisement</fullName>
                <isActive>false</isActive>
                <label>Advertisement</label>
            </value>
            <value>
                <fullName>Archive Leads</fullName>
                <isActive>false</isActive>
                <label>Archive Leads</label>
            </value>
            <value>
                <fullName>ChatBot</fullName>
            </value>
            <value>
                <fullName>Cold Calling</fullName>
                <isActive>false</isActive>
                <label>Cold Calling</label>
            </value>
            <value>
                <fullName>Core Leads</fullName>
                <isActive>false</isActive>
                <label>Core Leads</label>
            </value>
            <value>
                <fullName>CTI</fullName>
            </value>
            <value>
                <fullName>Database</fullName>
                <isActive>false</isActive>
                <label>Database</label>
            </value>
            <value>
                <fullName>Databases</fullName>
                <isActive>false</isActive>
                <label>Databases</label>
            </value>
            <value>
                <fullName>Digital Media</fullName>
                <isActive>false</isActive>
                <label>Digital Media</label>
            </value>
            <value>
                <fullName>Direct</fullName>
                <isActive>false</isActive>
                <label>Direct</label>
            </value>
            <value>
                <fullName>Direct Client</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Employee Referral</fullName>
                <isActive>false</isActive>
                <label>Employee Referral</label>
            </value>
            <value>
                <fullName>Employee Referral Scheme</fullName>
                <isActive>false</isActive>
                <label>Employee Referral Scheme</label>
            </value>
            <value>
                <fullName>Exhibition</fullName>
                <isActive>false</isActive>
                <label>Exhibition</label>
            </value>
            <value>
                <fullName>Existing Client</fullName>
            </value>
            <value>
                <fullName>External Referral</fullName>
                <isActive>false</isActive>
                <label>External Referral</label>
            </value>
            <value>
                <fullName>EYI Contact Center</fullName>
                <isActive>false</isActive>
                <label>EYI Contact Center</label>
            </value>
            <value>
                <fullName>IVR</fullName>
                <isActive>false</isActive>
                <label>IVR</label>
            </value>
            <value>
                <fullName>Lead Reference</fullName>
                <isActive>false</isActive>
                <label>Lead Reference</label>
            </value>
            <value>
                <fullName>Lost Leads</fullName>
                <isActive>false</isActive>
                <label>Lost Leads</label>
            </value>
            <value>
                <fullName>Loyalty</fullName>
                <isActive>false</isActive>
                <label>Loyalty</label>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Mobile App</fullName>
            </value>
            <value>
                <fullName>Newspaper Ad</fullName>
                <isActive>false</isActive>
                <label>Newspaper Ad</label>
            </value>
            <value>
                <fullName>OOH</fullName>
                <isActive>false</isActive>
                <label>OOH</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Outdoor Activation</fullName>
                <isActive>false</isActive>
                <label>Outdoor Activation</label>
            </value>
            <value>
                <fullName>Partner</fullName>
                <isActive>false</isActive>
                <label>Partner</label>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>EYI_Lead_Status__c</fullName>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Follow Up</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Visit Proposed</fullName>
            </value>
            <value>
                <fullName>Visit Confirmed</fullName>
            </value>
            <value>
                <fullName>Visit Done</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Non-contactable</fullName>
                <label>Non-Contactable</label>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>REC</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
                <isActive>false</isActive>
                <label>Converted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_LeadType__c.field-meta.xml
<CustomField>
    <fullName>EYI_LeadType__c</fullName>
    <label>Lead Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>EYI_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apartment</fullName>
            </value>
            <value>
                <fullName>FnB</fullName>
            </value>
            <value>
                <fullName>Office Unit</fullName>
            </value>
            <value>
                <fullName>Plot</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Business Unit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Nature_of_Lead__c.field-meta.xml
<CustomField>
    <fullName>EYI_Nature_of_Lead__c</fullName>
    <label>Nature of Lead</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Outright</fullName>
            </value>
            <value>
                <fullName>Leasing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Parent_Record__c.field-meta.xml
<CustomField>
    <fullName>EYI_Parent_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Lead_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Phone__c.field-meta.xml
<CustomField>
    <fullName>EYI_Phone__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Purpose_of_Purchase__c.field-meta.xml
<CustomField>
    <fullName>EYI_Purpose_of_Purchase__c</fullName>
    <label>Purpose of Purchase</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>EYI_Nature_of_Lead__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>End Use</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Second Home</fullName>
            </value>
            <value>
                <fullName>End User</fullName>
                <isActive>false</isActive>
                <label>End User</label>
            </value>
            <value>
                <fullName>Gift</fullName>
                <isActive>false</isActive>
                <label>Gift</label>
            </value>
            <value>
                <fullName>Investor</fullName>
                <isActive>false</isActive>
                <label>Investor</label>
            </value>
            <value>
                <fullName>NA</fullName>
                <isActive>false</isActive>
                <label>NA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Segment__c.field-meta.xml
<CustomField>
    <fullName>EYI_Segment__c</fullName>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Notification_Settings__c/EYI_Notification_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting is used to on/off the notifications</description>
    <label>Notification Settings</label>
</CustomObject>

force-app/main/default/objects/EYI_Notification_Settings__c/fields/EYI_Is_Notifications_Enabled__c.field-meta.xml
<CustomField>
    <fullName>EYI_Is_Notifications_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Notifications Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EYI_NotificationHandlerTest.cls
@isTest
public with sharing class EYI_NotificationHandlerTest {
    @TestSetup
    static void makeData(){
        EYI_Notification_Settings__c testSetting = new EYI_Notification_Settings__c(
            EYI_Is_Notifications_Enabled__c = true
        );
        insert testSetting;
    }
    @IsTest
    static void EYI_NotificationHandlerTest(){
        EYI_Assignment_Group_Member__c member = EYI_TestDataFactory.createAssignmentGroupMember(System.Label.Presales_Assignment_Group_Label,true);
        Test.startTest();
            List<Lead> leadList = EYI_TestDataFactory.createLeads('Test',4,'983434334','Direct Client','',true);
            EYI_Lead_Enquiry__c enq = new EYI_Lead_Enquiry__c();
            enq.EYI_Parent_Record__c = leadList[0].Id;
            enq.EYI_Lead_Status__c = 'Open';
            enq.EYI_Client_Communication_Preference__c = 'All';
            enq.EYI_Lead_Source__c = 'Web';
            enq.EYI_Phone__c = '+918877664455';

            insert enq;
        Test.stopTest();
    }
    @IsTest
    static void EYI_NotificationHandlerTest1(){
        EYI_Assignment_Group_Member__c member = EYI_TestDataFactory.createAssignmentGroupMember(System.Label.Presales_Assignment_Group_Label,true);
        EYI_Assignment_Group_Member__c member2 = EYI_TestDataFactory.createAssignmentGroupMember(System.Label.EYI_ClosingManagerGroupName,true);

        Test.startTest();
            List<Lead> leadList = EYI_TestDataFactory.createLeads('Test',4,'983434334','Direct Client','',true);
            EYI_Lead_Enquiry__c enq = new EYI_Lead_Enquiry__c();
            enq.EYI_Parent_Record__c = leadList[0].Id;
        	enq.EYI_Nature_of_Lead__c = 'Outright';
        	enq.EYI_Purpose_of_Purchase__c = 'End Use';
        	enq.EYI_Segment__c = 'Residential';
        	enq.EYI_LeadType__c	 = 'Villa';
        	enq.EYI_Property__c = '46 Banyan Tree';
        	enq.Name = 'Testing123';
        	enq.EYI_Company__c = 'Testing123';
        	enq.EYI_Email__c = 'testing321@gmail.com';
        	enq.EYI_Rating__c = 'Hot';
            enq.EYI_Lead_Status__c = 'Open';
            enq.EYI_Client_Communication_Preference__c = 'All';
            enq.EYI_Lead_Source__c = 'Web';
            enq.EYI_Phone__c = '+918877664455';
            enq.EYI_Site_Visit_Date__c = system.now();

            insert enq;
			System.debug('Lead Status 1 = '+enq.EYI_Lead_Status__c);
            enq.EYI_Lead_Status__c='Visit Confirmed';
            update enq;
            System.debug('Lead Status 2 = '+enq.EYI_Lead_Status__c);
        	EYI_LeadEnquiryUtility.getLeadInfo(enq.id);
        	enq.EYI_Lead_Status__c='No Show';
            update enq;
            System.debug('Lead Status 3 = '+enq.EYI_Lead_Status__c);
        
        	List<EYI_Lead_Enquiry__History> leadHistories = [
            SELECT ParentId, CreatedById, Field, OldValue, NewValue, CreatedDate
            FROM EYI_Lead_Enquiry__History
            WHERE ParentId = :enq.id 
            AND (Field = 'EYI_Lead_Status__c' OR Field = 'Created')
            ORDER BY CreatedDate
        ];
        
        System.debug('Lead histories.size = >'+leadHistories.size());
            EYI_LeadEnquiryUtility.getLeadStatusTime(enq.Id);
        Test.stopTest();
    }
    @IsTest
    static void EYI_NotificationHandlerTest2(){
        EYI_Assignment_Group_Member__c member = EYI_TestDataFactory.createAssignmentGroupMember(System.Label.Presales_Assignment_Group_Label,true);
        EYI_Assignment_Group_Member__c member2 = EYI_TestDataFactory.createAssignmentGroupMember(System.Label.EYI_ClosingManagerGroupName,true);
        List<EYI_Project__c> projectList = EYI_TestDataFactory.createProjects('One North', 1, true,'Commercial');        

        Test.startTest();
            List<Lead> leadList = EYI_TestDataFactory.createLeads('Test',4,'983434334','Direct Client','',true);
            EYI_Lead_Enquiry__c enq = new EYI_Lead_Enquiry__c();
            enq.EYI_Parent_Record__c = leadList[0].Id;
            enq.EYI_Lead_Status__c = 'Open';
            enq.EYI_Client_Communication_Preference__c = 'All';
            enq.EYI_Lead_Source__c = 'Web';
            enq.EYI_Phone__c = '+918877664455';
            insert enq;
            enq.EYI_Lead_Source__c = 'Other';
            enq.EYI_Lead_Status__c='No Show';
            update enq;

            //EYI_SMSService.sendSMSBrochure(enq.EYI_Phone__c,'{!Name} hi',enq.id);
        Test.stopTest();
    }
    @IsTest
    static void EYI_NotificationHandlerTest3(){
        EYI_Assignment_Group_Member__c member = EYI_TestDataFactory.createAssignmentGroupMember(System.Label.Presales_Assignment_Group_Label,true);
        EYI_Assignment_Group_Member__c member2 = EYI_TestDataFactory.createAssignmentGroupMember(System.Label.EYI_ClosingManagerGroupName,true);
        List<EYI_Project__c> projectList = EYI_TestDataFactory.createProjects('One North', 1, true,'Commercial');        
        
        Test.startTest();
            List<Lead> leadList = EYI_TestDataFactory.createLeads('Test',4,'983434334','Direct Client','',true);
            EYI_Lead_Enquiry__c enq = new EYI_Lead_Enquiry__c();
            enq.EYI_Parent_Record__c = leadList[0].Id;
            enq.EYI_Lead_Status__c = 'Open';
            enq.EYI_Client_Communication_Preference__c = 'All';
            enq.EYI_Lead_Source__c = 'Web';
            enq.EYI_Email__c = 'Web@gmail.com';
            enq.EYI_Phone__c = '+918877664455';
            enq.EYI_Site_Visit_Date__c = system.now();

            insert enq;
            ContentVersion contentVersion = new ContentVersion();
            contentVersion.Title = 'Test File';
            contentVersion.PathOnClient = 'TestFile.txt';
            contentVersion.VersionData = Blob.valueOf('Sample content');
            insert contentVersion;


        // Query the ContentDocumentId
        ContentVersion insertedContentVersion = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion.Id];
        List<String> myList = new List<String>();
        myList.add(insertedContentVersion.ContentDocumentId);
     
        EYI_BrochureCommunicationWrapper wrapper = new EYI_BrochureCommunicationWrapper();
            wrapper.leadId = enq.id;
            wrapper.projectId = projectList[0].id;
            wrapper.projectName = projectList[0].name;
            wrapper.senderEmail = enq.EYI_Email__c;
            wrapper.senderPhone = enq.EYI_Phone__c;
            wrapper.selectedFileIds = myList;
            wrapper.messagebody = 'enq.EYI_Phone__c';
            wrapper.emailSubject = 'enq.EYI_Phone__c';

            String jsonString = JSON.serialize(wrapper);
            EYI_EmailService.sendEmail(jsonString);
            EYI_MergeFieldsWrapper testWrapper = new EYI_MergeFieldsWrapper(enq.id,'EYI_Phone__c','EYI_Phone__c','EYI_Phone__c' );
            EYI_LeadEnquiryUtility.getFilesByProjectId(projectList[0].Id);
            EYI_LeadEnquiryUtility.StatusWrapper stwrapper = new EYI_LeadEnquiryUtility.StatusWrapper('test','test',10,System.now());

        Test.stopTest();
    }

    @IsTest
    static void EYI_NotificationHandlerTest4(){
        EYI_Assignment_Group_Member__c member = EYI_TestDataFactory.createAssignmentGroupMember(System.Label.Presales_Assignment_Group_Label,true);
        EYI_Assignment_Group_Member__c member2 = EYI_TestDataFactory.createAssignmentGroupMember(System.Label.EYI_ClosingManagerGroupName,true);
        List<EYI_Project__c> projectList = EYI_TestDataFactory.createProjects('One North', 1, true,'Commercial');        
        
        Test.startTest();
            List<Lead> leadList = EYI_TestDataFactory.createLeads('Test',4,'983434334','Direct Client','',true);
            EYI_Lead_Enquiry__c enq = new EYI_Lead_Enquiry__c();
            enq.EYI_Parent_Record__c = leadList[0].Id;
            enq.EYI_Lead_Status__c = 'Open';
            enq.EYI_Client_Communication_Preference__c = 'All';
            enq.EYI_Lead_Source__c = 'Web';
            enq.EYI_Email__c = 'Web@gmail.com';
            enq.EYI_Phone__c = '+918877664455';
            enq.EYI_Site_Visit_Date__c = system.now();

            insert enq;
            ContentVersion contentVersion = new ContentVersion();
            contentVersion.Title = 'Test File';
            contentVersion.PathOnClient = 'TestFile.txt';
            contentVersion.VersionData = Blob.valueOf('Sample content');
            insert contentVersion;

        // Query the ContentDocumentId
        ContentVersion insertedContentVersion = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion.Id];
        List<String> myList = new List<String>();
        myList.add(insertedContentVersion.ContentDocumentId);
        
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = insertedContentVersion.ContentDocumentId; // Example ContentDocumentId
        cdl.LinkedEntityId = projectList[0].Id; // Example LinkedEntityId (e.g., Account ID)
        cdl.ShareType = 'V'; // Viewer
        cdl.Visibility = 'AllUsers';
        insert cdl;

        EYI_BrochureCommunicationWrapper wrapper = new EYI_BrochureCommunicationWrapper();
            wrapper.leadId = enq.id;
            wrapper.projectId = projectList[0].id;
            wrapper.projectName = projectList[0].name;
            wrapper.senderEmail = enq.EYI_Email__c;
            wrapper.senderPhone = enq.EYI_Phone__c;
            wrapper.selectedFileIds = myList;
            wrapper.messagebody = 'enq.EYI_Phone__c';
            wrapper.emailSubject = 'enq.EYI_Phone__c';

            String jsonString = JSON.serialize(wrapper);
            EYI_EmailService.sendEmail(jsonString);
            EYI_MergeFieldsWrapper testWrapper = new EYI_MergeFieldsWrapper(enq.id,'EYI_Phone__c','EYI_Phone__c','EYI_Phone__c' );
            EYI_LeadEnquiryUtility.getFilesByProjectId(projectList[0].Id);
            EYI_LeadEnquiryUtility.StatusWrapper stwrapper = new EYI_LeadEnquiryUtility.StatusWrapper('test','test',10,System.now());
        Test.stopTest();
    }
    
    @isTest
    public static void getEmailTemplatesTest(){
        Test.startTest();
        EYI_LeadEnquiryUtility.getEmailTemplates();
        Test.stopTest();
    }
    
    @isTest
    public static void getEmailTemplateDetailsTest(){
        
    }
}