force-app/main/default/objects/EYI_Lead_Enquiry__c/EYI_Lead_Enquiry__c.object-meta.xml
<CustomObject>
    <label>Lead Enquiry</label>
    <nameField>
        <label>Lead Entries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Enquiries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>EYI_Lead_Status__c</fullName>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Follow Up</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Visit Proposed</fullName>
            </value>
            <value>
                <fullName>Visit Confirmed</fullName>
            </value>
            <value>
                <fullName>Visit Done</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Non-contactable</fullName>
                <label>Non-Contactable</label>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>REC</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
                <isActive>false</isActive>
                <label>Converted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Phone__c.field-meta.xml
<CustomField>
    <fullName>EYI_Phone__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Site_Visit_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Site_Visit_Date__c</fullName>
    <label>Proposed Date of Visit</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/EYI_VisitConfirmationWAppAlertBatch.cls
global with sharing class EYI_VisitConfirmationWAppAlertBatch implements Database.Batchable<Sobject>,Database.AllowsCallouts,Database.Stateful {
        global Database.QueryLocator start(Database.BatchableContext BC) {
            // Query to get the eyi_leadenqury records
            String query = 'SELECT Id, EYI_Lead_Status__c, EYI_Site_Visit_Date__c, EYI_Phone__c FROM EYI_Lead_Enquiry__c WHERE EYI_Site_Visit_Date__c!= NULL AND EYI_Lead_Status__c = \'Visit Confirmed\'';
            return Database.getQueryLocator(query);
        }
    
        global void execute(Database.BatchableContext BC, List<EYI_Lead_Enquiry__c> scope) {
            // Process each batch of records
            for (EYI_Lead_Enquiry__c enq : scope) {
                Date siteVisitDate = enq.EYI_Site_Visit_Date__c.date();
                if (enq.EYI_Phone__c != null) {
                    if (siteVisitDate != null && siteVisitDate == System.today()) {
                        try {
                            tdc_tsw.GlobalSMSSender.messageType = 'WhatsApp';  
                            tdc_tsw.GlobalSMSSender.senderNumber = System.Label.EYI_WhatsAppSenderNumber;
                            tdc_tsw.GlobalSMSSender.isSyncCall = true;
                            tdc_tsw.GlobalSMSSender.SendSmsWithPhoneAPiAndTemplateId(
                                'EYI_Phone__c',
                                System.Label.EYI_VC_TodayWPTemplate,
                                enq.Id
                            );
                            System.debug('===>'+enq.Id +'===>'+System.Label.EYI_VC_TodayWPTemplate);
                        } catch (Exception e) {
                            System.debug('Exception : '+e);
                        }
                    } else if (siteVisitDate != null && siteVisitDate == Date.today().addDays(1)) {  // Compare Date with Date
                        try {
                            tdc_tsw.GlobalSMSSender.messageType = 'WhatsApp'; 
                            tdc_tsw.GlobalSMSSender.senderNumber = System.Label.EYI_WhatsAppSenderNumber;
                            tdc_tsw.GlobalSMSSender.isSyncCall = true;
                            tdc_tsw.GlobalSMSSender.SendSmsWithPhoneAPiAndTemplateId(
                                'EYI_Phone__c',
                                System.Label.EYI_VC_TomorrowWPTemplate,
                                enq.Id
                            );
                        } catch (Exception e) {
                            System.debug('Exception : '+e);
                        }
                    }
                }
            }
        }
    
        global void finish(Database.BatchableContext BC) {
            System.debug('finish : ');
        }
    }