force-app/main/default/objects/EYI_Lead_Enquiry__c/EYI_Lead_Enquiry__c.object-meta.xml
<CustomObject>
    <label>Lead Enquiry</label>
    <nameField>
        <label>Lead Entries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Enquiries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Budget__c.field-meta.xml
<CustomField>
    <fullName>EYI_Budget__c</fullName>
    <label>Budget</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>EYI_Nature_of_Lead__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>EYI_Budget</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Client_Communication_Preference__c.field-meta.xml
<CustomField>
    <fullName>EYI_Client_Communication_Preference__c</fullName>
    <label>Client Communication Preference</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>All</fullName>
                <default>true</default>
                <label>All</label>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Whats App</fullName>
                <isActive>false</isActive>
                <label>Whats App</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Designation__c.field-meta.xml
<CustomField>
    <fullName>EYI_Designation__c</fullName>
    <label>Designation</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Lead_Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>EYI_Lead_Sub_Source__c</fullName>
    <label>Lead Sub Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>EYI_Lead_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>99Acres</fullName>
            </value>
            <value>
                <fullName>AIC</fullName>
                <isActive>false</isActive>
                <label>AIC</label>
            </value>
            <value>
                <fullName>Amazon</fullName>
            </value>
            <value>
                <fullName>Archive Leads</fullName>
            </value>
            <value>
                <fullName>Atul Sir</fullName>
            </value>
            <value>
                <fullName>Bill Board</fullName>
                <isActive>false</isActive>
                <label>Bill Board</label>
            </value>
            <value>
                <fullName>Bombay Times</fullName>
                <isActive>false</isActive>
                <label>Bombay Times</label>
            </value>
            <value>
                <fullName>Booked_Cancelled</fullName>
            </value>
            <value>
                <fullName>Booked Cancelled</fullName>
                <isActive>false</isActive>
                <label>Booked Cancelled</label>
            </value>
            <value>
                <fullName>Brochure Download</fullName>
                <isActive>false</isActive>
                <label>Brochure Download</label>
            </value>
            <value>
                <fullName>Bulk Whatsapp</fullName>
                <isActive>false</isActive>
                <label>Bulk WhatsApp</label>
            </value>
            <value>
                <fullName>Bulk Whatsapp_Lost</fullName>
            </value>
            <value>
                <fullName>Bulk Whatsapp Lost</fullName>
                <isActive>false</isActive>
                <label>Bulk Whatsapp Lost</label>
            </value>
            <value>
                <fullName>Bus Shelter</fullName>
                <isActive>false</isActive>
                <label>Bus Shelter</label>
            </value>
            <value>
                <fullName>Bus Wrap</fullName>
                <isActive>false</isActive>
                <label>Bus Wrap</label>
            </value>
            <value>
                <fullName>Cable Network</fullName>
                <isActive>false</isActive>
                <label>Cable Network</label>
            </value>
            <value>
                <fullName>Centralised</fullName>
                <isActive>false</isActive>
                <label>Centralised</label>
            </value>
            <value>
                <fullName>Centralized IVR</fullName>
            </value>
            <value>
                <fullName>Channel Partner</fullName>
                <isActive>false</isActive>
                <label>Channel Partner</label>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Columbia Ads</fullName>
                <isActive>false</isActive>
                <label>Columbia Ads</label>
            </value>
            <value>
                <fullName>Common Floor</fullName>
                <isActive>false</isActive>
                <label>Common Floor</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>CPC</fullName>
                <isActive>false</isActive>
                <label>CPC</label>
            </value>
            <value>
                <fullName>CPC Colombia</fullName>
                <isActive>false</isActive>
                <label>CPC Colombia</label>
            </value>
            <value>
                <fullName>CPC Moneycontrol</fullName>
                <isActive>false</isActive>
                <label>CPC Moneycontrol</label>
            </value>
            <value>
                <fullName>CTI</fullName>
            </value>
            <value>
                <fullName>D&amp;B Database</fullName>
            </value>
            <value>
                <fullName>Database</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
                <isActive>false</isActive>
                <label>Direct</label>
            </value>
            <value>
                <fullName>Retail</fullName>
                <isActive>false</isActive>
                <label>Retail</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_LeadType__c.field-meta.xml
<CustomField>
    <fullName>EYI_LeadType__c</fullName>
    <label>Lead Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>EYI_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apartment</fullName>
            </value>
            <value>
                <fullName>FnB</fullName>
            </value>
            <value>
                <fullName>Office Unit</fullName>
            </value>
            <value>
                <fullName>Plot</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Business Unit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Property__c.field-meta.xml
<CustomField>
    <fullName>EYI_Property__c</fullName>
    <label>Project</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>EYI_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>46 Banyan Tree</fullName>
                <isActive>false</isActive>
                <label>46 Banyan Tree</label>
            </value>
            <value>
                <fullName>57 Avenue</fullName>
                <isActive>false</isActive>
                <label>57 Avenue</label>
            </value>
            <value>
                <fullName>86 Banyan Tree</fullName>
                <isActive>false</isActive>
                <label>86 Banyan Tree</label>
            </value>
            <value>
                <fullName>Avant Garde</fullName>
            </value>
            <value>
                <fullName>Balewadi</fullName>
            </value>
            <value>
                <fullName>Bougain Villa</fullName>
            </value>
            <value>
                <fullName>Casa 9</fullName>
            </value>
            <value>
                <fullName>Central Park</fullName>
                <isActive>false</isActive>
                <label>Central Park</label>
            </value>
            <value>
                <fullName>ELEVEN WEST</fullName>
            </value>
            <value>
                <fullName>EON Waterfront II</fullName>
            </value>
            <value>
                <fullName>Eon Waterfront PH I</fullName>
            </value>
            <value>
                <fullName>Forest Castle</fullName>
            </value>
            <value>
                <fullName>Futura</fullName>
            </value>
            <value>
                <fullName>Generic</fullName>
                <isActive>false</isActive>
                <label>Generic</label>
            </value>
            <value>
                <fullName>Gold Craft</fullName>
                <isActive>false</isActive>
                <label>Gold Craft</label>
            </value>
            <value>
                <fullName>Golden Bell</fullName>
            </value>
            <value>
                <fullName>New Commercial</fullName>
                <isActive>false</isActive>
                <label>New Commercial</label>
            </value>
            <value>
                <fullName>New Residential</fullName>
                <isActive>false</isActive>
                <label>New Residential</label>
            </value>
            <value>
                <fullName>Ocean Tower</fullName>
                <isActive>false</isActive>
                <label>Ocean Tower</label>
            </value>
            <value>
                <fullName>One North</fullName>
            </value>
            <value>
                <fullName>Panchshil Avenue</fullName>
                <isActive>false</isActive>
                <label>Panchshil Avenue</label>
            </value>
            <value>
                <fullName>Panchshil Towers</fullName>
            </value>
            <value>
                <fullName>Queens Court</fullName>
            </value>
            <value>
                <fullName>Satellite Towers</fullName>
            </value>
            <value>
                <fullName>SoHo</fullName>
            </value>
            <value>
                <fullName>Ssilverwoods</fullName>
            </value>
            <value>
                <fullName>The Address</fullName>
            </value>
            <value>
                <fullName>The Chambers</fullName>
            </value>
            <value>
                <fullName>The Golden Bell II</fullName>
            </value>
            <value>
                <fullName>Trump Towers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Segment__c.field-meta.xml
<CustomField>
    <fullName>EYI_Segment__c</fullName>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Project__c/EYI_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Opportunity_TAT__c.field-meta.xml
<CustomField>
    <fullName>EYI_Opportunity_TAT__c</fullName>
    <label>Opportunity TAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Project_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Code__c</fullName>
    <label>Project Code</label>
    <length>55</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Project_Property_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Property_Type__c</fullName>
    <label>Project Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
                <default>true</default>
                <label>Residential</label>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Stamp_Duty__c.field-meta.xml
<CustomField>
    <fullName>EYI_Stamp_Duty__c</fullName>
    <label>Stamp Duty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/recordTypes/Commercial.recordType-meta.xml
<RecordType>
    <fullName>Commercial</fullName>
    <active>true</active>
    <label>Commercial</label>
</RecordType>

force-app/main/default/objects/EYI_Project__c/recordTypes/Residential.recordType-meta.xml
<RecordType>
    <fullName>Residential</fullName>
    <active>true</active>
    <label>Residential</label>
</RecordType>

force-app/main/default/classes/EYI_TestDataFactory.cls
/**
* @description       : This class is used to create the test records for the testing purposes.
* @group             : EY Notification Framework
* @last modified by  : Digambar Ganage 
**/
@isTest
public with sharing class EYI_TestDataFactory {

    public static List<Account> createAccounts(String Name, Integer numberOfAccounts, Boolean isInsert) {
        List<Account> accountList = new List<Account>();
        for(Integer i=0; i<numberOfAccounts; i++) {
            Account account = new Account(
                Name = Name
            );
            accountList.add(account);
        }
        if(isInsert){
            insert accountList;
        }
        return accountList;
    }

    public static List<EYI_Project__c> createProjects(String Name, Integer numberOfProjects, Boolean isInsert, String projectType) {
        List<EYI_Project__c> projectList = new List<EYI_Project__c>();
        Map<String, Id> recordTypeMap = new Map<String, Id>();
        for (RecordType rt : [SELECT Id, SObjectType, DeveloperName FROM RecordType WHERE SObjectType = 'EYI_Project__c' AND (DeveloperName = 'Commercial' OR DeveloperName = 'Residential')]) {
            recordTypeMap.put(rt.DeveloperName, rt.Id);
        }
        String uniqueId = String.valueOf(DateTime.now().getTime()) + String.valueOf(Math.random()).substring(2,8);
        for(Integer i=0; i<numberOfProjects; i++) {
            EYI_Project__c project = new EYI_Project__c(
                Name = Name + '_' + uniqueId + '_' + i,
                EYI_Project_Code__c = 'P-00'+uniqueId+i,
                EYI_Project_Property_Type__c = 'Commercial',
                RecordTypeId = recordTypeMap.get(projectType),
				EYI_Stamp_Duty__c= 10,
                EYI_Opportunity_TAT__c = 1
            );
            projectList.add(project);
        }
        if(isInsert){
            insert projectList;
        }
        return projectList;
    }
	
    public static List<EYI_Project__c> createProjectsForLeads(String Name, Integer numberOfProjects, Boolean isInsert, String projectType) {
        List<EYI_Project__c> projectList = new List<EYI_Project__c>();
        Map<String, Id> recordTypeMap = new Map<String, Id>();
        for (RecordType rt : [SELECT Id, SObjectType, DeveloperName FROM RecordType WHERE SObjectType = 'EYI_Project__c' AND (DeveloperName = 'Commercial' OR DeveloperName = 'Residential')]) {
            recordTypeMap.put(rt.DeveloperName, rt.Id);
        }
        String uniqueId = String.valueOf(DateTime.now().getTime()) + String.valueOf(Math.random()).substring(2,8);
        for(Integer i=0; i<numberOfProjects; i++) {
            EYI_Project__c project = new EYI_Project__c(
                Name = Name,
                EYI_Project_Code__c = 'P-00'+uniqueId+i,
                EYI_Project_Property_Type__c = 'Commercial',
                RecordTypeId = recordTypeMap.get(projectType),
				EYI_Stamp_Duty__c= 10,
                EYI_Opportunity_TAT__c = 1
            );
            projectList.add(project);
        }
        if(isInsert){
            insert projectList;
        }
        return projectList;
    }
    public static List<Lead> createLeads(String LastName,String Project, Integer numberOfLeads,String MobileNo, String Source, String SubSource, Boolean isInsert) {
        String uniqueId = String.valueOf(DateTime.now().getTime()) + String.valueOf(Math.random()).substring(2,8);
        List<EYI_Project__c> projectList = createProjectsForLeads(Project, 1, true,'Commercial');        
        List<Lead> leadList = new List<Lead>();
        for(Integer i=0; i<numberOfLeads; i++) {
            Lead lead = new Lead(
                FirstName = 'Test' + i,
                LastName = LastName + i, 
                Status='',
                LeadSource = Source,
                EYI_Lead_Sub_Source__c = SubSource,
                EYI_Segment__c = 'Commercial',
                EYI_Designation__c='Test',
                Company='Panchshil',
                Description='test',
                EYI_LeadType__c = 'Retail',
                EYI_Property__c = 'Golden Bell',
                //EYI_Budget__c='3.25 Crore to 3.50 Crore',
                EYI_Client_Communication_Preference__c='SMS;WhatsApp',
                EYI_Nature_of_Lead__c='Outright',
                EYI_Project_Enquired__c=projectList[0].id,
                Email = LastName+i+'@example.com', 
                Phone = MobileNo + i,
                MobilePhone = MobileNo + i
            );
            
            leadList.add(lead);
        }
        if(isInsert){
            insert leadList;
        }
        return leadList;
    }

    public static List<Contact> createContacts(String LastName, Integer numberOfContacts, Boolean isInsert) {
        List<Account> accountList = createAccounts('Test', 1, true);
        List<Contact> contactList = new List<Contact>();
        for(Integer i=0; i<numberOfContacts;  i++  ){
            Contact contact = new Contact(
                FirstName = 'FirstName',
                LastName = LastName + i,
                Email = 'test'+i+'@test.com',
                description = 'Title',
                AccountId = accountList[0].Id
            ); 
            contactList.add(contact);
        }
        if(isInsert){
            insert contactList;
        }   
        return contactList;
    }     

    public static List<Task> createPresalesTask(String Subject, Integer numberOfTasks, Boolean isInsert) {
        List<Task> taskList = new List<Task>();
        List<Lead> leadList = createLeads('Test','Panchshil Towers',4,'983434334','Direct Client','',true);
        EYI_Lead_Enquiry__c enq = new EYI_Lead_Enquiry__c();
        enq.EYI_Parent_Record__c = leadList[0].Id;
        enq.EYI_Lead_Source__c = 'Web';
        enq.OwnerId = UserInfo.getUserId();
        enq.EYI_Phone__c = '1234567890';
        insert enq;
        System.debug('Lead Id: '+enq);
		System.debug('System.Label.EYI_Presales_Record_Type_Id ==> '+System.Label.EYI_Presales_Record_Type_Id);
        for(Integer i=0; i<numberOfTasks; i++) {
            Task task = new Task(
                Subject = 'Follow Up',
                WhatId = enq.Id,
                RecordTypeId =System.Label.EYI_Presales_Record_Type_Id,
                Priority = 'Normal',
                Status = 'Open',
                Type = 'Presales Task',
                EYI_Next_Action_Date__c =  System.today(),
                EYI_Next_Action_Time__c =  '10:30 AM - 11:30 AM',
                ReminderDateTime = System.now(),
                OwnerId = UserInfo.getUserId(),
				EYI_Next_Action_Date_Time__c = DateTime.newInstance(System.today().addDays(1), Time.newInstance(10, 30, 0, 0))
            );
			System.debug('task.recordTypeId ==> '+task.recordTypeId);
            taskList.add(task);
        }
        if(isInsert){
            insert taskList;
        }
        return taskList;
    }

    public static User createUser(String userName, String profileName) {
        // Fetch the profile by its name dynamically
        Profile userProfile = [SELECT Id FROM Profile WHERE Name = :profileName LIMIT 1];
        
        // Create a new User record with the dynamic name and profile
        User newUser = new User(
            FirstName = userName.split(' ')[0],  // Assuming the first name is the first part of the name
            LastName = userName.split(' ')[1],   // Assuming the last name is the second part of the name
            Alias = userName.substring(0, 5),    // Alias is typically a shortened version of the name
            Username = userName.replace(' ', '.') +System.now().getTime()+ '@example.com', // Make username unique with email domain
            Email = userName.replace(' ', '.') + '@example.com',   // Create an email using the name
            ProfileId = userProfile.Id,   // Set the profile ID dynamically
            TimeZoneSidKey = 'America/Los_Angeles',  // Set default timezone
            LocaleSidKey = 'en_US',      // Set default locale
            LanguageLocaleKey = 'en_US', // Set default language
            EmailEncodingKey = 'UTF-8'  // Set email encoding
        );
        
        // Insert the user record into the database
        insert newUser;
        // Return the created user
        return newUser;
    }

    public static EYI_Assignment_Group__c createassignmentGroup(String grpName, Boolean isInsert) {
        user user1 = createUser('Jay Shah', System.Label.Presales_Assignment_Group_Label);
        EYI_Assignment_Group__c grp = new EYI_Assignment_Group__c();
        grp.Name = grpName;
        grp.EYI_Presales_Head__c = user1.Id;
        grp.EYI_Team_Lead_TL__c = user1.Id;
        if(isinsert){
            insert grp;
        }
        return grp;
    }
    public static EYI_Assignment_Group_Member__c createAssignmentGroupMember(String grpName, Boolean isInsert) {
        EYI_Assignment_Group__c grp = createassignmentGroup(grpName,true);
        user user1 = createUser('Jaydip Shah', System.Label.Presales_Assignment_Group_Label);

        EYI_Assignment_Group_Member__c grpMember = new EYI_Assignment_Group_Member__c();
        grpMember.EYI_Assignment_Group__c = grp.Id;
        grpMember.EYI_Assignment_Member__c = user1.Id;
        if(isInsert){
            insert grpMember;
        }
        return grpMember;
    }

   
}