force-app/main/default/objects/EYI_Lead_Enquiry__c/EYI_Lead_Enquiry__c.object-meta.xml
<CustomObject>
    <label>Lead Enquiry</label>
    <nameField>
        <label>Lead Entries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Enquiries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/DNC__c.field-meta.xml
<CustomField>
    <fullName>DNC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DNC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Closing_Manager__c.field-meta.xml
<CustomField>
    <fullName>EYI_Closing_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Closing Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Lead_Enquiries2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_DNC__c.field-meta.xml
<CustomField>
    <fullName>EYI_DNC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EYI DNC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Inbound_L1_Escalation_Time__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inbound_L1_Escalation_Time__c</fullName>
    <description>This field is used to store the level 1 escalation time for inbound calls.</description>
    <label>Inbound L1 Escalation Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Inbound_L2_Escalation_Time__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inbound_L2_Escalation_Time__c</fullName>
    <description>This field is used to store the escalation time for level 2 for inbound calls.</description>
    <label>Inbound L2 Escalation Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Inbound_L3_Escalation_Time__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inbound_L3_Escalation_Time__c</fullName>
    <description>This field is used to store the level 3 escalation time for inbound calls.</description>
    <label>Inbound L3 Escalation Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>EYI_Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Advertisement</fullName>
                <isActive>false</isActive>
                <label>Advertisement</label>
            </value>
            <value>
                <fullName>Archive Leads</fullName>
                <isActive>false</isActive>
                <label>Archive Leads</label>
            </value>
            <value>
                <fullName>ChatBot</fullName>
            </value>
            <value>
                <fullName>Cold Calling</fullName>
                <isActive>false</isActive>
                <label>Cold Calling</label>
            </value>
            <value>
                <fullName>Core Leads</fullName>
                <isActive>false</isActive>
                <label>Core Leads</label>
            </value>
            <value>
                <fullName>CTI</fullName>
            </value>
            <value>
                <fullName>Database</fullName>
                <isActive>false</isActive>
                <label>Database</label>
            </value>
            <value>
                <fullName>Databases</fullName>
                <isActive>false</isActive>
                <label>Databases</label>
            </value>
            <value>
                <fullName>Digital Media</fullName>
                <isActive>false</isActive>
                <label>Digital Media</label>
            </value>
            <value>
                <fullName>Direct</fullName>
                <isActive>false</isActive>
                <label>Direct</label>
            </value>
            <value>
                <fullName>Direct Client</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Employee Referral</fullName>
                <isActive>false</isActive>
                <label>Employee Referral</label>
            </value>
            <value>
                <fullName>Employee Referral Scheme</fullName>
                <isActive>false</isActive>
                <label>Employee Referral Scheme</label>
            </value>
            <value>
                <fullName>Exhibition</fullName>
                <isActive>false</isActive>
                <label>Exhibition</label>
            </value>
            <value>
                <fullName>Existing Client</fullName>
            </value>
            <value>
                <fullName>External Referral</fullName>
                <isActive>false</isActive>
                <label>External Referral</label>
            </value>
            <value>
                <fullName>EYI Contact Center</fullName>
                <isActive>false</isActive>
                <label>EYI Contact Center</label>
            </value>
            <value>
                <fullName>IVR</fullName>
                <isActive>false</isActive>
                <label>IVR</label>
            </value>
            <value>
                <fullName>Lead Reference</fullName>
                <isActive>false</isActive>
                <label>Lead Reference</label>
            </value>
            <value>
                <fullName>Lost Leads</fullName>
                <isActive>false</isActive>
                <label>Lost Leads</label>
            </value>
            <value>
                <fullName>Loyalty</fullName>
                <isActive>false</isActive>
                <label>Loyalty</label>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Mobile App</fullName>
            </value>
            <value>
                <fullName>Newspaper Ad</fullName>
                <isActive>false</isActive>
                <label>Newspaper Ad</label>
            </value>
            <value>
                <fullName>OOH</fullName>
                <isActive>false</isActive>
                <label>OOH</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Outdoor Activation</fullName>
                <isActive>false</isActive>
                <label>Outdoor Activation</label>
            </value>
            <value>
                <fullName>Partner</fullName>
                <isActive>false</isActive>
                <label>Partner</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Parent_Record__c.field-meta.xml
<CustomField>
    <fullName>EYI_Parent_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Lead_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Project_Enquired__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Enquired__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Enquired</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>EYI_Project__c.EYI_Project_Property_Type__c</field>
            <operation>equals</operation>
            <valueField>$Source.EYI_Segment__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Lead Enquiries</relationshipLabel>
    <relationshipName>Lead_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Property__c.field-meta.xml
<CustomField>
    <fullName>EYI_Property__c</fullName>
    <label>Project</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>EYI_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>46 Banyan Tree</fullName>
                <isActive>false</isActive>
                <label>46 Banyan Tree</label>
            </value>
            <value>
                <fullName>57 Avenue</fullName>
                <isActive>false</isActive>
                <label>57 Avenue</label>
            </value>
            <value>
                <fullName>86 Banyan Tree</fullName>
                <isActive>false</isActive>
                <label>86 Banyan Tree</label>
            </value>
            <value>
                <fullName>Avant Garde</fullName>
            </value>
            <value>
                <fullName>Balewadi</fullName>
            </value>
            <value>
                <fullName>Bougain Villa</fullName>
            </value>
            <value>
                <fullName>Casa 9</fullName>
            </value>
            <value>
                <fullName>Central Park</fullName>
                <isActive>false</isActive>
                <label>Central Park</label>
            </value>
            <value>
                <fullName>ELEVEN WEST</fullName>
            </value>
            <value>
                <fullName>EON Waterfront II</fullName>
            </value>
            <value>
                <fullName>Eon Waterfront PH I</fullName>
            </value>
            <value>
                <fullName>Forest Castle</fullName>
            </value>
            <value>
                <fullName>Futura</fullName>
            </value>
            <value>
                <fullName>Generic</fullName>
                <isActive>false</isActive>
                <label>Generic</label>
            </value>
            <value>
                <fullName>Gold Craft</fullName>
                <isActive>false</isActive>
                <label>Gold Craft</label>
            </value>
            <value>
                <fullName>Golden Bell</fullName>
            </value>
            <value>
                <fullName>New Commercial</fullName>
                <isActive>false</isActive>
                <label>New Commercial</label>
            </value>
            <value>
                <fullName>New Residential</fullName>
                <isActive>false</isActive>
                <label>New Residential</label>
            </value>
            <value>
                <fullName>Ocean Tower</fullName>
                <isActive>false</isActive>
                <label>Ocean Tower</label>
            </value>
            <value>
                <fullName>One North</fullName>
            </value>
            <value>
                <fullName>Panchshil Avenue</fullName>
                <isActive>false</isActive>
                <label>Panchshil Avenue</label>
            </value>
            <value>
                <fullName>Panchshil Towers</fullName>
            </value>
            <value>
                <fullName>Queens Court</fullName>
            </value>
            <value>
                <fullName>Satellite Towers</fullName>
            </value>
            <value>
                <fullName>SoHo</fullName>
            </value>
            <value>
                <fullName>Ssilverwoods</fullName>
            </value>
            <value>
                <fullName>The Address</fullName>
            </value>
            <value>
                <fullName>The Chambers</fullName>
            </value>
            <value>
                <fullName>The Golden Bell II</fullName>
            </value>
            <value>
                <fullName>Trump Towers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Secondary_Owner__c.field-meta.xml
<CustomField>
    <fullName>EYI_Secondary_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Lead_Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Segment__c.field-meta.xml
<CustomField>
    <fullName>EYI_Segment__c</fullName>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry_Escalation_Settings__mdt/EYI_Lead_Enquiry_Escalation_Settings__mdt.object-meta.xml
<CustomObject>
    <description>This custom setting is used to store the Lead Enquiry escalation minutes.</description>
    <label>Escalation TAT Settings</label>
    <pluralLabel>Escalation TAT Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/EYI_Lead_Enquiry_Escalation_Settings__mdt/fields/L1_Escalation_Time__c.field-meta.xml
<CustomField>
    <fullName>L1_Escalation_Time__c</fullName>
    <label>L1 Escalation Time (Min.)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry_Escalation_Settings__mdt/fields/L2_Escalation_Time__c.field-meta.xml
<CustomField>
    <fullName>L2_Escalation_Time__c</fullName>
    <label>L2 Escalation Time (Min.)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry_Escalation_Settings__mdt/fields/L3_Escalation_Time__c.field-meta.xml
<CustomField>
    <fullName>L3_Escalation_Time__c</fullName>
    <label>L3 Escalation Time (Min.)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/EYI_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Project_Property_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Property_Type__c</fullName>
    <label>Project Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
                <default>true</default>
                <label>Residential</label>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EYI_LeadEnquiryTriggerHandler.cls
public without sharing class EYI_LeadEnquiryTriggerHandler {
    public static void updateTotalCountOnLead(List<EYI_Lead_Enquiry__c> EnquiryList){
        List<Lead> updateLeadList = new List<Lead>();
        Set<ID> leadID = new Set<Id>();
        Map<Id,Integer> leadMap = new Map<Id,Integer>();
        for(EYI_Lead_Enquiry__c enquiry: EnquiryList) {
            leadID.add(enquiry.EYI_Parent_Record__c);
            //system.debug('ldId'+enquiry.ownerid__c);
            
        }
        List<Lead> getAllLead = [Select Name,OwnerId,Id, EYI_Total_Lead_Inquiries__c from Lead where Id IN : leadID];

        for(Lead l: getAllLead){
            leadMap.put(l.Id,l.EYI_Total_Lead_Inquiries__c!=null?(Integer)l.EYI_Total_Lead_Inquiries__c:0);
            system.debug('id'+l.id);
            system.debug('leadName'+l.Name);
            system.debug('leadOwner'+l.OwnerId);
            
        }
        for(EYI_Lead_Enquiry__c enquiry: EnquiryList) {
            if(leadMap.containsKey(enquiry.EYI_Parent_Record__c)){
                leadMap.put(enquiry.EYI_Parent_Record__c, leadMap.get(enquiry.EYI_Parent_Record__c) + 1);
            }
        }
        for(Id lID: leadMap.keySet()){
            Lead leadUpdate = new Lead();
            leadUpdate.id = lID;
            leadUpdate.EYI_Total_Lead_Inquiries__c = leadMap.get(lID);
            updateLeadList.add(leadUpdate);
        }      
        if(!updateLeadList.isEmpty()){
            update updateLeadList;
        }
    }
    public static void updateProjectOnLead(List<EYI_Lead_Enquiry__c> enquiryList, Map<id,EYI_Lead_Enquiry__c> oldMap){
        List<EYI_Lead_Enquiry__c> leadList = new List<EYI_Lead_Enquiry__c>();
        List<String> projectVal = new List<String>();
        Map<String,EYI_Project__c> projectDetails = new Map<String, EYI_Project__c>();
        List<EYI_Project__c> projectList = new List<EYI_Project__c>();
        for(EYI_Lead_Enquiry__c ld: enquiryList){
           if(oldMap ==null){
            projectVal.add(ld.EYI_Property__c);
           }
            else if(oldMap != null && oldMap.get(ld.id).EYI_Property__c != ld.EYI_Property__c){
             projectVal.add(ld.EYI_Property__c);
            }
        
            
        }
        if(!projectVal.isEmpty()){
            projectList  = [SELECT Id,Name,EYI_Project_Property_Type__c FROM EYI_Project__c WHERE Name IN: projectVal];
        }
        if(!projectList.isEmpty()){
            for(EYI_Project__c p: projectList){
                projectDetails.put(p.Name, p);
            }
            for(EYI_Lead_Enquiry__c ld: enquiryList){
                if(projectDetails.containsKey(ld.EYI_Property__c)){
                ld.EYI_Project_Enquired__c = projectDetails.get(ld.EYI_Property__c).Id;
                ld.EYI_Segment__c = projectDetails.get(ld.EYI_Property__c).EYI_Project_Property_Type__c;
                
                }
    
            }
        }
        
    }
    
    //@future
    public static void shareRecordAccess(List<EYI_Lead_Enquiry__c> enquiryList, Map<id,EYI_Lead_Enquiry__c> oldMap){
        List<EYI_Lead_Enquiry__Share> shareRecords = new List<EYI_Lead_Enquiry__Share>();
        Map<Id,Id> primaryToSecondayShare = new Map<Id,Id>();
        Map<Id,Id> deleteAccess = new Map<Id,Id>();

        for(EYI_Lead_Enquiry__c enquiry: enquiryList){
            if(enquiry.EYI_Secondary_Owner__c != null && enquiry.EYI_Secondary_Owner__c != oldMap.get(enquiry.Id).EYI_Secondary_Owner__c && enquiry.OwnerId != enquiry.EYI_Secondary_Owner__c){
                primaryToSecondayShare.put(enquiry.id,enquiry.EYI_Secondary_Owner__c);
                
                

            }
            if(oldMap.get(enquiry.Id).EYI_Secondary_Owner__c != null && oldMap.get(enquiry.Id).EYI_Secondary_Owner__c != null && oldMap.get(enquiry.Id).EYI_Secondary_Owner__c != enquiry.EYI_Secondary_Owner__c){
                deleteAccess.put(enquiry.Id,oldMap.get(enquiry.Id).EYI_Secondary_Owner__c);
            }
        }
        List<EYI_Lead_Enquiry__Share> shareRecordsToDelete = new List<EYI_Lead_Enquiry__Share>();

        for(Id leadId :primaryToSecondayShare.keySet() ){
           // EYI_Lead_Enquiry__Share enquiryShare = new EYI_Lead_Enquiry__Share();
            EYI_Lead_Enquiry__Share leadShare = new EYI_Lead_Enquiry__Share();
                leadShare.ParentId = leadId;           // The Lead record to be shared
                leadShare.UserOrGroupId = primaryToSecondayShare.get(leadId);     // The User with whom the record will be shared
                leadShare.AccessLevel = 'Edit';  // Access level (e.g., 'Read' or 'Edit')
                leadShare.RowCause = 'Manual';
                shareRecords.add(leadShare);
        }
        if (!shareRecords.isEmpty()) {
            insert shareRecords;
        }
        List<EYI_Lead_Enquiry__Share> existingShareRecords = [ 
        SELECT Id, ParentId, UserOrGroupId 
        FROM EYI_Lead_Enquiry__Share 
        WHERE ParentId IN :deleteAccess.keySet() 
          AND UserOrGroupId IN :deleteAccess.values()
        ];
        for (EYI_Lead_Enquiry__Share shareRecord : existingShareRecords) {
            // Check if the sharing record matches the correct user and lead, then add it to the delete list
            if (deleteAccess.containsKey(shareRecord.ParentId) && 
            deleteAccess.get(shareRecord.ParentId) == shareRecord.UserOrGroupId) {
                shareRecordsToDelete.add(shareRecord);
            }
        }
        if (!shareRecordsToDelete.isEmpty()) {
            try {
                delete shareRecordsToDelete;
            } catch (DmlException e) {
                System.debug('Error deleting sharing records: ' + e.getMessage());
            }
        }
    }
    
    public static void shareRecordAccesstoLeasingTeam(Map<id,EYI_Lead_Enquiry__c> oldMap,Map<id,EYI_Lead_Enquiry__c> newMap) {
        Map<String,String> LeasingTeamIDVsPreviousIDMap = new Map<String,String>();
        String leasingQueueTeam = System.label.EYI_Leasing_Queue_Id;
        List<EYI_Lead_Enquiry__Share> shareEnqList = new List<EYI_Lead_Enquiry__Share>();
        System.debug('newMap.keySet()==>'+newMap.keySet());
        System.debug('oldMap==>'+oldMap);
        System.debug('newMap==>'+newMap);
        for(String leadId: newMap.keySet()){
            if(newMap.get(leadId).OwnerId == leasingQueueTeam && newMap.get(leadId).OwnerId != oldMap.get(leadId).OwnerId && oldMap.get(leadId).OwnerId != leasingQueueTeam){
                LeasingTeamIDVsPreviousIDMap.Put(leadId,oldMap.get(leadId).OwnerId);
            }
        }
        System.debug('LeasingTeamIDVsPreviousIDMap==>'+LeasingTeamIDVsPreviousIDMap);

        if(!LeasingTeamIDVsPreviousIDMap.isEmpty()){
            for(String leadId: LeasingTeamIDVsPreviousIDMap.keySet()){
                EYI_Lead_Enquiry__Share customObjectShare = new EYI_Lead_Enquiry__Share();
                customObjectShare.ParentId = leadId;
                Id userId = LeasingTeamIDVsPreviousIDMap.get(leadId);
                customObjectShare.UserOrGroupId = userId;
                customObjectShare.AccessLevel = 'Read';
                customObjectShare.RowCause = Schema.EYI_Lead_Enquiry__Share.RowCause.Manual;
                shareEnqList.add(customObjectShare);
            }
        }
        if(!shareEnqList.isEmpty()){
            insert shareEnqList;
        }
    }


    public static void shareRecordToClosingManager(Map<id,EYI_Lead_Enquiry__c> oldMap,Map<id,EYI_Lead_Enquiry__c> newMap) {
        Map<String,String> closingManagerVsRecordIdMap = new Map<String,String>();
        List<EYI_Lead_Enquiry__Share> shareEnqList = new List<EYI_Lead_Enquiry__Share>();

        for(String leadId: newMap.keySet()){
            /*if(oldMap.get(leadId).EYI_Closing_Manager__c == '' && newMap.get(leadId).EYI_Closing_Manager__c != ''){
                closingManagerVsRecordIdMap.put(leadId,newMap.get(leadId).EYI_Closing_Manager__c);
            }*/
             if(oldMap.get(leadId).EYI_Closing_Manager__c != NULL){

            }else{
                if(oldMap.get(leadId).EYI_Closing_Manager__c == '' && newMap.get(leadId).EYI_Closing_Manager__c != ''){
                    closingManagerVsRecordIdMap.put(leadId,newMap.get(leadId).EYI_Closing_Manager__c);
                }
            }
        }
        if(!closingManagerVsRecordIdMap.isEmpty()){
            for(String leadId: closingManagerVsRecordIdMap.keySet()){
                EYI_Lead_Enquiry__Share customObjectShare = new EYI_Lead_Enquiry__Share();
                customObjectShare.ParentId = leadId;
                Id userId = closingManagerVsRecordIdMap.get(leadId);
                customObjectShare.UserOrGroupId = userId;
                customObjectShare.AccessLevel = 'Read';
                customObjectShare.RowCause = Schema.EYI_Lead_Enquiry__Share.RowCause.Manual;
                shareEnqList.add(customObjectShare);
            }
        }
        if(!shareEnqList.isEmpty()){
            insert shareEnqList;
        }
    }

    public static void updateEscalationTimeOnEnquiry(List<EYI_Lead_Enquiry__c> leadList) {
        Map<String, EYI_Lead_Enquiry_Escalation_Settings__mdt> callTypeToMDTMap = EYI_CustomMetadataUtility.getEscalationTimeMatrix('Inbound');
        EYI_Lead_Enquiry_Escalation_Settings__mdt callTypeToMDT;
        Datetime inboundL1;
        Datetime inboundL2;
        Datetime InboundL3;
        if(callTypeToMDTMap.size()>0){
            callTypeToMDT = callTypeToMDTMap.get('Inbound');
            if(callTypeToMDT.L1_Escalation_Time__c != NULL){
                inboundL1 = EYI_BusinessHoursUtility.addBusinessMinutes(System.now(),(Integer)callTypeToMDT.L1_Escalation_Time__c);
            }
            if(callTypeToMDT.L2_Escalation_Time__c !=NULL){
                inboundL2 = EYI_BusinessHoursUtility.addBusinessMinutes(System.now(),(Integer)callTypeToMDT.L2_Escalation_Time__c);
            }
            if(callTypeToMDT.L3_Escalation_Time__c !=NULL){
                inboundL3 = EYI_BusinessHoursUtility.addBusinessMinutes(System.now(),(Integer)callTypeToMDT.L3_Escalation_Time__c);
            } 
        }
        for(EYI_Lead_Enquiry__c enquiry: leadList) {
            system.debug('enquiry.CreatedDate'+(System.now()));
            system.debug('enquiry.CreatedDate12'+(System.now()).time());
            system.debug('enquiry.CreatedDate'+enquiry.CreatedDate);
            Time createdTime = (System.now()).time();
            Time startTime = Time.newInstance(9, 30, 0, 0);  // 9:30 AM
            Time endTime = Time.newInstance(18, 30, 0, 0);
            if(enquiry.EYI_Lead_Source__c != null && enquiry.EYI_Lead_Source__c != '' && (createdTime >= startTime && createdTime <= endTime) ) {
                if(System.Label.EYI_Lead_Source_For_Escalation.contains(enquiry.EYI_Lead_Source__c)){
                    enquiry.EYI_Inbound_L1_Escalation_Time__c = inboundL1;
                    enquiry.EYI_Inbound_L2_Escalation_Time__c = inboundL2;
                    enquiry.EYI_Inbound_L3_Escalation_Time__c = InboundL3;
                }
            }
        }
    }
    private static Boolean isTriggerRunning = false;
     public static void updateDNCOnAllRecords(List<EYI_Lead_Enquiry__c> leadList) {
        if (isTriggerRunning) {
            return; // Exit if the trigger is already running
        }
        
        isTriggerRunning = true; // Set the flag to prevent recursion

        system.debug('check if calling');
        List<String> phoneList = new List<String>();
        Set<String> leadID = new Set<String>();
        
        for (EYI_Lead_Enquiry__c lead : leadList) {
            leadID.add(lead.id);
            if (lead.DNC__c == true && lead.EYI_DNC__c != true && lead.EYI_Lead_Status__c != 'Lost'  && (lead.EYI_Phone__c != null && lead.EYI_Phone__c != '')) {
                phoneList.add(lead.EYI_Phone__c);
            }
            if (lead.DNC__c == true && lead.EYI_DNC__c != true && lead.EYI_Lead_Status__c != 'Lost'  && (lead.EYI_Mobile__c != null && lead.EYI_Mobile__c != '')) {
                phoneList.add(lead.EYI_Mobile__c);
            }
        }

        system.debug('phoneList' + phoneList);

        if (!phoneList.isEmpty()) {
            List<EYI_Lead_Enquiry__c> leadEnquiryList = [
                SELECT DNC__c
                FROM EYI_Lead_Enquiry__c
                WHERE (EYI_Mobile__c IN :phoneList OR EYI_Phone__c IN :phoneList)
                AND DNC__c != true
                AND Id NOT IN :leadID
            ];

            system.debug('phoneList2' + leadEnquiryList);

            for (EYI_Lead_Enquiry__c leadEnquiry : leadEnquiryList) {
                if (!leadID.contains(leadEnquiry.id)) {
                    leadEnquiry.DNC__c = true;
                    leadEnquiry.EYI_DNC__c = false;
                }
            }

            system.debug('phoneList23' + leadEnquiryList);
            update leadEnquiryList;
        }

        isTriggerRunning = false; // Reset the flag after the update is completed
    }
    public static void updateParentOwnerTLLostLead(List<EYI_Lead_Enquiry__c> leadList){
        Set<Id> ownerIds = new Set<Id>();
         Set<Id> parentLeadIds = new Set<Id>();
        for (EYI_Lead_Enquiry__c lead : leadList) {
            if (lead.EYI_Lost_Lead__c == true && lead.OwnerId != null) {
                ownerIds.add(lead.OwnerId);
                if (lead.EYI_Parent_Record__c != null) {
                    parentLeadIds.add(lead.EYI_Parent_Record__c);
                }
            }
        }
        
        Map<Id, Id> ownerToManagerMap = new Map<Id, Id>();
        for (User u : [SELECT Id, ManagerId FROM User WHERE Id IN :ownerIds]) {
            ownerToManagerMap.put(u.Id, u.ManagerId);
        }
         List<EYI_Lead_Enquiry__c> leadsToUpdate = new List<EYI_Lead_Enquiry__c>();
        List<Lead> parentLeadsToUpdate = new List<Lead>();
        for (EYI_Lead_Enquiry__c leadEnquiry : leadList) {
            
            if (leadEnquiry.EYI_Lost_Lead__c == true && ownerToManagerMap.containsKey(leadEnquiry.OwnerId)) {
                Id managerId = ownerToManagerMap.get(leadEnquiry.OwnerId);
                leadEnquiry.OwnerId = managerId;
                leadEnquiry.EYI_AutomationBypassDatetime__c =  System.now();
               // if (leadEnquiry.EYI_Parent_Record__c != null ){
              //  Lead parent = new Lead();
              //  parent.Id = leadEnquiry.EYI_Parent_Record__c;
              //  parent.OwnerId = managerId;
              //  parentLeadsToUpdate.add(parent);
              //  }
            }   
            
        }
       // if (!parentLeadsToUpdate.isEmpty()) {
       //     update parentLeadsToUpdate;
       // }
        // if (!leadsToUpdate.isEmpty()) {
        // update leadsToUpdate;
        // }

    }        
    
}