force-app/main/default/objects/EYI_Demand__c/EYI_Demand__c.object-meta.xml
<CustomObject>
    <label>Demand</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Demand Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Demand__c/fields/EYI_Amount_to_be_paid__c.field-meta.xml
<CustomField>
    <fullName>EYI_Amount_to_be_paid__c</fullName>
    <label>Milestone Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EYI_Demand__c/fields/EYI_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Billing_Date__c</fullName>
    <label>Billing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Demand__c/fields/EYI_Demand_Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>EYI_Demand_Payment_Status__c</fullName>
    <label>Demand Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Demand__c/fields/EYI_Demand_Status__c.field-meta.xml
<CustomField>
    <fullName>EYI_Demand_Status__c</fullName>
    <label>Demand Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Demand Raised</fullName>
            </value>
            <value>
                <fullName>Demand Sent</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Demand Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>In progress</fullName>
                <isActive>false</isActive>
                <label>In progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Demand__c/fields/EYI_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>EYI_Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Demand__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Tower__c/EYI_Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Target__c/Monthly_Target__c.object-meta.xml
<CustomObject>
    <label>Monthly Target</label>
    <nameField>
        <label>Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Target__c/fields/EYI_Overall_Outstanding_Amount1__c.field-meta.xml
<CustomField>
    <fullName>EYI_Overall_Outstanding_Amount1__c</fullName>
    <label>Total Collectable Outstanding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Monthly_Target__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Monthly Targets</relationshipLabel>
    <relationshipName>Monthly_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EYI_TargetOutstandingCalculationBatch.cls
global with sharing class EYI_TargetOutstandingCalculationBatch implements Database.Batchable<SObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([ SELECT Id ,EYI_Project_Tower_Enquired__c FROM Opportunity WHERE StageName 
        NOT IN ('Cancelled', 'Sales Lost')]);
    }
    global void execute(Database.BatchableContext BC, List<Opportunity> scope) {
                System.debug('scope===>'+scope);

        Set<Id> oppIds = new Set<Id>();
        Map<Id, Decimal> towerToDemandSum = new Map<Id, Decimal>();
        Decimal totalDemandAmount = 0;
        List<Monthly_Target__c> targetList = new List<Monthly_Target__c>();
        for (Opportunity opp : scope) {
            oppIds.add(opp.Id);
        }
       for (AggregateResult ar : [
            SELECT EYI_Tower__c tower, SUM(EYI_Amount_to_be_paid__c) total
            FROM EYI_Demand__c
            WHERE EYI_Demand_Status__c IN ('Open', 'Demand Sent', 'Demand Raised')
                AND EYI_Demand_Payment_Status__c = 'Pending'
                AND EYI_Opportunity__c IN :oppIds
                AND EYI_Billing_Date__c = THIS_MONTH
            GROUP BY EYI_Tower__c
        ]) {
            Id towerId = (Id)ar.get('tower');
            Decimal totalAmount = (Decimal)ar.get('total');

            system.debug('ar tower =====> ' + towerId);
            system.debug('ar total =====> ' + totalAmount);

            if (totalAmount != null) {
                if (!towerToDemandSum.containsKey(towerId)) {
                    // If not present, put directly
                    towerToDemandSum.put(towerId, totalAmount);
                } else {
                    // If present, get and update (or just update)
                    Decimal existingAmount = towerToDemandSum.get(towerId); // optional use
                    towerToDemandSum.put(towerId, totalAmount); // replace or update
                }
            }
        }

                System.debug('towerToDemandSum===>'+towerToDemandSum);

        for (Monthly_Target__c target: [SELECT Id,EYI_Tower__c	 from Monthly_Target__c WHERE Createddate= THIS_MONTH]) {
                if(towerToDemandSum.containsKey(target.EYI_Tower__c)) {
                    Monthly_Target__c updateTarget = new Monthly_Target__c();
                    updateTarget.Id = target.Id;
                    updateTarget.EYI_Tower__c = target.EYI_Tower__c;
                    updateTarget.EYI_Overall_Outstanding_Amount1__c = towerToDemandSum.get(target.EYI_Tower__c);
                            System.debug('updateTarget===>'+updateTarget);

                    if(updateTarget.EYI_Overall_Outstanding_Amount1__c > 0){
                        targetList.add(updateTarget);
                    }
                } 
        }
        System.debug('targetList===>'+targetList);
        if(targetList.size()>0){
            update targetList;
        }
    }
 
    global void finish(Database.BatchableContext BC) {
        System.debug('Batch processing completed.');
    }
}