force-app/main/default/objects/EYI_Demand__c/EYI_Demand__c.object-meta.xml
<CustomObject>
    <label>Demand</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Demand Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Demand__c/fields/EYI_Actual_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Actual_Date__c</fullName>
    <label>Actual Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Demand__c/fields/EYI_Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>EYI_Payment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fiel created to update date for specific demand.</description>
    <label>Payment Schedule</label>
    <referenceTo>EYI_Payment_Schedule__c</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/EYI_Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PM-{000000}</displayFormat>
        <label>Payment Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/EYI_Actual_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Actual_Date__c</fullName>
    <description>Actual Completion Date</description>
    <label>Actual Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/EYI_UpdateDemandDateTriggerHandler.cls
public class EYI_UpdateDemandDateTriggerHandler {
    public static void handleAfterUpdate(Map<Id,EYI_Payment_Schedule__c> newMap, Map<Id, EYI_Payment_Schedule__c> oldMap){
        List<EYI_Demand__c> recordsToUpdate = new List<EYI_Demand__c>();
        Set<Id> paymentScheduleIds = new Set<Id>();
        for (Id payId : newMap.keySet()) {
            EYI_Payment_Schedule__c newPay = newMap.get(payId);
            EYI_Payment_Schedule__c oldPay = oldMap.get(payId);
            
            if (newPay.EYI_Actual_Date__c != oldPay.EYI_Actual_Date__c) {
                paymentScheduleIds.add(payId);
                system.debug(paymentScheduleIds);
            }
        }
        if (!paymentScheduleIds.isEmpty()){
            
            for(EYI_Demand__c dem : [select id,EYI_Actual_Date__c, EYI_Payment_Schedule__c from EYI_Demand__c where EYI_Payment_Schedule__c IN:paymentScheduleIds]){
                
               dem.EYI_Actual_Date__c = newMap.get(dem.EYI_Payment_Schedule__c).EYI_Actual_Date__c;
                recordsToUpdate.add(dem);
            }
            if (!recordsToUpdate.isEmpty()) {
                update recordsToUpdate;
                System.debug('Updated rec --> ' + recordsToUpdate);
            }
            
        }
        
        
    }
    
}