force-app/main/default/objects/EYI_Booking__c/EYI_Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>BF-{0000000}</displayFormat>
        <label>Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Booking__c/fields/EYI_REC_Account__c.field-meta.xml
<CustomField>
    <fullName>EYI_REC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is lookup field for REC account object.</description>
    <label>REC Account</label>
    <referenceTo>EYI_REC__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/EYI_Customer_Information_Form__c.object-meta.xml
<CustomObject>
    <label>CIF Records</label>
    <nameField>
        <displayFormat>CIF-{0000}</displayFormat>
        <label>Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CIF Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_First_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_REC_Account__c.field-meta.xml
<CustomField>
    <fullName>EYI_REC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>REC Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>EYI_REC__c.EYI_REC_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EYI_REC__c</referenceTo>
    <relationshipLabel>CIF Records</relationshipLabel>
    <relationshipName>CIF_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/EYI_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Project_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Code__c</fullName>
    <label>Project Code</label>
    <length>55</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Stamp_Duty__c.field-meta.xml
<CustomField>
    <fullName>EYI_Stamp_Duty__c</fullName>
    <label>Stamp Duty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/EYI_Project_REC_Mapping__c/EYI_Project_REC_Mapping__c.object-meta.xml
<CustomObject>
    <label>Project REC Mapping</label>
    <nameField>
        <displayFormat>PRM-{00000}</displayFormat>
        <label>Project REC Mapping Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project REC Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Project_REC_Mapping__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Project REC Mappings</relationshipLabel>
    <relationshipName>Project_REC_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EYI_Project_REC_Mapping__c/fields/EYI_REC_Account__c.field-meta.xml
<CustomField>
    <fullName>EYI_REC_Account__c</fullName>
    <label>REC Account</label>
    <referenceTo>EYI_REC__c</referenceTo>
    <relationshipLabel>Project REC Mappings</relationshipLabel>
    <relationshipName>Project_REC_Mappings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EYI_REC__c/EYI_REC__c.object-meta.xml
<CustomObject>
    <label>REC Account</label>
    <nameField>
        <label>REC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REC Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_REC__c/fields/EYI_Company_PAN_No__c.field-meta.xml
<CustomField>
    <fullName>EYI_Company_PAN_No__c</fullName>
    <label>Company TAN No.</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_REC__c/fields/EYI_Email__c.field-meta.xml
<CustomField>
    <fullName>EYI_Email__c</fullName>
    <label>Primary Email Id</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/EYI_REC__c/fields/EYI_First_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_First_Name__c</fullName>
    <label>First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_REC__c/fields/EYI_Mobile__c.field-meta.xml
<CustomField>
    <fullName>EYI_Mobile__c</fullName>
    <label>REC Primary Mobile Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/EYI_REC__c/fields/EYI_PAN_No__c.field-meta.xml
<CustomField>
    <fullName>EYI_PAN_No__c</fullName>
    <label>PAN No</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_REC__c/fields/EYI_Type_Of_RERA_Registration__c.field-meta.xml
<CustomField>
    <fullName>EYI_Type_Of_RERA_Registration__c</fullName>
    <label>Type Of RERA Registration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Company/ Firm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Target_Management__c/EYI_Target_Management__c.object-meta.xml
<CustomObject>
    <label>Target Management</label>
    <nameField>
        <displayFormat>TM-{000}</displayFormat>
        <label>Target Management Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Managements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Target_Management__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Target Managements</relationshipLabel>
    <relationshipName>Target_Managements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Target_Management__c/fields/EYI_Target_End_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Target_End_Date__c</fullName>
    <label>Target End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Target_Management__c/fields/EYI_Target_KPI__c.field-meta.xml
<CustomField>
    <fullName>EYI_Target_KPI__c</fullName>
    <label>Target KPI</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>EYI_Target_Module__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Follow-up by CTI</fullName>
                <label>Follow-up by CTI (%)</label>
            </value>
            <value>
                <fullName>Walk-in to Booking Conversion</fullName>
                <label>Walk-in to Booking Conversion (%)</label>
            </value>
            <value>
                <fullName>Number of EOIs</fullName>
            </value>
            <value>
                <fullName>EOI Conversions</fullName>
                <label>EOI Conversions (%)</label>
            </value>
            <value>
                <fullName>Revenue Target</fullName>
            </value>
            <value>
                <fullName>Meeting Target</fullName>
            </value>
            <value>
                <fullName>New CP Empanelment</fullName>
            </value>
            <value>
                <fullName>Walkin Achieved</fullName>
            </value>
            <value>
                <fullName>VC/VP Target</fullName>
            </value>
            <value>
                <fullName>REC Calls by SM</fullName>
            </value>
            <value>
                <fullName>Visit Confirmed</fullName>
            </value>
            <value>
                <fullName>Visit Done</fullName>
            </value>
            <value>
                <fullName>Average Talk Time</fullName>
                <label>Total Talk Time (In Minutes)</label>
            </value>
            <value>
                <fullName>Lead to Walk-In Conversion ratio</fullName>
            </value>
            <value>
                <fullName>Total Outbound Calls to be Done</fullName>
            </value>
            <value>
                <fullName>Total Inbound Calls Completed</fullName>
            </value>
            <value>
                <fullName>Re-visit (Unique revisits / Total revisits)</fullName>
                <label>Re-visit (Unique revisits / Total revisits) (%)</label>
            </value>
            <value>
                <fullName>Average Follow-Ups</fullName>
                <isActive>false</isActive>
                <label>Average Follow-Ups (Per Day)</label>
            </value>
            <value>
                <fullName>Average TAT from Walk-in to Booking</fullName>
                <isActive>false</isActive>
                <label>Average TAT from Walk-in to Booking</label>
            </value>
            <value>
                <fullName>Booking from Cold/Lost leads</fullName>
                <isActive>false</isActive>
                <label>Booking from Cold/Lost leads (%)</label>
            </value>
            <value>
                <fullName>Cancellation Count</fullName>
                <isActive>false</isActive>
                <label>Cancellation Count</label>
            </value>
            <value>
                <fullName>Follow-ups missed</fullName>
                <isActive>false</isActive>
                <label>Follow-ups missed (%)</label>
            </value>
            <value>
                <fullName>L1 TAT Approval</fullName>
                <isActive>false</isActive>
                <label>L1 TAT Approval  (In Minutes)</label>
            </value>
            <value>
                <fullName>L2 TAT Approval</fullName>
                <isActive>false</isActive>
                <label>L2 TAT Approval (In Minutes)</label>
            </value>
            <value>
                <fullName>L3 TAT Approval</fullName>
                <isActive>false</isActive>
                <label>L3 TAT Approval (In Minutes)</label>
            </value>
            <value>
                <fullName>Number of Cases Where the Cooling Period is Extended</fullName>
                <isActive>false</isActive>
                <label>Number of Cases Where the Cooling Period is Extended (%)</label>
            </value>
            <value>
                <fullName>Number of references generated by the Sales Manager</fullName>
                <isActive>false</isActive>
                <label>Number of references generated by the Sales Manager (%)</label>
            </value>
            <value>
                <fullName>Revenue (Project-Wise Revenue Target in Crore)</fullName>
                <isActive>false</isActive>
                <label>Revenue (Project-Wise Revenue Target in Crore)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Target_Management__c/fields/EYI_Target_Module__c.field-meta.xml
<CustomField>
    <fullName>EYI_Target_Module__c</fullName>
    <label>Target Module</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Presales</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Sourcing</fullName>
            </value>
            <value>
                <fullName>Revenue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Target_Management__c/fields/EYI_Target_Month_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Target_Month_Date__c</fullName>
    <label>Target Month Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Target_Management__c/fields/EYI_Target_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Target_Start_Date__c</fullName>
    <label>Target Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_VP_VC__c/EYI_VP_VC__c.object-meta.xml
<CustomObject>
    <label>VP/VC</label>
    <nameField>
        <displayFormat>VP/VC - {00000}</displayFormat>
        <label>VP/VC Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VP/VC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_VP_VC__c/fields/EYI_Email__c.field-meta.xml
<CustomField>
    <fullName>EYI_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/EYI_VP_VC__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>VP/VC</relationshipLabel>
    <relationshipName>VP_VC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_VP_VC__c/fields/EYI_Project_REC_Mapping__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_REC_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project REC SM Name</label>
    <referenceTo>EYI_Project_REC_Mapping__c</referenceTo>
    <relationshipLabel>VP/VC</relationshipLabel>
    <relationshipName>VP_VC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EYI_SourcingTargetsBatchTest.cls
@IsTest
public with sharing class EYI_SourcingTargetsBatchTest {
   

    @testSetup
    static void setupData() {
       
        Profile salesProfile = [SELECT Id FROM Profile WHERE Name = 'Sales' LIMIT 1];

        // Step 2: Create the test user with current user as manager
        User u = new User(
            FirstName = 'Test',
            LastName = 'SalesUser',
            Email = 'salesuser@example.com',
            Username = 'salesuser' + DateTime.now().getTime() + '@example.com',
            Alias = 'tsales',
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            ProfileId = salesProfile.Id,
            ManagerId = UserInfo.getUserId()
        );

        insert u;
        // Calculate fiscal year boundaries based on April start
        Integer fiscalStartMonth = 4; // April
        Date today = Date.today();
        Integer fiscalYear;
        
        if (today.month() >= fiscalStartMonth) {
            fiscalYear = today.year() + 1;
        } else {
            fiscalYear = today.year();
        }
        
        Integer fiscalStartYear = fiscalYear - 1;
        Date fiscalStart = Date.newInstance(fiscalStartYear, fiscalStartMonth, 1);
        Date fiscalEnd = fiscalStart.addYears(1).addDays(-1);
        
        // Reference an existing project and owner
        //EYI_Project__c project = [SELECT Id FROM EYI_Project__c LIMIT 1];
        // Create Project
        EYI_Project__c project2 = new EYI_Project__c(
            Name = 'Test Project2',
            EYI_Project_Code__c = 'P123',
            EYI_Stamp_Duty__c = 123
        );
        insert project2;
		Id ownerId = UserInfo.getUserId();

		// Create target records for each KPI type the batch uses
		List<EYI_Target_Management__c> sourcingTargets = new List<EYI_Target_Management__c>();

		sourcingTargets.add(new EYI_Target_Management__c(
          //  Name = 'Meeting Target',
            OwnerId = ownerId,
            EYI_Project__c = project2.Id,
            EYI_Target_Module__c = 'Sourcing',
            EYI_Target_KPI__c = 'Meeting Target',
            EYI_Target_Start_Date__c = fiscalStart,
            EYI_Target_End_Date__c = fiscalEnd,
            EYI_Target_Month_Date__c = Date.today()
        ));

            sourcingTargets.add(new EYI_Target_Management__c(
               // Name = 'New CP Empanelment',
                OwnerId = ownerId,
                EYI_Project__c = project2.Id,
                EYI_Target_Module__c = 'Sourcing',
                EYI_Target_KPI__c = 'New CP Empanelment',
                EYI_Target_Start_Date__c = fiscalStart,
                EYI_Target_End_Date__c = fiscalEnd,
                EYI_Target_Month_Date__c = Date.today()
            ));
            
            sourcingTargets.add(new EYI_Target_Management__c(
               // Name = 'Walkin Achieved',
                OwnerId = ownerId,
                EYI_Project__c = project2.Id,
                EYI_Target_Module__c = 'Sourcing',
                EYI_Target_KPI__c = 'Walkin Achieved',
                EYI_Target_Start_Date__c = fiscalStart,
                EYI_Target_End_Date__c = fiscalEnd,
                EYI_Target_Month_Date__c = Date.today()
            ));
            
            sourcingTargets.add(new EYI_Target_Management__c(
             //   Name = 'VC/VP Target',
                OwnerId = ownerId,
                EYI_Project__c = project2.Id,
                EYI_Target_Module__c = 'Sourcing',
                EYI_Target_KPI__c = 'VC/VP Target',
                EYI_Target_Start_Date__c = fiscalStart,
                EYI_Target_End_Date__c = fiscalEnd,
                EYI_Target_Month_Date__c = Date.today()
            ));
            
            insert sourcingTargets;

        // Create REC Account
        EYI_REC__c rec = new EYI_REC__c(
            Name = 'Test REC',
            EYI_Mobile__c = '9999999999',
            EYI_Email__c = 'test@email.com',
            EYI_Last_Name__c = 'Last',
            EYI_First_Name__c = 'First',
            OwnerId = UserInfo.getUserId(),
            EYI_Type_Of_RERA_Registration__c = 'Company/ Firm',
            EYI_PAN_No__c = 'ABCDE1234F',
            EYI_Company_PAN_No__c = 'ABCD12345E'
        );
        insert rec;

        

        // Project REC Mapping
        EYI_Project_REC_Mapping__c mapping = new EYI_Project_REC_Mapping__c(
            EYI_Project__c = project2.Id,
            EYI_REC_Account__c = rec.Id,
            EYI_Sourcing_Manager__c = UserInfo.getUserId()
        );
        insert mapping;

        Opportunity testOpportunity = new Opportunity();
            testOpportunity.Name = 'Test Opportunity';
            testOpportunity.StageName = 'Prospecting';
            testOpportunity.EYI_Project_Enquired__c = project2.Id;
            testOpportunity.EYI_Sourcing_Manager__c = UserInfo.getUserId();
            testOpportunity.EYI_REC__c = rec.Id;
            testOpportunity.CloseDate = Date.today().addDays(30);
        insert testOpportunity;
        
        Quote q = new Quote(
            Name='Test Quote', OpportunityId=testOpportunity.Id,
            EYI_Agreement_Value__c=500000, Stamp_Duty__c=10000
        );
        insert q;

        testOpportunity.EYI_Ownership_Status__c='Accepted';
        testOpportunity.SyncedQuoteId = q.Id;
        testOpportunity.EYI_AutomationBypassDatetime__c = System.Now();
        update testOpportunity;
        // Booking
        EYI_Booking__c booking = new EYI_Booking__c(
            EYI_Project_Name__c = project2.Id,
            EYI_Opportunity_Name__c = testOpportunity.Id,
            EYI_Sourcing_manager__c = UserInfo.getUserId(),
            EYI_Booking_Date__c = System.today(),
            EYI_Actual_Booking_Date__c = System.today(),
            EYI_REC_Account__c = rec.Id
        );
        insert booking;

        
        Opportunity testOpportunity2 = new Opportunity();
            testOpportunity2.Name = 'Test Opportunity';
            testOpportunity2.StageName = 'Prospecting';
            testOpportunity2.EYI_Project_Enquired__c = project2.Id;
            testOpportunity2.EYI_Sourcing_Manager__c = UserInfo.getUserId();
            testOpportunity2.EYI_REC__c = rec.Id;
            testOpportunity2.EYI_Primary_Closing_Manager__c = UserInfo.getUserId();
            testOpportunity2.CloseDate = Date.today().addDays(30);
        insert testOpportunity2;
        
        Quote q2 = new Quote(
            Name='Test Quote', OpportunityId=testOpportunity2.Id,
            EYI_Agreement_Value__c=500000, Stamp_Duty__c=10000
        );
        insert q2;
        testOpportunity2.EYI_Ownership_Status__c='Accepted';
        testOpportunity2.SyncedQuoteId = q2.Id;
        testOpportunity2.EYI_AutomationBypassDatetime__c = System.Now();
        update testOpportunity2;
        // Booking
        EYI_Booking__c booking2 = new EYI_Booking__c(
            EYI_Project_Name__c = project2.Id,
            EYI_Opportunity_Name__c = testOpportunity2.Id,
            EYI_Sourcing_manager__c = UserInfo.getUserId(),
            EYI_Booking_Date__c = System.today(),
            EYI_Actual_Booking_Date__c = System.today(),
            EYI_REC_Account__c = rec.Id
        );
        insert booking2;
          Opportunity testOpportunity3 = new Opportunity();
            testOpportunity3.Name = 'Test Opportunity';
            testOpportunity3.StageName = 'Prospecting';
            testOpportunity3.EYI_Project_Enquired__c = project2.Id;
            testOpportunity3.EYI_Sourcing_Manager__c = UserInfo.getUserId();
            testOpportunity3.EYI_REC__c = rec.Id;
            testOpportunity3.EYI_Primary_Closing_Manager__c = u.id;
            testOpportunity3.CloseDate = Date.today().addDays(30);
        insert testOpportunity3;
        
        Quote q3 = new Quote(
            Name='Test Quote', OpportunityId=testOpportunity3.Id,
            EYI_Agreement_Value__c=500000, Stamp_Duty__c=10000
        );
        insert q3;
        testOpportunity3.EYI_Ownership_Status__c='Accepted';
        testOpportunity3.SyncedQuoteId = q3.Id;
        testOpportunity3.EYI_AutomationBypassDatetime__c = System.Now();
        update testOpportunity2;
        // Booking
        EYI_Booking__c booking3 = new EYI_Booking__c(
            EYI_Project_Name__c = project2.Id,
            EYI_Opportunity_Name__c = testOpportunity3.Id,
            EYI_Sourcing_manager__c = UserInfo.getUserId(),
            EYI_Booking_Date__c = System.today(),
            EYI_Actual_Booking_Date__c = System.today(),
            EYI_REC_Account__c = rec.Id
        );
        insert booking3;
        // CIF
        
        EYI_Customer_Information_Form__c cif = new EYI_Customer_Information_Form__c(
            EYI_First_Name__c = 'John',
            EYI_Last_Name__c = 'Doe',
            EYI_Email_Id__c = 'john.doe@example.com',
            EYI_Mobile_number__c = '9876543210',
            EYI_Project_Enquired__c = project2.Id,
			EYI_Customer_Address_Type__c = 'Mumbai',
			EYI_State__c = 'Maharashtra',
            EYI_REC_Account__c = rec.Id,
            EYI_Sourcing_Manager__c = UserInfo.getUserId()
        );
        insert cif;

        // Task
        Task task = new Task(
            Subject = 'Test Task',
            Status = 'Completed',
            OwnerId = UserInfo.getUserId(),
            WhatId = rec.Id,
            EYI_Next_Action_Date_Time__c = System.now().addDays(1) 
        );
        insert task;

        // VPVC
        EYI_VP_VC__c vpvc = new EYI_VP_VC__c(
            EYI_Client_Name__c = 'Client X',
            EYI_Company_Name__c = 'Company Y',
            EYI_Project__c = project2.Id,
            EYI_REC_Account__c = rec.Id,
            EYI_Visit_Proposed_Date__c = Date.today(),
            EYI_Visit_Confirmed_Date__c = Date.today(),
            OwnerId = UserInfo.getUserId(),
            EYI_Status__c = 'Visit Proposed'
        );
        insert vpvc;

        

    }

    @IsTest
    static void methodName(){
        
        Test.startTest();
        AggregateResult[] taskResults = [
                SELECT OwnerId, COUNT(Id) taskCount
                FROM Task
                WHERE EYI_REC_Account__c != null
                AND Createddate = THIS_MONTH
                GROUP BY OwnerId
            ];
            System.debug('taskResults====>'+taskResults);
            database.executebatch(new EYI_SourcingTargetsAchievementBatch(),10);
        Test.stopTest();
        
    }
}