force-app/main/default/objects/EYI_Booking__c/EYI_Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>BF-{0000000}</displayFormat>
        <label>Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Booking__c/fields/EYI_AutomationBypassDatetime__c.field-meta.xml
<CustomField>
    <fullName>EYI_AutomationBypassDatetime__c</fullName>
    <label>AutomationBypassDatetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EYI_Booking__c/fields/EYI_Project_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Booking__c/fields/EYI_REC_Account__c.field-meta.xml
<CustomField>
    <fullName>EYI_REC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is lookup field for REC account object.</description>
    <label>REC Account</label>
    <referenceTo>EYI_REC__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Booking__c/fields/EYI_REC_Mapping__c.field-meta.xml
<CustomField>
    <fullName>EYI_REC_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is lookup field for Project REC Mapping Object.</description>
    <label>REC Mapping</label>
    <referenceTo>EYI_Project_REC_Mapping__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/EYI_Customer_Information_Form__c.object-meta.xml
<CustomObject>
    <label>CIF Records</label>
    <nameField>
        <displayFormat>CIF-{0000}</displayFormat>
        <label>Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CIF Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Project_Enquired__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Enquired__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Enquired</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipName>CIF</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_REC_Account__c.field-meta.xml
<CustomField>
    <fullName>EYI_REC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>REC Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>EYI_REC__c.EYI_REC_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EYI_REC__c</referenceTo>
    <relationshipLabel>CIF Records</relationshipLabel>
    <relationshipName>CIF_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Joint_Business_Plan__c/EYI_Joint_Business_Plan__c.object-meta.xml
<CustomObject>
    <label>Joint Business Plan</label>
    <nameField>
        <displayFormat>JBP-{0000}</displayFormat>
        <label>Joint Business Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Joint Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Joint_Business_Plan__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Joint Business Plans</relationshipLabel>
    <relationshipName>Joint_Business_Plans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Joint_Business_Plan__c/fields/EYI_Project_REC_Mapping__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_REC_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project REC Mapping</label>
    <referenceTo>EYI_Project_REC_Mapping__c</referenceTo>
    <relationshipLabel>Joint Business Plans</relationshipLabel>
    <relationshipName>Joint_Business_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Joint_Business_Plan__c/fields/REC_Account__c.field-meta.xml
<CustomField>
    <fullName>REC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>REC Account</label>
    <referenceTo>EYI_REC__c</referenceTo>
    <relationshipLabel>Joint Business Plans</relationshipLabel>
    <relationshipName>Joint_Business_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/EYI_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Project_REC_Mapping__c/EYI_Project_REC_Mapping__c.object-meta.xml
<CustomObject>
    <label>Project REC Mapping</label>
    <nameField>
        <displayFormat>PRM-{00000}</displayFormat>
        <label>Project REC Mapping Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project REC Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Project_REC_Mapping__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Project REC Mappings</relationshipLabel>
    <relationshipName>Project_REC_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EYI_Project_REC_Mapping__c/fields/EYI_REC_Account__c.field-meta.xml
<CustomField>
    <fullName>EYI_REC_Account__c</fullName>
    <label>REC Account</label>
    <referenceTo>EYI_REC__c</referenceTo>
    <relationshipLabel>Project REC Mappings</relationshipLabel>
    <relationshipName>Project_REC_Mappings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EYI_Project_REC_Mapping__c/fields/EYI_REC_Classification_Current__c.field-meta.xml
<CustomField>
    <fullName>EYI_REC_Classification_Current__c</fullName>
    <label>REC Classification Current</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>P1</fullName>
            </value>
            <value>
                <fullName>P2</fullName>
            </value>
            <value>
                <fullName>P3</fullName>
            </value>
            <value>
                <fullName>P4</fullName>
                <default>true</default>
                <label>P4</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Project_REC_Mapping__c/fields/EYI_REC_Classification_Lifetime__c.field-meta.xml
<CustomField>
    <fullName>EYI_REC_Classification_Lifetime__c</fullName>
    <label>REC Classification Lifetime</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>P1</fullName>
            </value>
            <value>
                <fullName>P2</fullName>
            </value>
            <value>
                <fullName>P3</fullName>
            </value>
            <value>
                <fullName>P4</fullName>
                <default>true</default>
                <label>P4</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_REC__c/EYI_REC__c.object-meta.xml
<CustomObject>
    <label>REC Account</label>
    <nameField>
        <label>REC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REC Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_REC__c/fields/EYI_REC_Current_Status__c.field-meta.xml
<CustomField>
    <fullName>EYI_REC_Current_Status__c</fullName>
    <label>REC Current Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CAT A</fullName>
            </value>
            <value>
                <fullName>CAT B</fullName>
            </value>
            <value>
                <fullName>CAT C</fullName>
            </value>
            <value>
                <fullName>CAT D</fullName>
                <default>true</default>
                <label>CAT D</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_REC__c/fields/EYI_REC_Overall_Performance__c.field-meta.xml
<CustomField>
    <fullName>EYI_REC_Overall_Performance__c</fullName>
    <label>REC Overall Performance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CAT A</fullName>
            </value>
            <value>
                <fullName>CAT B</fullName>
            </value>
            <value>
                <fullName>CAT C</fullName>
            </value>
            <value>
                <fullName>CAT D</fullName>
                <default>true</default>
                <label>CAT D</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_VP_VC__c/EYI_VP_VC__c.object-meta.xml
<CustomObject>
    <label>VP/VC</label>
    <nameField>
        <displayFormat>VP/VC - {00000}</displayFormat>
        <label>VP/VC Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VP/VC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_VP_VC__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>VP/VC</relationshipLabel>
    <relationshipName>VP_VC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_VP_VC__c/fields/EYI_Project_REC_Mapping__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_REC_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project REC SM Name</label>
    <referenceTo>EYI_Project_REC_Mapping__c</referenceTo>
    <relationshipLabel>VP/VC</relationshipLabel>
    <relationshipName>VP_VC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_VP_VC__c/fields/EYI_REC_Account__c.field-meta.xml
<CustomField>
    <fullName>EYI_REC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>REC Account</label>
    <referenceTo>EYI_REC__c</referenceTo>
    <relationshipLabel>VP/VCs</relationshipLabel>
    <relationshipName>Sitevisits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EYI_RECCategoryService.cls
// public class EYI_RECCategoryService {
//     // Method to update the REC Category Lifetime
//     public static void updateRecCategoryLifetime(Set<ID> recIds) {
//         List<EYI_REC__c> recsToUpdate = new List<EYI_REC__c>();
//         // Query to retrieve all RECs (Accounts) with related Bookings, Walkins, and Activities
//         List<EYI_REC__c> recs = [SELECT Id,EYI_REC_Overall_Performance__c
//                                 , (SELECT Id FROM tasks)
//                                 , (SELECT Id FROM Bookings__r)
//                                 , (SELECT Id FROM Sitevisits__r) //vp/vc
//                                 , (SELECT Id FROM CIF_Records__r), // CIF Record
//                                 (SELECT Id FROM Joint_Business_Plans__r),
//                                 (SELECT Id, Subject, ActivityDate FROM ActivityHistories)
//                                 FROM EYI_REC__c WHERE Id IN: recIds];
//         for(EYI_REC__c rec : recs) {
//             String overallPerformance = 'CAT D';
//             if (rec.ActivityHistories.size() > 0 || rec.Joint_Business_Plans__r.size() > 0) { 
//                 overallPerformance = 'CAT C';
//             } else if (rec.Sitevisits__r.size() > 0 || rec.CIF_Records__r.size() > 0) {
//                 overallPerformance = 'CAT B';
//             } else if (rec.Bookings__r.size() > 0) {
//                 overallPerformance = 'CAT A';
//             }
//             rec.EYI_REC_Overall_Performance__c = overallPerformance;  // Update the lifetime category
//             //rec.REC_Classification_Legacy__c = classificationCurrent;
//             System.debug('REC===>'+rec);
//             recsToUpdate.add(rec);
//         }
//         if (!recsToUpdate.isEmpty()) {
//             update recsToUpdate;  // Save updates to the database
//         }
//     }
    
//     // Method to update the REC Category Current (based on last 180 days)
//     public static void updateRecCategoryCurrent(Set<ID> recIds) {
//         List<EYI_REC__c> recsToUpdate = new List<EYI_REC__c>();
//         Integer lastNDays = Integer.valueOf(System.Label.EYI_REC_Performance_Days);

//         // Query to retrieve RECs that had any activity in the last n days
//         String query = 'SELECT Id, EYI_REC_Current_Status__c, ' +
//                '(SELECT Id FROM Bookings__r WHERE CreatedDate >= LAST_N_DAYS:' + lastNDays + '), ' +
//                '(SELECT Id FROM Sitevisits__r WHERE CreatedDate >= LAST_N_DAYS:' + lastNDays + '), ' +
//                '(SELECT Id FROM Joint_Business_Plans__r WHERE CreatedDate >= LAST_N_DAYS:' + lastNDays + '), ' +
//                '(SELECT Id, Subject, ActivityDate FROM ActivityHistories WHERE CreatedDate >= LAST_N_DAYS:' + lastNDays + ') ' +
//                'FROM EYI_REC__c WHERE Id IN :recIds';

//         // Execute the dynamic SOQL query
//         List<EYI_REC__c> recs = Database.query(query);
//         System.debug('recs :: ' + recs);
        
//         for(EYI_REC__c rec : recs) {
//             String categoryCurrent = 'CAT D';
//             if (rec.ActivityHistories.size() > 0 || rec.Joint_Business_Plans__r.size() > 0) { 
//                 categoryCurrent = 'CAT C';
//             } else if (rec.Sitevisits__r.size() > 0) {
//                 categoryCurrent = 'CAT B';
//             } else if (rec.Bookings__r.size() > 0) {
//                 categoryCurrent = 'CAT A';
//             }
//             rec.EYI_REC_Current_Status__c = categoryCurrent;  
//             recsToUpdate.add(rec);
//         }
        
//         if (!recsToUpdate.isEmpty()) {
//             update recsToUpdate;  // Save updates to the database
//         }
//     }
// }
public class EYI_RECCategoryService {
    public static void updateRecCategories(Set<Id> recIds) {
        // Map to store overall performance
        Map<Id, EYI_REC__c> overallPerformanceMap = new Map<Id, EYI_REC__c>();
        
        // Query to retrieve overall performance
        List<EYI_REC__c> overallRecs = [SELECT Id, EYI_REC_Overall_Performance__c,
                                         (SELECT Id FROM tasks),
                                         (SELECT Id FROM Bookings__r),
                                         (SELECT Id FROM Sitevisits__r),
                                         (SELECT Id FROM CIF_Records__r),
                                         (SELECT Id FROM Joint_Business_Plans__r)
                                         FROM EYI_REC__c WHERE Id IN :recIds];
        
        for (EYI_REC__c rec : overallRecs) {
            String overallPerformance = 'CAT D';
            if (rec.tasks.size() > 0 || rec.Joint_Business_Plans__r.size() > 0) {
                overallPerformance = 'CAT C';
            } else if (rec.Sitevisits__r.size() > 0 || rec.CIF_Records__r.size() > 0) {
                overallPerformance = 'CAT B';
            } else if (rec.Bookings__r.size() > 0) {
                overallPerformance = 'CAT A';
            }
            rec.EYI_REC_Overall_Performance__c = overallPerformance;
            overallPerformanceMap.put(rec.Id, rec);
        }
        System.debug('overallPerformance ==> ' + overallPerformanceMap.keySet());
        System.debug('overallPerformance ==> ' + overallPerformanceMap.values());

        // Map to store current performance based on last N days
        Map<Id, EYI_REC__c> currentPerformanceMap = new Map<Id, EYI_REC__c>();
        Integer lastNDays = Integer.valueOf(System.Label.EYI_REC_Performance_Days);

        // Construct the dynamic SOQL query for current performance based on last N days
        String query = 'SELECT Id, EYI_REC_Current_Status__c, ' +
                       '(SELECT Id FROM Bookings__r WHERE CreatedDate >= LAST_N_DAYS:' + lastNDays + '), ' +
                       '(SELECT Id FROM CIF_Records__r WHERE CreatedDate >= LAST_N_DAYS:' + lastNDays + '), ' +
                       '(SELECT Id FROM Sitevisits__r WHERE CreatedDate >= LAST_N_DAYS:' + lastNDays + '), ' +
                       '(SELECT Id FROM Joint_Business_Plans__r WHERE CreatedDate >= LAST_N_DAYS:' + lastNDays + '), ' +
                       '(SELECT Id FROM tasks WHERE CreatedDate >= LAST_N_DAYS:' + lastNDays + ') ' +
                       'FROM EYI_REC__c WHERE Id IN :recIds';

        // Execute the dynamic SOQL query
        List<EYI_REC__c> currentRecs = Database.query(query);
        System.debug('recs :: ' + currentRecs);

        for (EYI_REC__c rec : currentRecs) {
            String categoryCurrent = 'CAT D';
            if (rec.tasks.size() > 0 || rec.Joint_Business_Plans__r.size() > 0) {
                categoryCurrent = 'CAT C';
            } else if (rec.Sitevisits__r.size() > 0 || rec.CIF_Records__r.size() > 0) {
                categoryCurrent = 'CAT B';
            } else if (rec.Bookings__r.size() > 0) {
                categoryCurrent = 'CAT A';
            }
            rec.EYI_REC_Current_Status__c = categoryCurrent;
            currentPerformanceMap.put(rec.Id, rec);
        }
        System.debug('currentPerformanceMap ==> ' + currentPerformanceMap.keySet());
        System.debug('currentPerformanceMap ==> ' + currentPerformanceMap.values());

        // Map to store combined results
        Map<Id, EYI_REC__c> combinedMap = new Map<Id, EYI_REC__c>();

        // Combine results from both maps
        for (Id recId : recIds) {
            EYI_REC__c overallRec = overallPerformanceMap.get(recId);
            EYI_REC__c currentRec = currentPerformanceMap.get(recId);
            EYI_REC__c combinedRec = new EYI_REC__c();
            combinedRec.Id = recId;
            combinedRec.EYI_AutomationBypassDatetime__c	= System.now();
            if (overallRec != null) {
                combinedRec.EYI_REC_Overall_Performance__c = overallRec.EYI_REC_Overall_Performance__c;
            }
            if (currentRec != null) {
                combinedRec.EYI_REC_Current_Status__c = currentRec.EYI_REC_Current_Status__c;
            }
            combinedMap.put(recId, combinedRec);
        }
        
        System.debug('combinedMap ==> ' + combinedMap.keySet());
        System.debug('combinedMap ==> ' + combinedMap.values());
        // Perform a single update DML statement
        if (!combinedMap.isEmpty()) {
            update combinedMap.values();
        }
    }


    public static void updateRecProjectCategories(Set<Id> recIds) {
        // Add a specific ID to the recIds set
        // Map to store overall performance for EYI_Project_REC_Mapping__c
        Map<Id, EYI_Project_REC_Mapping__c> overallPerformanceMap = new Map<Id, EYI_Project_REC_Mapping__c>();

        // Query to retrieve overall performance for EYI_Project_REC_Mapping__c
        List<EYI_Project_REC_Mapping__c> overallMappings = [SELECT Id, EYI_Project__c
                                                            FROM EYI_Project_REC_Mapping__c WHERE EYI_REC_Account__c IN :recIds];

        // Iterate above and get projectIds
        Set<Id> projectIds = new Set<Id>();
        for (EYI_Project_REC_Mapping__c mapping : overallMappings) {
            projectIds.add(mapping.EYI_Project__c);
        }

        // Retrieve project-related child records for lifetime and last N days
        Map<Id, Map<String, List<SObject>>> projectChildRecordsMap = getProjectChildRecords(projectIds);
        Map<Id, Map<String, List<SObject>>> projectChildRecordsLastNDaysMap = getProjectChildRecordsLastNDays(projectIds);

        // Classify projects based on related records
        for (EYI_Project_REC_Mapping__c mapping : overallMappings) {
            String overallPerformance = 'P4';
            String categoryCurrent = 'P4';
            Map<String, List<SObject>> childRecords = projectChildRecordsMap.get(mapping.EYI_Project__c);
            Map<String, List<SObject>> childRecordsLastNDays = projectChildRecordsLastNDaysMap.get(mapping.EYI_Project__c);

            if (childRecords != null) {
                if ((childRecords.get('activities') != null && !childRecords.get('activities').isEmpty()) ||
                    (childRecords.get('joint_business_plans') != null && !childRecords.get('joint_business_plans').isEmpty())) {
                    overallPerformance = 'P3';
                } else if ((childRecords.get('sitevisits') != null && !childRecords.get('sitevisits').isEmpty()) ||
                           (childRecords.get('cif') != null && !childRecords.get('cif').isEmpty())) {
                    overallPerformance = 'P2';
                } else if (childRecords.get('bookings') != null && !childRecords.get('bookings').isEmpty()) {
                    overallPerformance = 'P1';
                }
            }

            if (childRecordsLastNDays != null) {
                if ((childRecordsLastNDays.get('activities') != null && !childRecordsLastNDays.get('activities').isEmpty()) ||
                    (childRecordsLastNDays.get('joint_business_plans') != null && !childRecordsLastNDays.get('joint_business_plans').isEmpty())) {
                    categoryCurrent = 'P3';
                } else if ((childRecordsLastNDays.get('sitevisits') != null && !childRecordsLastNDays.get('sitevisits').isEmpty()) ||
                           (childRecordsLastNDays.get('cif') != null && !childRecordsLastNDays.get('cif').isEmpty())) {
                    categoryCurrent = 'P2';
                } else if (childRecordsLastNDays.get('bookings') != null && !childRecordsLastNDays.get('bookings').isEmpty()) {
                    categoryCurrent = 'P1';
                }
            }

            mapping.EYI_REC_Classification_Lifetime__c = overallPerformance;
            mapping.EYI_REC_Classification_Current__c = categoryCurrent;
            overallPerformanceMap.put(mapping.Id, mapping);
        }
        
        System.debug('overallPerformanceMap.values()===>'+overallPerformanceMap.values());
        System.debug('overallPerformanceMap ===>'+overallPerformanceMap.keySet());

        // Perform a single update DML statement
        if (!overallPerformanceMap.isEmpty()) {
            update overallPerformanceMap.values();
        }
    }

    // Method to retrieve project-related child records for lifetime
    public static Map<Id, Map<String, List<SObject>>> getProjectChildRecords(Set<Id> projectIds) {
        Map<Id, Map<String, List<SObject>>> projectChildRecordsMap = new Map<Id, Map<String, List<SObject>>>();

        List<EYI_Project__c> projects = [SELECT Id, Name,
                                         (SELECT Id FROM activities__r),
                                         (SELECT Id FROM Bookings__r),
                                         (SELECT Id FROM VP_VC__r),
                                         (SELECT Id FROM CIF__r),
                                         (SELECT Id FROM Joint_Business_Plans__r)
                                         FROM EYI_Project__c WHERE Id IN :projectIds];

        for (EYI_Project__c project : projects) {
            Map<String, List<SObject>> childRecordsMap = new Map<String, List<SObject>>();
            childRecordsMap.put('activities', project.activities__r);
            childRecordsMap.put('bookings', project.Bookings__r);
            childRecordsMap.put('vp_vc', project.VP_VC__r);
            childRecordsMap.put('cif', project.CIF__r);
            childRecordsMap.put('joint_business_plans', project.Joint_Business_Plans__r);
            projectChildRecordsMap.put(project.Id, childRecordsMap);
        }

        return projectChildRecordsMap;
    }

    // Method to retrieve project-related child records for last N days
    public static Map<Id, Map<String, List<SObject>>> getProjectChildRecordsLastNDays(Set<Id> projectIds) {
        Map<Id, Map<String, List<SObject>>> projectChildRecordsMap = new Map<Id, Map<String, List<SObject>>>();
        Integer lastNDays = Integer.valueOf(System.Label.EYI_REC_Performance_Days);

        String query = 'SELECT Id, Name, ' +
        '(SELECT Id FROM activities__r WHERE CreatedDate >= LAST_N_DAYS:' + lastNDays + '), ' +
        '(SELECT Id FROM Bookings__r WHERE CreatedDate >= LAST_N_DAYS:' + lastNDays + '), ' +
        '(SELECT Id FROM VP_VC__r WHERE CreatedDate >= LAST_N_DAYS:' + lastNDays + '), ' +
        '(SELECT Id FROM CIF__r WHERE CreatedDate >= LAST_N_DAYS:' + lastNDays + '), ' +
        '(SELECT Id FROM Joint_Business_Plans__r WHERE CreatedDate >= LAST_N_DAYS:' + lastNDays + ') ' +
        'FROM EYI_Project__c WHERE Id IN :projectIds';

        // Execute the dynamic query
        List<EYI_Project__c> projects = Database.query(query);
        for (EYI_Project__c project : projects) {
            Map<String, List<SObject>> childRecordsMap = new Map<String, List<SObject>>();
            childRecordsMap.put('activities', project.activities__r);
            childRecordsMap.put('bookings', project.Bookings__r);
            childRecordsMap.put('vp_vc', project.VP_VC__r);
            childRecordsMap.put('cif', project.CIF__r);
            childRecordsMap.put('joint_business_plans', project.Joint_Business_Plans__r);
            projectChildRecordsMap.put(project.Id, childRecordsMap);
        }
        return projectChildRecordsMap;
    }






}