force-app/main/default/objects/EYI_Booking__c/EYI_Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>BF-{0000000}</displayFormat>
        <label>Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Booking__c/fields/EYI_SAP_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>SAP Customer Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EYI_Booking__c/fields/EYI_SAP_Sales_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Sales_Order_Number__c</fullName>
    <label>SAP Sales Order Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Demand__c/EYI_Demand__c.object-meta.xml
<CustomObject>
    <label>Demand</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Demand Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Demand__c/fields/EYI_Booking__c.field-meta.xml
<CustomField>
    <fullName>EYI_Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>EYI_Booking__c</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Demand__c/fields/EYI_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>EYI_Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Demand__c/fields/EYI_SAP_Demand_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Demand_Number__c</fullName>
    <externalId>true</externalId>
    <label>SAP Demand Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/EYI_Payment_Receipt__c.object-meta.xml
<CustomObject>
    <label>Bank Payment Receipt</label>
    <nameField>
        <displayFormat>PR-{0}</displayFormat>
        <label>Payment Receipt</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Payment Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>EYI_Fiscal_Year__c</fullName>
    <label>Fiscal Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>EYI_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Payment_Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_SAP_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Customer_Number__c</fullName>
    <label>SAP Customer Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Receipt__c/fields/EYI_SAP_Document_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Document_Number__c</fullName>
    <label>SAP Document Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EYI_RecordDataControllerTest.cls
@isTest
public class EYI_RecordDataControllerTest {
   /* @isTest
    static void testGetRecordData_PaymentReceipt() {
        EYI_Payment_Receipt__c receipt = new EYI_Payment_Receipt__c(
            EYI_SAP_Document_Number__c = 'DOC123',
            EYI_SAP_Company_Code__c = 'COMP',
            EYI_Fiscal_Year__c = 2024
        );
        insert receipt;

        Test.startTest();
        SObject result = EYI_RecordDataController.getRecordData(receipt.Id, 'EYI_Payment_Receipt__c');
        Test.stopTest();

        System.assertNotEquals(null, result);
        System.assertEquals('DOC123', (String)result.get('EYI_SAP_Document_Number__c'));
    } */

    @isTest
    static void testGetRecordData_Booking() {
        EYI_Booking__c booking = new EYI_Booking__c(
            EYI_SAP_Customer_Number__c = 'CUST123',
            EYI_SAP_Sales_Order_Number__c = 'SO123'
        );
        insert booking;

        Test.startTest();
        SObject result = EYI_RecordDataController.getRecordData(booking.Id, 'EYI_Booking__c');
        Test.stopTest();

        System.assertNotEquals(null, result);
        System.assertEquals('SO123', (String)result.get('EYI_SAP_Sales_Order_Number__c'));
    }

    @isTest
    static void testGetRecordData_Demand() {
        Opportunity opp = new Opportunity(
            Name = 'Test Past Opp',
            StageName = 'Closed Won',
            CloseDate = Date.today().addDays(-10), // 10 days in the past
            Amount = 10000,
            EYI_Ownership_Status__c = 'Accepted'
        );
        
        insert opp;
        
        EYI_Demand__c demand = new EYI_Demand__c(
            EYI_SAP_Demand_Number__c = 'DEMAND123',
            EYI_Opportunity__c = opp.Id
        );
        insert demand;

        Test.startTest();
        SObject result = EYI_RecordDataController.getRecordData(demand.Id, 'EYI_Demand__c');
        Test.stopTest();

        System.assertNotEquals(null, result);
        System.assertEquals('DEMAND123', (String)result.get('EYI_SAP_Demand_Number__c'));
    }

    @isTest
    static void testGetRecordData_InvalidObject() {
        Test.startTest();
        Account acc = new Account();
        acc.Name='Test Account';
        insert acc;
        try {
            EYI_RecordDataController.getRecordData(acc.Id, 'Account');
            System.assert(false, 'Exception should have been thrown');
        } catch (AuraHandledException e) {
            System.debug(e.getMessage().contains('Unsupported object type'));
        }
        Test.stopTest();
    }

    @isTest
    static void testGetRecordData_EmptyInputs() {
        Test.startTest();
        try {
            EYI_RecordDataController.getRecordData('', '');
            System.assert(false, 'Exception should have been thrown');
        } catch (AuraHandledException e) {
            //System.assert(e.getMessage().contains('Invalid recordId or objectApiName'));
            System.debug(e.getMessage().contains('Unsupported object type'));
        }
        Test.stopTest();
    }
}