force-app/main/default/objects/EYI_Booking__c/EYI_Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>BF-{0000000}</displayFormat>
        <label>Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Booking__c/fields/EYI_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Booking__c/fields/EYI_Actual_Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Actual_Booking_Date__c</fullName>
    <label>Actual Booking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Booking__c/fields/EYI_Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>EYI_Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Poor quality</fullName>
            </value>
            <value>
                <fullName>Sales call</fullName>
            </value>
            <value>
                <fullName>Damaged in transit</fullName>
            </value>
            <value>
                <fullName>Booking Form not Approved on Time</fullName>
            </value>
            <value>
                <fullName>Customer Requested</fullName>
            </value>
            <value>
                <fullName>Due to Non Payment</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>MISMATCH OF PAYMENT SCHEDULE</fullName>
            </value>
            <value>
                <fullName>Applicant to Co-applicant Transfer</fullName>
            </value>
            <value>
                <fullName>Unit Transfer</fullName>
            </value>
            <value>
                <fullName>Assigned by the System (Internal)</fullName>
                <isActive>false</isActive>
                <label>Assigned by the System (Internal)</label>
            </value>
            <value>
                <fullName>Bill of services completed</fullName>
                <isActive>false</isActive>
                <label>Bill of services completed</label>
            </value>
            <value>
                <fullName>Competitor better</fullName>
                <isActive>false</isActive>
                <label>Competitor better</label>
            </value>
            <value>
                <fullName>Copied and Rejected</fullName>
                <isActive>false</isActive>
                <label>Copied and Rejected</label>
            </value>
            <value>
                <fullName>Copy Failure: New SA Rejected</fullName>
                <isActive>false</isActive>
                <label>Copy Failure: New SA Rejected</label>
            </value>
            <value>
                <fullName>Cust.to receive replacement</fullName>
                <isActive>false</isActive>
                <label>Cust.to receive replacement</label>
            </value>
            <value>
                <fullName>DRM Claim Canellation/Rejection</fullName>
                <isActive>false</isActive>
                <label>DRM Claim Canellation/Rejection</label>
            </value>
            <value>
                <fullName>Delivery date too late</fullName>
                <isActive>false</isActive>
                <label>Delivery date too late</label>
            </value>
            <value>
                <fullName>Guarantee</fullName>
                <isActive>false</isActive>
                <label>Guarantee</label>
            </value>
            <value>
                <fullName>Rejected by Selling Company</fullName>
                <isActive>false</isActive>
                <label>Rejected by Selling Company</label>
            </value>
            <value>
                <fullName>SMP-Declined</fullName>
                <isActive>false</isActive>
                <label>SMP-Declined</label>
            </value>
            <value>
                <fullName>SMP-Flagged (Deleted during Release)</fullName>
                <isActive>false</isActive>
                <label>SMP-Flagged (Deleted during Release)</label>
            </value>
            <value>
                <fullName>SMP-Notification</fullName>
                <isActive>false</isActive>
                <label>SMP-Notification</label>
            </value>
            <value>
                <fullName>SMP-Suspended</fullName>
                <isActive>false</isActive>
                <label>SMP-Suspended</label>
            </value>
            <value>
                <fullName>Too expensive</fullName>
                <isActive>false</isActive>
                <label>Too expensive</label>
            </value>
            <value>
                <fullName>Transaction is being checked</fullName>
                <isActive>false</isActive>
                <label>Transaction is being checked</label>
            </value>
            <value>
                <fullName>Unreasonable request</fullName>
                <isActive>false</isActive>
                <label>Unreasonable request</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Booking__c/fields/EYI_Divisions__c.field-meta.xml
<CustomField>
    <fullName>EYI_Divisions__c</fullName>
    <label>Divisions</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Booking__c/fields/EYI_Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Booking__c/fields/EYI_Project_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Booking__c/fields/EYI_SAP_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>SAP Customer Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EYI_Booking__c/fields/EYI_SAP_Sales_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Sales_Order_Number__c</fullName>
    <label>SAP Sales Order Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Booking__c/fields/EYI_Sourcing_manager__c.field-meta.xml
<CustomField>
    <fullName>EYI_Sourcing_manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sourcing manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Bookings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/EYI_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Project_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Code__c</fullName>
    <label>Project Code</label>
    <length>55</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_SAP_Company_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Company_Code__c</fullName>
    <label>SAP Company Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Sourcing_Manager__c.field-meta.xml
<CustomField>
    <fullName>EYI_Sourcing_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sourcing Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/recordTypes/Residential.recordType-meta.xml
<RecordType>
    <fullName>Residential</fullName>
    <active>true</active>
    <label>Residential</label>
</RecordType>

force-app/main/default/classes/EYI_TDSOutstandingBatchTest.cls
@isTest
public class EYI_TDSOutstandingBatchTest {
    class MockHttpResponseGenerator implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
        HttpResponse res = new HttpResponse();
        res.setStatusCode(200);
        res.setHeader('Content-Type', 'application/json');

        // Mocked JSON response with one TDS item
        Map<String, Object> responseBody = new Map<String, Object>{
            'n0:ZSD_CUSTOMER_LEDGER_SFResponse' => new Map<String, Object>{
                'EX_OUTPUT' => new Map<String, Object>{
                    'item' => new List<Map<String, Object>>{
                        new Map<String, Object>{
                            'INVOICE' => 'INV001',
                            'COMPANYCODE' => '1580',
                            'CUSTOMERCODE' => 'CUST001',
                            'PAYMENTMILESTONE' => 'TDS',
                            'DEMANDRAISEDDATE' => '2025-07-01',
                            'DUEDATE' => '2025-07-10',
                            'PRINCIPALAMOUNT' => 1000000,
                            'GSTAMOUNT' => 180000,
                            'TOTALRECEIVABLE' => 1180000,
                            'PAYMENTRECEIVED' => 0,
                            'OTHERADJUSTMENT' => 0,
                            'TOTALOUTSTANDING' => '1180000',
                            'DOCNUMBER' => '8020001234',
                            'RECEIVEDDATE' => '',
                            'SOURCEOFPAYMENT' => '',
                            'BANKDETAILS' => '',
                            'INSTRUMENTNUMBER' => '',
                            'INSTRUMENTDATE' => ''
                        }
                    }
                }
            }
        };

        res.setBody(JSON.serialize(responseBody));
        return res;
    }
    }
    
    // Mock for empty response
    class MockEmptyResponse implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(200);
            res.setBody(JSON.serialize(
                new Map<String, Object>{
                    'n0:ZSD_OUTSTANDING_BALANCE_SFResponse' => new Map<String, Object>{
                        'EX_MESSAGE' => '',
                            'EX_OUTPUT' => new Map<String, Object>{
                                'item' => new List<Map<String, Object>>()
                                    }
                    }
                }
            ));
            return res;
        }
    }
    
    // Mock for 500 error
    class MockSAP500Error implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(500);
            res.setBody('Internal Server Error');
            return res;
        }
    }

    
    @isTest
    static void testProcessApiResponseMethod() {
        EYI_Project__c proj = new EYI_Project__c(
            Name = 'Test Project',
            EYI_SAP_Company_Code__c = '1320',
            EYI_Project_Code__c = 'PRJ001'
        );
        insert proj;
        
        Opportunity opp = new Opportunity(
            Name = 'Test Opp',
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(10),
            EYI_SAP_Customer_Number__c = '0010000001',
            EYI_Project_Enquired__c = proj.Id,
            EYI_Ownership_Status__c = 'Accepted'
        );
        insert opp;
        
        EYI_Booking__c book = new EYI_Booking__c(
            EYI_SAP_Sales_Order_Number__c ='1234400994',
            EYI_Opportunity_Name__c= opp.id,
            EYI_Project_Name__c= proj.id,
            EYI_Divisions__c='Residential',
            //EYI_Account_Name__c= Acc.id,
            EYI_Actual_Booking_Date__c= system.today()-10,
            EYI_Cancellation_Reason__c = 'Sales call',
            EYI_Sourcing_manager__c= UserInfo.getUserId()
        );
        insert book;
        opp.EYI_Booking__c =book.Id;
        update opp;
        // Use the same mock body as MockSAPCallout
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

         Test.startTest();
        EYI_TDSOutstandingBatch batch = new EYI_TDSOutstandingBatch();
        Database.executeBatch(batch, 1);
        Test.stopTest();
    }
    @isTest
    static void testSchedulerExecute() {
        Test.startTest();
        
        // Instantiate and execute the scheduler
        EYI_TDSOutstandingSchedular scheduler = new EYI_TDSOutstandingSchedular();
        scheduler.execute(null); // Passing null is okay in test context
        
        Test.stopTest();
        
        System.assert(true, 'Scheduler execute method should run without error');
    }
}