force-app/main/default/objects/EYI_Project__c/EYI_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Project__c/fields/EYI_SAP_Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Plant_Code__c</fullName>
    <label>SAP Plant Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_SAP_Salesorg__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Salesorg__c</fullName>
    <label>SAP Sales-org</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project_Unit__c/EYI_Project_Unit__c.object-meta.xml
<CustomObject>
    <label>Project Unit</label>
    <nameField>
        <label>Project Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Project_Unit__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Project Units</relationshipLabel>
    <relationshipName>Project_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Project_Unit__c/fields/EYI_Unit_SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_Unit_SAP_Code__c</fullName>
    <label>Unit SAP Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/EYI_Rate_List__c.object-meta.xml
<CustomObject>
    <label>Rate List</label>
    <nameField>
        <displayFormat>Rate List-{00}</displayFormat>
        <label>Rate List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Calculation_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Calculation_Type__c</fullName>
    <label>Calculation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Fixed Amount</fullName>
            </value>
            <value>
                <fullName>Quantity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Condition_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Condition_Type__c</fullName>
    <label>Condition Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Infra Charges</fullName>
            </value>
            <value>
                <fullName>Base Price</fullName>
            </value>
            <value>
                <fullName>Brokerage Additional</fullName>
            </value>
            <value>
                <fullName>Brokerage</fullName>
            </value>
            <value>
                <fullName>Club House</fullName>
            </value>
            <value>
                <fullName>Floor Rise</fullName>
            </value>
            <value>
                <fullName>Land Cost</fullName>
            </value>
            <value>
                <fullName>2 Wheeler Charges</fullName>
            </value>
            <value>
                <fullName>Base Price-Booking</fullName>
            </value>
            <value>
                <fullName>MSEB Charges</fullName>
            </value>
            <value>
                <fullName>STAMP DUTY AND REG - RECOVERABLE</fullName>
            </value>
            <value>
                <fullName>STAMP DUTY NON RECOVERABLE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Project_Unit__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Unit</label>
    <referenceTo>EYI_Project_Unit__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EYI_PricingCreationWrapper.cls
public class EYI_PricingCreationWrapper {
    
    /* //public List<cls_item> item;
public I_MASTER I_MASTER;
// Constructor for the outer class (optional)
public EYI_PricingCreationWrapper() {
// public list<item> item; 

this.I_MASTER = new I_MASTER();  // Initialize inner class
}
public class I_MASTER{
public list<cls_item> item; 
}
//public List<EReturn> E_RETURN;
*/
    public IMaster I_MASTER;
    
    // Constructor for the outer class
    public EYI_PricingCreationWrapper() {
        this.I_MASTER = new IMaster();
    }
    
    public class IMaster {
        public list<cls_item> item;
        
        // Constructor for IMaster
        public IMaster() {
            this.item = new cls_item[0]; // Initialize as an empty array
        }
    }
    
    public class cls_item{
        public String KSCHL;
        public String VKORG;
        public String WERKS;
        public String VTWEG;
        public String MATNR;
        public Decimal KBETR;
        public String KMEIN;
        //public Integer KPEIN;
        public string KPEIN;
        public String KRECH;
        //public Date DATAB;
        public string DATAB;
        //public Date DATBI;
        public string DATBI;
        
        // public EReturn(){
        public cls_item(){
            
            this.KSCHL = '';
            this.VKORG= '';
            this.WERKS= '';
            this.VTWEG= '';
            this.MATNR= '';//depend on inventory
            this.KBETR= 0.0;
            this.KMEIN= '';//inventory 
            this.KPEIN ='';
            this.KRECH= '';
            
            Date today = System.today();
            String day = String.valueOf(today.day()).leftPad(2, '0');
            String month = String.valueOf(today.month()).leftPad(2, '0');
            String year = String.valueOf(today.year());
            
            String formattedDate = day + '-' + month + '-' + year;
            System.debug('Formatted Date: ' + formattedDate);
            
            this.DATAB = formattedDate;
            this.DATBI= '31-12-9999';//string.valueof(system.today());
            
            
        }
        //public EReturn(EYI_Rate_List__c pricingRecord){
        public cls_item(EYI_Rate_List__c pricingRecord){
            this.KSCHL = pricingRecord.EYI_Condition_Type__c;
            this.VKORG = pricingRecord.EYI_Project__r.EYI_SAP_Salesorg__c;
            this.WERKS = pricingRecord.EYI_Project__r.EYI_SAP_Plant_Code__c;
            this.MATNR = pricingRecord.EYI_Project_Unit__r.EYI_Unit_SAP_Code__c;
            //this.KBETR;
            //this.KMEIN;
            //this.KPEIN;
            //this.KRECH = pricingRecord.EYI_Calculation_Type__c;
        }
    }
    
    
}