force-app/main/default/objects/EYI_Project__c/EYI_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Configuration_Types__c.field-meta.xml
<CustomField>
    <fullName>EYI_Configuration_Types__c</fullName>
    <label>Configuration Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2BHK</fullName>
            </value>
            <value>
                <fullName>3BHK</fullName>
            </value>
            <value>
                <fullName>4BHK</fullName>
            </value>
            <value>
                <fullName>3.5BHK</fullName>
            </value>
            <value>
                <fullName>4.5BHK</fullName>
            </value>
            <value>
                <fullName>Penthouse</fullName>
            </value>
            <value>
                <fullName>Business Unit</fullName>
            </value>
            <value>
                <fullName>Office Spaces</fullName>
            </value>
            <value>
                <fullName>Retail Store</fullName>
            </value>
            <value>
                <fullName>Retail Unit</fullName>
            </value>
            <value>
                <fullName>Duplex</fullName>
            </value>
            <value>
                <fullName>Simplex</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Plot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Land_Area__c.field-meta.xml
<CustomField>
    <fullName>EYI_Land_Area__c</fullName>
    <label>Land Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Number_Of_Towers__c.field-meta.xml
<CustomField>
    <fullName>EYI_Number_Of_Towers__c</fullName>
    <label>Number Of Towers</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Number_Of_Units__c.field-meta.xml
<CustomField>
    <fullName>EYI_Number_Of_Units__c</fullName>
    <label>Number Of Units</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Price_Onwards__c.field-meta.xml
<CustomField>
    <fullName>EYI_Price_Onwards__c</fullName>
    <label>Price Onwards</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Project_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Code__c</fullName>
    <label>Project Code</label>
    <length>55</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Project_Description__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Description__c</fullName>
    <label>Project Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Project_Location__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Location__c</fullName>
    <label>Project Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Project_Property_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Property_Type__c</fullName>
    <label>Project Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
                <default>true</default>
                <label>Residential</label>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Project_Size_In_Sq_Ft__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Size_In_Sq_Ft__c</fullName>
    <label>Project Size In Sq Ft</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Project_Size_In_Sq_Mtr__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Size_In_Sq_Mtr__c</fullName>
    <label>Project Size In Sq Mtr</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Project_Status__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Status__c</fullName>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Teaser</fullName>
            </value>
            <value>
                <fullName>Pre- Launch</fullName>
            </value>
            <value>
                <fullName>Launch</fullName>
            </value>
            <value>
                <fullName>Post Launch</fullName>
            </value>
            <value>
                <fullName>Sustenance</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Rera_Carpet_Area_In_Sq_Ft__c.field-meta.xml
<CustomField>
    <fullName>EYI_Rera_Carpet_Area_In_Sq_Ft__c</fullName>
    <label>Rera Carpet Area  In Sq Ft</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Rera_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Rera_Number__c</fullName>
    <label>Rera Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_SAP_Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Plant_Code__c</fullName>
    <label>SAP Plant Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_SAP_Salesorg__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Salesorg__c</fullName>
    <label>SAP Sales-org</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/recordTypes/Residential.recordType-meta.xml
<RecordType>
    <fullName>Residential</fullName>
    <active>true</active>
    <label>Residential</label>
</RecordType>

force-app/main/default/objects/EYI_Tower__c/EYI_Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Tower__c/fields/EYI_Project_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Tower__c/fields/EYI_RERA_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_RERA_Number__c</fullName>
    <label>RERA Number</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Tower__c/recordTypes/Residential.recordType-meta.xml
<RecordType>
    <fullName>Residential</fullName>
    <active>true</active>
    <label>Residential</label>
</RecordType>

force-app/main/default/classes/EYI_ProjectSyncToMobileAppTest.cls
@isTest
private class EYI_ProjectSyncToMobileAppTest {

    @TestSetup
    static void setupProjectData() {
        EYI_Project__c project = new EYI_Project__c(
            Name = 'Test Sync Project',
            EYI_Project_Code__c = 'PRJ_TEST_001',
            EYI_SAP_Salesorg__c = '1000',
            EYI_SAP_Plant_Code__c = '1100',
            EYI_Project_Property_Type__c = 'Residential',
            EYI_Project_Status__c = 'Teaser',
            EYI_Project_Location__c = 'Mumbai',
            EYI_Configuration_Types__c = '2BHK',
            EYI_Project_Description__c = 'Test description',
            EYI_Price_Onwards__c = '15000000',
            EYI_Project_Size_In_Sq_Mtr__c = 120,
            EYI_Project_Size_In_Sq_Ft__c = 1292,
            EYI_Rera_Carpet_Area_In_Sq_Ft__c = 1100,
            EYI_Number_Of_Towers__c = 2,
            EYI_Number_Of_Units__c = 120,
            EYI_Rera_Number__c = 'RERA123'
            //EYI_Land_Area__c = 5000
        );
        insert project;
       
    }

    @isTest
    static void testProjectSyncCalloutFlow() {
        // Register your existing mock class
        Test.setMock(HttpCalloutMock.class, new EYI_ProjectSyncToMobileApp_Mock());

        EYI_Project__c insertedProject = [
            SELECT Id FROM EYI_Project__c LIMIT 1
        ];

        // Invoke the method that triggers @future callout
        Test.startTest();
        EYI_ProjectSyncToMobileApp.getProjectDetails(new List<EYI_Project__c>{insertedProject}, true);
        Test.stopTest();

        // Optional: verify if project was updated with mocked ID
        EYI_Project__c updated = [SELECT EYI_Project_Code__c FROM EYI_Project__c WHERE Id = :insertedProject.Id];
        System.assertEquals('1234567890', updated.EYI_Project_Code__c); // Based on your mock response
    }
    @isTest
    static void testTowerSyncCalloutFlow() {
        EYI_Project__c insertedProject = [
            SELECT Id FROM EYI_Project__c LIMIT 1
        ];
        EYI_Tower__c towerObj = new EYI_Tower__c();
        towerObj.Name='Tower 1';
        towerObj.EYI_Project_Name__c = insertedProject.Id;
        insert towerObj;
        Test.setMock(HttpCalloutMock.class, new EYI_ProjectSyncToMobileApp_Mock());
        
        Test.startTest();
        EYI_ProjectSyncToMobileApp.syncTowersToMobileApp(new Set<Id>{towerObj.Id});
        Test.stopTest();
	}
}