force-app/main/default/objects/EYI_Project__c/EYI_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Asset_Class__c.field-meta.xml
<CustomField>
    <fullName>EYI_Asset_Class__c</fullName>
    <label>Asset Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Outright</fullName>
            </value>
            <value>
                <fullName>Leasing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Chatbot_Active__c.field-meta.xml
<CustomField>
    <fullName>EYI_Chatbot_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Chatbot Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Condition_Group_1__c.field-meta.xml
<CustomField>
    <fullName>EYI_Condition_Group_1__c</fullName>
    <label>Condition Group 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PMC</fullName>
            </value>
            <value>
                <fullName>PCMC</fullName>
            </value>
            <value>
                <fullName>PMRDA</fullName>
            </value>
            <value>
                <fullName>Township</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>EYI_Distribution_Channel__c</fullName>
    <label>Distribution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
                <label>Common</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Residential Sales</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Commercial Sales</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Domestic Sales</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>Export Sales</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>Sale of Services</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>Group Company Sales</label>
            </value>
            <value>
                <fullName>70</fullName>
                <label>Stock Transfer</label>
            </value>
            <value>
                <fullName>80</fullName>
                <label>Other Sales</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Project_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Code__c</fullName>
    <label>Project Code</label>
    <length>55</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Project_Location__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Location__c</fullName>
    <label>Project Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Project_Property_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Property_Type__c</fullName>
    <label>Project Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
                <default>true</default>
                <label>Residential</label>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Project_Site_Location_Link__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Site_Location_Link__c</fullName>
    <label>Project Site Location Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Project_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Start_Date__c</fullName>
    <label>Project Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Project_Status__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Status__c</fullName>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Teaser</fullName>
            </value>
            <value>
                <fullName>Pre- Launch</fullName>
            </value>
            <value>
                <fullName>Launch</fullName>
            </value>
            <value>
                <fullName>Post Launch</fullName>
            </value>
            <value>
                <fullName>Sustenance</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Project_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Type__c</fullName>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Plot</fullName>
            </value>
            <value>
                <fullName>Flat</fullName>
            </value>
            <value>
                <fullName>Business Unit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_RDS_State__c.field-meta.xml
<CustomField>
    <fullName>EYI_RDS_State__c</fullName>
    <label>State</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Sales_District__c.field-meta.xml
<CustomField>
    <fullName>EYI_Sales_District__c</fullName>
    <label>Sales District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IN0001</fullName>
                <label>Pune</label>
            </value>
            <value>
                <fullName>IN0002</fullName>
                <label>Mumbai</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_SAP_Company_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Company_Code__c</fullName>
    <label>SAP Company Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_SAP_Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Plant_Code__c</fullName>
    <label>SAP Plant Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_SAP_Salesorg__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Salesorg__c</fullName>
    <label>SAP Sales-org</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_SAPMaterial_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAPMaterial_Code__c</fullName>
    <label>SAPMaterial Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Sourcing_Manager__c.field-meta.xml
<CustomField>
    <fullName>EYI_Sourcing_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sourcing Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Stamp_Duty__c.field-meta.xml
<CustomField>
    <fullName>EYI_Stamp_Duty__c</fullName>
    <label>Stamp Duty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Sub_Asset_Class__c.field-meta.xml
<CustomField>
    <fullName>EYI_Sub_Asset_Class__c</fullName>
    <label>Sub Asset Class</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>EYI_Asset_Class__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Plot</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Apartment</fullName>
            </value>
            <value>
                <fullName>Business Unit</fullName>
            </value>
            <value>
                <fullName>Retail and F&amp;B</fullName>
            </value>
            <value>
                <fullName>Office Space</fullName>
            </value>
            <value>
                <fullName>Business Units</fullName>
                <isActive>false</isActive>
                <label>Business Units</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Total_Budget__c.field-meta.xml
<CustomField>
    <fullName>EYI_Total_Budget__c</fullName>
    <description>This field is used to store total budget cost of project. This value will be capture from SAP.</description>
    <label>Total Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Zone__c.field-meta.xml
<CustomField>
    <fullName>EYI_Zone__c</fullName>
    <label>Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pune City</fullName>
            </value>
            <value>
                <fullName>PCMC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Project__c/recordTypes/Residential.recordType-meta.xml
<RecordType>
    <fullName>Residential</fullName>
    <active>true</active>
    <label>Residential</label>
</RecordType>

force-app/main/default/classes/EYI_SAP_ReportController_Test.cls
@isTest
public class EYI_SAP_ReportController_Test {
	@isTest
    public static void getTDSReportTest(){
        Map<String, List<String>> testFilter = new Map<String, List<String>>();
        testFilter.put('CompanyCode', new List<String>{'1000', '2000'});
        testFilter.put('Vendor', new List<String>{'V001'});
        testFilter.put('FiscalYear', new List<String>{'2024'});
        
        String filterJson = JSON.serialize(testFilter);
        String badJson = '{badJson: [unquotedValue]}';
        Test.startTest();
        String result = EYI_SAP_ReportController.getTDSReport(filterJson);
		//String result1 = EYI_SAP_ReportController.getTDSReport(badJson);
        Test.stopTest();
    }
    
    @isTest
    public static void getAgeingReportTest(){
        
         Map<String, Object> input = new Map<String, Object>{
            'KeyDate' => '2025-05-01',
            'CompanyCode' => new List<String>{'1000', '2000'},
            'CustomerNo' => new List<String>{'C001', 'C002'},
            'DueDays1' => new List<String>{'30'},
            'DueDays2' => new List<String>{'60'}
        };

        String inputJson = JSON.serialize(input);
		String badJson = '{badJson: [unquotedValue]}';
        Test.startTest();
         Test.setMock(HttpCalloutMock.class, new MockApiResponse());
        String result = EYI_SAP_ReportController.getAgeingReport(inputJson);
        //String result1 = EYI_SAP_ReportController.getAgeingReport(badJson);
        Test.stopTest();
    }
    
    @isTest
    public static void getAllProjectTest(){
        EYI_Project__c projctobj = new EYI_Project__c(
            Name = 'Balewadi 23',
            EYI_Sourcing_Manager__c = UserInfo.getUserId(),
            EYI_Condition_Group_1__c = 'PMC',
            EYI_Distribution_Channel__c = '10',
            EYI_Project_Status__c = 'Pre- Launch',
            EYI_Project_Type__c = 'Flat',
            EYI_Zone__c = 'Pune City',
            EYI_Chatbot_Active__c = true,
            EYI_Project_Location__c = 'Kharadi',
            EYI_Project_Site_Location_Link__c = 'https://maps.app.goo.gl/ZzSkyikTyHoDYoKr5',
            EYI_Project_Start_Date__c = System.today() - 10,
            EYI_SAP_Company_Code__c = '1320',
            EYI_SAP_Plant_Code__c = 'R15A',
            EYI_Sales_District__c = 'IN0001',
            EYI_SAP_Salesorg__c = 'R152',
            EYI_Stamp_Duty__c = 5,
            EYI_RDS_State__c = 'Maharashtra',
            EYI_Asset_Class__c = 'Outright',
            EYI_Sub_Asset_Class__c = 'Plot',
            EYI_Total_Budget__c = 1000000,
            EYI_Project_Code__c = '83',
            EYI_Project_Property_Type__c = 'Residential',
            EYI_SAPMaterial_Code__c = 'EYI_SAPMaterial_Code__c'
        );
        insert projctobj;
        Test.startTest();
        EYI_SAP_ReportController.getAllProjects();
        Test.stopTest();
    }
    
    class MockApiResponse implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(200);
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"EX_MESSAGE":{"Message":""},"EX_OUTPUT":{"item":[{"SalesDocument":"3020000159","SOLineItem":"10","CustomerNo":"20000245","CustomerName":"Yugantara Vishwakaram","TotalConsideration":"27006000","BookingDate":"2023-07-28"}]}}');
            return res;
        }
    }
    
    @isTest
    public static void getApiDataTest(){
        Map<String, List<String>> filterMap = new Map<String, List<String>>();
        filterMap.put('CustomerNo', new List<String>{'20000245'});
        filterMap.put('SalesOrg', new List<String>{'R150'});
        filterMap.put('KeyDate', new List<String>{'2024-12-31'});

        String filterString = JSON.serialize(filterMap);
        
        Test.startTest();
		Test.setMock(HttpCalloutMock.class, new MockApiResponse());
        String response = EYI_SAP_ReportController.getApiData(filterString);
		Test.stopTest();        
    }
}