force-app/main/default/objects/EYI_Customer_Information_Form__c/EYI_Customer_Information_Form__c.object-meta.xml
<CustomObject>
    <label>CIF Records</label>
    <nameField>
        <displayFormat>CIF-{0000}</displayFormat>
        <label>Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CIF Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>EYI_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>CIF Records</relationshipLabel>
    <relationshipName>CIF_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Referral_Employee__c.field-meta.xml
<CustomField>
    <fullName>EYI_Referral_Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referral Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CIF_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Walk_in_Source__c.field-meta.xml
<CustomField>
    <fullName>EYI_Walk_in_Source__c</fullName>
    <label>Walk-in Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct Client</fullName>
            </value>
            <value>
                <fullName>PREC</fullName>
            </value>
            <value>
                <fullName>Presales</fullName>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>Existing Client</fullName>
            </value>
            <value>
                <fullName>IVR</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Privilege</fullName>
            </value>
            <value>
                <fullName>REC Lead</fullName>
            </value>
            <value>
                <fullName>SM Self Sourcing</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>CTI</fullName>
            </value>
            <value>
                <fullName>Archive Leads</fullName>
                <isActive>false</isActive>
                <label>Archive Leads</label>
            </value>
            <value>
                <fullName>Channel Partner</fullName>
                <isActive>false</isActive>
                <label>Channel Partner</label>
            </value>
            <value>
                <fullName>Cold Calling</fullName>
                <isActive>false</isActive>
                <label>Cold Calling</label>
            </value>
            <value>
                <fullName>Core Leads</fullName>
                <isActive>false</isActive>
                <label>Core Leads</label>
            </value>
            <value>
                <fullName>Databases</fullName>
                <isActive>false</isActive>
                <label>Databases</label>
            </value>
            <value>
                <fullName>Digital Media</fullName>
                <isActive>false</isActive>
                <label>Digital Media</label>
            </value>
            <value>
                <fullName>Direct</fullName>
                <isActive>false</isActive>
                <label>Direct</label>
            </value>
            <value>
                <fullName>EYI Contact Center</fullName>
                <isActive>false</isActive>
                <label>EYI Contact Center</label>
            </value>
            <value>
                <fullName>Email</fullName>
                <isActive>false</isActive>
                <label>Email</label>
            </value>
            <value>
                <fullName>Employee Referral Scheme</fullName>
                <isActive>false</isActive>
                <label>Employee Referral Scheme</label>
            </value>
            <value>
                <fullName>Exhibition</fullName>
                <isActive>false</isActive>
                <label>Exhibition</label>
            </value>
            <value>
                <fullName>Facebook</fullName>
                <isActive>false</isActive>
                <label>Facebook</label>
            </value>
            <value>
                <fullName>Google</fullName>
                <isActive>false</isActive>
                <label>Google</label>
            </value>
            <value>
                <fullName>Lead Reference</fullName>
                <isActive>false</isActive>
                <label>Lead Reference</label>
            </value>
            <value>
                <fullName>Lost Leads</fullName>
                <isActive>false</isActive>
                <label>Lost Leads</label>
            </value>
            <value>
                <fullName>Loyalty</fullName>
                <isActive>false</isActive>
                <label>Loyalty</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Expression_Of_Interest__c/EYI_Expression_Of_Interest__c.object-meta.xml
<CustomObject>
    <label>Expression Of Interest</label>
    <nameField>
        <displayFormat>EOI-{000000}</displayFormat>
        <label>EOI Unique ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expression Of Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Expression_Of_Interest__c/fields/EYI_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>EYI_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Expression Of Interests</relationshipLabel>
    <relationshipName>Expression_Of_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Target_Management__c/EYI_Target_Management__c.object-meta.xml
<CustomObject>
    <label>Target Management</label>
    <nameField>
        <displayFormat>TM-{000}</displayFormat>
        <label>Target Management Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Managements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Target_Management__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Target Managements</relationshipLabel>
    <relationshipName>Target_Managements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Target_Management__c/fields/EYI_Target_End_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Target_End_Date__c</fullName>
    <label>Target End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Target_Management__c/fields/EYI_Target_KPI__c.field-meta.xml
<CustomField>
    <fullName>EYI_Target_KPI__c</fullName>
    <label>Target KPI</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>EYI_Target_Module__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Follow-up by CTI</fullName>
                <label>Follow-up by CTI (%)</label>
            </value>
            <value>
                <fullName>Walk-in to Booking Conversion</fullName>
                <label>Walk-in to Booking Conversion (%)</label>
            </value>
            <value>
                <fullName>Number of EOIs</fullName>
            </value>
            <value>
                <fullName>EOI Conversions</fullName>
                <label>EOI Conversions (%)</label>
            </value>
            <value>
                <fullName>Revenue Target</fullName>
            </value>
            <value>
                <fullName>Meeting Target</fullName>
            </value>
            <value>
                <fullName>New CP Empanelment</fullName>
            </value>
            <value>
                <fullName>Walkin Achieved</fullName>
            </value>
            <value>
                <fullName>VC/VP Target</fullName>
            </value>
            <value>
                <fullName>REC Calls by SM</fullName>
            </value>
            <value>
                <fullName>Visit Confirmed</fullName>
            </value>
            <value>
                <fullName>Visit Done</fullName>
            </value>
            <value>
                <fullName>Average Talk Time</fullName>
                <label>Total Talk Time (In Minutes)</label>
            </value>
            <value>
                <fullName>Lead to Walk-In Conversion ratio</fullName>
            </value>
            <value>
                <fullName>Total Outbound Calls to be Done</fullName>
            </value>
            <value>
                <fullName>Total Inbound Calls Completed</fullName>
            </value>
            <value>
                <fullName>Re-visit (Unique revisits / Total revisits)</fullName>
                <label>Re-visit (Unique revisits / Total revisits) (%)</label>
            </value>
            <value>
                <fullName>Average Follow-Ups</fullName>
                <isActive>false</isActive>
                <label>Average Follow-Ups (Per Day)</label>
            </value>
            <value>
                <fullName>Average TAT from Walk-in to Booking</fullName>
                <isActive>false</isActive>
                <label>Average TAT from Walk-in to Booking</label>
            </value>
            <value>
                <fullName>Booking from Cold/Lost leads</fullName>
                <isActive>false</isActive>
                <label>Booking from Cold/Lost leads (%)</label>
            </value>
            <value>
                <fullName>Cancellation Count</fullName>
                <isActive>false</isActive>
                <label>Cancellation Count</label>
            </value>
            <value>
                <fullName>Follow-ups missed</fullName>
                <isActive>false</isActive>
                <label>Follow-ups missed (%)</label>
            </value>
            <value>
                <fullName>L1 TAT Approval</fullName>
                <isActive>false</isActive>
                <label>L1 TAT Approval  (In Minutes)</label>
            </value>
            <value>
                <fullName>L2 TAT Approval</fullName>
                <isActive>false</isActive>
                <label>L2 TAT Approval (In Minutes)</label>
            </value>
            <value>
                <fullName>L3 TAT Approval</fullName>
                <isActive>false</isActive>
                <label>L3 TAT Approval (In Minutes)</label>
            </value>
            <value>
                <fullName>Number of Cases Where the Cooling Period is Extended</fullName>
                <isActive>false</isActive>
                <label>Number of Cases Where the Cooling Period is Extended (%)</label>
            </value>
            <value>
                <fullName>Number of references generated by the Sales Manager</fullName>
                <isActive>false</isActive>
                <label>Number of references generated by the Sales Manager (%)</label>
            </value>
            <value>
                <fullName>Revenue (Project-Wise Revenue Target in Crore)</fullName>
                <isActive>false</isActive>
                <label>Revenue (Project-Wise Revenue Target in Crore)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Target_Management__c/fields/EYI_Target_Module__c.field-meta.xml
<CustomField>
    <fullName>EYI_Target_Module__c</fullName>
    <label>Target Module</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Presales</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Sourcing</fullName>
            </value>
            <value>
                <fullName>Revenue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Target_Management__c/fields/EYI_Target_Month_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Target_Month_Date__c</fullName>
    <label>Target Month Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Target_Management__c/fields/EYI_Target_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Target_Start_Date__c</fullName>
    <label>Target Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Target_Management__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Target Managements</relationshipLabel>
    <relationshipName>Target_Managements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EYI_MonthlySalesAchievementsBatch.cls
global with sharing class EYI_MonthlySalesAchievementsBatch implements Database.Batchable<SObject> {
	global Database.QueryLocator start(Database.BatchableContext BC) {
        Integer fiscalStartMonth = Integer.ValueOf(System.Label.EYI_FINANCIAL_START_MONTH); // April
        Date today = Date.today();
        Integer fiscalYear;

        if (today.month() >= fiscalStartMonth) {
            fiscalYear = today.year() + 1;
        } else {
            fiscalYear = today.year();
        }

        // Fiscal year starts in April of the previous calendar year
        Integer fiscalStartYear = fiscalYear - 1;

        Date fiscalStart = Date.newInstance(fiscalStartYear, fiscalStartMonth, 1);
        Date fiscalEnd = fiscalStart.addYears(1).addDays(-1);
        return Database.getQueryLocator([ SELECT Id, Name,OwnerId,EYI_Project__c,EYI_Target_Start_Date__c,EYI_Target_END_Date__c,EYI_Target_KPI__c,EYI_Tower__c,EYI_Target_Month_Date__c 
        FROM EYI_Target_Management__c  WHERE EYI_Target_Start_Date__c >= :fiscalStart
            AND EYI_Target_End_Date__c <= :fiscalEnd AND EYI_Target_KPI__c != 'Revenue Target' AND EYI_Target_Module__c = 'Sales'  ]);
    }
     global void execute(Database.BatchableContext BC, List<EYI_Target_Management__c> monthlyTargetRec) {
          system.debug('monthlyTargetRec'+monthlyTargetRec);
        Map<Id,String> monthlyTargetMap = new Map<Id,String>();
        Map<String,Id> monthlyTargetMapValues = new Map<String,Id>();
        Date monthStart;
        Date monthEnd;
         
        Set<String> filterKeys = new Set<String>();
        for(EYI_Target_Management__c mt:monthlyTargetRec){
            monthStart = mt.EYI_Target_Start_Date__c;
            monthEnd = mt.EYI_Target_End_Date__c;
          if (mt.OwnerId != null && mt.EYI_Target_KPI__c != null ) {
            String key = mt.OwnerId + '_' + mt.EYI_Target_KPI__c;
                monthlyTargetMap.put(mt.Id, key);
              	monthlyTargetMapValues.put(key,mt.Id);
              	filterKeys.add(mt.OwnerId);
           }
        }
        
        Map<String, Integer> achievementCounts = new Map<String, Integer>();
        Map<String,Integer> totaFollowUpMissed = new Map<String,Integer>();
         Map<String,Integer> totaOppCreated = new Map<String,Integer>();
          Map<String,Integer> totaEOICreated = new Map<String,Integer>();
         Map<String,String> stepNameMap = new Map<String,String>();
         Map<String,String> stepNameMapTL = new Map<String,String>();
         Map<String,Id> userNameWithId = new Map<String,Id>();
        List<AggregateResult> followUpMissedAggResults = [
            select Count(id) totalCount, OwnerId  
            from task 
            where Status != 'Completed' AND  CreatedDate >= :monthStart AND CreatedDate < :monthEnd  AND Subject LIKE '%Follow Up%' AND ActivityDate < TODAY AND what.type = 'Opportunity'  
            Group BY OwnerId  
        ];
         //total follow up of this month of non CTI
         List<AggregateResult> totalFollowUpAggResults = [
            select Count(id) totalCount, OwnerId  
            from task 
            where   Status = 'Completed' AND CreatedDate >= :monthStart AND CreatedDate < :monthEnd  AND   EYI_Next_Action_Status__c != null AND EYI_Next_Action_Status__c != ''  AND what.type = 'Opportunity'  
            Group BY OwnerId  
        ];
         List<AggregateResult> totalCTIFollowUpAggResults = [
            select Count(id) totalCount , OwnerId  
            from task 
            where  Status = 'Completed' AND CreatedDate >= :monthStart AND CreatedDate < :monthEnd  AND tdc_360CTI__Call_Log__c  != '' AND EYI_Next_Action_Status__c != null AND EYI_Next_Action_Status__c != '' AND  TaskSubtype = 'Call' AND what.type = 'Opportunity'  
            Group BY OwnerId  
        ];
         //booking cold lost
         List<AggregateResult> totalColdLostBookingResults = [
             select Count(id) totalCount, OwnerId  
            from Opportunity 
            where   EYI_Booked_Date__c >= :monthStart AND EYI_Booked_Date__c < :monthEnd   AND (EYI_Initial_Rating__c = 'Cold' OR EYI_Initial_Rating__c = 'Lost')  AND StageName != 'Cancelled'
            Group BY OwnerId  
        ];
         //booking cold lost
         List<AggregateResult> totalBookingResults = [
             select Count(id) totalCount, OwnerId  
            from Opportunity 
            where  EYI_Booked_Date__c >= :monthStart AND EYI_Booked_Date__c < :monthEnd    AND StageName != 'Cancelled'
            Group BY OwnerId  
        ];
         
         //cooling period extended
         List<AggregateResult> totalCoolingPeriodExtResults = [
             select Count(id) totalCount, OwnerId  
            from Opportunity 
            where  EYI_Close_Date_Before_Extension__c >= :monthStart AND EYI_Close_Date_Before_Extension__c < :monthEnd  AND Extension_Requested__c =  true
            Group BY OwnerId  
        ];
         List<AggregateResult> totalOppCreatedResults = [
            select Count(id) totalCount, OwnerId  
            from Opportunity 
            where  CreatedDate >= :monthStart AND CreatedDate < :monthEnd 
            Group BY OwnerId  
        ];
         List<AggregateResult> oppWalkToBookedResults = [
            select SUM(EYI_Walk_In_to_Booking_TAT__c) totalCount, OwnerId  
            from Opportunity 
            where  EYI_Booked_Date__c >= :monthStart AND EYI_Booked_Date__c < :monthEnd  AND EYI_Booked_Date__c != null AND StageName != 'Cancelled'
            Group BY OwnerId  
        ];
         List<AggregateResult> totalRevisitedOpp = [
            select Count(id) totalCount, OwnerId  
            from Opportunity 
            where  CreatedDate >= :monthStart AND CreatedDate < :monthEnd  AND EYI_Revisit_Count__c >= 1
            Group BY OwnerId  
        ];
         List<AggregateResult> totalCancellationApprovedOpp = [
            select Count(id) totalCount, OwnerId  
            from Opportunity 
            where  EYI_Cancellation_Approval_Date__c >= :monthStart AND EYI_Cancellation_Approval_Date__c < :monthEnd
            Group BY OwnerId  
        ];
         List<AggregateResult> totalNumberOfEOI = [
            select Count(id) totalCount, OwnerId  
            from EYI_Expression_Of_Interest__c 
            where  EYI_Opportunity__c != '' AND CreatedDate >= :monthStart AND CreatedDate < :monthEnd 
            Group BY OwnerId  
        ];
         List<AggregateResult> totalNumberOfEOIConversion = [
            select Count(id) totalCount, OwnerId  
            from EYI_Expression_Of_Interest__c 
            where  EYI_Opportunity__c != '' AND EYI_Opportunity__r.EYI_Booked_Date__c >= :monthStart AND EYI_Opportunity__r.EYI_Booked_Date__c < :monthEnd  AND EYI_Opportunity__r.StageName != 'Cancelled' 
            Group BY OwnerId  
        ];
         //Approval TAT
        /* List<AggregateResult> totalApprovalTAT = [Select StepNodeId,ProcessInstance.SubmittedById ActorId,SUM(ElapsedTimeInMinutes) totalCount   from ProcessInstanceStep where ProcessInstance.ProcessDefinition.Name = 'Deviation approval2' AND StepNodeId!= '' AND CreatedDate >= 2025-06-01T00:00:00Z AND CreatedDate < 2025-07-01T00:00:00Z  GROUP BY StepNodeId,ProcessInstance.SubmittedById];
         List<AggregateResult> totalApprovalTATTL = [Select StepNodeId,ProcessInstance.SubmittedById ActorId,SUM(ElapsedTimeInMinutes) totalCount   from ProcessInstanceStep where ProcessInstance.ProcessDefinition.Name = 'Deviation approval2 for TL' AND StepNodeId!= '' AND CreatedDate >= 2025-06-01T00:00:00Z AND CreatedDate < 2025-07-01T00:00:00Z  GROUP BY StepNodeId,ProcessInstance.SubmittedById];
         List<ProcessNode> tatStep = [Select id, Name, ProcessDefinition.Name from ProcessNode where ProcessDefinition.Name = 'Deviation approval2'];
         List<ProcessNode> tatStepTL = [Select id, Name, ProcessDefinition.Name from ProcessNode where ProcessDefinition.Name = 'Deviation approval2 for TL']; */
         //number of referral 
         List<User> getAllUser = [select id, Name from User where IsActive = true ];
         //List<AggregateResult> referencesGeneratedBySM = [select Count(id), EYI_Referral_Employee__c from EYI_Customer_Information_Form__c where ((EYI_Walk_in_Source__c = 'Referral' AND EYI_Walk_in_Sub_source__c ='Employee' ) OR (EYI_Walk_in_Source__c = 'SM Self Sourcing'))  GROUP BY EYI_Referral_Employee__c];
         List<AggregateResult> referencesGeneratedBySM = [Select Count(id) totalCount,EYI_Sourcing_Manager__c From Opportunity where ((EYI_Walk_in_Source__c = 'Referral' AND EYI_Walk_in_Sub_source__c ='Employee' ) OR (EYI_Walk_in_Source__c = 'SM Self Sourcing')) AND EYI_Sourcing_Manager__c != null  AND CreatedDate = THIS_MONTH  GROUP BY EYI_Sourcing_Manager__c ];
         List<AggregateResult> referencesGeneratedBySMWIthPrimaryOwner = [Select Count(id) totalCount,OwnerID From Opportunity where ((EYI_Walk_in_Source__c = 'Referral' AND EYI_Walk_in_Sub_source__c ='Employee' ) OR (EYI_Walk_in_Source__c = 'SM Self Sourcing')) AND EYI_Sourcing_Manager__c = null AND CreatedDate = THIS_MONTH  GROUP BY OwnerID ];
         for(User us : getAllUser) {
            userNameWithId.put(us.Name, us.Id);
         }
        /* for(ProcessNode node : tatStep) {
            stepNameMap.put(node.Id, node.Name);
         }
         for(ProcessNode node : tatStepTL) {
            stepNameMapTL.put(node.Id, node.Name);
         } */
         //Number of references generated by the Sales Manager
         for (AggregateResult ar : referencesGeneratedBySM) {
                 	String key = (Id)ar.get('EYI_Sourcing_Manager__c') + '_' + 'Number of references generated by the Sales Manager';
            		Integer count = (Integer)ar.get('totalCount');
                 if (monthlyTargetMapValues.containsKey(key)) {
                     if(achievementCounts.containsKey(monthlyTargetMapValues.get(key))){
                         achievementCounts.put(monthlyTargetMapValues.get(key),achievementCounts.get(monthlyTargetMapValues.get(key)) + count);
                     }else{
                         achievementCounts.put(monthlyTargetMapValues.get(key), count);
                     }
                       
                	
            	}   
        }
         for (AggregateResult ar : referencesGeneratedBySMWIthPrimaryOwner) {
                 	String key = (Id)ar.get('OwnerId') + '_' + 'Number of references generated by the Sales Manager';
            		Integer count = (Integer)ar.get('totalCount');
                 if (monthlyTargetMapValues.containsKey(key)) {
                	if(achievementCounts.containsKey(monthlyTargetMapValues.get(key))){
                         achievementCounts.put(monthlyTargetMapValues.get(key),achievementCounts.get(monthlyTargetMapValues.get(key)) + count);
                     }else{
                         achievementCounts.put(monthlyTargetMapValues.get(key), count);
                     }
            	}   
        }
         
		//Cancel count
		/*for (AggregateResult ar : totalCancellationApprovedOpp) {
            String key = (Id)ar.get('OwnerId') + '_' + 'Cancellation Count';
            Integer count = (Integer)ar.get('totalCount');
            if (monthlyTargetMapValues.containsKey(key)) {
                achievementCounts.put(monthlyTargetMapValues.get(key), count);
            } 
        }*/
         
         
         //total no of EOI's
         for (AggregateResult ar : totalNumberOfEOI) {
            String key = (Id)ar.get('OwnerId') + '_' + 'Number of EOIs';
            String key2 = (Id)ar.get('OwnerId') + '_' + 'EOI Conversions';
            Integer count = (Integer)ar.get('totalCount');
             totaEOICreated.put(key2,count);
            if (monthlyTargetMapValues.containsKey(key)) {
                achievementCounts.put(monthlyTargetMapValues.get(key), count);
            } 
        }
       /*  //total no of EOI's conversation
         for (AggregateResult ar : totalNumberOfEOIConversion) {
            String key = (Id)ar.get('OwnerId') + '_' + 'EOI Conversions';
            Integer count = (Integer)ar.get('totalCount');
            if (monthlyTargetMapValues.containsKey(key)) {
                Integer percentage = (Integer) Math.round(((double) count / totaEOICreated.get(key)) * 100);
                achievementCounts.put(monthlyTargetMapValues.get(key), percentage);
            } 
        } */
         /*
         //average follow Up
         for (AggregateResult ar : totalFollowUpAggResults) {
            String key = (Id)ar.get('OwnerId') + '_' + 'Average Follow-Ups';
             String key2 = (Id)ar.get('OwnerId') + '_' + 'Follow-ups missed';
             String key3 = (Id)ar.get('OwnerId') + '_' + 'Follow-up by CTI';
            Integer count = (Integer)ar.get('totalCount');
             totaFollowUpMissed.put(key2,count);
             totaFollowUpMissed.put(key3,count);
            if (monthlyTargetMapValues.containsKey(key)) {
                achievementCounts.put(monthlyTargetMapValues.get(key), (count/30));
            } 
        }
         //for missed follow up
        for (AggregateResult ar : followUpMissedAggResults) {
            String key = (Id)ar.get('OwnerId') + '_' + 'Follow-ups missed';
            Integer count = (Integer)ar.get('totalCount');
            if (monthlyTargetMapValues.containsKey(key)) {
                Integer percentage = (Integer) Math.round(((double) count / totaFollowUpMissed.get(key)) * 100);
                achievementCounts.put(monthlyTargetMapValues.get(key),percentage);
            } 
        } */
         /*
         //for followup done by CTI
         for (AggregateResult ar : totalCTIFollowUpAggResults) {
            String key = (Id)ar.get('OwnerId') + '_' + 'Follow-up by CTI';
            Integer count = (Integer)ar.get('totalCount');
            if (monthlyTargetMapValues.containsKey(key)) {
                Integer percentage = (Integer) Math.round(((double) count / totaFollowUpMissed.get(key)) * 100);
                achievementCounts.put(monthlyTargetMapValues.get(key),percentage );
            } 
        }
		*/
        //totla opp        
        for (AggregateResult ar : totalOppCreatedResults) {
           
            String key4 = (Id)ar.get('OwnerId') + '_' + 'Walk-in to Booking Conversion';
            String key3 = (Id)ar.get('OwnerId') + '_' + 'Re-visit (Unique revisits / Total revisits)';
            String key2 = (Id)ar.get('OwnerId') + '_' + 'Number of Cases Where the Cooling Period is Extended';
            Integer count = (Integer)ar.get('totalCount');
            
            totaOppCreated.put(key2,count);
            totaOppCreated.put(key3,count);
            totaOppCreated.put(key4,count);
            
        }
         //walkIn to booking ratio
        for (AggregateResult ar : totalBookingResults) {
            String key = (Id)ar.get('OwnerId') + '_' + 'Walk-in to Booking Conversion';
             String key2 = (Id)ar.get('OwnerId') + '_' + 'Booking from Cold/Lost leads';
            String key3 = (Id)ar.get('OwnerId') + '_' + 'Average TAT from Walk-in to Booking';
            
            Integer count = (Integer)ar.get('totalCount');
            totaOppCreated.put(key2,count);
            totaOppCreated.put(key3,count);
            if (monthlyTargetMapValues.containsKey(key)) {
                Integer percentage = (Integer) Math.round(((double) count / totaOppCreated.get(key)) * 100);
                achievementCounts.put(monthlyTargetMapValues.get(key), percentage);
            } 
        }
         /*
         //Booking from Cold/Lost leads 

        for (AggregateResult ar : totalColdLostBookingResults) {
            String key = (Id)ar.get('OwnerId') + '_' + 'Booking from Cold/Lost leads';
            Integer count = (Integer)ar.get('totalCount');
            if (monthlyTargetMapValues.containsKey(key)) {
                Integer percentage = (Integer) Math.round(((double) count / totaOppCreated.get(key)) * 100);
                achievementCounts.put(monthlyTargetMapValues.get(key), percentage);
            } 
        }
        //oppwalkInBookingTAT
         for (AggregateResult ar : oppWalkToBookedResults) {
            String key = (Id)ar.get('OwnerId') + '_' + 'Average TAT from Walk-in to Booking';
            Integer count = ((Decimal)ar.get('totalCount')).intValue();
            if (monthlyTargetMapValues.containsKey(key)) {
                achievementCounts.put(monthlyTargetMapValues.get(key), count/totaOppCreated.get(key));
            } 
        }
        //No of EOI Conversion
        
        //coolingPeriodExtension
        for (AggregateResult ar : totalCoolingPeriodExtResults) {
            String key = (Id)ar.get('OwnerId') + '_' + 'Number of Cases Where the Cooling Period is Extended';
            Integer count = (Integer)ar.get('totalCount');
            if (monthlyTargetMapValues.containsKey(key)) {
                Integer percentage = (Integer) Math.round(((double) count / totaOppCreated.get(key)) * 100);
                achievementCounts.put(monthlyTargetMapValues.get(key), percentage);
            } 
        }
        //ApprovalTAT
        for (AggregateResult ar : totalApprovalTAT) {
            if(stepNameMap.get((Id)ar.get('StepNodeId')) == 'TL Approval'){
                String key = (Id)ar.get('ActorId') + '_' + 'L1 TAT Approval';
            	//Decimal count = (Integer)ar.get('totalCount');
                Integer count = ((Decimal)ar.get('totalCount')).intValue();
                if (monthlyTargetMapValues.containsKey(key)) {
                achievementCounts.put(monthlyTargetMapValues.get(key), count);
                }
            } 
            if(stepNameMap.get((Id)ar.get('StepNodeId')) == 'Functional Head Approval'){
                String key2 = (Id)ar.get('ActorId') + '_' + 'L2 TAT Approval';
            	Integer count2 = ((Decimal)ar.get('totalCount')).intValue();
                if (monthlyTargetMapValues.containsKey(key2)) {
                achievementCounts.put(monthlyTargetMapValues.get(key2), count2);
                }     
            } 
            if(stepNameMap.get((Id)ar.get('StepNodeId')) == 'Final Approval'){
                String key3 = (Id)ar.get('ActorId') + '_' + 'L3 TAT Approval';
            	Integer count3 = ((Decimal)ar.get('totalCount')).intValue();
                if (monthlyTargetMapValues.containsKey(key3)) {
                achievementCounts.put(monthlyTargetMapValues.get(key3), count3);
                }
            }     
        }
        for (AggregateResult ar : totalApprovalTATTL) {
            
            if(stepNameMapTL.get((Id)ar.get('StepNodeId')) == 'Functional Head Approval'){
                String key2 = (Id)ar.get('ActorId') + '_' + 'L2 TAT Approval';
            	Integer count2 = ((Decimal)ar.get('totalCount')).intValue();
                if (monthlyTargetMapValues.containsKey(key2)) {
                    if(achievementCounts.containsKey(monthlyTargetMapValues.get(key2))){
                        achievementCounts.put(monthlyTargetMapValues.get(key2),achievementCounts.get(monthlyTargetMapValues.get(key2)) + count2);
                    }else{
                        achievementCounts.put(monthlyTargetMapValues.get(key2), count2);
                    }
                
                }     
            } 
            if(stepNameMapTL.get((Id)ar.get('StepNodeId')) == 'Final Approval'){
                String key3 = (Id)ar.get('ActorId') + '_' + 'L3 TAT Approval';
            	Integer count3 = ((Decimal)ar.get('totalCount')).intValue();
                if (monthlyTargetMapValues.containsKey(key3)) {
                    if(achievementCounts.containsKey(monthlyTargetMapValues.get(key3))){
                        achievementCounts.put(monthlyTargetMapValues.get(key3),achievementCounts.get(monthlyTargetMapValues.get(key3)) + count3);
                    }else{
                        achievementCounts.put(monthlyTargetMapValues.get(key3), count3);
                    }
                //achievementCounts.put(monthlyTargetMapValues.get(key3), count3);
                }
            }     
        } 
        for (AggregateResult ar : totalFollowUpAggResults) {
            String key = (Id)ar.get('OwnerId') + '_' + 'Average Follow-Ups';
             String key2 = (Id)ar.get('OwnerId') + '_' + 'Follow-ups missed';
            Integer count = (Integer)ar.get('totalCount');
             totaFollowUpMissed.put(key2,count);
            if (monthlyTargetMapValues.containsKey(key)) {
                achievementCounts.put(monthlyTargetMapValues.get(key), (count/30));
            } 
        } */
         //Revist
       for (AggregateResult ar : totalRevisitedOpp) {
            String key = (Id)ar.get('OwnerId') + '_' + 'Re-visit (Unique revisits / Total revisits)';
            Integer count = (Integer)ar.get('totalCount');
            if (monthlyTargetMapValues.containsKey(key)) {
                Integer percentage = (Integer) Math.round(((double) count / totaOppCreated.get(key)) * 100);
                achievementCounts.put(monthlyTargetMapValues.get(key), percentage);
            } 
        }
         List<EYI_Target_Management__c> updateAchievements =  new List<EYI_Target_Management__c>();
        for(String key:achievementCounts.keySet()){
            EYI_Target_Management__c updatetm = new EYI_Target_Management__c();
            updatetm.Id  = key;
            updatetm.EYI_Achivements__c = achievementCounts.get(key);
            updateAchievements.add(updatetm);
        }
        update updateAchievements;
        //lead to walkInRation
        
		system.debug('achievementCounts'+achievementCounts);
     }
         
     
    global void finish(Database.BatchableContext BC) {
    	System.debug('Batch processing completed.');
    } 

}