force-app/main/default/objects/EYI_Customer_Information_Form__c/EYI_Customer_Information_Form__c.object-meta.xml
<CustomObject>
    <label>CIF Records</label>
    <nameField>
        <displayFormat>CIF-{0000}</displayFormat>
        <label>Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CIF Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>EYI_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>CIF Records</relationshipLabel>
    <relationshipName>CIF_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Sourcing_Manager__c.field-meta.xml
<CustomField>
    <fullName>EYI_Sourcing_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sourcing Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CIF_Form</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/EYI_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Sourcing_Manager__c.field-meta.xml
<CustomField>
    <fullName>EYI_Sourcing_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sourcing Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_REC__c/EYI_REC__c.object-meta.xml
<CustomObject>
    <label>REC Account</label>
    <nameField>
        <label>REC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REC Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_REC__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>REC Accounts</relationshipLabel>
    <relationshipName>REC_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Target_Management__c/EYI_Target_Management__c.object-meta.xml
<CustomObject>
    <label>Target Management</label>
    <nameField>
        <displayFormat>TM-{000}</displayFormat>
        <label>Target Management Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Managements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Target_Management__c/fields/EYI_Achivements__c.field-meta.xml
<CustomField>
    <fullName>EYI_Achivements__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Achivements</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Target_Management__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Target Managements</relationshipLabel>
    <relationshipName>Target_Managements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Target_Management__c/fields/EYI_Target_End_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Target_End_Date__c</fullName>
    <label>Target End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Target_Management__c/fields/EYI_Target_KPI__c.field-meta.xml
<CustomField>
    <fullName>EYI_Target_KPI__c</fullName>
    <label>Target KPI</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>EYI_Target_Module__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Follow-up by CTI</fullName>
                <label>Follow-up by CTI (%)</label>
            </value>
            <value>
                <fullName>Walk-in to Booking Conversion</fullName>
                <label>Walk-in to Booking Conversion (%)</label>
            </value>
            <value>
                <fullName>Number of EOIs</fullName>
            </value>
            <value>
                <fullName>EOI Conversions</fullName>
                <label>EOI Conversions (%)</label>
            </value>
            <value>
                <fullName>Revenue Target</fullName>
            </value>
            <value>
                <fullName>Meeting Target</fullName>
            </value>
            <value>
                <fullName>New CP Empanelment</fullName>
            </value>
            <value>
                <fullName>Walkin Achieved</fullName>
            </value>
            <value>
                <fullName>VC/VP Target</fullName>
            </value>
            <value>
                <fullName>REC Calls by SM</fullName>
            </value>
            <value>
                <fullName>Visit Confirmed</fullName>
            </value>
            <value>
                <fullName>Visit Done</fullName>
            </value>
            <value>
                <fullName>Average Talk Time</fullName>
                <label>Total Talk Time (In Minutes)</label>
            </value>
            <value>
                <fullName>Lead to Walk-In Conversion ratio</fullName>
            </value>
            <value>
                <fullName>Total Outbound Calls to be Done</fullName>
            </value>
            <value>
                <fullName>Total Inbound Calls Completed</fullName>
            </value>
            <value>
                <fullName>Re-visit (Unique revisits / Total revisits)</fullName>
                <label>Re-visit (Unique revisits / Total revisits) (%)</label>
            </value>
            <value>
                <fullName>Average Follow-Ups</fullName>
                <isActive>false</isActive>
                <label>Average Follow-Ups (Per Day)</label>
            </value>
            <value>
                <fullName>Average TAT from Walk-in to Booking</fullName>
                <isActive>false</isActive>
                <label>Average TAT from Walk-in to Booking</label>
            </value>
            <value>
                <fullName>Booking from Cold/Lost leads</fullName>
                <isActive>false</isActive>
                <label>Booking from Cold/Lost leads (%)</label>
            </value>
            <value>
                <fullName>Cancellation Count</fullName>
                <isActive>false</isActive>
                <label>Cancellation Count</label>
            </value>
            <value>
                <fullName>Follow-ups missed</fullName>
                <isActive>false</isActive>
                <label>Follow-ups missed (%)</label>
            </value>
            <value>
                <fullName>L1 TAT Approval</fullName>
                <isActive>false</isActive>
                <label>L1 TAT Approval  (In Minutes)</label>
            </value>
            <value>
                <fullName>L2 TAT Approval</fullName>
                <isActive>false</isActive>
                <label>L2 TAT Approval (In Minutes)</label>
            </value>
            <value>
                <fullName>L3 TAT Approval</fullName>
                <isActive>false</isActive>
                <label>L3 TAT Approval (In Minutes)</label>
            </value>
            <value>
                <fullName>Number of Cases Where the Cooling Period is Extended</fullName>
                <isActive>false</isActive>
                <label>Number of Cases Where the Cooling Period is Extended (%)</label>
            </value>
            <value>
                <fullName>Number of references generated by the Sales Manager</fullName>
                <isActive>false</isActive>
                <label>Number of references generated by the Sales Manager (%)</label>
            </value>
            <value>
                <fullName>Revenue (Project-Wise Revenue Target in Crore)</fullName>
                <isActive>false</isActive>
                <label>Revenue (Project-Wise Revenue Target in Crore)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Target_Management__c/fields/EYI_Target_Module__c.field-meta.xml
<CustomField>
    <fullName>EYI_Target_Module__c</fullName>
    <label>Target Module</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Presales</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Sourcing</fullName>
            </value>
            <value>
                <fullName>Revenue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Target_Management__c/fields/EYI_Target_Month_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Target_Month_Date__c</fullName>
    <label>Target Month Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Target_Management__c/fields/EYI_Target_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Target_Start_Date__c</fullName>
    <label>Target Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Target_Management__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Target Managements</relationshipLabel>
    <relationshipName>Target_Managements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_VP_VC__c/EYI_VP_VC__c.object-meta.xml
<CustomObject>
    <label>VP/VC</label>
    <nameField>
        <displayFormat>VP/VC - {00000}</displayFormat>
        <label>VP/VC Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VP/VC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_VP_VC__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>VP/VC</relationshipLabel>
    <relationshipName>VP_VC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EYI_SourcingTargetsAchievementBatch.cls
public with sharing class EYI_SourcingTargetsAchievementBatch implements Database.Batchable<sObject>, Database.Stateful {
    public Database.QueryLocator start(Database.BatchableContext BC){
        Integer fiscalStartMonth = Integer.ValueOf(System.Label.EYI_FINANCIAL_START_MONTH); // April
        Date today = Date.today();
        Integer fiscalYear;

        if (today.month() >= fiscalStartMonth) {
            fiscalYear = today.year() + 1;
        } else {
            fiscalYear = today.year();
        }

        // Fiscal year starts in April of the previous calendar year
        Integer fiscalStartYear = fiscalYear - 1;

        Date fiscalStart = Date.newInstance(fiscalStartYear, fiscalStartMonth, 1);
        Date fiscalEnd = fiscalStart.addYears(1).addDays(-1);
        return Database.getQueryLocator([
            SELECT Id, Name, OwnerId, EYI_Project__c, EYI_Target_Module__c,
                EYI_Achivements__c, EYI_Target_KPI__c, EYI_Tower__c, EYI_Target_Month_Date__c ,EYI_Target_Start_Date__c,EYI_Target_End_Date__c
            FROM EYI_Target_Management__c
            WHERE EYI_Target_Start_Date__c >= :fiscalStart
            AND EYI_Target_End_Date__c <= :fiscalEnd
            AND EYI_Target_KPI__c != 'Revenue Target'
            AND EYI_Target_Module__c = 'Sourcing'
        ]);

    }

    public void execute(Database.BatchableContext BC, List<EYI_Target_Management__c> targetList){
        Set<Id> ownerIdSet =  new Set<Id>();
        Map<String,EYI_Target_Management__c> monthlyTargetMap = new Map<String,EYI_Target_Management__c>();
        Date monthStart;
        Date monthEnd;
        if(targetList.size() >0){
            EYI_Target_Management__c sampleRecord = targetList[0]; // Since batch size is 1
            monthStart = sampleRecord.EYI_Target_Start_Date__c;
            monthEnd = sampleRecord.EYI_Target_End_Date__c;
            for(EYI_Target_Management__c target:targetList){
                ownerIdSet.add(target.OwnerId);
                if(target.OwnerId != null && target.EYI_Target_KPI__c != null){
                    String key = target.OwnerId + '_' + target.EYI_Target_KPI__c;
                    monthlyTargetMap.put(key,target);
                }
            }
        }
        if (!ownerIdSet.isEmpty()) {
            AggregateResult[] groupedResults = [
                SELECT OwnerId, COUNT(Id) total
                FROM EYI_VP_VC__c
                WHERE OwnerId IN :ownerIdSet
                AND CreatedDate >= :monthStart
                AND CreatedDate <= :monthEnd
                GROUP BY OwnerId
            ];

            for (AggregateResult ar : groupedResults) {
                Id ownerId = (Id) ar.get('OwnerId');
                Integer count = (Integer) ar.get('total');
                String key = ownerId + '_' + 'VC/VP Target';
                EYI_Target_Management__c target = monthlyTargetMap.get(key);
                if(target != null && target.EYI_Target_KPI__c == 'VC/VP Target'){
                    target.EYI_Achivements__c = count;
                }
            }

            Map<String, Integer> managerToCIFCount = new Map<String, Integer>();

            List<EYI_Customer_Information_Form__c> cifList = [SELECT Id, EYI_Opportunity__r.EYI_Sourcing_Manager__c, EYI_Opportunity__r.EYI_Walk_in_Source__c
                                                , CreatedDate ,EYI_Opportunity__r.EYI_Project_Tower_Enquired__c
                                                  FROM EYI_Customer_Information_Form__c
                                                  WHERE EYI_Opportunity__r.EYI_Sourcing_Manager__c IN :ownerIdSet
                                                  AND EYI_Opportunity__r.EYI_Walk_in_Source__c = 'PREC'
                                                  AND CreatedDate >= :monthStart
                                                  AND CreatedDate <= :monthEnd];

            for (EYI_Customer_Information_Form__c cif : cifList) {
                String key = cif.EYI_Opportunity__r.EYI_Sourcing_Manager__c + '_Walkin Achieved';
                if (managerToCIFCount.containsKey(key)) {
                    managerToCIFCount.put(key, managerToCIFCount.get(key) + 1);
                } else {
                    managerToCIFCount.put(key, 1);
                }
            }

            for(String key : managerToCIFCount.keySet()) {
                EYI_Target_Management__c target = monthlyTargetMap.get(key);
                if(target != null && target.EYI_Target_KPI__c == 'Walkin Achieved'){
                    target.EYI_Achivements__c = managerToCIFCount.get(key);
                }
            }
            System.debug('managerToCIFCount===> '+monthlyTargetMap);
            System.debug('managerToCIFCount===> '+managerToCIFCount.values());

            // AggregateResult[] groupedCIFResults = [
            //     SELECT EYI_Sourcing_Manager__c, COUNT(Id) formCount
            //     FROM EYI_Customer_Information_Form__c
            //     WHERE EYI_Sourcing_Manager__c IN :ownerIdSet
            //     AND EYI_Opportunity__r.EYI_Walk_in_Source__c = 'PREC'
            //     AND CreatedDate >= :monthStart
            //     AND CreatedDate <= :monthEnd
            //     GROUP BY EYI_Sourcing_Manager__c
            // ];

            // for (AggregateResult ar : groupedCIFResults) {
            //     Id managerId = (Id) ar.get('EYI_Sourcing_Manager__c');
            //     Integer count = (Integer) ar.get('formCount');
            //     String key = managerId + '_' + 'Walkin Achieved';
            //     EYI_Target_Management__c target = monthlyTargetMap.get(key);
            //     if(target != null && target.EYI_Target_KPI__c == 'Walkin Achieved'){
            //         target.EYI_Achivements__c = count;
            //     }
            // }



            AggregateResult[] groupedRECResults = [
                SELECT OwnerId, COUNT(Id) total
                FROM EYI_REC__c
                WHERE OwnerId IN :ownerIdSet
                AND CreatedDate >= :monthStart
                AND CreatedDate <= :monthEnd
                GROUP BY OwnerId
            ];

            for (AggregateResult ar : groupedRECResults) {
                Id ownerId = (Id) ar.get('OwnerId');
                Integer count = (Integer) ar.get('total');
                String key = ownerId + '_' + 'New CP Empanelment';
                EYI_Target_Management__c target = monthlyTargetMap.get(key);
                if(target != null && target.EYI_Target_KPI__c == 'New CP Empanelment'){
                    target.EYI_Achivements__c = count;
                }
            }

            AggregateResult[] taskResults = [
                SELECT OwnerId, COUNT(Id) taskCount
                FROM Task
                WHERE EYI_REC_Account__c != null
                AND OwnerId IN :ownerIdSet
                AND EYI_Meeting_Status__c != null
                AND CreatedDate >= :monthStart
                AND CreatedDate <= :monthEnd
                AND EYI_Meeting_Status__c  = 'Completed'
                GROUP BY OwnerId
            ];

            for (AggregateResult ar : taskResults) {
                Id ownerId = (Id) ar.get('OwnerId');
                Integer count = (Integer) ar.get('taskCount');
                String key = ownerId + '_' + 'Meeting Target';
                EYI_Target_Management__c target = monthlyTargetMap.get(key);
                if(target != null && target.EYI_Target_KPI__c == 'Meeting Target'){
                    target.EYI_Achivements__c = count;
                }
            }

            System.debug('monthlyTargetMap ==> '+monthlyTargetMap.values());
        }
        if(monthlyTargetMap!=null){
            update monthlyTargetMap.values();
        }
    }

    public void finish(Database.BatchableContext BC){
        Database.executebatch(new EYI_RevenueAchievementBatch());
    }
}