force-app/main/default/objects/EYI_Customer_Information_Form__c/EYI_Customer_Information_Form__c.object-meta.xml
<CustomObject>
    <label>CIF Records</label>
    <nameField>
        <displayFormat>CIF-{0000}</displayFormat>
        <label>Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CIF Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Closing_Manager__c.field-meta.xml
<CustomField>
    <fullName>EYI_Closing_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Closing Manager</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Please tag a valid closing sales manager</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Sales</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Leasing</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Customer_Information_Form1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Email_Id__c.field-meta.xml
<CustomField>
    <fullName>EYI_Email_Id__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_First_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Lead_Enquiry__c.field-meta.xml
<CustomField>
    <fullName>EYI_Lead_Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Enquiry</label>
    <referenceTo>EYI_Lead_Enquiry__c</referenceTo>
    <relationshipLabel>CIF Records</relationshipLabel>
    <relationshipName>CIF_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Mobile_number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Mobile_number__c</fullName>
    <label>Mobile number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>EYI_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>CIF Records</relationshipLabel>
    <relationshipName>CIF_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Project_Enquired__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Enquired__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Enquired</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipName>CIF</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_Property__c.field-meta.xml
<CustomField>
    <fullName>EYI_Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>46 Banyan Tree</fullName>
            </value>
            <value>
                <fullName>86 Banyan Tree</fullName>
            </value>
            <value>
                <fullName>Avant Garde</fullName>
            </value>
            <value>
                <fullName>Balewadi</fullName>
            </value>
            <value>
                <fullName>Casa 9</fullName>
            </value>
            <value>
                <fullName>Central Park</fullName>
            </value>
            <value>
                <fullName>ELEVEN WEST</fullName>
            </value>
            <value>
                <fullName>EON Waterfront II</fullName>
            </value>
            <value>
                <fullName>Eon Waterfront PH I</fullName>
            </value>
            <value>
                <fullName>Forest Castle</fullName>
            </value>
            <value>
                <fullName>Futura</fullName>
            </value>
            <value>
                <fullName>Generic</fullName>
            </value>
            <value>
                <fullName>Gold Craft</fullName>
            </value>
            <value>
                <fullName>Golden Bell</fullName>
            </value>
            <value>
                <fullName>New Commercial</fullName>
            </value>
            <value>
                <fullName>New Residential</fullName>
            </value>
            <value>
                <fullName>Ocean Tower</fullName>
            </value>
            <value>
                <fullName>One North</fullName>
            </value>
            <value>
                <fullName>Panchshil Avenue</fullName>
            </value>
            <value>
                <fullName>Panchshil Towers</fullName>
            </value>
            <value>
                <fullName>Queens Court</fullName>
            </value>
            <value>
                <fullName>Satellite Towers</fullName>
            </value>
            <value>
                <fullName>SoHo</fullName>
            </value>
            <value>
                <fullName>Ssilverwoods</fullName>
            </value>
            <value>
                <fullName>The Address</fullName>
            </value>
            <value>
                <fullName>The Chambers</fullName>
            </value>
            <value>
                <fullName>The Golden Bell II</fullName>
            </value>
            <value>
                <fullName>Trump Towers</fullName>
            </value>
            <value>
                <fullName>Waterfront</fullName>
            </value>
            <value>
                <fullName>WestView</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Customer_Information_Form__c/fields/EYI_REC_Account__c.field-meta.xml
<CustomField>
    <fullName>EYI_REC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>REC Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>EYI_REC__c.EYI_REC_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EYI_REC__c</referenceTo>
    <relationshipLabel>CIF Records</relationshipLabel>
    <relationshipName>CIF_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Conversion_Metadata__mdt/EYI_Lead_Conversion_Metadata__mdt.object-meta.xml
<CustomObject>
    <label>Lead Conversion Metadata</label>
    <pluralLabel>Lead Conversion Metadata</pluralLabel>
</CustomObject>

force-app/main/default/objects/EYI_Lead_Conversion_Metadata__mdt/fields/EYI_LeadEnquiryVsOppField__c.field-meta.xml
<CustomField>
    <fullName>EYI_LeadEnquiryVsOppField__c</fullName>
    <label>LeadEnquiryVsOppField</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/EYI_Lead_Enquiry__c.object-meta.xml
<CustomObject>
    <label>Lead Enquiry</label>
    <nameField>
        <label>Lead Entries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Enquiries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Alternate_Email__c.field-meta.xml
<CustomField>
    <fullName>EYI_Alternate_Email__c</fullName>
    <label>Secondary Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_AutomationBypassDatetime__c.field-meta.xml
<CustomField>
    <fullName>EYI_AutomationBypassDatetime__c</fullName>
    <description>This is to start the time for automation, for bypassing the validations</description>
    <label>AutomationBypassDatetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Closing_Manager__c.field-meta.xml
<CustomField>
    <fullName>EYI_Closing_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Closing Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Lead_Enquiries2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Email__c.field-meta.xml
<CustomField>
    <fullName>EYI_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>EYI_Lead_Status__c</fullName>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Follow Up</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Visit Proposed</fullName>
            </value>
            <value>
                <fullName>Visit Confirmed</fullName>
            </value>
            <value>
                <fullName>Visit Done</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Non-contactable</fullName>
                <label>Non-Contactable</label>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>REC</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
                <isActive>false</isActive>
                <label>Converted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>EYI_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Lead Enquiries</relationshipLabel>
    <relationshipName>Lead_Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_Project_Enquired__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Enquired__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Enquired</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>EYI_Project__c.EYI_Project_Property_Type__c</field>
            <operation>equals</operation>
            <valueField>$Source.EYI_Segment__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Lead Enquiries</relationshipLabel>
    <relationshipName>Lead_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Lead_Enquiry__c/fields/EYI_REC_Account__c.field-meta.xml
<CustomField>
    <fullName>EYI_REC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>REC Account</label>
    <referenceTo>EYI_REC__c</referenceTo>
    <relationshipLabel>Lead Enquiries</relationshipLabel>
    <relationshipName>Lead_Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/EYI_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Project__c/fields/EYI_Opportunity_TAT__c.field-meta.xml
<CustomField>
    <fullName>EYI_Opportunity_TAT__c</fullName>
    <label>Opportunity TAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EYI_LeadConvertionClass.cls
public with sharing class EYI_LeadConvertionClass {
    public EYI_LeadConvertionClass() {

    }
    @AuraEnabled
    public static void updateLeadOnCIF(String cifId, String recId, String leadEnquiryId,String opptId) {
        EYI_Customer_Information_Form__c cifRecord = new EYI_Customer_Information_Form__c();
        System.debug(
            'cifId==> ' +
            cifId +
            ' recId==> ' +
            recId +
            ' leadEnquiryId==> ' +
            leadEnquiryId
            + 
            ' opptId==> ' +
            opptId  );

        try {
            cifRecord.Id = cifId;
            cifRecord.EYI_REC_Account__c = recId;
            cifRecord.EYI_Lead_Enquiry__c = leadEnquiryId;
            cifRecord.EYI_Opportunity__c = opptId;
            System.debug('before cif update ===>'+cifRecord);
            update cifRecord;
            // if(recId != null && recId!= ''){
            //     updateRECOnLeadEnquiry(recId,leadEnquiryId);
            // }
            System.debug('after cif update ===>'+cifRecord);
        } catch (Exception e) {
            System.debug('Error updating Lead on Opportunity: ' + e.getMessage());
            System.debug(' cif update failed ===>'+cifRecord);

            throw new AuraHandledException('exceptionText' + e.getMessage() + ' : ' + e.getLineNumber() + ' :');
        }
    }

    
    // @AuraEnabled
    // public static void updateRECOnLeadEnquiry(String recId,String leadEnquiryId){
    //     EYI_Lead_Enquiry__c leadEnq = new EYI_Lead_Enquiry__c();
    //     try {
    //         leadEnq.Id = leadEnquiryId;
    //         leadEnq.EYI_REC_Account__c = recId;
    //         leadenq.EYI_AutomationBypassDatetime__c = System.now();
    //         leadenq.EYI_Lead_Status__c = 'Visit Done';
    //         update leadEnq;
    //     } catch (Exception e) {
    //         System.debug('Error updating Lead on Opportunity: ' + e.getMessage());
    //     }
    // }
    @AuraEnabled
    public static void updatesOnLeadEnquiry(String oppId,String leadEnquiryId,String recId){
        System.debug('leadEnquiryId==>'+leadEnquiryId);
        System.debug('oppId==>'+oppId);
        System.debug('recId==>'+recId);

        EYI_Lead_Enquiry__c leadEnq = new EYI_Lead_Enquiry__c();
        try {
            leadEnq.Id = leadEnquiryId;
            leadEnq.EYI_Opportunity__c = oppId;
            leadEnq.EYI_REC_Account__c = recId;
            leadenq.EYI_Lead_Status__c = 'Visit Done';
            leadenq.EYI_AutomationBypassDatetime__c = System.now();
            update leadEnq;
        } catch (Exception e) {
            Opportunity opp = new Opportunity();
            opp.Id=oppId;
            opp.Error_Message_LWC__c=e.getMessage() + 'LeadEnqId- '+ leadEnquiryId;
            update opp;
            System.debug('Error updating Lead on Opportunity: ' + e.getMessage());
        }
    }

    @AuraEnabled
    public static String convertLeadEnquiryToOpp(String CIFId){
        system.debug('check convertleadEnquiry');
        List<EYI_Lead_Conversion_Metadata__mdt> customMetadataRecords = getAllCustomMetadata('Lead_Conversion', 'EYI_Lead_Conversion_Metadata__mdt');
        List<String> valuesList = new List<String>();
        Map<String,String> valuesMap = new Map<String,String>();
        List<String> allFieldCIF = new List<String>();
        List<String> phoneNumber = new List<String>();
        List<String> emailIds = new List<String>();
        for (EYI_Lead_Conversion_Metadata__mdt record : customMetadataRecords) {
            String commaSeparatedValue = record.EYI_LeadEnquiryVsOppField__c; // Replace with your actual field name
            valuesList = commaSeparatedValue.split(',');
        }    
        for (String value : valuesList) {
            List<String> keyValue = value.split(':');
            if (keyValue.size() == 2) {
                allFieldCIF.add(keyValue[0].trim());
                valuesMap.put(keyValue[0].trim(), keyValue[1].trim());
            }
        }
        system.debug('valuesMap'+valuesMap);
        List<EYI_Customer_Information_Form__c> cifRecord =getCIFData(CIFId,allFieldCIF);
        for (EYI_Customer_Information_Form__c cif : cifRecord) {
            if(cif.EYI_Mobile_number__c != null && cif.EYI_Mobile_number__c != ''){
                phoneNumber.add(cif.EYI_Mobile_number__c);
            }
            if(cif.EYI_Email_Id__c != null && cif.EYI_Email_Id__c != ''){
                emailIds.add(cif.EYI_Email_Id__c);
            }
            
           
        }
        List<EYI_Project__c> getOppTAT = [Select Id, EYI_Opportunity_TAT__c from EYI_Project__c where Id =: cifRecord[0].EYI_Project_Enquired__c];
        List<Account> getAccounts = [Select Id,Phone,EYI_Email__c from Account where Phone IN:phoneNumber OR EYI_Email__c IN:emailIds];
        List<Opportunity> oppRecordsInsert = new List<Opportunity>();
        Account newAccount = new Account();
        if(getAccounts.isEmpty()){
            
            newAccount.Phone = cifRecord[0].EYI_Mobile_number__c;
            newAccount.EYI_Email__c = cifRecord[0].EYI_Email_Id__c;
            newAccount.Name = cifRecord[0].EYI_First_Name__c + ' ' + cifRecord[0].EYI_Last_name__c;
            insert newAccount;
            
        }else{
            newAccount = getAccounts[0];
        }
        Integer closeDate = Integer.valueOf(Label.EYI_Opportunity_Close_Date);
        String currentProfileName = [SELECT Profile.Name FROM User WHERE Id = :UserInfo.getUserId()].Profile.Name;
        for (EYI_Customer_Information_Form__c cif : cifRecord) {
            Opportunity opp = new Opportunity();
            for (String cifField : valuesMap.keySet()) {
                String oppField = valuesMap.get(cifField);
                opp.put(oppField, cif.get(cifField));
                opp.StageName = 'Walk-in';
                //opp.OwnerId = cif.EYI_Closing_Manager__c;
                
                if (currentProfileName == 'Leasing') {
                    opp.OwnerId = UserInfo.getUserId();
                } else {
                	opp.OwnerId = cif.EYI_Closing_Manager__c;
                }

                opp.EYI_AutomationBypassDatetime__c =  System.now();
                opp.EYI_Converted_Lead_Enquiry__c = cif.EYI_Lead_Enquiry__c;
                opp.AccountId = newAccount.Id;
                opp.EYI_CIF_Record__c = cif.Id;
                opp.EYI_Alternate_Email__c = cif.EYI_Email_Id__c;
                opp.Name = cif.EYI_First_Name__c + ' ' + cif.EYI_Last_name__c;
                opp.EYI_First_Name__c = cif.EYI_First_Name__c;
                opp.EYI_Last_Name__c = cif.EYI_Last_name__c;
                opp.EYI_Property__c = cif.EYI_Property__c;
                opp.CloseDate = System.today().addDays((Integer)getOppTAT[0].EYI_Opportunity_TAT__c);
                
            }   
            System.debug('69 EYI_Converted_Lead_Enquiry__c===> '+ cif);
            System.debug('69 EYI_Converted_Lead_Enquiry__c===> '+ opp);

            // Set Opportunity fields based on CIF and other logic
            // opp.Name = cif.Name; // Example field mapping
            // opp.CloseDate = Date.today().addMonths(1); // Example field
            // opp.StageName = 'Prospecting'; // Example field
            oppRecordsInsert.add(opp);
            
        }
        if(!oppRecordsInsert.isEmpty()){
            insert oppRecordsInsert;
        }
        //List<EYI_Lead_Enquiry__c> updateLeadEnquiryOPPId = new List<EYI_Lead_Enquiry__c>();
        // for (EYI_Customer_Information_Form__c cif : cifRecord) {
        //     System.debug('81 EYI_Customer_Information_Form__c===> '+ cif);

        //     cif.EYI_Opportunity__c = oppRecordsInsert[0].Id;
        //     // EYI_Lead_Enquiry__c leadEnqIdMap = new EYI_Lead_Enquiry__c();
        //     // leadEnqIdMap.Id = cif.EYI_Lead_Enquiry__c;
        //     // leadEnqIdMap.EYI_Opportunity__c = oppRecordsInsert[0].Id;
        //     // leadEnqIdMap.EYI_Lead_Status__c = 'Visit Done';
        //     // updateLeadEnquiryOPPId.add(leadEnqIdMap);
        // } 
        // update cifRecord;
        //update updateLeadEnquiryOPPId;
        System.debug('oppRecordsInsert'+oppRecordsInsert[0].Id);
        System.debug('customMetadataRecords'+customMetadataRecords);
        return oppRecordsInsert[0].Id;
    }
    public static List<EYI_Customer_Information_Form__c> getCIFData(String cifIDs,List<String> fieldsToretrive){
        List<EYI_Customer_Information_Form__c> cifRecords= new List<EYI_Customer_Information_Form__c>();
        String query = 'SELECT Id, EYI_Lead_Enquiry__c , EYI_Email_Id__c,EYI_First_Name__c, EYI_Property__c,EYI_Last_name__c, ';
        query += String.join(fieldsToretrive, ', ');
        query += ' FROM EYI_Customer_Information_Form__c WHERE Id = ' + '\''+cifIDs+'\'';        
        system.debug('query'+query);
        try {
            // Perform the query and cast the results to a list of Lead
            cifRecords = (List<SObject>)Database.query(query);
            
        } catch (QueryException e) {System.debug('Error executing query: ' + e.getMessage());
        }
        return cifRecords;
    }
    public static List<SObject> getAllCustomMetadata(String recordApiName, string objectName) {
        Map<String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get(objectName).getDescribe().fields.getMap();
        String query = 'SELECT ';
        for (String fieldName : fieldMap.keySet()) {
            query += fieldName + ', ';
        }
        
        query = query.removeEnd(', ') + ' FROM ' + objectName + ' WHERE DeveloperName = :recordApiName';
        return Database.query(query);
    }
    // public static void convertLeadEnquiryToOpp(Map<String,String> LeadAndCIFIDs){
       
    //     //List<EYI_Lead_Enquiry__c> leadEnquiries = [SELECT Id,  FROM Lead_Enquiry__c WHERE Id IN :LeadEnquiryId];
    //    // List<CIF__c> cifs = [SELECT Id, CIF_Field1__c, CIF_Field2__c FROM CIF__c WHERE Id IN :CIFId];
    //     // List<Account> existingAccounts = [SELECT Id FROM Account WHERE Name = :accountName LIMIT 1];
    //     List<EYI_Lead_Conversion_Metadata__mdt> customMetadataRecords = getAllCustomMetadata('Lead_Conversion', 'EYI_Lead_Conversion_Metadata__mdt');
    //     List<String> valuesList = new List<String>();
    //     Map<String,String> valuesMap = new Map<String,String>();
    //     List<String> allFieldCIF = new List<String>();
    //     List<String> phoneNumber = new List<String>();
    //     List<String> emailIds = new List<String>();
    //     List<EYI_Customer_Information_Form__c> cifRecord =getCIFData(LeadAndCIFIDs.values(),allFieldCIF);
    //     for (EYI_Customer_Information_Form__c cif : cifRecord) {
    //         phoneNumber.add(cif.EYI_Mobile_number__c);
    //         emailIds.add(cif.EYI_Email_Id__c);
    //     }
    //     List<Account> getAccounts = [Select Id from Account where Phone IN:phoneNumber OR EYI_Email__c IN:emailIds];
    //     List<Opportunity> oppRecordsInsert = new List<Opportunity>();
    //     for (EYI_Customer_Information_Form__c cif : cifRecord) {
    //         Opportunity opp = new Opportunity();
    //         for (String cifField : valuesMap.keySet()) {
    //             String oppField = valuesMap.get(cifField);
    //             opp.put(oppField, cif.get(cifField));
    //         }   
    //         // Set Opportunity fields based on CIF and other logic
    //         // opp.Name = cif.Name; // Example field mapping
    //         // opp.CloseDate = Date.today().addMonths(1); // Example field
    //         // opp.StageName = 'Prospecting'; // Example field
    //         oppRecordsInsert.add(opp);
    //     }
    //     if(!oppRecordsInsert.isEmpty()){
    //         insert oppRecordsInsert;
    //     }
    //     System.debug('oppRecordsInsert'+oppRecordsInsert);
    //     System.debug('customMetadataRecords'+customMetadataRecords);
    //     for (EYI_Lead_Conversion_Metadata__mdt record : customMetadataRecords) {
    //         String commaSeparatedValue = record.EYI_LeadEnquiryVsOppField__c; // Replace with your actual field name
    //         valuesList = commaSeparatedValue.split(',');
    //     }    
    //     for (String value : valuesList) {
    //         List<String> keyValue = value.split(':');
    //         if (keyValue.size() == 2) {
    //             allFieldCIF.add(keyValue[0].trim());
    //             valuesMap.put(keyValue[0].trim(), keyValue[1].trim());
    //         }
    //     }
    //     system.debug('valuesMap'+valuesMap);
        
    // }
    // public static List<EYI_Customer_Information_Form__c> getCIFData(List<ID> cifIDs,List<String> fieldsToretrive){
    //     List<EYI_Customer_Information_Form__c> cifRecords= new List<EYI_Customer_Information_Form__c>();
    //     String query = 'SELECT Id, EYI_Lead_Enquiry__c,';
    //     query += String.join(fieldsToretrive, ', ');
    //     query += ' FROM EYI_Customer_Information_Form__c WHERE Id IN ('+ String.join(cifIDs, ', ') + ')';
    //     // List<String> quotedIds = new List<String>();
    //     // for (String id : newParentID) {
    //     //     quotedIds.add('\'' + id + '\'');
    //     // }
    //    // query += ' And EYI_Lead_Generation_Medium__c != '+ typeOfInsert;
    //    // query += ' AND Id NOT IN (' + String.join(newParentID, ', ') + ')';
    //     // if(queryCondition != null && queryCondition!= ''){
    //     //     query = query + ' AND ( ' + queryCondition + ' )';
    //     // }
    //    // query += ' ORDER BY CreatedDate ASC';
    //     //adding order by bcoz wanted to retrive record first which is already exist so that new record will get delete if it is duplicate
    //     //
        
    //     system.debug('query'+query);
    //     //List<EYI_Customer_Information_Form__c> cifRecords = new List<EYI_Customer_Information_Form__c>();
    //     try {
    //         // Perform the query and cast the results to a list of Lead
    //         cifRecords = (List<SObject>)Database.query(query);
            
    //     } catch (QueryException e) {System.debug('Error executing query: ' + e.getMessage());
    //     }
    //     return cifRecords;
    // }
    
}