force-app/main/default/objects/EYI_Inventory__c/EYI_Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Built_up_Area__c.field-meta.xml
<CustomField>
    <fullName>EYI_Built_up_Area__c</fullName>
    <label>Built-up Area</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Inventory_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Inventory Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>EYI_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Parking_Count__c.field-meta.xml
<CustomField>
    <fullName>EYI_Parking_Count__c</fullName>
    <label>Parking Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Saleable_Area_in_Sq_Mtr__c.field-meta.xml
<CustomField>
    <fullName>EYI_Saleable_Area_in_Sq_Mtr__c</fullName>
    <label>Saleable Area in Sq. Mtr</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>EYI_Tower__c.EYI_SubProject_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.EYI_SubProject__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plan</label>
    <referenceTo>Payment_Plan__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/EYI_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Project_Unit__c/EYI_Project_Unit__c.object-meta.xml
<CustomObject>
    <label>Project Unit</label>
    <nameField>
        <label>Project Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Project_Unit__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Project Units</relationshipLabel>
    <relationshipName>Project_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Project_Unit__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Project Units</relationshipLabel>
    <relationshipName>Project_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/EYI_Rate_List__c.object-meta.xml
<CustomObject>
    <label>Rate List</label>
    <nameField>
        <displayFormat>Rate List-{00}</displayFormat>
        <label>Rate List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Inventory__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory</label>
    <referenceTo>EYI_Inventory__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Project_Unit__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Unit</label>
    <referenceTo>EYI_Project_Unit__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Rate__c.field-meta.xml
<CustomField>
    <fullName>EYI_Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Rate_List__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Rate Lists</relationshipLabel>
    <relationshipName>Rate_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Tower__c/EYI_Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Plan__c/Payment_Plan__c.object-meta.xml
<CustomObject>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Plan__c/fields/EYI_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>EYI_Is_Active__c</fullName>
    <formula>IF(
    ISPICKVAL( EYI_Plan_Type__c , &quot;Construction Linked Payment&quot;) || ISPICKVAL( EYI_Plan_Type__c , &quot;CLP + Time bound&quot;),
    TRUE,
    IF(
        AND(
            TODAY() &gt;= EYI_Start_Date__c,
            TODAY() &lt;= EYI_End_Date__c
        ),
        TRUE,
        FALSE
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Plan__c/fields/EYI_Is_Extended__c.field-meta.xml
<CustomField>
    <fullName>EYI_Is_Extended__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Extended</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Plan__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Payment Plans</relationshipLabel>
    <relationshipName>Payment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Plan__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>EYI_Tower__c.EYI_Project_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Payment Plans</relationshipLabel>
    <relationshipName>Payment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuotationPageController.cls
/**
* @File Name : QuotationPageController.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : January 22, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | January 22, 2025 |   | Initial Version
**/

public class QuotationPageController {


@AuraEnabled(cacheable=true)
public static List<Object> searchRecords(string searchKey,string objName) {
    list<Object> lstobj ;
    if(objName=='opportunity'){
        if(searchKey!=null){
        lstobj = [SELECT Id, Name FROM Opportunity Where Name LIKE :('%' + searchKey + '%')  ORDER BY CreatedDate DESC LIMIT 5 ];
        }else{
        lstobj = [SELECT Id, Name FROM Opportunity ORDER BY CreatedDate DESC  LIMIT 5];     
        }
    }
        if(objName=='project'){
        if(searchKey!=null){
        lstobj = [select id,name from EYI_Project__c where NAME  LIKE :('%' + searchKey + '%')
        ORDER BY CreatedDate DESC LIMIT 4];
        }  else{
        lstobj = [SELECT Id, Name FROM EYI_Project__c ORDER BY CreatedDate DESC LIMIT 4 ];     
        }
        }

        if(objName=='plantype'){
            if(searchKey!=null){
        lstobj = [select id,name from Payment_Plan__c  where NAME  LIKE :('%' + searchKey + '%')  ORDER BY CreatedDate DESC ];
        }
        else{
        lstobj = [SELECT Id, Name FROM Payment_Plan__c ORDER BY CreatedDate DESC ];     
        }
        }
        system.debug(lstobj);
        return lstobj;
}

@Auraenabled(cacheable=true)
public static list<Payment_Plan__c> getPlanType(String projId,String towerId){
	system.debug('projid' + projId);
      list<Payment_Plan__c>  lstplan = [select id,name from Payment_Plan__c Where Project__c = :projId AND Tower__c = :towerId AND EYI_Is_Extended__c = false AND EYI_Is_Active__c = true
         ORDER BY CreatedDate DESC];
       return lstplan;
    
}

@AuraEnabled
public static string getDummyOpportunity(){
    try {
        Opportunity opp = [SELECT ID FROM opportunity WHERE name LIKE '%Placeholder%' LIMIT 1];
        return opp.Id;
    } catch (Exception e) {
        system.debug('Error retreiving dummy opp' + e);
        return null;
    }
}
@AuraEnabled(cacheable=true)
public static EYI_Inventory__c getInventory(string inventoryId ){

      EYI_Inventory__c inventory = [
            SELECT Id, EYI_Opportunity__c, EYI_Opportunity__r.Name, 
             EYI_Project__c,EYI_Tower__c, EYI_Project__r.Name, Payment_Plan__c,
            Payment_Plan__r.Name, EYI_Built_up_Area__c,EYI_Inventory_Number__c
            FROM EYI_Inventory__c  
            WHERE ID = :inventoryId
            LIMIT 1
        ]; 

        return inventory;
}

@AuraEnabled(cacheable=true)
public static inventoryData getQuoteValues(string inventoryId){

     EYI_Inventory__c inventory;
 try {
         inventory = [
            SELECT Id, EYI_Opportunity__c, EYI_Opportunity__r.Name,
                   EYI_Project__c, EYI_Project__r.Name, Payment_Plan__c, Payment_Plan__r.Name, EYI_Built_up_Area__c,
                   EYI_Parking_Count__c,EYI_Saleable_Area_in_Sq_Mtr__c
            FROM EYI_Inventory__c  
            WHERE ID = :inventoryId
            LIMIT 1
        ]; 

        EYI_Rate_List__c ratelist = [select id,EYI_Rate__c from EYI_Rate_List__c 
        where EYI_Inventory__c=:inventoryId limit 1];
     
     EYI_Project_Unit__c punit;
    //  if(ratelist!=null){
    //      punit = [select id,CGST__c, SGST__c from EYI_Project_Unit__c where 
    //     EYI_Project__c=:ratelist.Id LIMIT 1];
    //  }

        inventoryData inv = new inventoryData();

           if(ratelist.EYI_Rate__c!=null && inventory.EYI_Saleable_Area_in_Sq_Mtr__c!=null){
               inv.unit = ratelist.EYI_Rate__c * inventory.EYI_Saleable_Area_in_Sq_Mtr__c;
           }
        //     if(punit.CGST__c!=null && punit.SGST__c!=null){
        //        inv.centralGst = punit.CGST__c;
        //        inv.stateGst = punit.SGST__c;
        //    }


        if (inventory == null) {
            return null;
        }

     

        // inv.infrastructureCharge ;

        // inv.stateGst;

        // inv.centralGst;

        // inv.stampDuty;

        // inv.registration ;
       

        // inv.mainitenance_deposit;

        // inv.msebc_charges;

        // inv.legal_charges;
        // inv.maintenance_charges ;


 System.debug('inv values : ' + inv);
        return inv;
    } catch (Exception e) {
        System.debug('Error in getQuoteValues: ' + e.getMessage());
        return null;
    }
}

  public class inventoryData {
        @AuraEnabled public Decimal unit { get; set; }
        @AuraEnabled public Decimal infrastructureCharge { get; set; }
        @AuraEnabled public Decimal stateGst { get; set; }
        @AuraEnabled public Decimal centralGst { get; set; }
        @AuraEnabled public Decimal stampDuty { get; set; }
         @AuraEnabled public Decimal registration { get; set; }
        @AuraEnabled public Decimal mainitenance_deposit  { get; set; }
        @AuraEnabled public Decimal msebc_charges  { get; set; }
        @AuraEnabled public Decimal legal_charges  { get; set; }
        @AuraEnabled public Decimal maintenance_charges{ get; set; }
         
    }


}