force-app/main/default/objects/EYI_Inventory__c/EYI_Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Inventory_Status__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory_Status__c</fullName>
    <label>Inventory Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vacant</fullName>
            </value>
            <value>
                <fullName>Refuge</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Possesion Given</fullName>
            </value>
            <value>
                <fullName>Reserve</fullName>
            </value>
            <value>
                <fullName>Booking</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
                <isActive>false</isActive>
                <label>Available</label>
            </value>
            <value>
                <fullName>EOI Blocked</fullName>
                <isActive>false</isActive>
                <label>EOI Blocked</label>
            </value>
            <value>
                <fullName>Hold For Booking</fullName>
                <isActive>false</isActive>
                <label>Hold For Booking</label>
            </value>
            <value>
                <fullName>Not Sanctioned</fullName>
                <isActive>false</isActive>
                <label>Not Sanctioned</label>
            </value>
            <value>
                <fullName>Payment In Progress</fullName>
                <isActive>false</isActive>
                <label>Payment In Progress</label>
            </value>
            <value>
                <fullName>Possession Given</fullName>
                <isActive>false</isActive>
                <label>Possession Given</label>
            </value>
            <value>
                <fullName>Quotation Is Sent</fullName>
                <isActive>false</isActive>
                <label>Quotation Is Sent</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Is_Syc__c.field-meta.xml
<CustomField>
    <fullName>EYI_Is_Syc__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Syc</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Is_updated__c.field-meta.xml
<CustomField>
    <fullName>EYI_Is_updated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>flag to trigger batch job for SAP data syncing</description>
    <label>Is updated?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>EYI_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Reserver_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Reserver_Date__c</fullName>
    <label>Reserver Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/EYI_InventoryTriggerHandler.cls
/* Author: Mrinal Tripathi
* Purpose: Trigger handler for EYI_Inventory__c
* Created date: 19 Feburary 2025
*/
public class EYI_InventoryTriggerHandler {
    public static void handleBeforeUpdate(){
        Boolean IS_StatusChange = false;
        Set<Id> inventoryIds = new Set<Id> ();
        List<String> statusList = new List<String>{'Vacant', 'Refuge', 'Blocked', 'Booked', 'Hold', 'Sold', 'Possesion Given'};
            // Get the field set fields dynamically
            Set<String> fieldSetFields = new Set<String>();
        
        Schema.SObjectType objType = Schema.getGlobalDescribe().get('EYI_Inventory__c');
        if (objType != null) {
            Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
            
            // Replace 'Your_Field_Set_API_Name' with the actual Field Set API Name
            Schema.FieldSet fieldSet = objDescribe.fieldSets.getMap().get('SAP_Inventory_Field_Set');
            
            if (fieldSet != null) {
                for (Schema.FieldSetMember field : fieldSet.getFields()) {
                    fieldSetFields.add(field.getFieldPath());
                }
            }
            Boolean hasFieldChanged = false;
            for(EYI_Inventory__c newRecord : (List<EYI_Inventory__c>)Trigger.new){
                EYI_Inventory__c oldRecord = (EYI_Inventory__c)Trigger.oldMap.get(newRecord.Id);
                
                for (String fieldName : fieldSetFields) {
                    if (oldRecord.get(fieldName) != newRecord.get(fieldName)) {
                        hasFieldChanged = true;
                        newRecord.EYI_Is_Syc__c = false;
                        break;
                    }
                }
                if (newRecord.EYI_Inventory_Status__c != oldRecord.EYI_Inventory_Status__c && statusList.contains(newRecord.EYI_Inventory_Status__c)){
                    newRecord.EYI_Is_Syc__c = false;
                    
                    hasFieldChanged = true;
                    IS_StatusChange = true;
                    
                }
                if(hasFieldChanged){
                    newRecord.EYI_Is_updated__c = true;
                    inventoryIds.add(newRecord.Id);
                }
                
            }
            if(inventoryIds.size() == 1){
                EYI_FutureCalloutClass.inventoryDataSync(inventoryIds ,IS_StatusChange);
            }
            
        }
    }
    public static void handleErrorOnOppTag(List<EYI_Inventory__c> invList, Map<Id,EYI_Inventory__c> oldInv){
        Set<Id> opportunityIds = new Set<Id>();

        // Collect Opportunity Ids from the Inventory records being inserted/updated
        for (EYI_Inventory__c inv : invList) {
            if (inv.EYI_Opportunity__c != null) {
                opportunityIds.add(inv.EYI_Opportunity__c);
            }
        }
    
        // Query Opportunities to check for existing inventory tags
        Map<Id, Opportunity> opportunityMap = new Map<Id, Opportunity>(
            [SELECT Id, EYI_Inventory__c FROM Opportunity WHERE Id IN :opportunityIds]
        );
    
        // Iterate through Inventory records and check if the related Opportunity has an inventory tag
        for (EYI_Inventory__c inv : invList) {
            if(inv.EYI_Inventory_Status__c == 'Reserve' && inv.EYI_Inventory_Status__c != oldInv.get(inv.Id).EYI_Inventory_Status__c )
                {
                    inv.EYI_Reserver_Date__c = System.now();
                }
            if (inv.EYI_Opportunity__c != null && inv.EYI_Opportunity__c != oldInv.get(inv.Id).EYI_Opportunity__c) {
                Opportunity opp = opportunityMap.get(inv.EYI_Opportunity__c);
                if (opp != null && opp.EYI_Inventory__c != null ) {
                    inv.addError('The related Opportunity already has an inventory tag.');
                }
            }
        }
    }

    public static void handleUpdateInvIdOnOpp(List<EYI_Inventory__c> invList, Map<Id,EYI_Inventory__c> oldInv){
        List<Opportunity> listOpp = new List<Opportunity>();
        for(EYI_Inventory__c inv:invList){
            if(inv.EYI_Inventory_Status__c == 'Reserve' && inv.EYI_Inventory_Status__c != oldInv.get(inv.Id).EYI_Inventory_Status__c ){
                Opportunity oppRec =  new Opportunity();
                oppRec.Id =inv.EYI_Opportunity__c;
                oppRec.EYI_Inventory__c = inv.Id;
                listOpp.add(oppRec);
            }
        }
        system.debug('listOpp'+listOpp);
        update listOpp;
    }
}