force-app/main/default/objects/EYI_Inventory__c/EYI_Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Balcony_Area__c.field-meta.xml
<CustomField>
    <fullName>EYI_Balcony_Area__c</fullName>
    <label>Balcony Area</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Built_up_Area__c.field-meta.xml
<CustomField>
    <fullName>EYI_Built_up_Area__c</fullName>
    <label>Built-up Area</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Carpet_Area__c.field-meta.xml
<CustomField>
    <fullName>EYI_Carpet_Area__c</fullName>
    <label>Carpet Area</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Common_Area__c.field-meta.xml
<CustomField>
    <fullName>EYI_Common_Area__c</fullName>
    <label>Common Area</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Garden_Area__c.field-meta.xml
<CustomField>
    <fullName>EYI_Garden_Area__c</fullName>
    <label>Garden Area</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_GST_Tax_Classification__c.field-meta.xml
<CustomField>
    <fullName>EYI_GST_Tax_Classification__c</fullName>
    <label>GST Tax Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Taxable under GST</fullName>
            </value>
            <value>
                <fullName>GST - Exempted</fullName>
            </value>
            <value>
                <fullName>Non Taxable GST</fullName>
            </value>
            <value>
                <fullName>Excisable with GST</fullName>
            </value>
            <value>
                <fullName>Bill of supply</fullName>
            </value>
            <value>
                <fullName>5% Scheme-New RERA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Inventory_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Inventory Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Inventory_Status__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory_Status__c</fullName>
    <label>Inventory Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vacant</fullName>
            </value>
            <value>
                <fullName>Refuge</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Possesion Given</fullName>
            </value>
            <value>
                <fullName>Reserve</fullName>
            </value>
            <value>
                <fullName>Booking</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
                <isActive>false</isActive>
                <label>Available</label>
            </value>
            <value>
                <fullName>EOI Blocked</fullName>
                <isActive>false</isActive>
                <label>EOI Blocked</label>
            </value>
            <value>
                <fullName>Hold For Booking</fullName>
                <isActive>false</isActive>
                <label>Hold For Booking</label>
            </value>
            <value>
                <fullName>Not Sanctioned</fullName>
                <isActive>false</isActive>
                <label>Not Sanctioned</label>
            </value>
            <value>
                <fullName>Payment In Progress</fullName>
                <isActive>false</isActive>
                <label>Payment In Progress</label>
            </value>
            <value>
                <fullName>Possession Given</fullName>
                <isActive>false</isActive>
                <label>Possession Given</label>
            </value>
            <value>
                <fullName>Quotation Is Sent</fullName>
                <isActive>false</isActive>
                <label>Quotation Is Sent</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Inventory_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory_Type__c</fullName>
    <label>Inventory Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential Sales</fullName>
            </value>
            <value>
                <fullName>Commercial Sales</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
                <isActive>false</isActive>
                <label>Commercial</label>
            </value>
            <value>
                <fullName>Residential</fullName>
                <isActive>false</isActive>
                <label>Residential</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Material_Group__c.field-meta.xml
<CustomField>
    <fullName>EYI_Material_Group__c</fullName>
    <label>Material Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apartment</fullName>
            </value>
            <value>
                <fullName>Business Unit</fullName>
            </value>
            <value>
                <fullName>Plots</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Club House</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
                <isActive>false</isActive>
                <label>Parking</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_OC_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_OC_Received_Date__c</fullName>
    <label>OC Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Project__c.field-meta.xml
<CustomField>
    <fullName>EYI_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_SAP_Material_Description__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Material_Description__c</fullName>
    <label>Description</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_SAP_Material_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Material_Type__c</fullName>
    <label>Material Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finished Unit</fullName>
            </value>
            <value>
                <fullName>Saleable Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Super_Built_up_Area__c.field-meta.xml
<CustomField>
    <fullName>EYI_Super_Built_up_Area__c</fullName>
    <label>Super Built-Up Area</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_TCS_Tax_Classification__c.field-meta.xml
<CustomField>
    <fullName>EYI_TCS_Tax_Classification__c</fullName>
    <label>TCS Tax Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TCS Applicable</fullName>
            </value>
            <value>
                <fullName>TCS Not Applicable</fullName>
            </value>
            <value>
                <fullName>TDS Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Terrace_Area__c.field-meta.xml
<CustomField>
    <fullName>EYI_Terrace_Area__c</fullName>
    <label>Terrace Area</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_Tower__c.field-meta.xml
<CustomField>
    <fullName>EYI_Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>EYI_Tower__c.EYI_SubProject_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.EYI_SubProject__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EYI_Tower__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/fields/EYI_UOM__c.field-meta.xml
<CustomField>
    <fullName>EYI_UOM__c</fullName>
    <label>UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Square foot</fullName>
            </value>
            <value>
                <fullName>Each</fullName>
                <isActive>false</isActive>
                <label>Each</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Project__c/EYI_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Project__c/fields/EYI_SAP_Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Plant_Code__c</fullName>
    <label>SAP Plant Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_SAP_Salesorg__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Salesorg__c</fullName>
    <label>SAP Sales-org</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Tower__c/EYI_Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Tower__c/fields/EYI_SAP_Delivery_Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Delivery_Plant_Code__c</fullName>
    <label>SAP Delivery Plant Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Tower__c/fields/EYI_SAP_Plant_ID__c.field-meta.xml
<CustomField>
    <fullName>EYI_SAP_Plant_ID__c</fullName>
    <label>SAP Plant Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EYI_InventoryCalloutBatch.cls
global class EYI_InventoryCalloutBatch implements Database.Batchable<sObject>, Database.AllowsCallouts { 
    
    private List<EYI_Inventory__c> recordsToProcess;
    private Boolean isFromAura;
    private Boolean isPatchOperation = true;
    // Constructor to accept records when called from Aura
    global EYI_InventoryCalloutBatch(List<EYI_Inventory__c> records, Boolean isPatchOperation) {
        this.recordsToProcess = records;
        this.isFromAura = true;
        this.isPatchOperation = isPatchOperation;
    }
    // Default constructor for scheduled execution
    global EYI_InventoryCalloutBatch() {
        this.isFromAura = false;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        if (isFromAura && recordsToProcess != null && !recordsToProcess.isEmpty()) {
            return Database.getQueryLocator([SELECT Id, EYI_Project__r.EYI_SAP_Salesorg__c, EYI_OC_Received_Date__c, EYI_Project__r.EYI_SAP_Plant_Code__c,
                                                 EYI_Inventory_Number__c,EYI_SAP_Material_Type__c,EYI_SAP_Material_Description__c,EYI_GST_Tax_Classification__c,EYI_TCS_Tax_Classification__c,
                                                 EYI_Inventory_Type__c,EYI_UOM__c,EYI_Material_Group__c,EYI_Super_Built_up_Area__c, EYI_Tower__r.EYI_SAP_Delivery_Plant_Code__c,
                                                 EYI_Carpet_Area__c,EYI_Garden_Area__c,EYI_Built_up_Area__c,EYI_Common_Area__c,EYI_Terrace_Area__c,EYI_Balcony_Area__c, EYI_Tower__r.EYI_SAP_Plant_ID__c,
                                                 EYI_Inventory_Status__c,EYI_Inventory_Floor_No__c, EYI_View_based_on_Directions__c,Configuration__c,Name, EYI_Typology__c,
                                                 EYI_View_based_on_Amenities__c ,EYI_SAP_Affordable_Type__c,EYI_SAP_Profit_Center__c, EYI_Saleable_Area__c FROM EYI_Inventory__c WHERE Id IN :recordsToProcess]);
        } else {
            Dynamic_Batch_Setting__c batchSetting = [SELECT Id, Last_Batch_Run__c FROM Dynamic_Batch_Setting__c WHERE Name = 'Inventory Sync'];
            
            return Database.getQueryLocator([SELECT id, EYI_Project__r.EYI_SAP_Salesorg__c, EYI_OC_Received_Date__c, EYI_Project__r.EYI_SAP_Plant_Code__c,
                                                 EYI_Inventory_Number__c, EYI_SAP_Material_Type__c,EYI_SAP_Material_Description__c,EYI_GST_Tax_Classification__c,EYI_TCS_Tax_Classification__c,
                                                 EYI_Inventory_Type__c,EYI_UOM__c,EYI_Material_Group__c,EYI_Super_Built_up_Area__c, EYI_Tower__r.EYI_SAP_Delivery_Plant_Code__c, //EYI_SAP_Plant_Code__c
                                                 EYI_Carpet_Area__c,EYI_Garden_Area__c,EYI_Built_up_Area__c,EYI_Common_Area__c,EYI_Terrace_Area__c,EYI_Balcony_Area__c, EYI_Tower__r.EYI_SAP_Plant_ID__c,
                                                 EYI_Inventory_Status__c,EYI_Inventory_Floor_No__c, EYI_View_based_on_Directions__c,Configuration__c,Name, EYI_Typology__c,
                                                 EYI_View_based_on_Amenities__c ,EYI_SAP_Affordable_Type__c,EYI_SAP_Profit_Center__c, EYI_Saleable_Area__c FROM EYI_Inventory__c 
                                             WHERE EYI_Is_Syc__c = false 
                                             AND EYI_Is_updated__c = true 
                                             AND LastModifiedDate >= :batchSetting.Last_Batch_Run__c]);
        }
    }

    global void execute(Database.BatchableContext BC, List<EYI_Inventory__c> scope) {
        EYI_InventorySyncLwcController.processInventoryRecords(scope, isPatchOperation, false);
        for (EYI_Inventory__c inv : scope) {
            inv.EYI_Is_updated__c = false;
        }   
        update scope;
    }

    global void finish(Database.BatchableContext BC) {
        if (!isFromAura) { // Only update batch setting when called from Scheduler
            Dynamic_Batch_Setting__c batchSetting = [SELECT Id, Last_Batch_Run__c FROM Dynamic_Batch_Setting__c WHERE Name = 'Inventory Sync'];
            batchSetting.Last_Batch_Run__c = System.now();
            update batchSetting;
        }
    }
}