force-app/main/default/objects/EYI_Applicants__c/EYI_Applicants__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicants Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Applicants__c/fields/EYI_Aadhar_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Aadhar_Number__c</fullName>
    <label>Aadhar Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Applicants__c/fields/EYI_Anniversary_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Anniversary_Date__c</fullName>
    <label>Anniversary Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Applicants__c/fields/EYI_Applicant_No__c.field-meta.xml
<CustomField>
    <fullName>EYI_Applicant_No__c</fullName>
    <label>Applicant No.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Applicants__c/fields/EYI_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_Company_Name__c</fullName>
    <label>Company Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Applicants__c/fields/EYI_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>EYI_Date_of_Birth__c</fullName>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Applicants__c/fields/EYI_Designation__c.field-meta.xml
<CustomField>
    <fullName>EYI_Designation__c</fullName>
    <label>Designation</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Applicants__c/fields/EYI_First_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_First_Name__c</fullName>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Applicants__c/fields/EYI_Inventory__c.field-meta.xml
<CustomField>
    <fullName>EYI_Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>EYI_Inventory__c.EYI_Type__c</field>
            <operation>notEqual</operation>
            <value>Parking</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EYI_Inventory__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Applicants__c/fields/EYI_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Applicants__c/fields/EYI_Pancard_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Pancard_Number__c</fullName>
    <label>Pancard Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Applicants__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Indian</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Utd.Arab Emir.</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Antigua/Barbuda</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Samoa, America</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bosnia-Herz.</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Burkina Faso</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Burundi</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>St. Barthelemy</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Brunei Daruss.</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Applicants__c/fields/Verified_AADHAR_Card_Address__c.field-meta.xml
<CustomField>
    <fullName>Verified_AADHAR_Card_Address__c</fullName>
    <label>Verified AADHAR Card Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EYI_Applicants__c/fields/Verified_AADHAR_Card_Name__c.field-meta.xml
<CustomField>
    <fullName>Verified_AADHAR_Card_Name__c</fullName>
    <label>Verified AADHAR Card Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/EYI_Inventory__c/EYI_Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EYI_WelcomCallUtilityClass.cls
public with sharing class EYI_WelcomCallUtilityClass {
    //Method return opportunity Details
    @AuraEnabled
    public static Opportunity getOppRec(String recordId){
        try {
            List<Opportunity> getOppRec = [Select Id,Name,EYI_Agreement_Value__c, EYI_First_Name__c, EYI_Last_Name__c,EYI_Project_Enquired__r.Name,EYI_Inventory__r.Name,Owner.Name, EYI_Primary_Applicant__r.EYI_Designation__c, EYI_Primary_Applicant__r.EYI_Date_of_Birth__c,EYI_Primary_Applicant__r.EYI_Anniversary_Date__c,EYI_Primary_Applicant__r.Nationality__c,EYI_Primary_Applicant__r.EYI_Company_Name__c, EYI_Primary_Applicant__r.Name, EYI_Primary_Applicant__r.EYI_Aadhar_Number__c, EYI_Primary_Applicant__r.EYI_Pancard_Number__c, EYI_Primary_Applicant__r.Verified_AADHAR_Card_Address__c,EYI_Primary_Applicant__r.Verified_AADHAR_Card_Name__c,EYI_Relationship_Manager__r.Name, EYI_Relationship_Manager__r.Email,EYI_Relationship_Manager__r.MobilePhone  from Opportunity where Id=: recordId];
            return getOppRec[0];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static EYI_Applicants__c getSecondApp(String recordId){
        try {
            List<EYI_Applicants__c> getSecondApp = [Select Id,Name,Verified_AADHAR_Card_Name__c from EYI_Applicants__c where Opportunity__c =: recordId AND EYI_Applicant_No__c = 2];
            return getSecondApp[0];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}