force-app/main/default/objects/EYI_Applicants__c/EYI_Applicants__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicants Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Applicants__c/fields/EYI_Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary Applicant</fullName>
            </value>
            <value>
                <fullName>Co-applicant</fullName>
            </value>
            <value>
                <fullName>AADHAR Card Number</fullName>
                <isActive>false</isActive>
                <label>AADHAR Card Number</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EYI_Applicants__c/fields/EYI_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>EYI_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Applicants__c/fields/EYI_Pancard_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Pancard_Number__c</fullName>
    <label>Pancard Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Applicants__c/fields/Is_Aadhar_EKYC_Completed__c.field-meta.xml
<CustomField>
    <fullName>Is_Aadhar_EKYC_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Aadhar EKYC Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AadharTxnDetailsUpdateAppBatchSchdTest.cls
@isTest
public class AadharTxnDetailsUpdateAppBatchSchdTest {

    @testSetup
    static void setupData() {
        EYI_Applicants__c applicant = new EYI_Applicants__c(
            Name='Nilesh Ghodke',
            EYI_Last_Name__c='Ghodke',
            EYI_Pancard_Number__c='DLWPG4197L',
            EYI_Applicant_Type__c='Primary Applicant',
            DigiLocker_Transaction_Id__c = 324232,
            Is_Aadhar_EKYC_Completed__c = false
        );
        insert applicant;
    }

    @isTest
    static void testScheduleJob() {
        Test.startTest();
        AadharTxnDetailsUpdateAppBatchSchedule sch = new AadharTxnDetailsUpdateAppBatchSchedule();
        sch.execute(null);
        Test.stopTest();
    }
}