force-app/main/default/objects/EYI_Payment_Milestone_Usage_Mapping__mdt/EYI_Payment_Milestone_Usage_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Payment Milestone Usage Mapping</label>
    <pluralLabel>Payment Milestone Usage Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/EYI_Payment_Schedule__c/EYI_Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PM-{000000}</displayFormat>
        <label>Payment Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/EYI_Actual_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Actual_Date__c</fullName>
    <description>Actual Completion Date</description>
    <label>Actual Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/EYI_Amount_to_be_paid__c.field-meta.xml
<CustomField>
    <fullName>EYI_Amount_to_be_paid__c</fullName>
    <label>Amount to be paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/EYI_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>EYI_Billing_Date__c</fullName>
    <label>Billing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/EYI_Due_Amount__c.field-meta.xml
<CustomField>
    <fullName>EYI_Due_Amount__c</fullName>
    <label>Due Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/EYI_GST__c.field-meta.xml
<CustomField>
    <fullName>EYI_GST__c</fullName>
    <label>GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/EYI_Invoice_Percentage__c.field-meta.xml
<CustomField>
    <fullName>EYI_Invoice_Percentage__c</fullName>
    <label>Percentage of value to be invoiced</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/EYI_Milestone_Number__c.field-meta.xml
<CustomField>
    <fullName>EYI_Milestone_Number__c</fullName>
    <label>Milestone Number</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/EYI_Net_Payable__c.field-meta.xml
<CustomField>
    <fullName>EYI_Net_Payable__c</fullName>
    <formula>EYI_Due_Amount__c  +  EYI_GST__c - EYI_TDS__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Payable</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/EYI_Payable_Amount__c.field-meta.xml
<CustomField>
    <fullName>EYI_Payable_Amount__c</fullName>
    <formula>IF(ISBLANK(EYI_Actual_Date__c),
Payment_Plan__r.EYI_Quote__r.EYI_Agreement_Value__c * EYI_Invoice_Percentage__c/100,
EYI_Amount_to_be_paid__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payable Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/EYI_TDS__c.field-meta.xml
<CustomField>
    <fullName>EYI_TDS__c</fullName>
    <formula>IF( Payment_Plan__r.EYI_Quote__r.EYI_Agreement_Value__c &gt; 5000000 , CEILING( EYI_Due_Amount__c * Payment_Plan__r.Project__r.EYI_TDS_Charge__c ), 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TDS</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/EYI_Usage__c.field-meta.xml
<CustomField>
    <fullName>EYI_Usage__c</fullName>
    <label>Usage</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/EYI_Usage_Description__c.field-meta.xml
<CustomField>
    <fullName>EYI_Usage_Description__c</fullName>
    <label>Usage Description</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EYI_Payment_Schedule__c/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plan</label>
    <referenceTo>Payment_Plan__c</referenceTo>
    <relationshipLabel>Payment Schedules</relationshipLabel>
    <relationshipName>Payment_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/EYI_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EYI_Project__c/fields/EYI_GST_Pay_Schedule_Charge__c.field-meta.xml
<CustomField>
    <fullName>EYI_GST_Pay_Schedule_Charge__c</fullName>
    <label>GST Pay Schedule Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_NPV_Percent__c.field-meta.xml
<CustomField>
    <fullName>EYI_NPV_Percent__c</fullName>
    <label>NPV Percent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/EYI_Project__c/fields/EYI_TDS_Charge__c.field-meta.xml
<CustomField>
    <fullName>EYI_TDS_Charge__c</fullName>
    <label>TDS Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment_Plan__c/Payment_Plan__c.object-meta.xml
<CustomObject>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Plan__c/fields/EYI_Is_Extended__c.field-meta.xml
<CustomField>
    <fullName>EYI_Is_Extended__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Extended</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Plan__c/fields/EYI_NPV_Percent__c.field-meta.xml
<CustomField>
    <fullName>EYI_NPV_Percent__c</fullName>
    <formula>(EYI_Total_NPV__c  /  EYI_Quote__r.EYI_Quoatation_Grand_Total__c) * 100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NPV %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment_Plan__c/fields/EYI_Plan_Type__c.field-meta.xml
<CustomField>
    <fullName>EYI_Plan_Type__c</fullName>
    <label>Plan Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Construction Linked Payment</fullName>
            </value>
            <value>
                <fullName>CLP + Time bound</fullName>
            </value>
            <value>
                <fullName>Time bound</fullName>
            </value>
            <value>
                <fullName>Subvention</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Plan__c/fields/EYI_Quote__c.field-meta.xml
<CustomField>
    <fullName>EYI_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Payment Plans</relationshipLabel>
    <relationshipName>Payment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Plan__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EYI_Project__c</referenceTo>
    <relationshipLabel>Payment Plans</relationshipLabel>
    <relationshipName>Payment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EYI_PaymentSchedulesUtility.cls
public with sharing class EYI_PaymentSchedulesUtility {
    @AuraEnabled(cacheable=true)
    public static List<EYI_Payment_Milestone_Usage_Mapping__mdt> getUsageMappingMetadata() {
        //system.debug(PaymentPlanId);
        return [Select Id,MasterLabel,DeveloperName FROM EYI_Payment_Milestone_Usage_Mapping__mdt];
       
    }
    @AuraEnabled(cacheable=true)
    public static List<EYI_Payment_Schedule__c> getPaymentSchedules(String recordId) {
        //system.debug(PaymentPlanId);
        List<EYI_Payment_Schedule__c> fl = new List<EYI_Payment_Schedule__c>();
        List<EYI_Payment_Schedule__c> fl1 = [Select Id,Payment_Plan__r.EYI_Quote__r.EYI_Agreement_Value__c,Payment_Plan__r.EYI_Quote__c,Payment_Plan__r.EYI_Quote__r.OpportunityId,Payment_Plan__r.EYI_Plan_Type__c,EYI_Usage_Description__c,EYI_Usage__c, EYI_Invoice_Percentage__c, EYI_Billing_Date__c,EYI_Due_Amount__c,EYI_Amount_to_be_paid__c,EYI_Payable_Amount__c,EYI_TDS__c,Payment_Plan__r.Project__r.EYI_TDS_Charge__c,Payment_Plan__r.EYI_Quote__r.EYI_Quoatation_Grand_Total__c,EYI_Net_Payable__c,EYI_GST__c,EYI_Actual_Date__c,Payment_Plan__r.EYI_Is_Extended__c,Payment_Plan__r.Project__r.EYI_GST_Pay_Schedule_Charge__c,Payment_Plan__r.Project__r.EYI_NPV_Percent__c,EYI_Milestone_Number__c from EYI_Payment_Schedule__c
                Where Payment_Plan__c = :recordId AND EYI_Actual_Date__c != null ORDER BY EYI_Actual_Date__c ASC];
        fl.addAll(fl1);
        List<EYI_Payment_Schedule__c> fl2 = [Select Id,Payment_Plan__r.EYI_Quote__r.EYI_Agreement_Value__c,Payment_Plan__r.EYI_Quote__c,Payment_Plan__r.EYI_Quote__r.OpportunityId,Payment_Plan__r.EYI_Plan_Type__c,EYI_Usage_Description__c,EYI_Usage__c, EYI_Invoice_Percentage__c, EYI_Billing_Date__c,EYI_Due_Amount__c,EYI_Amount_to_be_paid__c,EYI_Payable_Amount__c,EYI_TDS__c,Payment_Plan__r.Project__r.EYI_TDS_Charge__c,Payment_Plan__r.EYI_Quote__r.EYI_Quoatation_Grand_Total__c,EYI_Net_Payable__c,EYI_GST__c,EYI_Actual_Date__c,Payment_Plan__r.EYI_Is_Extended__c,Payment_Plan__r.Project__r.EYI_GST_Pay_Schedule_Charge__c,Payment_Plan__r.Project__r.EYI_NPV_Percent__c,EYI_Milestone_Number__c from EYI_Payment_Schedule__c
                Where Payment_Plan__c = :recordId AND EYI_Actual_Date__c = null ORDER BY  EYI_Actual_Date__c ASC];
        fl.addAll(fl2);        
        return fl;
       
    }
    @AuraEnabled
    public static String updatePaymentSchedules(List<EYI_Payment_Schedule__c> paymentSchedules) {
        upsert paymentSchedules;
        return 'Success';
    }
    @AuraEnabled
    public static String deletePaymentSchedules(String paymentScheduleId) {
        EYI_Payment_Schedule__c paymentSchedule = new EYI_Payment_Schedule__c();
        paymentSchedule.Id = paymentScheduleId;
        List<EYI_Payment_Schedule__c> paymentSchedules = new List<EYI_Payment_Schedule__c>();
        paymentSchedules.add(paymentSchedule);
        Delete paymentSchedules;
        return 'Success';
    }
}